### ISSUE TITLE
Crash when database connection is lost

### ISSUE THREAD

**Issue by tjwelde** [ether/etherpad-lite#2100]
We had the issue, that etherpad shuts down, when the database connection was lost (for example due to a database server restart).

Etherpad version: 1.3.0
Node version: 0.8.26 (There were some issues with newer versions)

Reproduce:
Use etherpad with mysql/postgresql
shutdown database

Log with postgresql:

```
[2014-03-03 15:39:57.699] [ERROR] console - error: terminating connection due to administrator command
    at Connection.parseE (/Users/timowelde/Documents/workspaces/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/pg/lib/connection.js:508:11)
    at Connection.parseMessage (/Users/timowelde/Documents/workspaces/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/pg/lib/connection.js:368:17)
    at Socket.Connection.attachListeners (/Users/timowelde/Documents/workspaces/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/pg/lib/connection.js:84:20)
    at Socket.EventEmitter.emit (events.js:96:17)
    at TCP.onread (net.js:397:14)
[2014-03-03 15:39:57.699] [INFO] console - graceful shutdown...
[2014-03-03 15:39:57.699] [INFO] console - db sucessfully closed.
```

Log with mysql:

```
[2014-03-03 15:37:19.249] [ERROR] console - Error: connect ECONNREFUSED
    at errnoException (net.js:770:11)
    at Object.afterConnect [as oncomplete] (net.js:761:19)
[2014-03-03 15:37:19.249] [INFO] console - graceful shutdown...
[2014-03-03 15:37:19.274] [INFO] console - db sucessfully closed.
```

Edit: added steps to reproduce, detailed log for postgres, added log for mysql, used code blocks, accidentally closed the issue

**Comment by JohnMcLear** [comment]
Help us hlep you!  https://www.bountysource.com/issues/2228137-crash-when-database-connection-is-lost

**Comment by JohnMcLear** [comment]
Closing as 99% of the time system scripts are handling this.
