### ISSUE TITLE
Abiword not installed

### ISSUE THREAD

**Issue by normalser** [ether/etherpad-lite#2130]
`Abiword.js` should catch an error if AbiWord is not installed but configured in settings.json.

Currently the following output is generated (which makes it impossible to understand what's the problem):

```
[2014-04-04 09:44:12.746] [INFO] console - The plugin admin page is at http://0.0.0.0:9001/admin/plugins
[2014-04-04 09:44:12.751] [ERROR] console - Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
[2014-04-04 09:44:12.751] [INFO] console - graceful shutdown...
```

Adding

``` js
    abiword.on('error', function(err) { ... });
```

would help in this case

**Comment by JohnMcLear** [comment]
When you try to export a document that depends on Abiword the user is presented with an error saying you need to install.  This is sufficient.

"This export is not enabled at this Etherpad instance. Set the path to Abiword or SOffice in settings.json to enable this feature"
