### ISSUE TITLE
etherpad ECONNRESET and graceful shutdown after 5 minutes of inactivity on MySQL with specific configurations

### ISSUE THREAD

**Issue by darkuncle** [ether/etherpad-lite#2148]
**OS: CentOS-6.5**
**Node: 0.10.26-1.el6**
all dependencies from packages (CentOS/EPEL/RPMForge), including abiword.

etherpad configured with default settings.json, with the following changes:
+ session key defined
+ database type set to mysql (connects to a remote mysql server over TCP; database, user and perms set up according to the wiki article on using etherpad with MySQL, confirmed working - am able to create and load pads stored there).

after installing and configuring etherpad, all features work as advertised - however, if the application is idle (receives no HTTP traffic) for five minutes, the application logs ECONNRESET and gracefully shuts down. Our use profile is fairly low-volume and periodic, so I expect the etherpad instance to be idle a majority of the time.

log output from bin/run.sh --root:

```Shell
# bin/run.sh --root
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json async-stacktrace@0.0.2 No repository field.
npm WARN package.json channels@0.0.4 No repository field.
npm WARN package.json ejs@0.6.1 No repository field.
npm WARN package.json formidable@1.0.9 No repository field.
npm WARN package.json jsdom-nocontextifiy@0.2.10 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json tinycon@0.0.1 No repository field.
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
ensure custom css/js files are created...
start...
[2014-05-06 09:06:56.766] [WARN] pluginfw - /var/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/npm-registry-client requires semver@'^2.2.1' but will load
/var/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/semver,
which is version 2.2.1 'unmet dependency'
[2014-05-06 09:06:56.774] [WARN] pluginfw - /var/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-username-repo@'^0.1.0' but will load
/var/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/github-url-from-username-repo,
which is version 0.1.0 'unmet dependency'
[2014-05-06 09:06:57.226] [INFO] console - Installed plugins: ep_etherpad-lite
[2014-05-06 09:06:57.253] [INFO] console - Your Etherpad git version is e85d094
[2014-05-06 09:06:57.253] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2014-05-06 09:06:57.309] [INFO] console -    info  - 'socket.io started'
[2014-05-06 09:06:57.359] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2014-05-06 09:06:57.360] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
[2014-05-06 09:11:58.963] [ERROR] console - Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
[2014-05-06 09:11:58.963] [INFO] console - graceful shutdown...
[2014-05-06 09:11:59.009] [INFO] console - db sucessfully closed.
```

have tested half a dozen times, same results in logs each time (the ECONNRESET error happens 5 min. plus a few seconds after the last previous message in the log). If I set up a remote caller (e.g. `while true ; do echo "GET / HTTP/1.0\n\n" | nc etherpad-server 9001" ; sleep 60 ; done`), the etherpad server will run indefinitely without crashing (or at least, not from this issue). I thought this might be related to a known bug in node.js related to connection timeouts that @isaacs patched a couple of years ago, but I know that has been since fixed, so I'm not sure what the actual root cause is of this.

**Comment by darkuncle** [comment]
this looks good from my end (limited testing, no apparent adverse effects)

/sf

**Comment by JohnMcLear** [comment]
merged and published.
