### ISSUE TITLE
Getting "Error: npm.load() required" when running "bin/run.sh"

### ISSUE THREAD

**Issue by LucasCioffi** [ether/etherpad-lite#2176]
I'm having difficulty during installation on Mac OSX 10.8.3.  I get "Error: npm.load() required" multiple times as shown below.  Perhaps something is wrong with my NPM or Node installations?

```
This is my first Node app, however Node seems to be working:
➜  etherpad-lite git:(develop) node
> console.log("hi")
hi
undefined
> 

➜  etherpad-lite git:(develop) echo $PATH
/usr/local/heroku/bin:/opt/chef/bin:/Users/lucas/.rbenv/shims:/Users/lucas/.rbenv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/bin:/bin:/usr/sbin:/sbin

➜  etherpad-lite git:(develop) node -v   
v0.10.28

➜  etherpad-lite git:(develop) npm -v
1.4.9

➜  bbpad4  git clone git://github.com/ether/etherpad-lite.git
Cloning into 'etherpad-lite'...
remote: Reusing existing pack: 21154, done.
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (14/14), done.
cd etherpad-lites:  97% (20591/21168), 16.35 MiB | 1.17 MiB/s   
remote: Total 21168 (delta 2), reused 0 (delta 0)
Receiving objects: 100% (21168/21168), 17.02 MiB | 1.17 MiB/s, done.
Resolving deltas: 100% (14759/14759), done.

➜  bbpad4  cd etherpad-lite 

➜  etherpad-lite git:(develop) bin/run.sh
Copy the settings template to settings.json...
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN engine helenus@0.6.2: wanted: {"node":">=0.6.0 <0.9.0"} (current: {"node":"v0.10.28","npm":"1.4.9"})

> pg@0.14.1 install /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/src/node_modules/ueberDB/node_modules/pg
> node-gyp rebuild || (exit 0)

  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node
  SOLINK_MODULE(target) Release/binding.node: Finished

> ws@0.4.31 install /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN package.json github-url-from-git@1.1.1 No repository field.
channels@0.0.4 node_modules/channels

security@1.0.0 node_modules/security

async-stacktrace@0.0.2 node_modules/async-stacktrace

semver@1.0.13 node_modules/semver

tinycon@0.0.1 node_modules/tinycon

async@0.1.22 node_modules/async

resolve@0.2.8 node_modules/resolve

ejs@0.6.1 node_modules/ejs

require-kernel@1.0.5 node_modules/require-kernel

languages4translatewiki@0.1.3 node_modules/languages4translatewiki

graceful-fs@1.1.5 node_modules/graceful-fs
└── fast-list@1.0.2

unorm@1.0.0 node_modules/unorm

measured@0.1.3 node_modules/measured

slide@1.1.3 node_modules/slide

request@2.9.100 node_modules/request

clean-css@0.3.2 node_modules/clean-css
└── optimist@0.1.9

underscore@1.3.1 node_modules/underscore

yajsml@1.1.6 node_modules/yajsml

formidable@1.0.9 node_modules/formidable

swagger-node-express@1.2.3 node_modules/swagger-node-express
└── docco@0.4.0 (commander@2.2.0)

log4js@0.6.6 node_modules/log4js
├── dequeue@1.0.3
├── semver@1.1.4
├── readable-stream@1.0.27-1 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.25-1, core-util-is@1.0.1)
└── async@0.1.15

connect@2.7.11 node_modules/connect
├── fresh@0.1.0
├── pause@0.0.1
├── cookie-signature@1.0.1
├── qs@0.6.5
├── bytes@0.2.0
├── buffer-crc32@0.2.1
├── cookie@0.0.5
├── debug@1.0.2 (ms@0.6.2)
├── send@0.1.1 (range-parser@0.0.4, mime@1.2.11)
└── formidable@1.0.14

jsonminify@0.2.2 node_modules/jsonminify

uglify-js@1.2.5 node_modules/uglify-js

wd@0.0.31 node_modules/wd
├── vargs@0.1.0
├── q@0.8.12
├── underscore@1.4.4
└── request@2.12.0

nodemailer@0.3.44 node_modules/nodemailer
├── simplesmtp@0.3.32 (xoauth2@0.1.8, rai@0.1.11)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
└── mailcomposer@0.2.11 (dkim-signer@0.1.2, follow-redirects@0.0.3, punycode@1.2.4, mime@1.2.11, he@0.3.6, mimelib@0.2.16)

express@3.1.0 node_modules/express
├── methods@0.0.1
├── fresh@0.1.0
├── cookie-signature@0.0.1
├── range-parser@0.0.4
├── buffer-crc32@0.1.1
├── cookie@0.0.5
├── commander@0.6.1
├── mkdirp@0.3.3
├── debug@1.0.2 (ms@0.6.2)
├── send@0.1.0 (mime@1.2.6)
└── connect@2.7.2 (pause@0.0.1, bytes@0.1.0, formidable@1.0.11, qs@0.5.1)

ueberDB@0.2.2 node_modules/ueberDB
├── channels@0.0.2
├── node-redis@0.1.7
├── dirty@0.9.9
├── async@0.1.15
├── helenus@0.6.2 (node-uuid@1.3.3, helenus-thrift@0.7.3)
├── mysql@0.9.5 (hashish@0.0.4)
└── pg@0.14.1 (deprecate@0.1.0, generic-pool@2.0.4)

jsdom-nocontextifiy@0.2.10 node_modules/jsdom-nocontextifiy
├── cssom@0.2.5
└── htmlparser@1.7.7

socket.io@0.9.17 node_modules/socket.io
├── base64id@0.1.0
├── policyfile@0.0.4
├── redis@0.7.3
└── socket.io-client@0.9.16 (xmlhttprequest@1.4.2, ws@0.4.31, active-x-obfuscator@0.0.1)

npm@1.4.15 node_modules/npm
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
ensure custom css/js files are created...
start...
[2014-06-12 12:15:47.017] [WARN] console - You need to set a sessionKey value in settings.json, this will allow your users to reconnect to your Etherpad Instance if your instance restarts
[2014-06-12 12:15:47.021] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2014-06-12 12:15:47.371] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/fstream requires graceful-fs@'^3.0.2' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/graceful-fs,
which is version 3.0.2 'unmet dependency'
[2014-06-12 12:15:47.373] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/glob requires minimatch@'^0.3.0' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/minimatch,
which is version 0.3.0 'unmet dependency'
[2014-06-12 12:15:47.373] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/glob requires once@'^1.3.0' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/once,
which is version 1.3.0 'unmet dependency'
[2014-06-12 12:15:47.374] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/inflight requires once@'^1.3.0' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/once,
which is version 1.3.0 'unmet dependency'
[2014-06-12 12:15:47.374] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/init-package-json requires glob@'^4.0.2' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/glob,
which is version 4.0.2 'unmet dependency'
[2014-06-12 12:15:47.375] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/npm-install-checks requires semver@'^2.3.0' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/semver,
which is version 2.3.0 'unmet dependency'
[2014-06-12 12:15:47.375] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/npm-registry-client requires npm-cache-filename@'^1.0.0' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/npm-cache-filename,
which is version 1.0.1 'unmet dependency'
[2014-06-12 12:15:47.376] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/npmconf requires ini@'^1.2.0' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/ini,
which is version 1.2.1 'unmet dependency'
[2014-06-12 12:15:47.376] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/npmconf requires osenv@'^0.1.0' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/osenv,
which is version 0.1.0 'unmet dependency'
[2014-06-12 12:15:47.376] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/npmlog requires ansi@'^0.3.0' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/ansi,
which is version 0.3.0 'unmet dependency'
[2014-06-12 12:15:47.376] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/read-package-json requires glob@'^4.0.2' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/glob,
which is version 4.0.2 'unmet dependency'
[2014-06-12 12:15:47.377] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore requires minimatch@'^0.3.0' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/minimatch,
which is version 0.3.0 'unmet dependency'
[2014-06-12 12:15:47.378] [WARN] pluginfw - /Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-username-repo@'^0.2.0' but will load
/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/github-url-from-username-repo,
which is version 0.2.0 'unmet dependency'
[2014-06-12 12:15:47.716] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/swagger:expressCreateServer' for 'ep_etherpad-lite/swagger/hooks/expressCreateServer': Error: npm.load() required
[2014-06-12 12:15:47.738] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/adminsettings:expressCreateServer' for 'ep_etherpad-lite/adminsettings/hooks/expressCreateServer': Error: npm.load() required
[2014-06-12 12:15:47.741] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/adminsettings:socketio' for 'ep_etherpad-lite/adminsettings/hooks/socketio': Error: npm.load() required
[2014-06-12 12:15:47.866] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/socketio:expressCreateServer' for 'ep_etherpad-lite/socketio/hooks/expressCreateServer': Error: npm.load() required
[2014-06-12 12:15:47.869] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/errorhandling:expressCreateServer' for 'ep_etherpad-lite/errorhandling/hooks/expressCreateServer': Error: npm.load() required
[2014-06-12 12:15:47.873] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/importexport:expressCreateServer' for 'ep_etherpad-lite/importexport/hooks/expressCreateServer': Error: npm.load() required
[2014-06-12 12:15:47.883] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/apicalls:expressCreateServer' for 'ep_etherpad-lite/apicalls/hooks/expressCreateServer': Error: npm.load() required
[2014-06-12 12:15:47.884] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/webaccess:expressConfigure' for 'ep_etherpad-lite/webaccess/hooks/expressConfigure': Error: npm.load() required
[2014-06-12 12:15:47.888] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/padreadonly:expressCreateServer' for 'ep_etherpad-lite/padreadonly/hooks/expressCreateServer': Error: npm.load() required
[2014-06-12 12:15:47.890] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/padurlsanitize:expressCreateServer' for 'ep_etherpad-lite/padurlsanitize/hooks/expressCreateServer': Error: npm.load() required
[2014-06-12 12:15:47.924] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/static:expressCreateServer' for 'ep_etherpad-lite/static/hooks/expressCreateServer': Error: npm.load() required
[2014-06-12 12:15:47.927] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express:createServer' for 'ep_etherpad-lite/express/hooks/createServer': Error: npm.load() required
[2014-06-12 12:15:47.929] [ERROR] console - Failed to load '/Users/lucas/Desktop/ruby/bbpad4/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express:restartServer' for 'ep_etherpad-lite/express/hooks/restartServer': Error: npm.load() required
[2014-06-12 12:15:47.931] [INFO] console - Installed plugins: ep_etherpad-lite
```

**Comment by guthikondaa** [comment]
[Pipeline] { (Build)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] echo ([hide](http://13.126.150.221:8080/job/test6/3/console#))
installing dependency
[Pipeline] sh
+ npm install
TypeError: isexe is not a function
    at E (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/lib/node_modules/npm/node_modules/which/which.js:82:7)
    at F (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/lib/node_modules/npm/node_modules/which/which.js:91:7)
    at which (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/lib/node_modules/npm/node_modules/which/which.js:92:5)
    at load (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/lib/node_modules/npm/lib/npm.js:250:5)
    at EventEmitter.npm.load (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/lib/node_modules/npm/lib/npm.js:246:5)
    at /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/lib/node_modules/npm/bin/npm-cli.js:79:7
    at Object.<anonymous> (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/lib/node_modules/npm/bin/npm-cli.js:155:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/lib/node_modules/npm/lib/npm.js:59
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/lib/node_modules/npm/lib/npm.js:59:13)
    at process.errorHandler (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/lib/node_modules/npm/lib/utils/error-handler.js:208:32)
    at process.emit (events.js:376:20)
    at process._fatalException (internal/process/execution.js:163:25)
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 7
Finished: FAILURE
