### ISSUE TITLE
Problem migrating from dirtydb to sqlite

### ISSUE THREAD

**Issue by jparyani** [ether/etherpad-lite#2214]
I'm having problems using bin/migrateDirtyDbtoMysql.js to migrate to sqlite. The script seems to run indefinitely without doing anything. Looking at the script, there doesn't appear to be anything particular to Mysql in it, but is it not intended to be used with sqlite?

If it helps, a dirty.db file that reproduces this for me is up at http://pastebin.com/HuU2KR22.

**Comment by stefan2904** [comment]
(Wow, this issue is from 2014 ...)

I have the same problem ... 

I am trying to migrate from dirtydb to MySQL
using `node bin/migrateDirtyDBtoRealDB.js`

The script runs for ~3 hours (for 600k records) and after it reports successful flushing, the `store` table in MySQL is still empty. No errors are displayed.

**Comment by stefan2904** [comment]
Quickfix, which did the job for me: disable the cache.

In `dbWrapperSettings` set `"writeInterval": 0`

In addition, I needed to increatse node's maximum memory size by calling `node --max-old-space-size=4096 bin/migrateDirtyDBtoRealDB.js` ([source](https://stackoverflow.com/a/38560292/1518225)).

**Comment by muxator** [comment]
@stefan2904, after your experience, would you advise to add `"writeInterval": 0` to the script?

https://github.com/ether/etherpad-lite/blob/c17f5e5f0450d14a00318158df0f65a43233cd6b/bin/migrateDirtyDBtoRealDB.js#L13-L15

Even if it's a workaround, it prevents a behavior that sounds definitely buggy, and costed at least three hours of your time...

**Comment by stefan2904** [comment]
@muxator, I am not entirely sure. It fixed the problem for me, but I am not sure what was wrong in the first place (except too little ram, which was fixed with the mentioned `node` option) and I also don't know what the implications of disabling the cache are (except higher database load).

I can only report the following: without setting `writeInterval` to 0 (= cache enabled) it flushed forever (>3 hours) and then nothing changed in the database. After setting it to 0 (= cache disabled) if wrote every record directly to the database, which worked (and took ~15 minutes). 

But since the script apparently works for other people without the change, I am not sure what was going on  - maybe a ueberDB maintainer knows? Or maybe other people had the same/similar problem, but did not report it? (Or maybe the script is not needed that much and thus no one noticed a problem.)

So maybe adding the line as remark/comment to the code makes sense?

(Also I suggest to add the `for larger dbs, call node the following way: node --max-old-space-size=4096 bin/migrateDirtyDBtoRealDB.js` remark somewhere.)

**Comment by muxator** [comment]
Ok: a user that runs `bin/migrateDirtyDbtoMysql.js` is probably advanced enough to benefit even from a simple code comment. At least we do not leave this information in a Github issue.

Feel free to submit a small PR, @stefan2904, it would be welcome.

**Comment by muxator** [comment]
Aaaand now I need help, @stefan2904.

I was willing to test your recently merged PR (#3519). Also, I have seen that the [original pastebin link from 2014](http://pastebin.com/HuU2KR22) still works, so I wanted to nail it testing on the original use case.

My problem? I cannot get to run the script. It always gets stuck at `Waiting for dirtyDB to parse its file.`, and then halts. This happens both before & after #3519.

In my installation the problem seems to be at

https://github.com/felixge/node-dirty/blob/f52d798146b09e245d9ab9d41df37a2ab1e907c6/lib/dirty/dirty.js#L188

`emit('load')` is called, but no actual callbacks fire.

I am on a clean install (tried with various nodejs versions, and on latest Etherpad).

**Comment by JohnMcLear** [comment]
``dirty.load`` is reporting ``length`` as 140 items
``dirty.forEach`` is only providing 135 results 🗡️

**Comment by JohnMcLear** [comment]
PR in with fix.  Lulz what a mess ;)  6 years tho?!  Really?!

**Comment by TheCrether** [comment]
Hi, so after trying to use the script with `node --max-old-space-size=4096 bin/migrateDirtyDBtoRealDB.js` it errors for all entries with this:
```
2020-10-31 16:28:58.006] [ERROR] console - (node:31631) UnhandledPromiseRejectionWarning: ReferenceError: _this is not defined
    at exports.database.exports.set (/home/crether/CTFPad/etherpad-lite/src/node_modules/ueberdb2/databases/postgres_common.js:141:19)
    at exports.database.set (/home/crether/CTFPad/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:290:22)
    at exports.channels.doOperation [as operatorFunction] (/home/crether/CTFPad/etherpad-lite/src/node_modules/ueberdb2/index.js:140:18)
    at exports.channels.emit (/home/crether/CTFPad/etherpad-lite/src/node_modules/channels/channels.js:49:11)
    at exports.database.set (/home/crether/CTFPad/etherpad-lite/src/node_modules/ueberdb2/index.js:85:17)
    at /home/crether/CTFPad/etherpad-lite/bin/migrateDirtyDBtoRealDB.js:34:30
    at exports.Dirty.Dirty.forEach (/home/crether/CTFPad/etherpad-lite/src/node_modules/dirty/lib/dirty/dirty.js:91:9)
    at exports.Dirty.<anonymous> (/home/crether/CTFPad/etherpad-lite/bin/migrateDirtyDBtoRealDB.js:33:13)
    at exports.Dirty.emit (events.js:314:20)
    at exports.Dirty.EventEmitter.emit (domain.js:483:12)
[2020-10-31 16:28:58.006] [ERROR] console - (node:31631) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 19243)
```

I then just tried removing the `"writeInterval": 0` and it suddenly worked. This is a really weird problem and the fix apparently doesn't work all the time.
