### ISSUE TITLE
etherpad-lite 1.4.0 crashes with Can't have op.lines of 2 in attribution lines Failed assertion

### ISSUE THREAD

**Issue by akosiaris** [ether/etherpad-lite#2215]
Recently we had etherpad-lite crash twice in 5 minutes with the folllowing assertion. It is not clear what have caused that or how to reproduce it. We run a public pad and logs don't help to pinpoint a specific pad. We ran 1.4.0. Opening a ticket so that it may be known/looked at

[ERROR] console - Error: Failed assertion: Can't have op.lines of 2 in attribution lines
    at Object.error (/usr/share/etherpad-lite/src/static/js/Changeset.js:39:11)
    at Object.assert (/usr/share/etherpad-lite/src/static/js/Changeset.js:53:13)
    at outputMutOp (/usr/share/etherpad-lite/src/static/js/Changeset.js:1167:15)
    at Object.exports.mutateAttributionLines (/usr/share/etherpad-lite/src/static/js/Changeset.js:1213:9)
    at async.series.callback.forwardsChangesets (/usr/share/etherpad-lite/src/node/handler/PadMessageHandler.js:1392:19)
    at async.series.results (/usr/share/etherpad-lite/src/node_modules/async/lib/async.js:486:21)
    at _asyncMap (/usr/share/etherpad-lite/src/node_modules/async/lib/async.js:185:13)
    at async.forEachSeries.iterate (/usr/share/etherpad-lite/src/node_modules/async/lib/async.js:108:13)
    at async.forEachSeries.iterate (/usr/share/etherpad-lite/src/node_modules/async/lib/async.js:119:25)
    at _asyncMap (/usr/share/etherpad-lite/src/node_modules/async/lib/async.js:187:17)
[INFO] console - graceful shutdown...

**Comment by JohnMcLear** [comment]
@webzwo0i did this fix get merged in?  If so we can close this issue :)

**Comment by JohnMcLear** [comment]
Closing because we're not seeing this any more.
