### ISSUE TITLE
Uncaught Error: The module at "ep_etherpad-lite/static/js/pad.js" does not exist.

### ISSUE THREAD

**Issue by eusonlito** [ether/etherpad-lite#2371]
I have done this actions:

```bash
$> git clone git://github.com/ether/etherpad-lite.git etherpad
$> cd etherpad
$> git checkout develop
$> vi settings.json # Enabled Auth
$> bin/run.sh
```

```
...
Started Etherpad...
[2014-12-12 15:15:00.851] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2014-12-12 15:15:02.589] [INFO] console - Installed plugins: ep_etherpad-lite
[2014-12-12 15:15:02.607] [INFO] console - Your Etherpad git version is e57c8fa
[2014-12-12 15:15:02.607] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2014-12-12 15:15:02.638] [WARN] console - setAppHandler is deprecated!  Pass it to the constructor instead.
[2014-12-12 15:15:02.643] [WARN] console - setAppHandler is deprecated!  Pass it to the constructor instead.
[2014-12-12 15:15:02.646] [WARN] console - setAppHandler is deprecated!  Pass it to the constructor instead.
[2014-12-12 15:15:02.649] [WARN] console - setAppHandler is deprecated!  Pass it to the constructor instead.
[2014-12-12 15:15:02.652] [WARN] console - setAppHandler is deprecated!  Pass it to the constructor instead.
[2014-12-12 15:15:02.662] [WARN] console - setAppHandler is deprecated!  Pass it to the constructor instead.
[2014-12-12 15:15:02.665] [WARN] console - setAppHandler is deprecated!  Pass it to the constructor instead.
[2014-12-12 15:15:02.667] [WARN] console - setAppHandler is deprecated!  Pass it to the constructor instead.
[2014-12-12 15:15:02.671] [WARN] console - setAppHandler is deprecated!  Pass it to the constructor instead.
[2014-12-12 15:15:02.722] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
```
But if I login into http://0.0.0.0:9001/ I get

```
[2014-12-12 15:15:12.292] [WARN] message - Authentication try failed:{"component":"pad","type":"CLIENT_READY","padId":"lVvplP49iB","sessionID":"null","password":null,"token":"t.Urved49OhOBVmu2A1XBN","protocolVersion":2}
[2014-12-12 15:15:12.489] [WARN] client - Uncaught Error: The module at "ep_etherpad-lite/static/js/pad.js" does not exist. -- { errorId: 'c37wiJv6k0Oar64KD3w7',
  msg: 'Uncaught Error: The module at "ep_etherpad-lite/static/js/pad.js" does not exist.',
  url: 'http://domain.com:9001/p/lVvplP49iB',
  linenumber: 588,
  userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.38 Safari/537.36' }
[2014-12-12 15:15:15.874] [WARN] message - Authentication try failed:{"component":"pad","type":"CLIENT_READY","padId":"lVvplP49iB","sessionID":"null","password":null,"token":"t.Urved49OhOBVmu2A1XBN","protocolVersion":2}
[2014-12-12 15:15:15.993] [WARN] client - Uncaught Error: The module at "ep_etherpad-lite/static/js/pad.js" does not exist. -- { errorId: '0yIK4vqXty6E4uuAeHvG',
  msg: 'Uncaught Error: The module at "ep_etherpad-lite/static/js/pad.js" does not exist.',
  url: 'http://domain.com:9001/p/lVvplP49iB',
  linenumber: 588,
  userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.38 Safari/537.36' }
```

I'm using an apache proxy configured as:

```
<VirtualHost *:443>
  ServerAdmin webmaster@domain.com
  ServerName domain.com
  ServerSignature Off

  ErrorLog /var/log/apache2/domain.com-error.log
  CustomLog /var/log/apache2/domain.com-access.log combined

  ProxyVia On
  ProxyRequests Off
  ProxyPreserveHost on

  <Proxy *>
    Options FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
  </Proxy>

  <Location />
    Options -Indexes

    AuthType Basic
    AuthName "A Navalla Suiza - Office"
    AuthBasicProvider file
    AuthUserFile /var/www/domain.com/conf/.passwd

    Require valid-user

    ProxyPass http://0.0.0.0:9001/
    ProxyPassReverse http://0.0.0.0:9001/
  </Location>

  <Location /socket.io>
    RewriteEngine On
    RewriteCond %{QUERY_STRING} transport=websocket    [NC]
    RewriteRule /(.*) ws://0.0.0.0:9001/socket.io/$1 [P,L]

    ProxyPass http://0.0.0.0:9001/socket.io
    ProxyPassReverse http://0.0.0.0:9001/socket.io
  </Location>

  SSLEngine on
  SSLVerifyClient none
  SSLCertificateFile /etc/apache2/ssl/domain.com.crt
  SSLCertificateKeyFile /etc/apache2/ssl/domain.com.key
  SSLCertificateChainFile /etc/apache2/ssl/gd_bundle.crt
  SSLCipherSuite ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP
  SetEnvIf User-Agent ".*MSIE.*" nokeepalive ssl-unclean-shutdown
</VirtualHost>
```

Apache error is:

```
[Fri Dec 12 15:14:21.177000 2014] [proxy_http:error] [pid 912] (20014)Internal error: [client 83.165.197.228:45684] AH01102: error reading status line from remote server 0.0.0.0:9001, referer: https://domain.com/p/Imp5QxbAn7
[Fri Dec 12 15:14:21.184138 2014] [proxy:error] [pid 915] (111)Connection refused: AH00957: HTTP: attempt to connect to 0.0.0.0:9001 (0.0.0.0) failed
[Fri Dec 12 15:14:21.184172 2014] [proxy:error] [pid 915] AH00959: ap_proxy_connect_backend disabling worker for (0.0.0.0) for 60s
[Fri Dec 12 15:14:21.184182 2014] [proxy_http:error] [pid 915] [client 83.165.197.228:45697] AH01114: HTTP: failed to make connection to backend: 0.0.0.0, referer: https://domain.com/p/Imp5QxbAn7
[Fri Dec 12 15:14:21.235613 2014] [proxy:error] [pid 917] (111)Connection refused: AH00957: HTTP: attempt to connect to 0.0.0.0:9001 (0.0.0.0) failed
[Fri Dec 12 15:14:21.235646 2014] [proxy:error] [pid 917] AH00959: ap_proxy_connect_backend disabling worker for (0.0.0.0) for 60s
[Fri Dec 12 15:14:21.235655 2014] [proxy_http:error] [pid 917] [client 83.165.197.228:45699] AH01114: HTTP: failed to make connection to backend: 0.0.0.0, referer: https://domain.com/p/Imp5QxbAn7
```

Using master branch it works, but cookie auth is not working with Proxy (https://github.com/ether/etherpad-lite/issues/1944)

Regards,
Lito.

**Comment by brecke** [comment]
Any solution to this? I get this error even without apache in front of 9001. Help?

**Comment by JohnMcLear** [comment]
Assuming you are doing a new install, it souds like it didn't finish..

Clean your install
```
rm -Rf src/node_modules
bin/run.sh
```

**Comment by brecke** [comment]
Tried it, same result. I get the following on the console:

```
[2015-02-03 12:02:34.484] [WARN] client - Error: The module at "ep_etherpad-lite/static/js/pad.js" does not exist. -- { errorId: 'faGK1A9Oq43jSbcSEvj9',
  msg: 'Error: The module at "ep_etherpad-lite/static/js/pad.js" does not exist.',
```

The weird thing is, ``ep_etherpad-lite/static/js/pad.js`` does exist if you're following symlinks, via ``etherpad-lite/node_modules/ep_etherpad-lite`` as in ``cd`` command. Any ideas?

**Comment by JohnMcLear** [comment]
Do a full clean install..

**Comment by sebschrader** [comment]
I'm affected by the same issue, but only with some pads. I did a clean install and imported pads from the original Etherpad to Etherpad-Lite using convert.js. Debugging using Firefox shows that the exception is triggered by this import:
https://github.com/ether/etherpad-lite/blob/b9802616b6cab99a43b470972f62f24fcc21f473/src/static/js/pad.js#L266

So it appears that the module tries to require itself.

**Comment by JohnMcLear** [comment]
Export your pad and share it?
----- Reply message -----

**Comment by sebschrader** [comment]
It's rather difficult to export a broken pad if i can't access it using the UI. I queried the database to get a pad:
https://gist.github.com/sebschrader/4fb19140bacd129cdc4f
I used the following where clause:
```
`key` LIKE "%<PADID>%"
```

**Comment by JohnMcLear** [comment]
@sebschrader all pads are available via the /export endpoint..  IE

http://beta.etherpad.org/p/test/export/etherpad

Just replace your url and padid with the broken pad.

**Comment by sebschrader** [comment]
If I try to export broken pads I get a
```
403 - Can't touch this
```
error.

**Comment by sebschrader** [comment]
Probably unrelated, but exporting a working pad, is actually crashing the server. This can even be demonstrated using the example link you posted yourself. After using that link you get a 
```
502 Bad Gateway
```
from https://beta.etherpad.org for a few seconds.

Here's a traceback from the instance I run:
```
[2015-02-16 23:20:01.838] [ERROR] console - TypeError: Cannot set property 'padIDs' of null
    at Object.callback (/srv/web/etherpad-lite.ifsr.de/src/node/utils/ExportEtherpad.js:51:36)
    at /srv/web/etherpad-lite.ifsr.de/src/node_modules/ueberDB/CloneAndAtomicLayer.js:100:17
    at /srv/web/etherpad-lite.ifsr.de/src/node_modules/ueberDB/CacheAndBufferLayer.js:185:7
    at Query._callback (/srv/web/etherpad-lite.ifsr.de/src/node_modules/ueberDB/mysql_db.js:116:5)
    at Query.Sequence.end (/srv/web/etherpad-lite.ifsr.de/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/srv/web/etherpad-lite.ifsr.de/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/srv/web/etherpad-lite.ifsr.de/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/srv/web/etherpad-lite.ifsr.de/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/srv/web/etherpad-lite.ifsr.de/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/srv/web/etherpad-lite.ifsr.de/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:39:16)
```

**Comment by webzwo0i** [comment]
Is your mysql really utf8? Had the same issue with special character in author names and non-utf8 database. Also had this issue with the dirty.db-sttore.
But yes, thats another unrelated bug

**Comment by webzwo0i** [comment]
also happens with empty authors. the only empty authors I see are from the newline changesets automatically inserted by etherpad

**Comment by webzwo0i** [comment]
the issue in the original bug report is resolved in develop, so if you experience 'Uncaught Error: The module at "ep_etherpad-lite/static/js/pad.js" does not exist.' please update.
Will open another issue for this other crash report

**Comment by JohnMcLear** [comment]
Fixed Export issue :)
