### ISSUE TITLE
Server crash "Failed assertion: line assembler not finished"

### ISSUE THREAD

**Issue by Gared** [ether/etherpad-lite#2375]
My server crashes nearly every hour caused by this exception:
```
[2014-12-16 09:43:42.298] [ERROR] console - Error: Failed assertion: line assembler not finished
    at Object.error (/eplite/src/static/js/Changeset.js:39:11)
    at Object.assert (/eplite/src/static/js/Changeset.js:53:13)
    at Object.exports.mutateAttributionLines (/eplite/src/static/js/Changeset.js:1219:11)
    at async.series.callback.forwardsChangesets (/eplite/src/node/handler/PadMessageHandler.js:1399:19)
    at async.series.results (/eplite/src/node_modules/async/lib/async.js:486:21)
    at _asyncMap (/eplite/src/node_modules/async/lib/async.js:185:13)
    at async.forEachSeries.iterate (/eplite/src/node_modules/async/lib/async.js:108:13)
    at async.forEachSeries.iterate (/eplite/src/node_modules/async/lib/async.js:119:25)
    at _asyncMap (/eplite/src/node_modules/async/lib/async.js:187:17)
    at async.series.results (/eplite/src/node_modules/async/lib/async.js:491:34)
```

**Comment by Gared** [comment]
The last time the error occured was a few days ago. So if I pull develop I can't be really sure that this fixes the problem. I will reopen this issue if I get further errors.

**Comment by JohnMcLear** [comment]
Same :-) thanks
----- Reply message -----
