### ISSUE TITLE
Etherpad-lite restarts after ueberDB Connection lost

### ISSUE THREAD

**Issue by StephenKing** [ether/etherpad-lite#2390]
Hi,

our etherpad-lite is restarting over and over again (after seconds or minutes) with the following message:

```
[2014-12-23 13:58:57.013] [ERROR] console - Error: Connection lost: The server closed the connection.
    at Protocol.end (/usr/local/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:103:13)
    at Socket.<anonymous> (/usr/local/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)
```

This looks similar to #2100, however, nobody restarts the MySQL server running on `localhost`.

I can reproduce it in a clean install (based on this [chef cookbook](https://github.com/TYPO3-cookbooks/site-notestypo3org)) without any plugins installed. The full log is here: https://gist.github.com/StephenKing/61560de66c9b31e3312d.

**Comment by BlackyFox** [comment]
Hi all ! I still have this issue with the latest version of EP and ep_user_pad and ep_user_pad_frontend.. 
I try updating the MySQL NPM package for those two plugins but it doesn't help.. I know this is caused by those plugins, but you might know how to solve it !

The only trick I found was in the /etc/mysql/my.cnf file. 
I changed the wait_timeout time to something bigger to make it loose the connection on a longer time.

FYI, I'm running last github version on a Debian 7. And the error is :
```bash
[2015-07-30 14:33:46.086] [ERROR] console - Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/antoine/Bureau/test_ep_etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/mysql/lib/protocol/Protocol.js:103:13)
    at Socket.<anonymous> (/home/antoine/Bureau/test_ep_etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
[2015-07-30 14:33:46.087] [INFO] console - graceful shutdown...
[2015-07-30 14:33:46.130] [INFO] console - db sucessfully closed.
```
