### ISSUE TITLE
Error while handling a changeset request for test { [Error: Failed assertion: mismatched apply: 18 / 16] easysync: true 

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2430]
```
[2015-01-02 18:29:00.821] [ERROR] console - Error while handling a changeset request for test { [Error: Failed assertion: mismatched apply: 18 / 16] easysync: true }
Async Stacktrace:
    at /home/jose/etherpad-lite/src/node/handler/PadMessageHandler.js:1514:8
    at /home/jose/etherpad-lite/src/node/handler/PadMessageHandler.js:1462:16
    at /home/jose/etherpad-lite/src/node/handler/PadMessageHandler.js:1573:8
    at /home/jose/etherpad-lite/src/node/handler/PadMessageHandler.js:1554:14
    at /home/jose/etherpad-lite/src/node/db/Pad.js:216:8

Error: Failed assertion: mismatched apply: 18 / 16
    at Object.error (/home/jose/etherpad-lite/src/static/js/Changeset.js:39:11)
    at Object.assert (/home/jose/etherpad-lite/src/static/js/Changeset.js:53:13)
    at Object.exports.applyToText (/home/jose/etherpad-lite/src/static/js/Changeset.js:915:11)
    at Object.exports.applyToAText (/home/jose/etherpad-lite/src/static/js/Changeset.js:1618:22)
    at /home/jose/etherpad-lite/src/node/db/Pad.js:206:29
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:610:21
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:249:17
    at iterate (/home/jose/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:160:25
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:251:21 { start: 2000, granularity: 10, requestID: 84765 }
```

**Comment by JohnMcLear** [comment]
```
[2015-01-02 18:49:27.316] [INFO] access - [ENTER] Pad "release-150": Client wmrYFgRpj8yUmNqMAABG with IP "82.41.200.220" entered the pad
[2015-01-02 18:49:27.357] [ERROR] console - Error: Failed assertion: mismatched composition of two changesets
    at Object.error (/home/jose/etherpad-lite/src/static/js/Changeset.js:39:11)
    at Object.assert (/home/jose/etherpad-lite/src/static/js/Changeset.js:53:13)
    at Object.exports.compose (/home/jose/etherpad-lite/src/static/js/Changeset.js:1319:11)
    at /home/jose/etherpad-lite/src/node/handler/PadMessageHandler.js:1636:31
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:610:21
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:249:17
    at iterate (/home/jose/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:160:25
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:251:21
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:615:34
[2015-01-02 18:49:27.358] [INFO] console - graceful shutdown...
[2015-01-02 18:49:27.386] [INFO] ueberDB - Flushed 3 values
[2015-01-02 18:49:27.424] [ERROR] console - Error while handling a changeset request for Test { [Error: Failed assertion: mismatched apply: 18 / 16] easysync: true }
Async Stacktrace:
    at /home/jose/etherpad-lite/src/node/handler/PadMessageHandler.js:1514:8
    at /home/jose/etherpad-lite/src/node/handler/PadMessageHandler.js:1462:16
    at /home/jose/etherpad-lite/src/node/handler/PadMessageHandler.js:1573:8
    at /home/jose/etherpad-lite/src/node/handler/PadMessageHandler.js:1554:14
    at /home/jose/etherpad-lite/src/node/db/Pad.js:216:8

Error: Failed assertion: mismatched apply: 18 / 16
    at Object.error (/home/jose/etherpad-lite/src/static/js/Changeset.js:39:11)
    at Object.assert (/home/jose/etherpad-lite/src/static/js/Changeset.js:53:13)
    at Object.exports.applyToText (/home/jose/etherpad-lite/src/static/js/Changeset.js:915:11)
    at Object.exports.applyToAText (/home/jose/etherpad-lite/src/static/js/Changeset.js:1618:22)
    at /home/jose/etherpad-lite/src/node/db/Pad.js:206:29
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:610:21
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:249:17
    at iterate (/home/jose/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:160:25
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:251:21 { start: 2000, granularity: 10, requestID: 49419 }
[2015-01-02 18:49:27.460] [WARN] message - Dropped message cause of bad permissions:{"type":"COLLABROOM","component":"pad","data":{"type":"cursor","action":"cursorPosition","locationY":8,"locationX":67,"padId":"mkJRDKgaFP","myAuthorId":"a.1QX931JRONhjoCbO"}}

```

**Comment by JohnMcLear** [comment]
Worst of all we're hitting crashes w/ out stack traces...

**Comment by JohnMcLear** [comment]
cc @marcelklehr

**Comment by marcelklehr** [comment]
I have no idea.

**Comment by webzwo0i** [comment]
i tried to debug this, but i think i crashed beta.etherpad.org... i am so sorry, could you paste the stacktrace? happens at revision 85 in pad "test", so i would look at this specific changeset

**Comment by JohnMcLear** [comment]
Haha yeah don't debug there please!

Crash was caused by a plugin I'm working on.

----- Reply message -----
