### ISSUE TITLE
Error "Something bad happened"

### ISSUE THREAD

**Issue by SPQRInc** [ether/etherpad-lite#2435]
I installed etherpad-lite on Debian 7 - I also configured NPM and Node.js, but if I try to open etherpad, I'm getting this error:

{ "error": "Sorry, something bad happened!" }

On the console I'm getting:

etherpad@pad:~/local/etherpad/etherpad-lite$ bin/run.sh
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json async-stacktrace@0.0.2 No repository field.
npm WARN package.json channels@0.0.4 No repository field.
npm WARN package.json tinycon@0.0.1 No repository field.
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-01-04 09:28:17.369] [INFO] console - Installed plugins: ep_etherpad-lite
[2015-01-04 09:28:17.384] [INFO] console - Your Etherpad git version is e2ea82f
[2015-01-04 09:28:17.385] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2015-01-04 09:28:17.499] [INFO] console - You can access your Etherpad instance at http://5.104.111.151:9001/
[2015-01-04 09:28:17.500] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
[2015-01-04 09:28:26.339] [ERROR] console - ReferenceError: ejs:1
 >> 1| <% e._init(buf); %><%
    2|   var settings = require("ep_etherpad-lite/node/utils/Settings");
    3| %>
    4| <!doctype html>

buf is not defined
    at eval (eval at <anonymous> (/opt/etherpad/local/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:281:12), <anonymous>:2:8000)
    at /opt/etherpad/local/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:307:17
    at Object.exports.render (/opt/etherpad/local/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:166:13)
    at Object.exports.require (/opt/etherpad/local/etherpad/etherpad-lite/src/node/eejs/index.js:122:17)
    at /opt/etherpad/local/etherpad/etherpad-lite/src/node/hooks/express/specialpages.js:15:19
    at callbacks (/opt/etherpad/local/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:164:37)
    at param (/opt/etherpad/local/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:138:11)
    at pass (/opt/etherpad/local/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/opt/etherpad/local/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/opt/etherpad/local/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:33:10)
[2015-01-04 09:28:26.422] [INFO] ueberDB - Flushed 1 values
^C[2015-01-04 09:29:13.354] [INFO] console - graceful shutdown...
[2015-01-04 09:29:13.433] [INFO] console - db sucessfully closed.

Any idea, what I can do here to solve this?

**Comment by JohnMcLear** [comment]
Do a clean install
----- Reply message -----

**Comment by SPQRInc** [comment]
Hi John,
it was a clean install :-(

**Comment by JohnMcLear** [comment]
Yeah I know and something went wrong so try again
----- Reply message -----

**Comment by SPQRInc** [comment]
Hm, it was my second attempt, but I'll try it a third time..
