### ISSUE TITLE
console - ReferenceError: ejs:1 ("Sorry, something bad happened")

### ISSUE THREAD

**Issue by SPQRInc** [ether/etherpad-lite#2437]
Hi there,

my last issue was closed, but the error still appears...

I installed Etherpad on CentOS according to this tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-etherpad-for-production-with-node-js-and-mysql-on-a-vps

I did a fresh install - unfortunately I'm getting this error:

[2015-01-04 18:08:20.111] [ERROR] console - ReferenceError: ejs:1
 >> 1| <% e._init(buf); %><%
    2|   var settings = require("ep_etherpad-lite/node/utils/Settings");
    3| %>
    4| <!doctype html>

buf is not defined
    at eval (eval at <anonymous> (/home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:281:12), <anonymous>:2:145)
    at /home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:307:17
    at Object.exports.render (/home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:166:13)
    at Object.exports.require (/home/etherpad/etherpad-lite/src/node/eejs/index.js:122:17)
    at /home/etherpad/etherpad-lite/src/node/hooks/express/specialpages.js:15:19
    at callbacks (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:164:37)
    at param (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:33:10)

If I start etherpad, I'm getting this error:

[etherpad@pad etherpad-lite]$ ./bin/run.sh
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json async-stacktrace@0.0.2 No repository field.
npm WARN package.json channels@0.0.4 No repository field.
npm WARN package.json tinycon@0.0.1 No repository field.
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-01-04 18:11:08.173] [INFO] console - Installed plugins: ep_etherpad-lite
[2015-01-04 18:11:08.192] [INFO] console - Your Etherpad git version is e2ea82f
[2015-01-04 18:11:08.192] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2015-01-04 18:11:08.320] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2015-01-04 18:11:08.321] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json

If I try to open etherpad via browser, the browser-output is:

{
  "error": "Sorry, something bad happened!"
}

The console shows:

[2015-01-04 18:11:50.853] [ERROR] console - ReferenceError: ejs:1
 >> 1| <% e._init(buf); %><%
    2|   var settings = require("ep_etherpad-lite/node/utils/Settings");
    3| %>
    4| <!doctype html>

buf is not defined
    at eval (eval at <anonymous> (/home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:281:12), <anonymous>:2:8000)
    at /home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:307:17
    at Object.exports.render (/home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:166:13)
    at Object.exports.require (/home/etherpad/etherpad-lite/src/node/eejs/index.js:122:17)
    at /home/etherpad/etherpad-lite/src/node/hooks/express/specialpages.js:15:19
    at callbacks (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:164:37)
    at param (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:33:10)
[2015-01-04 18:11:50.920] [INFO] ueberDB - Flushed 1 values

This error was on Debian 7 and now on CentOS - the VPS was always a fresh setup.

**Comment by JohnMcLear** [comment]
Use the official docs please.  If the problem still persists while using these docs let us know
----- Reply message -----

**Comment by SPQRInc** [comment]
Followed this doc: https://github.com/ether/etherpad-lite/blob/master/README.md

Same result. :-(

**Comment by zougoulou59** [comment]
Hi
I have the same error on ubuntu 12.04
It happened today after updating my fonctionnal etherpad-lite. I tried a fresh install, same error.
I went back to a backup.
Any ideas ?

**Comment by JohnMcLear** [comment]
I just tried building from develop and master and it's working fine, windows, centos and debian.

**Comment by btwe** [comment]
Sry, but same issue here:
```bash
$ node --version
v0.10.35
$ git describe
1.5.0-1-gcbfc833

$ ./bin/run.sh 
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json async-stacktrace@0.0.2 No repository field.
npm WARN package.json channels@0.0.4 No repository field.
npm WARN package.json tinycon@0.0.1 No repository field.
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-01-04 20:09:40.482] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2015-01-04 20:09:42.147] [INFO] console - Installed plugins: ep_etherpad-lite
[2015-01-04 20:09:42.182] [INFO] console - Your Etherpad git version is cbfc833
[2015-01-04 20:09:42.183] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2015-01-04 20:09:42.375] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2015-01-04 20:09:42.376] [INFO] console - The plugin admin page is at http://0.0.0.0:9001/admin/plugins
[2015-01-04 20:09:55.051] [ERROR] console - ReferenceError: ejs:1
 >> 1| <% e._init(buf); %><%
    2|   var settings = require("ep_etherpad-lite/node/utils/Settings");
    3| %>
    4| <!doctype html>

buf is not defined
    at eval (eval at <anonymous> (/home/etherpad/local/src/etherpad-lite/src/node_modules/ejs/lib/ejs.js:281:12), <anonymous>:2:8000)
    at /home/etherpad/local/src/etherpad-lite/src/node_modules/ejs/lib/ejs.js:307:17
    at Object.exports.render (/home/etherpad/local/src/etherpad-lite/src/node_modules/ejs/lib/ejs.js:166:13)
    at Object.exports.require (/home/etherpad/local/src/etherpad-lite/src/node/eejs/index.js:122:17)
    at /home/etherpad/local/src/etherpad-lite/src/node/hooks/express/specialpages.js:15:19
    at callbacks (/home/etherpad/local/src/etherpad-lite/src/node_modules/express/lib/router/index.js:164:37)
    at param (/home/etherpad/local/src/etherpad-lite/src/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/etherpad/local/src/etherpad-lite/src/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/home/etherpad/local/src/etherpad-lite/src/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/home/etherpad/local/src/etherpad-lite/src/node_modules/express/lib/router/index.js:33:10)

```

**Comment by JohnMcLear** [comment]
Okay what the fsck...

Was developing plugins, restarted maybe 50 times and then this suddenly came up..  No updates or anything..

```
[2015-01-04 20:49:55.595] [ERROR] console - ReferenceError: ejs:1
 >> 1| <% e._init(buf); %><%
    2|   var settings = require("ep_etherpad-lite/node/utils/Settings")
    3|     , hooks = require('ep_etherpad-lite/static/js/pluginfw/hooks')
    4|     , langs = require("ep_etherpad-lite/node/hooks/i18n").availableLangs

buf is not defined
    at eval (eval at <anonymous> (/home/jose/etherpad-lite/src/node_modules/ejs/lib/ejs.js:281:12), <anonymous>:2:21291)
    at /home/jose/etherpad-lite/src/node_modules/ejs/lib/ejs.js:307:17
    at Object.exports.render (/home/jose/etherpad-lite/src/node_modules/ejs/lib/ejs.js:166:13)
    at Object.exports.require (/home/jose/etherpad-lite/src/node/eejs/index.js:122:17)
    at /home/jose/etherpad-lite/src/node/hooks/express/specialpages.js:40:19
    at callbacks (/home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:164:37)
    at param (/home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:138:11)
    at paramCallback (/home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:150:30)
    at /home/jose/etherpad-lite/src/node/hooks/express/padurlsanitize.js:27:11
    at /home/jose/etherpad-lite/src/node/db/PadManager.js:217:9
```
No updates etc..  I will investigate..

**Comment by JohnMcLear** [comment]
Caused by https://github.com/mde/ejs

**Comment by JohnMcLear** [comment]
As a temporary fix change src/packages.json ejs to version 1..  The author of EJS dropped the ball here.

**Comment by SPQRInc** [comment]
Hi John,
thanks for your fast response. Sorry, English is not my mother language so pardon me, if I don't understand everything... 

What exactly do I have to change?

Should I edit something in src/packages.json?

Maybe this 

"ejs"                     : ">=1.0.0",

?

**Comment by wetterfrosch** [comment]
SPQRInc,
yes - remove the ">=" and say "make" in the base-directory of etherpad-lite/

worked for me, thanks John

**Comment by amalba21** [comment]
Worked also for me.

Thanks a lot John.

**Comment by mikowi** [comment]
Worked for me as well, thank you John.

btw: I have another instance running in a VM on exactly the same Env and it works without the change....

**Comment by zougoulou59** [comment]
Worked for me.
thanks everyone.

**Comment by JohnMcLear** [comment]
@mbe is taking a look now, should hopefully have a fix in ASAP..  Sorry if I was a bit abrupt..

**Comment by mde** [comment]
Apparently what's happening here is that the EtherpadLite bootstrapping code is actually using the internals of the EJS lib -- directly accessing the internal `buf` variable which is used to build the output. I've put in a shim (in v2.0.6) to unbreak your app, but obviously relying on undocumented internals of any library is not a great idea and you probably shouldn't do it.

As a side note, you might also consider locking down the versions for your dependencies, to either MINOR or PATCH, depending on whether you want just bugfixes, or backward-compatible new features. http://semver.org/ has a good summary of what to expect from changes at each version. I've been bitten in the ass by unceremonious upgrades myself, so I know how frustrating this stuff can be. Sorry this change broke your app.

**Comment by JohnMcLear** [comment]
Excellent thanks :)  Yea you are right we shouldn't depend on internals, any chance you can expose our solution as something graceful?

RE Semver, how about I set it as ~2.0.0 and we can be your guinea pigs? :)

**Comment by mde** [comment]
I have no idea why you'd be needing to access the EJS internals for just rendering a template. That code is pretty dense -- any idea who wrote that code, and why they couldn't use the documented API? If it's genuinely doing something special (I'm trying to imagine -- rendering template chunks in a series or something?) that needs to be supported, then there should be a tested API for you to use.

I'll do a minor version rev if I remove that shim or add any new functionality, so you should be good with your current code with either "~2.0.0" or "2.0.x".

**Comment by JohnMcLear** [comment]
@mde @redhog wrote the code and it's pretty old now so it's probable the API endpoints didn't exist when we did our implementation!

**Comment by JohnMcLear** [comment]
@mde The shim stopped plugins from displaying

**Comment by baptistedonaux** [comment]
It's possible to tag the current version with a tag 1.5.0-rc1 for example ?

**Comment by JohnMcLear** [comment]
@baptistedonaux go for it, the release docs are on the wiki, anyone can do it :)  I'd take a 1.5.1 to keep things simple

**Comment by baptistedonaux** [comment]
Yeah, great ! Thank for your job !

**Comment by JohnMcLear** [comment]
@baptistedonaux how's that release coming along?

**Comment by JohnMcLear** [comment]
Reopened with the hope @mde gets a solid fix in and we can bump..

**Comment by mde** [comment]
I've just started a brand-new job and it's unlikely I'll have a ton of time for the deep-dive into EtherPad Lite codebase needed to debug the use of the EJS v1 internals. A much easier fix for you would be to freeze your EJS version to the "1.0.0" exactly. That version of the lib in NPM is never going away.

**Comment by jmkolbe** [comment]
Maybe ejs should be set to "=1.0.0" in the release branches too?

**Comment by JohnMcLear** [comment]
@jmkolbe it already is.

**Comment by JohnMcLear** [comment]
@mde all you will need is : https://github.com/ether/etherpad-lite/blob/develop/src/node/eejs/index.js and the examples directory: https://github.com/ether/etherpad-lite/tree/develop/src/node/eejs/examples -- this should give you enough insight to get a proper "feature" into ejs so we don't have to hack into the internals?

**Comment by JohnMcLear** [comment]
For now we have a hack in place, using __output instead of buf.

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/commit/acc1a0626a71fa78d9e743abe3188dd9bc91cf9f is our commit for the hack we did

**Comment by redhog** [comment]
@mde TL;DR:

https://github.com/ether/etherpad-lite/blob/develop/src/node/eejs/index.js

is a mini-library we use that implements django-style blocks and inheritance on top of EJS. It's totally independent of the rest of Etherpad.

**Comment by gulaschskanone** [comment]
Hello guys,
after checkout release/1.5.6 (from release/1.5.2) we got almost the same error:

--------------------------
[2015-05-28 16:56:51.320] [ERROR] console - ReferenceError: ejs:1
 >> 1| <% e._init(__output); %><%
    2|   var settings = require("ep_etherpad-lite/node/utils/Settings");
    3| %>
    4| <!doctype html>

__output is not defined
[...]
--------------------------

and

--------------------------
[2015-05-28 16:54:22.709] [ERROR] console - TypeError: undefined is not a function
    at /opt/etherpad-lite/src/node/hooks/express/specialpages.js:63:9
    at callbacks (/opt/etherpad-lite/src/node_modules/express/lib/router/index.js:164:37)
    at param (/opt/etherpad-lite/src/node_modules/express/lib/router/index.js:138:11)
    at pass (/opt/etherpad-lite/src/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/opt/etherpad-lite/src/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/opt/etherpad-lite/src/node_modules/express/lib/router/index.js:33:10)
    at next (/opt/etherpad-lite/src/node_modules/express/node_modules/connect/lib/proto.js:194:15)
    at next (/opt/etherpad-lite/src/node_modules/express/node_modules/connect/lib/proto.js:169:78)
    at next (/opt/etherpad-lite/src/node_modules/express/node_modules/connect/lib/proto.js:169:78)
    at next (/opt/etherpad-lite/src/node_modules/express/node_modules/connect/lib/proto.js:169:78)
--------------------------

Frontend error:
--------------------------
{
  "error": "Sorry, something bad happened!"
}
--------------------------

Plugins are uninstalled and etherpad was restarted.
Did anyone know the solution?
The package.json contains "ejs" : "2.3.1",
Should we do anything else after git checkout?

Thanks for reading.

**Comment by JohnMcLear** [comment]
Did you try

bin/cleanRun.sh

?

On 28 May 2015 16:10, gulaschskanone <notifications@github.com> wrote:

Hello guys,
after checkout release/1.5.6 (from release/1.5.2) we got almost the same error:

________________________________

[2015-05-28 16:56:51.320] [ERROR] console - ReferenceError: ejs:1

1| <% e._init(__output); %><%
2| var settings = require("ep_etherpad-lite/node/utils/Settings");
3| %>
4| <!doctype html>

__output is not defined

[...]

and

________________________________

[2015-05-28 16:54:22.709] [ERROR] console - TypeError: undefined is not a function
at /opt/etherpad-lite/src/node/hooks/express/specialpages.js:63:9
at callbacks (/opt/etherpad-lite/src/node_modules/express/lib/router/index.js:164:37)
at param (/opt/etherpad-lite/src/node_modules/express/lib/router/index.js:138:11)
at pass (/opt/etherpad-lite/src/node_modules/express/lib/router/index.js:145:5)
at Router._dispatch (/opt/etherpad-lite/src/node_modules/express/lib/router/index.js:173:5)
at Object.router (/opt/etherpad-lite/src/node_modules/express/lib/router/index.js:33:10)
at next (/opt/etherpad-lite/src/node_modules/express/node_modules/connect/lib/proto.js:194:15)
at next (/opt/etherpad-lite/src/node_modules/express/node_modules/connect/lib/proto.js:169:78)
at next (/opt/etherpad-lite/src/node_modules/express/node_modules/connect/lib/proto.js:169:78)

at next (/opt/etherpad-lite/src/node_modules/express/node_modules/connect/lib/proto.js:169:78)
Frontend error:

{
"error": "Sorry, something bad happened!"

}

Plugins are uninstalled and etherpad was restarted.
Did anyone know the solution?
The package.json contains "ejs" : "2.3.1",
Should we do anything else after git checkout?

Thanks for reading.

**Comment by gulaschskanone** [comment]
wow, thanks for the instant answer!
I used the init.d script for restarting. 
Directly starting solved the problem. Thanks a lot, John!
> ws@0.5.0 install /opt/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws
