### ISSUE TITLE
Protocol.end, connection lost ... graceful shutdown?

### ISSUE THREAD

**Issue by LaKing** [ether/etherpad-lite#2439]
I left my pad open for several hours, as it seems the protocol end comes after 8 hours - that is fine, ..
but should this really shut down etherpad?

```
[2015-01-03 20:02:48.811] [INFO] ueberDB - Flushed 1 values
[2015-01-04 01:22:44.107] [INFO] access - [LEAVE] Pad "srvctl/build.sh": Author "a.GTxn797rsmbqCDDJ" on client Z7KuEVSO2mGWH4u5AAAC with IP "ANONYMOUS" left the pad
[2015-01-04 01:22:46.102] [INFO] access - [ENTER] Pad "srvctl/build.sh": Client 45X439dk4uAVf05hAAAD with IP "ANONYMOUS" entered the pad
[2015-01-04 01:22:46.121] [INFO] ueberDB - Flushed 1 values
[2015-01-04 09:22:46.127] [ERROR] console - Error: Connection lost: The server closed the connection.
    at Protocol.end (/srv/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:103:13)
    at Socket.<anonymous> (/srv/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-01-04 09:22:46.127] [INFO] console - graceful shutdown...
[2015-01-04 09:22:46.190] [INFO] console - db sucessfully closed.

```

**Comment by LaKing** [comment]
Hmm. On another pad, that I didn't have open ,.. 

```
[2015-01-03 03:33:11.610] [INFO] ueberDB - Flushed 1 values
[2015-01-03 03:33:11.812] [INFO] ueberDB - Flushed 1 values
[2015-01-03 11:33:11.819] [ERROR] console - Error: Connection lost: The server closed the connection.
    at Protocol.end (/srv/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:103:13)
    at Socket.<anonymous> (/srv/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:938:16
    at process._tickDomainCallback (node.js:463:13)
[2015-01-03 11:33:11.819] [INFO] console - graceful shutdown...
[2015-01-03 11:33:11.829] [INFO] console - db sucessfully closed.

```

**Comment by JohnMcLear** [comment]
Please test this pull request and let us know if it solves it or not: https://github.com/Pita/ueberDB/pull/71

**Comment by JohnMcLear** [comment]
@LaKing any luck?

**Comment by LaKing** [comment]
Yes, ..

It seems to fix it.
