### ISSUE TITLE
Update from 1.4.0 to 1.5.0 not working

### ISSUE THREAD

**Issue by 7adietri** [ether/etherpad-lite#2462]
My Etherpad installation completely broke when updating from 1.4.0 to 1.5.0. Accessing the application now just displays "Something bad has happened" in the browser.

This appears in the log:

    ReferenceError: ejs:1
     >> 1| <% e._init(buf); %><%
        2|   var settings = require("ep_etherpad-lite/node/utils/Settings");
        3| %>
        4| <!doctype html>

    buf is not defined
        at eval (eval at <anonymous> (/home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:312:12), <anonymous>:2:8007)
        at /home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:338:17
        at Object.exports.render (/home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:181:13)
        at Object.exports.require (/home/etherpad/etherpad-lite/src/node/eejs/index.js:122:17)
        at /home/etherpad/etherpad-lite/src/node/hooks/express/specialpages.js:15:19
        at callbacks (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:164:37)
        at param (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:138:11)
        at pass (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:145:5)
        at Router._dispatch (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:173:5)
        at Object.router (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:33:10)

Prior to that, this message appears:

    /home/etherpad/etherpad-lite/src/node_modules/wd requires async@'0.1.x' but will load
    /home/etherpad/etherpad-lite/src/node_modules/async,
    which is version 0.9.0

I tried running `npm update` manually, but the unmet dependency remained.

**Comment by JohnMcLear** [comment]
Waiting on https://github.com/ether/etherpad-lite/pull/2457 to be resolved.

If you want a quick fix just pull develop :)
