### ISSUE TITLE
Crash during import of .etherpad file

### ISSUE THREAD

**Issue by kaystrobach** [ether/etherpad-lite#2481]
I installed etherpad from the master branch on an uptodate debian wheezy.

The editing runs fine, but during import of an exported .etherpad file with approx 90kb the server crashes during import and won't come up again.
There are still prozesses, but the Webfrontend is not delivered anymore.

**Comment by JohnMcLear** [comment]
Please read this: http://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/

**Comment by kaystrobach** [comment]
Client Configs tried:
* Windows 8.1/7
 * Chrome Version 40.0.2214.91 (64-bit)
 * Firefox 35.0
 * latest IE 10 and 11
* OSX 10.10. latest
 * with Chrome Version 40.0.2214.91 (64-bit)
 * Firefox 35.0
 * Safari Version 8.0.2 (10600.2.5)

Host system:
* Debian GNU/Linux 7.0 \n \l
* latest updates installed via aptitude
* abiword 2.9.2 installed and configured
* npm 1.4.28
* nodejs v0.10.35
* etherpad branch develop
* Apache with proxypass (http / https on port 80 and 443)
* etherpad listening on port 9001 (default)
* etherpad extensions installed (made no difference for reproducing the issue if installed or not)
 * ep_align
 * ep_expiration
 * ep_headings2
 * ep_markdown
 * ep_prompt_for_name
 * ep_slideshow
 * ep_draw
 * ep_headings

Steps to reproduce
* https://www.youtube.com/watch?v=TLWoEwAZxWo&feature=youtube_gdata

Stack trace (and i think the failed object access is the problem) see [2015-01-23 07:43:25.723] [ERROR]

```
[2015-01-23 07:43:05.594] [INFO] ueberDB - Flushed 6 values
[2015-01-23 07:43:06.027] [DEBUG] SessionStore - SET VXNfmyuSOIMr1OVw4NkzBbzc
[2015-01-23 07:43:06.027] [DEBUG] ueberDB - SET    - sessionstorage:VXNfmyuSOIMr1OVw4NkzBbzc - {"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true}} - to buffer
[2015-01-23 07:43:06.028] [DEBUG] http - 304, GET /favicon.ico
[2015-01-23 07:43:06.100] [INFO] ueberDB - Flushed 1 values
[2015-01-23 07:43:16.101] [INFO] console - ping
[2015-01-23 07:43:25.613] [DEBUG] SessionStore - GET 67NKAGJLvu7cD0IgEtZFGR0G
[2015-01-23 07:43:25.614] [DEBUG] ueberDB - GET    - sessionstorage:67NKAGJLvu7cD0IgEtZFGR0G - {"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true},"user":{"password":"supersecret","is_admin":true,"username":"admin"}} - from cache
[2015-01-23 07:43:25.614] [DEBUG] ueberDB - GET    - pad:tVK1tGzVkY - {"atext":{"text":"  TEXT REMOVED    ","attribs":"|6+89"},"pool":{"numToAttrib":{},"nextNum":0},"head":0,"chatHead":-1,"publicStatus":false,"passwordHash":null,"savedRevisions":[]} - from cache
[2015-01-23 07:43:25.614] [DEBUG] ueberDB - GET    - token2author:t.vJJUVFgXpzuDMb5jTvOF - "a.XgxZlxXVm9YMEJmz" - from cache
[2015-01-23 07:43:25.615] [DEBUG] ueberDB - SETSUB - globalAuthor:a.XgxZlxXVm9YMEJmz["timestamp"] - 1421995405614
[2015-01-23 07:43:25.622] [DEBUG] ueberDB - GET    - globalAuthor:a.XgxZlxXVm9YMEJmz - {"colorId":"#a9d9d9","name":"asd","timestamp":1421995385580,"padIDs":{"j3YL2xvoLV":1}} - from cache
[2015-01-23 07:43:25.622] [DEBUG] ueberDB - SET    - globalAuthor:a.XgxZlxXVm9YMEJmz - {"colorId":"#a9d9d9","name":"asd","timestamp":1421995405614,"padIDs":{"j3YL2xvoLV":1}} - to buffer
[2015-01-23 07:43:25.652] [INFO] ueberDB - Flushed 1 values
[2015-01-23 07:43:25.718] [DEBUG] ueberDB - SET    - pad:tVK1tGzVkY - {"atext":{"text":"   TEXT REMOVED    "},"pool":{"numToAttrib":{"0":["author","a.nwpMrcILx43MLU1W"],"1":["author","a.KR1cH23dzMUP8N0T"],"2":["author","a.hkhbDa9qn0EWIb8H"],"3":["bold","true"],"4":["author","a.aTvqZu1FgD5pScBH"]},"nextNum":5},"head":423,"chatHead":32,"publicStatus":false,"passwordHash":null,"savedRevisions":[]} - to buffer
[2015-01-23 07:43:25.719] [DEBUG] ueberDB - GET    - globalAuthor:a.nwpMrcILx43MLU1W - {"colorId":"#e62323","name":"KT2","timestamp":1421937776157,"padIDs":{"t_kt1":1,"test_kt1":1}} - from cache
[2015-01-23 07:43:25.723] [ERROR] console - TypeError: Object #<Object> has no method 'push'
    at Object.callback (/export/home/etherpad-lite/builds/src/node/utils/ImportEtherpad.js:37:25)
    at /export/home/etherpad-lite/builds/src/node_modules/ueberDB/CloneAndAtomicLayer.js:100:17
    at exports.database.get (/export/home/etherpad-lite/builds/src/node_modules/ueberDB/CacheAndBufferLayer.js:144:5)
    at doOperation [as operatorFunction] (/export/home/etherpad-lite/builds/src/node_modules/ueberDB/CloneAndAtomicLayer.js:94:18)
    at exports.channels.emit (/export/home/etherpad-lite/builds/src/node_modules/ueberDB/node_modules/channels/channels.js:38:11)
    at exports.database.get (/export/home/etherpad-lite/builds/src/node_modules/ueberDB/CloneAndAtomicLayer.js:62:17)
    at /export/home/etherpad-lite/builds/src/node/utils/ImportEtherpad.js:34:10
    at iterate (/export/home/etherpad-lite/builds/src/node_modules/async/lib/async.js:149:13)
    at /export/home/etherpad-lite/builds/src/node_modules/async/lib/async.js:160:25
    at /export/home/etherpad-lite/builds/src/node/utils/ImportEtherpad.js:64:5
[2015-01-23 07:43:25.724] [INFO] console - graceful shutdown...
[2015-01-23 07:43:25.754] [INFO] ueberDB - Flushed 1 values
[2015-01-23 07:43:25.856] [INFO] console - db sucessfully closed.
```

anything else needed to fix it :smile:

**Comment by kaystrobach** [comment]
BTW: after restarting etherpad the DB content is completly available ...

**Comment by JohnMcLear** [comment]
The .etherpad file is the cause right?  Might make sense to provide that? :P

**Comment by kaystrobach** [comment]
i was asked not to send the etherpad file to public, even if the content is useless i send it to your github mailadresse (from the profile)

thanks a lot

**Comment by JohnMcLear** [comment]
That's fine, email is fine :)

**Comment by JohnMcLear** [comment]
Imported fine for me here on latest develop

**Comment by JohnMcLear** [comment]
Looks like maybe the author exists but he has no padIDs or something

**Comment by kaystrobach** [comment]
ok, should a truncate DB fix that?

**Comment by JohnMcLear** [comment]
in ImportEtherpad.js replace

```
      // Does this author already exist?
      db.get(key, function(err, author){
        if(author){
          // Yes, add the padID to the author..
          author.padIDs.push(padId);
          value = author;
        }else{
          // No, create a new array with the author info in
          value.padIDs = [padId];
        }
      });
```

With
```
      // Does this author already exist?
      db.get(key, function(err, author){
        if(author){
          // Yes, add the padID to the author..
console.error(author);
          author.padIDs.push(padId);
          value = author;
        }else{
          // No, create a new array with the author info in
          value.padIDs = [padId];
        }
      });
```

And see what you get in console..

**Comment by kaystrobach** [comment]
will check, need some minutes to get another project ready for production

**Comment by kaystrobach** [comment]
```
[2015-01-23 15:09:43.038] [DEBUG] ueberDB - GET    - globalAuthor:a.nwpMrcILx43MLU1W - {"colorId":"#e62323","name":"KT2","timestamp":1421937776157,"padIDs":{"t_kt1":1,"test_kt1":1}} - from cache
[2015-01-23 15:09:43.038] [INFO] console - { colorId: '#e62323',
  name: 'KT2',
  timestamp: 1421937776157,
  padIDs: { t_kt1: 1, test_kt1: 1 } }
[2015-01-23 15:09:43.044] [ERROR] console - TypeError: Object #<Object> has no method 'push'
    at Object.callback (/export/home/etherpad-lite/builds/src/node/utils/ImportEtherpad.js:38:25)
    at /export/home/etherpad-lite/builds/src/node_modules/ueberDB/CloneAndAtomicLayer.js:100:17
    at exports.database.get (/export/home/etherpad-lite/builds/src/node_modules/ueberDB/CacheAndBufferLayer.js:144:5)
    at doOperation [as operatorFunction] (/export/home/etherpad-lite/builds/src/node_modules/ueberDB/CloneAndAtomicLayer.js:94:18)
    at exports.channels.emit (/export/home/etherpad-lite/builds/src/node_modules/ueberDB/node_modules/channels/channels.js:38:11)
    at exports.database.get (/export/home/etherpad-lite/builds/src/node_modules/ueberDB/CloneAndAtomicLayer.js:62:17)
    at /export/home/etherpad-lite/builds/src/node/utils/ImportEtherpad.js:34:10
    at iterate (/export/home/etherpad-lite/builds/src/node_modules/async/lib/async.js:149:13)
    at /export/home/etherpad-lite/builds/src/node_modules/async/lib/async.js:160:25
    at /export/home/etherpad-lite/builds/src/node/utils/ImportEtherpad.js:65:5
```

IMHO the problem is, that ```  padIDs: { t_kt1: 1, test_kt1: 1 } }``` is an object rather than an array

so it should be tested if that is an array and if it is an object convert it:

```
var arr = Object.keys(o).map(function(k) { return o[k] });
```

http://stackoverflow.com/questions/20881213/converting-json-object-into-javascript-array

**Comment by JohnMcLear** [comment]
That looks wrong in your database..  nuke those rows from your database and try again..  Afaik PadIds should always be an array.  Also check your database to see if padids is an object elsewhere...
----- Reply message -----

**Comment by kaystrobach** [comment]
ok, after truncating the database, the import works smoothly.

Perhaps one of the plugins caused that scary entry ... i will try to reproduce that, but close the issue for now
