### ISSUE TITLE
EPL crashes when editing a pad

### ISSUE THREAD

**Issue by Matael** [ether/etherpad-lite#2511]
On a fresh new install, EPL wil serve the admin and pads but will crash on pad creation or edition with the following error : 

    [2015-02-09 22:17:58.032] [ERROR] console - Error: Callback was already called.
    at /home/haum/etherpad-lite/src/node_modules/async/lib/async.js:30:31
    at /home/haum/etherpad-lite/src/node_modules/async/lib/async.js:251:21
    at null.callback (/home/haum/etherpad-lite/src/node_modules/async/lib/async.js:575:34)
    at Query.handleReadyForQuery (/home/haum/etherpad-lite/node_modules/pg/lib/query.js:80:10)
    at null.<anonymous> (/home/haum/etherpad-lite/node_modules/pg/lib/client.js:158:19)
    at EventEmitter.emit (events.js:117:20)
    at Socket.<anonymous> (/home/haum/etherpad-lite/node_modules/pg/lib/connection.js:109:12)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:710:14)
    at Socket.EventEmitter.emit (events.js:92:17)

node version is 0.11.0 and EPL is the develop-branch one.

Full log is : 

    Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
    npm WARN package.json async-stacktrace@0.0.2 No repository field.
    npm WARN package.json channels@0.0.4 No repository field.
    npm WARN package.json tinycon@0.0.1 No repository field.
    npm WARN unmet dependency /home/haum/etherpad-lite/src/node_modules/ueberDB requires async@'0.1.15' but will load
    npm WARN unmet dependency /home/haum/etherpad-lite/src/node_modules/async,
    npm WARN unmet dependency which is version 0.9.0
    npm WARN unmet dependency /home/haum/etherpad-lite/src/node_modules/ueberDB requires channels@'0.0.2' but will load
    npm WARN unmet dependency /home/haum/etherpad-lite/src/node_modules/channels,
    npm WARN unmet dependency which is version 0.0.4
    npm WARN unmet dependency /home/haum/etherpad-lite/src/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/stream-counter requires readable-stream@'~1.1.8' but will load
    npm WARN unmet dependency /home/haum/etherpad-lite/src/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-stream,
    npm WARN unmet dependency which is version 1.1.13-1
    Ensure jQuery is downloaded and up to date...
    Clear minfified cache...
    Ensure custom css/js files are created...
    Started Etherpad...
    [2015-02-09 22:21:10.136] [WARN] pluginfw - /home/haum/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/ueberDB requires async@'0.1.15' but will load
    /home/haum/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/async,
    which is version 0.9.0 unmet dependency
    [2015-02-09 22:21:10.138] [WARN] pluginfw - /home/haum/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/ueberDB requires channels@'0.0.2' but will load
    /home/haum/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/channels,
    which is version 0.0.4 unmet dependency
    [2015-02-09 22:21:10.149] [WARN] pluginfw - /home/haum/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/stream-counter requires readable-stream@'~1.1.8' but will load
    /home/haum/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/express/node_modules/    connect/node_modules/multiparty/node_modules/readable-stream,
    which is version 1.1.13-1 unmet dependency
    [2015-02-09 22:21:11.410] [INFO] console - Installed plugins: ep_etherpad-lite
    [2015-02-09 22:21:11.460] [INFO] console - Your Etherpad git version is 26ae375
    [2015-02-09 22:21:11.461] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
    [2015-02-09 22:21:11.759] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9000/
    [2015-02-09 22:21:11.759] [INFO] console - The plugin admin page is at http://0.0.0.0:9000/admin/plugins
    [2015-02-09 22:21:15.735] [INFO] access - [ENTER] Pad "calendrier2015": Client tgrDrMz56vhHrkqgAAAA with IP "127.0.0.1" entered the pad
    [2015-02-09 22:21:15.769] [INFO] ueberDB - Flushed 1 values
    [2015-02-09 22:21:34.852] [ERROR] console - Error: Callback was already called.
        at /home/haum/etherpad-lite/src/node_modules/async/lib/async.js:30:31
        at /home/haum/etherpad-lite/src/node_modules/async/lib/async.js:251:21
        at null.callback (/home/haum/etherpad-lite/src/node_modules/async/lib/async.js:575:34)
        at Query.handleReadyForQuery (/home/haum/etherpad-lite/node_modules/pg/lib/query.js:80:10)
        at null.<anonymous> (/home/haum/etherpad-lite/node_modules/pg/lib/client.js:158:19)
        at EventEmitter.emit (events.js:117:20)
        at Socket.<anonymous> (/home/haum/etherpad-lite/node_modules/pg/lib/connection.js:109:12)
        at Socket.EventEmitter.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:710:14)
        at Socket.EventEmitter.emit (events.js:92:17)
    [2015-02-09 22:21:34.853] [INFO] console - graceful shutdown...
    [2015-02-09 22:21:34.858] [ERROR] console - Error: Callback was already called.
        at /home/haum/etherpad-lite/src/node_modules/async/lib/async.js:30:31
        at /home/haum/etherpad-lite/src/node_modules/async/lib/async.js:251:21
        at null.callback (/home/haum/etherpad-lite/src/node_modules/async/lib/async.js:575:34)
        at Query.handleReadyForQuery (/home/haum/etherpad-lite/node_modules/pg/lib/query.js:80:10)
        at null.<anonymous> (/home/haum/etherpad-lite/node_modules/pg/lib/client.js:158:19)
        at EventEmitter.emit (events.js:117:20)
        at Socket.<anonymous> (/home/haum/etherpad-lite/node_modules/pg/lib/connection.js:109:12)
        at Socket.EventEmitter.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:710:14)
        at Socket.EventEmitter.emit (events.js:92:17)
    [2015-02-09 22:21:34.928] [INFO] ueberDB - Flushed 1 values
    [2015-02-09 22:21:35.028] [INFO] console - db sucessfully closed.

**Comment by JohnMcLear** [comment]
Error is bubbling up from postgres module: 
```
at null.<anonymous> (/home/haum/etherpad-lite/node_modules/pg/lib/client.js:158:19)
```

So I assume you are running postgres?

You said "On a fresh new install" so I assume this can't be right?  What is the reality here?

**Comment by JohnMcLear** [comment]
Tested PG and everyting is workling fine.  Suggest your db is having issues.

**Comment by Matael** [comment]
Actually, my database doesn't seem to have issues. Even if EPL crashes, the first character you type is inserted in the database record too.

**Comment by webzwo0i** [comment]
any reason why you use this crazy node version? Can you try a stable branch (0.12 has just been released but better you try with 0.10 for the moment because it works for others) or at least the latest version (v0.11.16) of the unstable 0.11?

**Comment by Matael** [comment]
@webzwo0i I'll try that as soon as i have a little bit of time. Actually i'm pretty new to node and i don't have the time to dive in the different versions and stuff. I read in the EPL doc "Additionally, you'll need node.js installed, Ideally the latest stable version, we recommend installing/compiling nodejs from source (avoiding apt)." I tried 0.12, and it didn't work, so I switched back to 0.11...

I'll try with 0.10 and see what happens. Thanks for your help.

**Comment by webzwo0i** [comment]
OK, yes please come back if the error remains. Do you remember if with 0.12 it was the same error or something else?
Node uses the following versioning: if the second number is even it means stable, if the second number is odd it means unstable. The thing that confused me is that even if you use 0.11 you should not use 0.11.0 but https://raw.githubusercontent.com/joyent/node/v0.11.16/ChangeLog

**Comment by JohnMcLear** [comment]
0.12 works afaik
----- Reply message -----
