### ISSUE TITLE
[2015-02-27 03:21:56.248] [ERROR] console - Error: EMFILE, too many open files '/home

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2531]
When you try to connect 1000 lurkers to a pad you get this error...  It's weird because the loadtest clients dont actually open the pad html:?

To replicate `` etherpad-loadtest app.js -l 1000 -a 5``

```
[2015-02-27 03:21:56.248] [ERROR] console - Error: EMFILE, too many open files '/home/jose/etherpad-lite/node_modules/ep_etherpad-lite/templates/pad.html'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.exports.require (/home/jose/etherpad-lite/src/node/eejs/index.js:117:45)
    at /home/jose/etherpad-lite/src/node/hooks/express/specialpages.js:40:19
    at callbacks (/home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:164:37)
    at param (/home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:138:11)
    at paramCallback (/home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:150:30)
    at /home/jose/etherpad-lite/src/node/hooks/express/padurlsanitize.js:27:11
    at /home/jose/etherpad-lite/src/node/db/PadManager.js:217:9
    at Object.callback (/home/jose/etherpad-lite/src/node/db/PadManager.js:193:7)
^C[2015-02-27 03:22:01.345] [INFO] console - graceful shutdown...

```

**Comment by JohnMcLear** [comment]
Things are stable at ``etherpad-load-test$ etherpad-loadtest app.js -l 500 -a 5``

**Comment by JohnMcLear** [comment]
Mostly solved in node 12, I don't know if we can push any further on this if I'm honest
