### ISSUE TITLE
javascript-error on creating pads

### ISSUE THREAD

**Issue by marcgebauer** [ether/etherpad-lite#2532]
fresh install of the actual git-version of etherpad on centos 6.6
frontend / ("welcome-page" with the input-field of the pad-name) and /admin is working without any problem.
when trying to access an new pad via browser i get an error:

FireFox 35:
```
An error occured while loading the pad
SyntaxError: missing } in compound statement in http://$ip:$port/static/js/require-kernel.js (line 690)
```
```
SyntaxError: missing ) after condition pad.js:692
Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/ require-kernel.js:284
SyntaxError: missing } in compound statement require-kernel.js:690
window.controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. nsHeaderInfo.js:412
SyntaxError: missing ) after condition require-kernel.js:718
```

IE 11:
```
An error occured while loading the pad
'}' erwartet in http://$ip:$port/static/js/require-kernel.js (line 226)
```

Installed versions:
```
-bash-4.1$ /usr/local/node.js/bin/node -v
v0.12.0
```

```
Started Etherpad...
[2015-02-27 10:19:06.485] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2015-02-27 10:19:09.555] [INFO] console - Installed plugins: ep_etherpad-lite
[2015-02-27 10:19:09.603] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2015-02-27 10:19:09.603] [INFO] console - Your Etherpad git version is 38a4f1b
[2015-02-27 10:19:09.813] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2015-02-27 10:19:09.813] [INFO] console - The plugin admin page is at http://0.0.0.0:9001/admin/plugins
```

**Comment by JohnMcLear** [comment]
Try 

```
rm -Rf src/node_modules
bin/run.sh
```

**Comment by marcgebauer** [comment]
already tried. no changes.

**Comment by JohnMcLear** [comment]
Try another clean install plz.

**Comment by marcgebauer** [comment]
i installed a new instance of node.js and did ad git-clone of the etherpad-repo right now. The error remains.

```An error occured while loading the pad

NS_ERROR_FAILURE: in http://10.34.10.90:9001/static/js/require-kernel.js (line 293)
Chat 0
```

Here is the output of the initial startup - there is an error compilng a module, i don't know if this is important (because etherpad in the admin-section is working without any error)

```-bash-4.1$ bin/run.sh
Copy the settings template to settings.json...
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.

> ws@0.5.0 install /usr/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'

> ws@0.4.31 install /usr/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/usr/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'

> microtime@0.4.0 install /usr/local/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/helenus/node_modules/microtime
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/usr/local/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/helenus/node_modules/microtime/build'
  CXX(target) Release/obj.target/microtime/src/microtime.o
../src/microtime.cc:40: error: ISO C++ forbids declaration of ‘Arguments’ with no type
../src/microtime.cc:40: error: expected ‘,’ or ‘...’ before ‘&’ token
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> Now(int)’:
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h:816: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/microtime.cc:41: error: within this context
../src/microtime.cc:47: error: ‘ThrowException’ was not declared in this scope
../src/microtime.cc:50: error: ‘class v8::HandleScope’ has no member named ‘Close’
../src/microtime.cc:50: error: no matching function for call to ‘v8::Number::New(double)’
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h:1999: note: candidates are: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
../src/microtime.cc: At global scope:
../src/microtime.cc:53: error: ISO C++ forbids declaration of ‘Arguments’ with no type
../src/microtime.cc:53: error: expected ‘,’ or ‘...’ before ‘&’ token
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> NowDouble(int)’:
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h:816: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/microtime.cc:54: error: within this context
../src/microtime.cc:60: error: ‘ThrowException’ was not declared in this scope
../src/microtime.cc:63: error: ‘class v8::HandleScope’ has no member named ‘Close’
../src/microtime.cc:63: error: no matching function for call to ‘v8::Number::New(double)’
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h:1999: note: candidates are: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
../src/microtime.cc: At global scope:
../src/microtime.cc:66: error: ISO C++ forbids declaration of ‘Arguments’ with no type
../src/microtime.cc:66: error: expected ‘,’ or ‘...’ before ‘&’ token
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> NowStruct(int)’:
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h:816: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/microtime.cc:67: error: within this context
../src/microtime.cc:73: error: ‘ThrowException’ was not declared in this scope
../src/microtime.cc:76: error: invalid conversion from ‘int’ to ‘v8::Isolate*’
../src/microtime.cc:76: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’
../src/microtime.cc:77: error: no matching function for call to ‘v8::Integer::New(int)’
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h:2012: note: candidates are: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
../src/microtime.cc:77: error: no matching function for call to ‘v8::Integer::New(__time_t&)’
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h:2012: note: candidates are: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
../src/microtime.cc:78: error: no matching function for call to ‘v8::Integer::New(int)’
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h:2012: note: candidates are: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
../src/microtime.cc:78: error: no matching function for call to ‘v8::Integer::New(__suseconds_t&)’
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h:2012: note: candidates are: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
../src/microtime.cc:80: error: ‘class v8::HandleScope’ has no member named ‘Close’
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘void init(v8::Handle<v8::Object>)’:
/usr/local/etherpad/.node-gyp/0.12.0/deps/v8/include/v8.h:816: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/microtime.cc:85: error: within this context
../src/microtime.cc:87: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [4], v8::Handle<v8::Value> (&)(int))’
../src/microtime.cc:88: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [10], v8::Handle<v8::Value> (&)(int))’
../src/microtime.cc:89: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [10], v8::Handle<v8::Value> (&)(int))’
make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
make: Leaving directory `/usr/local/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/helenus/node_modules/microtime/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/etherpad/node-v0.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 2.6.32-504.8.1.el6.x86_64
gyp ERR! command "node" "/usr/local/etherpad/node-v0.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/helenus/node_modules/microtime
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing microtime@0.4.0
channels@0.0.4 node_modules/channels

security@1.0.0 node_modules/security

async-stacktrace@0.0.2 node_modules/async-stacktrace

slide@1.1.6 node_modules/slide

graceful-fs@3.0.5 node_modules/graceful-fs

tinycon@0.0.1 node_modules/tinycon

formidable@1.0.16 node_modules/formidable

async@0.9.0 node_modules/async

underscore@1.5.1 node_modules/underscore

etherpad-require-kernel@1.0.8 node_modules/etherpad-require-kernel

languages4translatewiki@0.1.3 node_modules/languages4translatewiki

unorm@1.3.3 node_modules/unorm

semver@4.2.0 node_modules/semver

ejs@1.0.0 node_modules/ejs

measured@1.0.0 node_modules/measured
└── inherits@2.0.1

resolve@1.1.0 node_modules/resolve

etherpad-yajsml@0.0.2 node_modules/etherpad-yajsml

supertest@0.15.0 node_modules/supertest
├── methods@1.1.1
└── superagent@0.21.0 (extend@1.2.1, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, qs@1.2.0, mime@1.2.11, debug@2.1.2, readable-stream@1.0.27-1, form-data@0.1.3, formidable@1.0.14)

log4js@0.6.22 node_modules/log4js
├── semver@1.1.4
├── async@0.2.10
└── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)

clean-css@3.0.8 node_modules/clean-css
├── commander@2.5.1
└── source-map@0.1.43 (amdefine@0.1.0)

connect@2.7.11 node_modules/connect
├── fresh@0.1.0
├── cookie-signature@1.0.1
├── pause@0.0.1
├── buffer-crc32@0.2.1
├── qs@0.6.5
├── bytes@0.2.0
├── cookie@0.0.5
├── debug@2.1.2 (ms@0.7.0)
├── send@0.1.1 (range-parser@0.0.4, mime@1.2.11)
└── formidable@1.0.14

uglify-js@2.4.16 node_modules/uglify-js
├── uglify-to-browserify@1.0.2
├── async@0.2.10
├── optimist@0.3.7 (wordwrap@0.0.2)
└── source-map@0.1.34 (amdefine@0.1.0)

mocha@2.1.0 node_modules/mocha
├── escape-string-regexp@1.0.2
├── diff@1.0.8
├── growl@1.8.1
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

request@2.53.0 node_modules/request
├── caseless@0.9.0
├── json-stringify-safe@5.0.0
├── forever-agent@0.5.2
├── aws-sign2@0.5.0
├── form-data@0.2.0
├── stringstream@0.0.4
├── oauth-sign@0.6.0
├── tunnel-agent@0.4.0
├── isstream@0.1.1
├── node-uuid@1.4.2
├── qs@2.3.3
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── mime-types@2.0.9 (mime-db@1.7.0)
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@0.9.4 (readable-stream@1.0.33)
├── tough-cookie@0.12.1 (punycode@1.3.2)
└── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.6.1, hoek@2.11.1)

jsonminify@0.2.3 node_modules/jsonminify

cheerio@0.18.0 node_modules/cheerio
├── dom-serializer@0.0.1 (domelementtype@1.1.3)
├── entities@1.1.1
├── htmlparser2@3.8.2 (domelementtype@1.1.3, domutils@1.5.1, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13)
├── CSSselect@0.4.1 (domutils@1.4.3, CSSwhat@0.4.7)
└── lodash@2.4.1

swagger-node-express@2.1.3 node_modules/swagger-node-express
└── lodash@1.3.1

wd@0.3.11 node_modules/wd
├── vargs@0.1.0
├── q@1.0.1
├── underscore.string@2.3.3
├── lodash@2.4.1
├── request@2.46.0 (caseless@0.6.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, tunnel-agent@0.4.0, oauth-sign@0.4.0, qs@1.2.2, node-uuid@1.4.2, mime-types@1.0.2, bl@0.9.4, http-signature@0.10.1, tough-cookie@0.12.1, form-data@0.1.4, hawk@1.1.1)
└── archiver@0.12.0 (buffer-crc32@0.2.5, lazystream@0.1.0, readable-stream@1.0.33, zip-stream@0.4.1, tar-stream@1.0.2, glob@4.0.6)

express@3.8.1 node_modules/express
├── parseurl@1.0.1
├── merge-descriptors@0.0.2
├── cookie@0.1.2
├── debug@0.8.1
├── cookie-signature@1.0.3
├── fresh@0.2.2
├── range-parser@1.0.0
├── methods@1.0.0
├── buffer-crc32@0.2.1
├── commander@1.3.2 (keypress@0.1.0)
├── proxy-addr@1.0.0 (ipaddr.js@0.1.2)
├── send@0.3.0 (debug@0.8.0, mime@1.2.11)
├── mkdirp@0.5.0 (minimist@0.0.8)
└── connect@2.17.3 (response-time@1.0.0, pause@0.0.1, method-override@1.0.2, connect-timeout@1.1.0, vhost@1.0.0, qs@0.6.6, on-headers@0.0.0, basic-auth-connect@1.0.0, bytes@1.0.0, serve-favicon@2.0.0, morgan@1.1.1, errorhandler@1.0.1, serve-static@1.1.0, cookie-parser@1.1.0, body-parser@1.2.2, csurf@1.2.0, type-is@1.2.0, compression@1.0.2, express-session@1.2.1, serve-index@1.0.3, multiparty@2.2.0)

npm@2.4.1 node_modules/npm

socket.io@1.3.3 node_modules/socket.io
├── debug@2.1.0 (ms@0.6.2)
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── socket.io-parser@2.2.3 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
├── engine.io@1.5.1 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.1, ws@0.5.0)
└── socket.io-client@1.3.3 (to-array@0.1.3, indexof@0.0.1, debug@0.7.4, component-bind@1.0.0, backo2@1.0.2, object-component@0.0.3, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.1)

ueberDB@0.2.12 node_modules/ueberDB
├── channels@0.0.2
├── felix-couchdb@1.0.7
├── redis@0.12.1
├── dirty@0.9.9
├── async@0.1.15
├── mysql@2.5.5 (require-all@1.0.0, bignumber.js@2.0.0, readable-stream@1.1.13)
├── pg@4.3.0 (packet-reader@0.2.0, pg-connection-string@0.1.3, buffer-writer@1.0.0, generic-pool@2.1.1, pg-types@1.7.0, pgpass@0.0.3)
└── helenus@0.6.10 (node-uuid@1.3.3, helenus-thrift@0.7.4)
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-03-02 09:22:41.735] [WARN] console - You need to set a sessionKey value in settings.json, this will allow your users to reconnect to your Etherpad Instance if your instance restarts
[2015-03-02 09:22:41.740] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2015-03-02 09:22:44.036] [INFO] console - Installed plugins: ep_etherpad-lite
[2015-03-02 09:22:44.084] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2015-03-02 09:22:44.084] [INFO] console - Your Etherpad git version is cc0eaba
[2015-03-02 09:22:44.331] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2015-03-02 09:22:44.332] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
```

**Comment by JohnMcLear** [comment]
build errors could be the cause.  Pretty sure we tested against node12 and it is fine though

**Comment by JohnMcLear** [comment]
@marcgebauer is your settings.json file modified at all?

**Comment by JohnMcLear** [comment]
I removed helenus from ueberdb, I don't think anyone was hardly using it anyway.

**Comment by JohnMcLear** [comment]
Everything is working fine for me on node12 op.

**Comment by marcgebauer** [comment]
not at the moment - this is a "clean" install without any modifications.
After editing the settings.json-file (enabling users, inserting session.key, a rm -rf src/node_modules , git-pull-origin, and a new bin/run.sh i get

```
-bash-4.1$ bin/run.sh
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.

> ws@0.5.0 install /usr/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'

> ws@0.4.31 install /usr/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/usr/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
channels@0.0.4 node_modules/channels

security@1.0.0 node_modules/security

async-stacktrace@0.0.2 node_modules/async-stacktrace

slide@1.1.6 node_modules/slide

graceful-fs@3.0.5 node_modules/graceful-fs

tinycon@0.0.1 node_modules/tinycon

formidable@1.0.16 node_modules/formidable

async@0.9.0 node_modules/async

underscore@1.5.1 node_modules/underscore

etherpad-require-kernel@1.0.8 node_modules/etherpad-require-kernel

languages4translatewiki@0.1.3 node_modules/languages4translatewiki

unorm@1.3.3 node_modules/unorm

semver@4.2.0 node_modules/semver

measured@1.0.0 node_modules/measured
└── inherits@2.0.1

ejs@1.0.0 node_modules/ejs

resolve@1.1.0 node_modules/resolve

etherpad-yajsml@0.0.2 node_modules/etherpad-yajsml

supertest@0.15.0 node_modules/supertest
├── methods@1.1.1
└── superagent@0.21.0 (extend@1.2.1, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, qs@1.2.0, mime@1.2.11, debug@2.1.2, form-data@0.1.3, readable-stream@1.0.27-1, formidable@1.0.14)

log4js@0.6.22 node_modules/log4js
├── semver@1.1.4
├── async@0.2.10
└── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)

clean-css@3.0.8 node_modules/clean-css
├── commander@2.5.1
└── source-map@0.1.43 (amdefine@0.1.0)

connect@2.7.11 node_modules/connect
├── fresh@0.1.0
├── pause@0.0.1
├── cookie-signature@1.0.1
├── qs@0.6.5
├── bytes@0.2.0
├── buffer-crc32@0.2.1
├── cookie@0.0.5
├── debug@2.1.2 (ms@0.7.0)
├── send@0.1.1 (range-parser@0.0.4, mime@1.2.11)
└── formidable@1.0.14

uglify-js@2.4.16 node_modules/uglify-js
├── uglify-to-browserify@1.0.2
├── async@0.2.10
├── optimist@0.3.7 (wordwrap@0.0.2)
└── source-map@0.1.34 (amdefine@0.1.0)

request@2.53.0 node_modules/request
├── caseless@0.9.0
├── json-stringify-safe@5.0.0
├── aws-sign2@0.5.0
├── forever-agent@0.5.2
├── form-data@0.2.0
├── stringstream@0.0.4
├── oauth-sign@0.6.0
├── tunnel-agent@0.4.0
├── isstream@0.1.1
├── node-uuid@1.4.2
├── qs@2.3.3
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── mime-types@2.0.9 (mime-db@1.7.0)
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@0.9.4 (readable-stream@1.0.33)
├── tough-cookie@0.12.1 (punycode@1.3.2)
└── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.6.1, hoek@2.11.1)

mocha@2.1.0 node_modules/mocha
├── escape-string-regexp@1.0.2
├── diff@1.0.8
├── growl@1.8.1
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

ueberDB@0.2.13 node_modules/ueberDB
├── channels@0.0.2
├── felix-couchdb@1.0.7
├── redis@0.12.1
├── dirty@0.9.9
├── async@0.1.15
├── mysql@2.5.5 (require-all@1.0.0, bignumber.js@2.0.0, readable-stream@1.1.13)
└── pg@4.3.0 (packet-reader@0.2.0, pg-connection-string@0.1.3, buffer-writer@1.0.0, generic-pool@2.1.1, pg-types@1.7.0, pgpass@0.0.3)

jsonminify@0.2.3 node_modules/jsonminify

cheerio@0.18.0 node_modules/cheerio
├── dom-serializer@0.0.1 (domelementtype@1.1.3)
├── entities@1.1.1
├── htmlparser2@3.8.2 (domelementtype@1.1.3, domutils@1.5.1, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13)
├── CSSselect@0.4.1 (domutils@1.4.3, CSSwhat@0.4.7)
└── lodash@2.4.1

socket.io@1.3.3 node_modules/socket.io
├── debug@2.1.0 (ms@0.6.2)
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── socket.io-parser@2.2.3 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
├── engine.io@1.5.1 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.1, ws@0.5.0)
└── socket.io-client@1.3.3 (to-array@0.1.3, indexof@0.0.1, component-bind@1.0.0, debug@0.7.4, backo2@1.0.2, object-component@0.0.3, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.1)

swagger-node-express@2.1.3 node_modules/swagger-node-express
└── lodash@1.3.1

wd@0.3.11 node_modules/wd
├── vargs@0.1.0
├── q@1.0.1
├── underscore.string@2.3.3
├── lodash@2.4.1
├── request@2.46.0 (caseless@0.6.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, qs@1.2.2, node-uuid@1.4.2, mime-types@1.0.2, form-data@0.1.4, tough-cookie@0.12.1, bl@0.9.4, hawk@1.1.1, http-signature@0.10.1)
└── archiver@0.12.0 (buffer-crc32@0.2.5, lazystream@0.1.0, readable-stream@1.0.33, zip-stream@0.4.1, tar-stream@1.0.2, glob@4.0.6)

express@3.8.1 node_modules/express
├── parseurl@1.0.1
├── merge-descriptors@0.0.2
├── cookie@0.1.2
├── debug@0.8.1
├── cookie-signature@1.0.3
├── fresh@0.2.2
├── range-parser@1.0.0
├── methods@1.0.0
├── buffer-crc32@0.2.1
├── commander@1.3.2 (keypress@0.1.0)
├── proxy-addr@1.0.0 (ipaddr.js@0.1.2)
├── send@0.3.0 (debug@0.8.0, mime@1.2.11)
├── mkdirp@0.5.0 (minimist@0.0.8)
└── connect@2.17.3 (response-time@1.0.0, method-override@1.0.2, connect-timeout@1.1.0, pause@0.0.1, vhost@1.0.0, qs@0.6.6, on-headers@0.0.0, basic-auth-connect@1.0.0, bytes@1.0.0, morgan@1.1.1, serve-favicon@2.0.0, errorhandler@1.0.1, serve-static@1.1.0, cookie-parser@1.1.0, body-parser@1.2.2, csurf@1.2.0, express-session@1.2.1, compression@1.0.2, type-is@1.2.0, serve-index@1.0.3, multiparty@2.2.0)

npm@2.4.1 node_modules/npm
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-03-02 10:03:13.929] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2015-03-02 10:03:16.121] [INFO] console - Installed plugins: ep_etherpad-lite
[2015-03-02 10:03:16.172] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2015-03-02 10:03:16.173] [INFO] console - Your Etherpad git version is 4e0353b
[2015-03-02 10:03:16.417] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2015-03-02 10:03:16.417] [INFO] console - The plugin admin page is at http://0.0.0.0:9001/admin/plugins
^C[2015-03-02 10:04:48.648] [INFO] console - graceful shutdown...
[2015-03-02 10:04:48.649] [INFO] console - db sucessfully closed.
```
but the error in the pad is still there.
```
An error occured while loading the pad

NS_ERROR_FAILURE: in http://10.34.10.90:9001/static/js/require-kernel.js (line 293)
```

**Comment by JohnMcLear** [comment]
Try a clean install without changing your settings.json, it sounds like you are breaking things.

**Comment by JohnMcLear** [comment]
Closing due to lack of activity

**Comment by fuero** [comment]
I ran into this issue too. It seems that etherpad works fine if accessed via localhost. Firefox and Chrome complain if accessed via IP and Port.
