### ISSUE TITLE
Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by Flauschie** [ether/etherpad-lite#2551]
Hi, I am receiving this error in etherpad log...

```
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json async-stacktrace@0.0.2 No repository field.
npm WARN package.json channels@0.0.4 No repository field.
npm WARN package.json tinycon@0.0.1 No repository field.
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-03-14 12:45:03.091] [INFO] console - Installed plugins: ep_adminpads, ep_author_hover, ep_autoscrolldown, ep_button_link, ep_colors, ep_etherpad-lite, ep_font_family, ep_headings, ep_infopanel, ep_margin, ep_message_all, ep_monospace_default, ep_previewimages, ep_print, ep_prompt_for_name, ep_subscript, ep_superscript, ep_table_of_contents
[2015-03-14 12:45:03.177] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2015-03-14 12:45:03.178] [INFO] console - Your Etherpad git version is 56dbad4
[2015-03-14 12:45:03.403] [INFO] console - You can access your Etherpad instance at http://127.0.0.1:9001/
[2015-03-14 12:45:03.403] [INFO] console - The plugin admin page is at http://127.0.0.1:9001/admin/plugins
[2015-03-14 12:45:03.411] [ERROR] console - Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at net.js:1253:9
    at dns.js:85:18
    at process._tickDomainCallback (node.js:381:11)
[2015-03-14 12:45:03.411] [INFO] console - graceful shutdown...
[2015-03-14 12:45:03.412] [INFO] console - db sucessfully closed.
RESTART!
```

**Comment by JohnMcLear** [comment]
[2015-03-14 12:45:03.411] [ERROR] console - Error: listen EADDRINUSE 

Is a big clue.

https://www.google.co.uk/search?client=ubuntu&channel=fs&q=listen+EADDRINUSE&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=bCkEVdKcNuSCiAaY44D4AQ

Please try to search for answers to your questions before posting here :) Thanks!

**Comment by Flauschie** [comment]
I posted because I can't fix it myself :( My pad keeps restarting over and over again...

**Comment by rasos** [comment]
I had the same error after updating etherpad after 3 years of smooth operation. 
Solved by reloading the etherpad window in your browser completely with Ctrl-R.

**Comment by Cyrille37** [comment]
I've got the same style error after updated from 1.5.6 to 1.5.7 - every 10 minutes I receive a mail with error:
```
[31m[2015-09-28 20:40:52.972] [ERROR] console - [39mError: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at net.js:1135:9
    at dns.js:72:18
    at process._tickDomainCallback (node.js:459:13)
[32m[2015-09-28 20:40:52.972] [INFO] console - [39mgraceful shutdown...
[32m[2015-09-28 20:40:52.972] [INFO] console - [39mdb sucessfully closed.
```

**Comment by Cyrille37** [comment]
Like @Flauschie I've restarted the server then EP run just fine.
Perhaps the problem comes from the start script or something else...

**Comment by sabarisan-gopinath** [comment]
i too have this error please try to change the port number manually in settings file
if you did so your port will be changed so that you will not be interrupted by the port 9001
i switched to port 9002
