### ISSUE TITLE
Error when running run.sh

### ISSUE THREAD

**Issue by p3k** [ether/etherpad-lite#2585]
I get the following error when running `./bin/run.sh` in an up-to-date clone from GitHub:

``` 
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at loadPlugin (/home/tobi/Install/etherpad-lite/src/static/js/pluginfw/plugins.js:121:26)
    at /home/tobi/Install/etherpad-lite/src/static/js/pluginfw/plugins.js:79:9
    at /home/tobi/Install/etherpad-lite/src/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/home/tobi/Install/etherpad-lite/src/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/home/tobi/Install/etherpad-lite/src/node_modules/async/lib/async.js:124:9)
    at /home/tobi/Install/etherpad-lite/src/static/js/pluginfw/plugins.js:76:11
    at /home/tobi/Install/etherpad-lite/src/static/js/pluginfw/plugins.js:116:5
    at /home/tobi/Install/etherpad-lite/src/static/js/pluginfw/read-installed.js:128:5
```

Using version 0.12.2 of node (via nave).

**Comment by JohnMcLear** [comment]
```
rm -Rf src/node_modules
bin/run.sh
```
Looks like a plugin might be at fault though

**Comment by p3k** [comment]
Thanks for the help, but unfortunately it did not solve my issue. Here is my whole installation log:

```bash
~                                                                                                                                                                                                   ⚡  cd Install/etherpad-lite/
~/Install/etherpad-lite on develop
⚡  git status
On branch develop
Your branch is up-to-date with 'origin/develop'.

nothing to commit, working directory clean
~/Install/etherpad-lite on develop
⚡  nave use stable
Already installed: 0.12.2
using 0.12.2
~/Install/etherpad-lite on develop
⚡  l src
total 40K
-rw-r--r-- 1 tobi tobi 2.4K Apr  9 15:43 ep.json
-rw-rw-r-- 1 tobi tobi 4.2K Apr 10 09:22 etherpad_icon.svg
drwxr-xr-x 2 tobi tobi 4.0K Apr 10 09:22 locales/
drwxr-xr-x 7 tobi tobi 4.0K Apr  9 15:43 node/
-rw-rw-r-- 1 tobi tobi 2.8K Apr 10 09:22 package.json
-rw-r--r-- 1 tobi tobi   66 Apr  9 15:43 README.md
drwxr-xr-x 6 tobi tobi 4.0K Apr 10 09:22 static/
drwxr-xr-x 3 tobi tobi 4.0K Apr 10 09:22 templates/
-rw-r--r-- 1 tobi tobi 1.2K Apr  9 15:43 web.config
~/Install/etherpad-lite on develop
⚡  npm -g ls
/home/tobi/.nave/installed/0.12.2/lib
└── npm@2.7.4

⚡  npm ls
/home/tobi/Install/etherpad-lite
└── (empty)

~/Install/etherpad-lite on develop
⚡  ./bin/run.sh 
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
 
> ws@0.5.0 install /home/tobi/Install/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/tobi/Install/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/tobi/Install/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
 
> ws@0.4.31 install /home/tobi/Install/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/tobi/Install/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/home/tobi/Install/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
channels@0.0.4 node_modules/channels

security@1.0.0 node_modules/security

async-stacktrace@0.0.2 node_modules/async-stacktrace

slide@1.1.6 node_modules/slide

graceful-fs@3.0.6 node_modules/graceful-fs

tinycon@0.0.1 node_modules/tinycon

formidable@1.0.17 node_modules/formidable

async@0.9.0 node_modules/async

underscore@1.5.1 node_modules/underscore

etherpad-require-kernel@1.0.8 node_modules/etherpad-require-kernel

languages4translatewiki@0.1.3 node_modules/languages4translatewiki

unorm@1.3.3 node_modules/unorm

semver@4.3.3 node_modules/semver

ejs@1.0.0 node_modules/ejs

measured@1.0.0 node_modules/measured
└── inherits@2.0.1

resolve@1.1.6 node_modules/resolve

etherpad-yajsml@0.0.2 node_modules/etherpad-yajsml

supertest@0.15.0 node_modules/supertest
├── methods@1.1.1
└── superagent@0.21.0 (extend@1.2.1, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, qs@1.2.0, mime@1.2.11, debug@2.1.3, form-data@0.1.3, readable-stream@1.0.27-1, formidab
le@1.0.14)

log4js@0.6.22 node_modules/log4js
├── semver@1.1.4
├── async@0.2.10
└── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)

connect@2.7.11 node_modules/connect
├── fresh@0.1.0
├── cookie-signature@1.0.1
├── pause@0.0.1
├── buffer-crc32@0.2.1
├── qs@0.6.5
├── bytes@0.2.0
├── cookie@0.0.5
├── debug@2.1.3 (ms@0.7.0)
├── send@0.1.1 (range-parser@0.0.4, mime@1.2.11)
└── formidable@1.0.14

clean-css@3.1.9 node_modules/clean-css
├── commander@2.6.0
└── source-map@0.1.43 (amdefine@0.1.0)

uglify-js@2.4.19 node_modules/uglify-js
├── uglify-to-browserify@1.0.2
├── async@0.2.10
├── yargs@3.5.4 (decamelize@1.0.0, camelcase@1.0.2, window-size@0.1.0, wordwrap@0.0.2)
└── source-map@0.1.34 (amdefine@0.1.0)

mocha@2.2.1 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.1
├── diff@1.0.8
├── growl@1.8.1
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

request@2.55.0 node_modules/request
├── caseless@0.9.0
├── json-stringify-safe@5.0.0
├── aws-sign2@0.5.0
├── forever-agent@0.6.1
├── form-data@0.2.0
├── stringstream@0.0.4
├── oauth-sign@0.6.0
├── tunnel-agent@0.4.0
├── isstream@0.1.2
├── node-uuid@1.4.3
├── qs@2.4.1
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── mime-types@2.0.10 (mime-db@1.8.0)
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@0.9.4 (readable-stream@1.0.33)
├── tough-cookie@0.12.1 (punycode@1.3.2)
├── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.7.0, hoek@2.12.0)
└── har-validator@1.6.1 (commander@2.7.1, chalk@1.0.0, is-my-json-valid@2.10.1, bluebird@2.9.24)

jsonminify@0.2.3 node_modules/jsonminify

ueberDB@0.2.15 node_modules/ueberDB
├── felix-couchdb@1.0.7
├── redis@0.12.1
├── dirty@0.9.9
├── async@0.1.15
├── cassandra-driver@2.0.1 (async@0.9.0, long@2.2.3)
├── mysql@2.6.1 (require-all@1.0.0, readable-stream@1.1.13, bignumber.js@2.0.5)
└── pg@4.3.0 (packet-reader@0.2.0, pg-connection-string@0.1.3, buffer-writer@1.0.0, generic-pool@2.1.1, pg-types@1.7.0, pgpass@0.0.3)

swagger-node-express@2.1.3 node_modules/swagger-node-express
└── lodash@1.3.1

cheerio@0.19.0 node_modules/cheerio
├── entities@1.1.1
├── dom-serializer@0.1.0 (domelementtype@1.1.3)
├── css-select@1.0.0 (boolbase@1.0.0, css-what@1.0.0, nth-check@1.0.1, domutils@1.4.3)
├── htmlparser2@3.8.2 (domelementtype@1.3.0, domutils@1.5.1, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13)
└── lodash@3.6.0

wd@0.3.11 node_modules/wd
├── vargs@0.1.0
├── q@1.0.1
├── underscore.string@2.3.3
├── lodash@2.4.1
├── request@2.46.0 (caseless@0.6.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, tunnel-agent@0.4.0, oauth-sign@0.4.0, qs@1.2.2, node-uuid@1.4.3, mime-types@1.0.2, f
orm-data@0.1.4, bl@0.9.4, http-signature@0.10.1, tough-cookie@0.12.1, hawk@1.1.1)
└── archiver@0.12.0 (buffer-crc32@0.2.5, lazystream@0.1.0, readable-stream@1.0.33, zip-stream@0.4.1, tar-stream@1.0.2, glob@4.0.6)

socket.io@1.3.5 node_modules/socket.io
├── debug@2.1.0 (ms@0.6.2)
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
├── engine.io@1.5.1 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.1, ws@0.5.0)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
└── socket.io-client@1.3.5 (to-array@0.1.3, indexof@0.0.1, debug@0.7.4, component-bind@1.0.0, backo2@1.0.2, object-component@0.0.3, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, engine.io-clie
nt@1.5.1)

express@3.8.1 node_modules/express
├── parseurl@1.0.1
├── merge-descriptors@0.0.2
├── cookie@0.1.2
├── debug@0.8.1
├── debug@0.8.1
├── cookie-signature@1.0.3
├── fresh@0.2.2
├── range-parser@1.0.0
├── methods@1.0.0
├── buffer-crc32@0.2.1
├── send@0.3.0 (debug@0.8.0, mime@1.2.11)
├── proxy-addr@1.0.0 (ipaddr.js@0.1.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── commander@1.3.2 (keypress@0.1.0)
└── connect@2.17.3 (response-time@1.0.0, pause@0.0.1, method-override@1.0.2, connect-timeout@1.1.0, vhost@1.0.0, qs@0.6.6, on-headers@0.0.0, basic-auth-connect@1.0.0, bytes@1.0.0, serve-favicon@2.0.0, morgan@1.1.1, errorhandler@1.0.1, serve-static@1.1.0, cookie-parser@1.1.0, type-is@1.2.0, compression@1.0.2, csurf@1.2.0, body-parser@1.2.2, express-session@1.2.1, serve-index@1.0.3, multiparty@2.2.0)

npm@2.7.5 node_modules/npm
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-04-10 09:27:49.259] [WARN] console - You need to set a sessionKey value in settings.json, this will allow your users to reconnect to your Etherpad Instance if your instance restarts
[2015-04-10 09:27:49.261] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at loadPlugin (/home/tobi/Install/etherpad-lite/src/static/js/pluginfw/plugins.js:121:26)
    at /home/tobi/Install/etherpad-lite/src/static/js/pluginfw/plugins.js:79:9
    at /home/tobi/Install/etherpad-lite/src/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/home/tobi/Install/etherpad-lite/src/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/home/tobi/Install/etherpad-lite/src/node_modules/async/lib/async.js:124:9)
    at /home/tobi/Install/etherpad-lite/src/static/js/pluginfw/plugins.js:76:11
    at /home/tobi/Install/etherpad-lite/src/static/js/pluginfw/plugins.js:116:5
    at /home/tobi/Install/etherpad-lite/src/static/js/pluginfw/read-installed.js:128:5
```

**Comment by JohnMcLear** [comment]
Remove any plugins you have and try to run again.

**Comment by p3k** [comment]
Sorry, what plugins do you mean? Where should they be located?

**Comment by JohnMcLear** [comment]
in ``/etherpad-lite/node_modules``

**Comment by p3k** [comment]
OK, I completely removed my etherpad-lite directory, made a fresh clone, checked that both, `etherpad-lite/node_modules` and `etherpad-lite/src/node_modules` are empty/gone, ran `nave use stable` and then `bin/run.sh` and still get the error.

**Comment by JohnMcLear** [comment]
wtf is ``nave use stable`` -- That's not in the docs.  Please follow the docs.

**Comment by p3k** [comment]
[nave](https://github.com/isaacs/nave) is a virtual environment manager for Node. Apologies for assuming this is already well-known.

> That's not in the docs. Please follow the docs.

OK, I am trying to:

> Additionally, you'll need node.js installed, Ideally the latest stable version, we recommend installing/compiling nodejs from source (avoiding apt).

`nave use stable` actually installs and activates the latest stable version of Node.

Which way is the recommended one to install Node, then?

**Comment by p3k** [comment]
Same error.

```bash
⚡  git clone https://github.com/joyent/node.git
⚡  git checkout -b v0.12.2-release origin/v0.12.2-release
⚡  cd node
⚡  ./configure --prefix=/home/tobi/local
⚡  make
⚡  make install

⚡  which node
/home/tobi/local/bin/node
⚡  node -v
v0.12.2

⚡  npm ls
/home/tobi/Install/node
└── (empty)

⚡  npm -g ls
/home/tobi/local/lib
└── npm@2.7.4

⚡   cd ../etherpad-lite
⚡  ./bin/run.sh
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
            ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at loadPlugin (/home/tobi/Install/etherpad-lite/src/static/js/pluginfw/plugins.js:121:26)
    at /home/tobi/Install/etherpad-lite/src/static/js/pluginfw/plugins.js:79:9
    at /home/tobi/Install/etherpad-lite/src/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/home/tobi/Install/etherpad-lite/src/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/home/tobi/Install/etherpad-lite/src/node_modules/async/lib/async.js:124:9)
    at /home/tobi/Install/etherpad-lite/src/static/js/pluginfw/plugins.js:76:11
    at /home/tobi/Install/etherpad-lite/src/static/js/pluginfw/plugins.js:116:5
    at /home/tobi/Install/etherpad-lite/src/static/js/pluginfw/read-installed.js:128:5
```

**Comment by JohnMcLear** [comment]
Not sure what's going on here..  

You are still doing ``./bin/run.sh``, ``bin/run.sh`` is the correct command, if you use the correct command does it work okay?

**Comment by akshat-g** [comment]
./bin/run.sh was also throwing error in my system.So I tried with sudo ./bin/run.sh , it will ask to type some random text and it will work. You can try the same

**Comment by a-delrio** [comment]
As a side note: @akshat-g running Etherpad on sudo is not exactly very recommended (unless you are on a testing environment).

About the original subject @p3k, I recommend you trying with nvm (https://github.com/creationix/nvm) for your Node's virtual environments, I don't know nave (I will try it someday, looks cool), thats a way to "reduce noise" for the issue you are having.

Here are the specs of my running etherpad-lite instance: Ubuntu 12.04, NVM 0.23.3, Node 0.11.16, NPM 2.3.0; works like charm!

**Comment by JohnMcLear** [comment]
Pretty sure this isn't a software bug anyway and due to an environmental thing..

**Comment by p3k** [comment]
@akshat-g Unfortunately, running as root did not help. Thanks, anyway.

@a-delrio Thanks for your specs. I tried it one last time with NVM and Node 0.11.16 (Ubuntu 14.10, though) – still getting the error. I think I am going to look for a docker image now… or something :smirk_cat:
