### ISSUE TITLE
Periodic crashes with TypeError: Uncaught, unspecified "error" event.

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2631]
Pretty much impossible to debug crashes periodically happens(every hour or so) under slight load(40 users, 3% cpu, 3% memory) on one of my hosts but there are no steps to replicate consistently.

Plenty of free system resources, it's a CentOS VM and this crash happens periodically..  I have tried turning off plugins etc.

Crash seems to be coming from engine.io..  

I can't replicate on any local instances..  Any tips anyone?

```
[ERROR] console - TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at WebSocket.EventEmitter.emit (events.js:74:15)
    at Receiver.onerror (/home/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:775:10)
    at Receiver.error (/home/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.hixie.js:153:8)
    at doAdd (/home/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.hixie.js:61:14)
    at Receiver.add (/home/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.hixie.js:104:22)
    at CleartextStream.firstHandler (/home/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:718:22)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:746:14)
    at CleartextStream.EventEmitter.emit (events.js:92:17)
```

**Comment by JohnMcLear** [comment]
Updating to Node 12+ fixed this for me..  Spooooooky :|

**Comment by kingmook** [comment]
I've been receiving this exact error under very similar circumstances (CentOS, low load and users) since upgrading to the most recent develop very of etherpad (cloned down on Oct 28th).

I was running node 4.2.1 but downgraded to 12.7 following your 12+ response. Doesn't seem to have helped.

Happy to give more details or create a separate issue if appropriate. Wondering if you ever got to the bottom of this one?

**Comment by webzwo0i** [comment]
Can you provide a new stacktrace and the corresponding versions in
socket.io/package.json
socket.io/node_modules/engine.io/package.json
socket.io/node_modules/engine.io/node_modules/ws/package.json

**Comment by kingmook** [comment]
Sorry for the delay webz. Stack trace and versions as requested:

    [ERROR] console - TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at WebSocket.EventEmitter.emit (events.js:74:15)
    at Receiver.onerror (/opt/etherpad/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:775:10)
    at Receiver.error (/opt/etherpad/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.hixie.js:153:8)
    at doAdd (/opt/etherpad/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.hixie.js:61:14)
    at Receiver.add (/opt/etherpad/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.hixie.js:104:22)
    at CleartextStream.firstHandler (/opt/etherpad/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:718:22)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:746:14)
    at CleartextStream.EventEmitter.emit (events.js:92:17)


socket.io/package.json - version 1.3.5

socket.io/node_modules/engine.io/package.json - version 1.5.1

socket.io/node_modules/engine.io/node_modules/ws/package.json - version 0.5.0

**Comment by kingmook** [comment]
Still getting this one as of today. Has upgrading to a newer version of the code base or node saved others?

**Comment by JohnMcLear** [comment]
Modern code is stable.
