### ISSUE TITLE
Errors with run.sh

### ISSUE THREAD

**Issue by emilyxxie** [ether/etherpad-lite#2637]
Hey, I have some issues when I try running etherpad.  I had no problem running it just a week or so ago. Originally, I got this message:

~~~~~~~~
 [ERROR] console - FATAL: The sqlite dependency could not be loaded. We removed it from the dependencies since it caused problems on several Platforms to compile it. If you still want to use sqlite, do a 'npm install sqlite3' in your etherpad-lite root folder.
~~~~~~~~
So I did a sudo npm install sqlite3 as prescribed. After this, I ran bin/run.sh in the etherpad root dir and I get this error message:

~~~~~~~~~
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json channels@0.0.4 No repository field.
npm WARN package.json async-stacktrace@0.0.2 No repository field.
npm WARN package.json tinycon@0.0.1 No repository field.
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
Ensure custom css/js files are created...
Started Etherpad...

path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
        ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at loadPlugin (/csnzoo/exie/etherpad-lite/src/static/js/pluginfw/plugins.js:121:26)
    at async.forEach.exports.plugins (/csnzoo/exie/etherpad-lite/src/static/js/pluginfw/plugins.js:79:9)
    at /csnzoo/exie/etherpad-lite/src/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/csnzoo/exie/etherpad-lite/src/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/csnzoo/exie/etherpad-lite/src/node_modules/async/lib/async.js:124:9)
    at /csnzoo/exie/etherpad-lite/src/static/js/pluginfw/plugins.js:76:11
    at /csnzoo/exie/etherpad-lite/src/static/js/pluginfw/plugins.js:116:5
    at /csnzoo/exie/etherpad-lite/src/static/js/pluginfw/read-installed.js:128:5
~~~~~~~~~

Not entirely sure what to do here. Let me know if you know how to solve the problem. Thanks.

**Comment by JohnMcLear** [comment]
Remove all plugins and try run again
----- Reply message -----

**Comment by emilyxxie** [comment]
Thanks. Sorry for the delayed response on this --- but I tried removing all the plugins. This did not work. However, commenting out the plugins in the etherpad root level package.json file did somehow work.

**Comment by JohnMcLear** [comment]
Lulwut
----- Reply message -----

**Comment by emilyxxie** [comment]
Yeah, no clue.

**Comment by JohnMcLear** [comment]
For future reference In included bin/cleanRun.sh which helps with broken installations like this.
