### ISSUE TITLE
run.sh errors

### ISSUE THREAD

**Issue by akuckartz** [ether/etherpad-lite#2638]
Any suggestions?

(Debian unstable)

$ bin/run.sh
~~~
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm ERR! Error: No compatible version found: inherits@'^2.0'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","2.0.0","2.0.1"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--loglevel" "warn"
npm ERR! cwd /home/andreas/etherpad-lite/src
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm WARN package.json dom-serializer@0.1.0 No README.md file found!
npm ERR! EEXIST, mkdir '/home/andreas/etherpad-lite/src/node_modules/uglify-js/node_modules/source-map/test/source-map'
File exists: /home/andreas/etherpad-lite/src/node_modules/uglify-js/node_modules/source-map/test/source-map                  
Move it away, and try again. 

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--loglevel" "warn"
npm ERR! cwd /home/andreas/etherpad-lite/src
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm ERR! path /home/andreas/etherpad-lite/src/node_modules/uglify-js/node_modules/source-map/test/source-map
npm ERR! fstream_path /home/andreas/etherpad-lite/src/node_modules/uglify-js/node_modules/source-map/test/source-map/test-base64.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/andreas/etherpad-lite/src/node_modules/wd/node_modules/archiver/node_modules/readable-stream/lib/_stream_readable.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
...
~~~

**Comment by JohnMcLear** [comment]
Ensure you are running latest node..

```
git checkout develop
bin/cleanRun.sh
```

**Comment by akuckartz** [comment]
Thanks for the quick reply. In parallel I had already executed this:
`$ npm install -g npm`

That resolved the issue and Etherpad is running now !
