### ISSUE TITLE
etherpad lite is working can not acces admin

### ISSUE THREAD

**Issue by stefanschauer** [ether/etherpad-lite#2639]
hi!

i am running etherpad on a debian machine and etherpad is running fine. 
but when i try to access the admin area (/admin) i get the error message "error": "Sorry, something bad happened!"
in the log I see the following 
TypeError: Cannot read property 'length' of undefined
    at /var/www/etherpad-lite/src/node/hooks/express/webaccess.js:13:29
    at next (/var/www/etherpad-lite/src/static/js/pluginfw/hooks.js:45:33)
    at Object.exports.mapFirst (/var/www/etherpad-lite/src/static/js/pluginfw/hooks.js:52:3)
    at Object.exports.aCallFirst (/var/www/etherpad-lite/src/static/js/pluginfw/hooks.js:108:11)
    at authorize (/var/www/etherpad-lite/src/node/hooks/express/webaccess.js:28:11)
    at Object.exports.basicAuth [as handle] (/var/www/etherpad-lite/src/node/hooks/express/webaccess.js:79:3)
    at next (/var/www/etherpad-lite/src/node_modules/express/node_modules/connect/lib/proto.js:194:15)
    at Object.session [as handle] (/var/www/etherpad-lite/src/node_modules/express/node_modules/connect/node_modules/express-session/index.js:209:7)
    at next (/var/www/etherpad-lite/src/node_modules/express/node_modules/connect/lib/proto.js:194:15)
    at Object.cookieParser [as handle] (/var/www/etherpad-lite/src/node_modules/express/node_modules/connect/node_modules/cookie-parser/index.js:45:5)

google didn't help me very much.

anyone any hint what went wrong?

**Comment by JohnMcLear** [comment]
What version of ep? Any plugins?
----- Reply message -----

**Comment by stefanschauer** [comment]
ah thanks!
i checked if i have any plugins installed and deleted ep_ldapauth and I can access now the admin area.
many thanks!
