### ISSUE TITLE
handleUserInfoUpdate does not guard against invalid sessions

### ISSUE THREAD

**Issue by cboylan** [ether/etherpad-lite#2674]
Recently we noticed two different failures in handleUserInfoUpdate that appear related to it not guarding against invalid session data.

> [2015-05-20 16:20:58.908] [ERROR] console - TypeError: Cannot read property 'author' of undefined
>     at handleUserInfoUpdate (/opt/etherpad-lite/etherpad-lite/src/node/handler/PadMessageHandler.js:537:39)
>     at finalHandler (/opt/etherpad-lite/etherpad-lite/src/node/handler/PadMessageHandler.js:222:9)
>     at /opt/etherpad-lite/etherpad-lite/src/node_modules/async/lib/async.js:610:21
>     at /opt/etherpad-lite/etherpad-lite/src/node_modules/async/lib/async.js:249:17
>     at iterate (/opt/etherpad-lite/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
>     at /opt/etherpad-lite/etherpad-lite/src/node_modules/async/lib/async.js:160:25
>     at /opt/etherpad-lite/etherpad-lite/src/node_modules/async/lib/async.js:251:21
>     at /opt/etherpad-lite/etherpad-lite/src/node_modules/async/lib/async.js:615:34
>     at checkAccessCallback (/opt/etherpad-lite/etherpad-lite/src/node/handler/PadMessageHandler.js:273:15)
>     at /opt/etherpad-lite/etherpad-lite/src/node/db/SecurityManager.js:89:11
> [2015-05-20 16:20:58.909] [INFO] console - graceful shutdown...

And

> [2015-05-20 16:37:39.699] [ERROR] console - TypeError: Cannot set property 'colorId' of null
>     at /opt/etherpad-lite/etherpad-lite/src/node_modules/ueberDB/CacheAndBufferLayer.js:317:41
>     at fn (/opt/etherpad-lite/etherpad-lite/src/node_modules/ueberDB/node_modules/async/lib/async.js:525:34)
>     at /opt/etherpad-lite/etherpad-lite/src/node_modules/ueberDB/node_modules/async/lib/async.js:449:34
>     at process._tickDomainCallback (node.js:459:13)
> [2015-05-20 16:37:39.699] [INFO] console - graceful shutdown...

We think this happens if the server is under enough load that clients can connect, send user info updates, then disconnect quickly enough that by the time we try to handle the user info update the session does not exist.

As far as reproducing goes the clients were at a relatively large event and the logs were not sufficient to trace back to a specific client/browser version. I even tried tcpdumping hoping I could work back from there but etherpad doesn't seem to have responded with an error (likely because the session is gone so there is no where to send the error to).

On the server we are running Ubuntu Precise (12.04) with node.js v0.10.21.

I do have a fix that we have deployed that seems to be working, I will get a pull request up momentarily.

**Comment by cboylan** [comment]
Pull request made at https://github.com/ether/etherpad-lite/pull/2675 (there was probably a better way to link the request and issue but I fail, sorry).

**Comment by cboylan** [comment]
This should be fixed by Pull Request #2675 so closing this issue now.
