### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ghost** [ether/etherpad-lite#2722]
hello,

I try to connect my etherpad instance with CouchDB!
Following steps i had done:
- Install etherpad on windows machine (8.1) - https://github.com/ether/etherpad-lite
- For that i also installed Node.JS before 
- Set port rules (i used 50000) etc., Etherpad runs now with dirtyDB!

So i want to run them with my CouchDB instance and i used ueberDB for that...
This article describe how to set up a connection to mongoDB and, so described in the article this is nearly equivalent to CouchDB:
http://blog.nikhilben.com/2013/11/01/etherpad-lite-and-mongo-db/
in settings.json, instead of: 
"dbType" : "mongodb",

"dbSettings" : {
  "user"    : "user",
  "host"    : "localhost",
  "port" : 43348,
  "password": "password",
  "dbname": "db_name"
}

i used: 
"dbType" : "couchdb",
… and my settings

And instead of:
sudo npm install mongodb –g

i used (without sudo because i run them on win):
npm install couchdb –g

works all, but after i started them with start.bat i get this:

[2015-07-07 16:56:14.507] [INFO] console - Installed plugins: ep_etherpad-lite
[2015-07-07 16:56:14.549] [INFO] console - Report bugs at https://github.com/eth
er/etherpad-lite/issues
[2015-07-07 16:56:14.551] [WARN] console - Can't get git version for server head
er
ENOENT, no such file or directory 'C:\etherpad.git\HEAD'
[2015-07-07 16:56:14.558] [WARN] console - Can't get git version for server head
er
ENOENT, no such file or directory 'C:\etherpad.git\HEAD'
[2015-07-07 16:56:14.559] [INFO] console - Your Etherpad version is 1.5.6 ()
[2015-07-07 16:56:14.686] [INFO] console - You can access your Etherpad instance
 at http://192.168.1.22:50000/
[2015-07-07 16:56:14.687] [INFO] console - The plugin admin page is at http://19
2.168.1.22:50000/admin/plugins
[2015-07-07 16:56:14.919] [ERROR] console - TypeError: Cannot read property '0'
of undefined
    at IncomingMessage.<anonymous> (C:\etherpad\node_modules\ep_etherpad-lite\no
de_modules\ueberDB\node_modules\felix-couchdb\lib\couchdb.js:220:47)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
[2015-07-07 16:56:14.925] [INFO] console - graceful shutdown...
[2015-07-07 16:56:14.991] [INFO] console - db sucessfully closed.

C:\etherpad>

... and etherpad shutdown :(

I searched many times to get them work, but still without success. i didn't found something helpfull.

Please help me,
Thanks!!!

**Comment by Pita** [comment]
Something that couchdb sends to etherpad lite causes it to crash. That could be anything really. A configuration error or a problem with your version of couchdb.
