### ISSUE TITLE
crash on html export

### ISSUE THREAD

**Issue by Flauschie** [ether/etherpad-lite#2725]
My etherpad instance crashes when trying to export a pad as html (any pad)

revision 200396

```
[2015-07-12 14:17:12.884] [WARN] client - TypeError: undefined is not an object (evaluating '$(span.target).closest('span').get(0).className') -- { errorId: '613MIzTeV76ip3SiBiLb',
  msg: 'TypeError: undefined is not an object (evaluating \'$(span.target).closest(\'span\').get(0).className\')',
  url: 'https://URL/p/Pads',
  linenumber: 65,
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12' }
[2015-07-12 14:17:12.887] [INFO] ueberDB - Flushed 1 values
[2015-07-12 14:17:15.727] [ERROR] console - ReferenceError: ChangeSet is not defined
    at checkHrInLine (/usr/share/nginx/www/etherpad-lite/node_modules/ep_horizontal_line/horizontalLine.js:21:14)
    at Object.getLineHTMLForExport [as hook_fn] (/usr/share/nginx/www/etherpad-lite/node_modules/ep_horizontal_line/horizontalLine.js:11:11)
    at normalizedhook (/usr/share/nginx/www/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
    at hookCallWrapper (/usr/share/nginx/www/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
    at /usr/share/nginx/www/etherpad-lite/src/static/js/pluginfw/hooks.js:76:14
    at Function._.map._.collect (/usr/share/nginx/www/etherpad-lite/src/node_modules/underscore/underscore.js:172:24)
    at Object.exports.callAll (/usr/share/nginx/www/etherpad-lite/src/static/js/pluginfw/hooks.js:75:24)
    at Object.exports.callAllStr (/usr/share/nginx/www/etherpad-lite/src/static/js/pluginfw/hooks.js:122:27)
    at getHTMLFromAtext (/usr/share/nginx/www/etherpad-lite/src/node/utils/ExportHtml.js:422:39)
    at /usr/share/nginx/www/etherpad-lite/src/node/utils/ExportHtml.js:55:12
[2015-07-12 14:17:15.727] [INFO] console - graceful shutdown...
[2015-07-12 14:17:15.804] [INFO] ueberDB - Flushed 1 values
[2015-07-12 14:17:15.907] [INFO] console - db sucessfully closed.
```

**Comment by JohnMcLear** [comment]
Read the error log, it tells you what is causing the crash.

**Comment by Flauschie** [comment]
I cannot see it... I created a new pad, horizontal line isn't used at all.
