### ISSUE TITLE
Errors on Raspbian (raspberry pi) using io.js 2.x

### ISSUE THREAD

**Issue by evitalis** [ether/etherpad-lite#2726]
I am using a clean install of Raspbian (Jessie) on my raspberry pi and am having issues with getting etherpad-lite to run using a semi recent release of io.js. I am running as root to test and ensure it runs properly but then will be using a system service to run it.

Using debsource repos I pulled the latest version of io.js available but then needed to use the pre-compiled binaries to resolve a segmentation fault issue. The versions below are for the pre-compiled binaries which do come with the file that is labelled as missing. I am also unsure how to resolve all of the warnings as well but they do not seem to impede the start of etherpad.

System details are here:
```
root@localhost:~# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

root@localhost:~# iojs -v
v2.3.3

root@localhost:~# npm -v
2.11.3
```
And the error:
```
root@localhost:/srv/etherpad-lite/bin# ./run.sh --root
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json ep_etherpad-lite@1.5.6 No license field.
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/ueberDB requires async@'0.1.15' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/async,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/uglify-js requires async@'~0.2.6' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/async,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/log4js requires async@'~0.2.0' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/async,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/log4js requires semver@'~1.1.4' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/semver,
npm WARN unmet dependency which is version 4.3.3
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/npm requires request@'~2.54.0' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/request,
npm WARN unmet dependency which is version 2.55.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/wd requires request@'~2.46.0' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/request,
npm WARN unmet dependency which is version 2.55.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/supertest/node_modules/superagent requires formidable@'1.0.14' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/formidable,
npm WARN unmet dependency which is version 1.0.17
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/supertest/node_modules/superagent requires methods@'1.0.1' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/supertest/node_modules/methods,
npm WARN unmet dependency which is version 1.1.1
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
module.js:338
    throw err;
          ^
Error: Cannot find module 'npm/lib/npm.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/srv/etherpad-lite/src/node/server.js:39:11)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
```
Using node.js from the Debian repos (0.10.x) results in the following, and the 0.12.x version has segmentation faults when attempting to run it:
```
root@localhost:/srv/etherpad-lite/bin# ./run.sh --root
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json async-stacktrace@0.0.2 No repository field.
npm WARN package.json channels@0.0.4 No repository field.
npm WARN package.json etherpad-yajsml@0.0.2 No README data
npm WARN package.json tinycon@0.0.1 No repository field.
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/ueberDB requires async@'0.1.15' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/async,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/uglify-js requires async@'~0.2.6' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/async,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/log4js requires async@'~0.2.0' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/async,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/log4js requires semver@'~1.1.4' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/semver,
npm WARN unmet dependency which is version 4.3.3
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/npm requires request@'~2.54.0' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/request,
npm WARN unmet dependency which is version 2.55.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/wd requires request@'~2.46.0' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/request,
npm WARN unmet dependency which is version 2.55.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/supertest/node_modules/superagent requires formidable@'1.0.14' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/formidable,
npm WARN unmet dependency which is version 1.0.17
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/supertest/node_modules/superagent requires methods@'1.0.1' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/supertest/node_modules/methods,
npm WARN unmet dependency which is version 1.1.1
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-07-12 13:45:46.569] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.

module.js:117
    throw e;
          ^
SyntaxError: Error parsing /srv/etherpad-lite/src/node_modules/ueberDB/node_modules/async/package.json: Unexpected end of input
    at Object.parse (native)
    at readPackage (module.js:113:52)
    at tryPackage (module.js:123:13)
    at Function.Module._findPath (module.js:190:18)
    at Function.Module._resolveFilename (module.js:336:25)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/etherpad-lite/src/node_modules/ueberDB/CacheAndBufferLayer.js:29:13)
    at Module._compile (module.js:456:26)
```
Finally I reinstalled the recent version of io.js and symlinked the missing lib directory and then got this:
```
root@localhost:/srv/etherpad-lite# ./bin/run.sh --root
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json ep_etherpad-lite@1.5.6 No license field.
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/npm requires request@'~2.54.0' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/request,
npm WARN unmet dependency which is version 2.55.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/wd requires request@'~2.46.0' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/request,
npm WARN unmet dependency which is version 2.55.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-parser requires debug@'0.7.4' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/socket.io/node_modules/debug,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client requires debug@'1.0.4' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/debug,
npm WARN unmet dependency which is version 0.7.4
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client requires parseuri@'0.0.4' but will load
npm WARN unmet dependency /srv/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/parseuri,
npm WARN unmet dependency which is version 0.0.2
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-07-12 14:39:06.697] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2015-07-12 14:39:16.839] [WARN] pluginfw - /srv/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm requires request@'~2.54.0' but will load
/srv/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/request,
which is version 2.55.0 unmet dependency
[2015-07-12 14:39:16.890] [WARN] pluginfw - /srv/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/wd requires request@'~2.46.0' but will load
/srv/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/request,
which is version 2.55.0 unmet dependency
[2015-07-12 14:39:16.942] [WARN] pluginfw - /srv/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/socket.io/node_modules/socket.io-parser requires debug@'0.7.4' but will load
/srv/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/socket.io/node_modules/debug,
which is version 2.1.0 unmet dependency
[2015-07-12 14:39:16.969] [WARN] pluginfw - /srv/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client requires debug@'1.0.4' but will load
/srv/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/socket.io/node_modules/socket.io-client/node_modules/debug,
which is version 0.7.4 unmet dependency
[2015-07-12 14:39:16.975] [WARN] pluginfw - /srv/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client requires parseuri@'0.0.4' but will load
/srv/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/socket.io/node_modules/socket.io-client/node_modules/parseuri,
which is version 0.0.2 unmet dependency
[2015-07-12 14:39:26.760] [ERROR] console - Failed to load '/srv/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/socketio:expressCreateServer' for 'ep_etherpad-lite/socketio/hooks/expressCreateServer': Error: Cannot find module 'ultron'
[2015-07-12 14:39:31.172] [INFO] console - Installed plugins:
[2015-07-12 14:39:31.322] [ERROR] console - Failed to load 'ep_etherpad-lite/node/hooks/express/socketio:expressCreateServer' for 'ep_etherpad-lite/socketio/hooks/expressCreateServer': Error: Cannot find module 'ultron'
[2015-07-12 14:39:31.386] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2015-07-12 14:39:31.407] [INFO] console - Your Etherpad version is 1.5.6 (2003968)
[2015-07-12 14:39:31.691] [ERROR] console - Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/srv/etherpad-lite/src/node_modules/swagger-node-express/lib/swagger.js:19:9)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
[2015-07-12 14:39:31.695] [INFO] console - graceful shutdown...
[2015-07-12 14:39:31.701] [INFO] console - db sucessfully closed.
```
Which again does exist:
```
root@localhost:/srv/etherpad-lite# find / -name 'lodash'
/tmp/npm-25062-4193671d/registry.npmjs.org/lodash
/root/.npm/registry.npmjs.org/lodash
/root/.npm/lodash
/srv/etherpad-lite/src/node_modules/cheerio/node_modules/lodash
/srv/etherpad-lite/src/node_modules/swagger-node-express/node_modules/lodash
```

**Comment by evitalis** [comment]
As an update to this, which I forgot to post yesterday. I was able to set this up in a x64 Debian VM and rsync the cloned etherpad directory to the Pi and it then started to work. I am unsure what is different though but may be an issue with one of the scripts not playing nice on Raspbian.
