### ISSUE TITLE
MySQL connection timeout shuts down etherpad-lite

### ISSUE THREAD

**Issue by monokles** [ether/etherpad-lite#2747]
Hey, I'm running Etherpad for a small group of people, and it keeps crashing telling me the database closed the connection. Some quick googling told me it had to do with the mysql global wait_timeout variable, which is 8 hours by default.
I tested this quickly by playing around with that setting on my mysql server (see log)
```
~/etherpad/etherpad-lite$ mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 81
Server version: 5.5.43-0+deb8u1 (Debian)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
mysql> set global wait_timeout = 5;
Query OK, 0 rows affected (0.00 sec)

mysql> exit
Bye
~/etherpad/etherpad-lite$ bin/run.sh -s settings.json
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json async-stacktrace@0.0.2 No repository field.
npm WARN package.json channels@0.0.4 No repository field.
npm WARN package.json tinycon@0.0.1 No repository field.
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-08-06 20:59:07.170] [ERROR] console - Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/mono/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:103:13)
    at Socket.<anonymous> (/home/mono/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickDomainCallback (node.js:463:13)
[2015-08-06 20:59:07.174] [INFO] console - graceful shutdown...
[2015-08-06 20:59:07.177] [INFO] console - Installed plugins: ep_copy_paste_images@0.0.13, ep_embedmedia@0.0.4, ep_headings2@0.0.9, ep_markdown@0.0.9, ep_previewimages@0.0.9, ep_user_pad@0.1.3, ep_xforwardedproto_redir@0.2.0
[2015-08-06 20:59:07.376] [INFO] console - db sucessfully closed.
~/etherpad/etherpad-lite$ 
```

While I can of course fix this by setting the wait_timeout to a  high enough  value to make sure it'll never be reached, I think there should be a cleaner way to handle this as pad usage is very irregular (sometimes a couple of times a day, but other times we go without using one for more than a month).

I'm thinking something along the lines of Etherpad being able to function without having an open database connection whenever there's no activity would make for a nice fix to this, then again I'm not sure if you consider this an etherpad issue or just a mysql configuration issue. I thought I'd let you know anyway :smile: 

I hope this is enough info in order to describe the issue, if not just let me know, and I'll try to provide the info you need!

**Comment by Gared** [comment]
@Pita I thought we fixed this?!
@monokles What version of etherpad are you using?

**Comment by monokles** [comment]
@Gared I was dumb enough to pull a new version before checking the current one, so I don't know which version I was using. It was the latest develop branch as of 2 weeks ago though. I haven't tested this with the newest version which I just pulled, but if you want I can do so

**Comment by Gared** [comment]
@monokles No, you don't have to test it again. It should have been fixed since a few months, so the error should never happen. Etherpad should send a "keep alive" request if no other request was made to the database in a specific time.
Which version of ueberDB are you using?

**Comment by monokles** [comment]
Hey, I did a quick check...
```
$ npm list | grep ueber
│ ├─┬ ueberDB@0.2.15
npm ERR! extraneous: lodash._basetostring@3.0.0 /home/mono/etherpad/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/lodash._basetostring
npm ERR! extraneous: lodash._createpadding@3.6.0 /home/mono/etherpad/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/lodash._createpadding
npm ERR! extraneous: async@0.9.0 /home/mono/etherpad/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/request/node_modules/async
npm ERR! not ok code 0
```
Now, I'm no node expert, but those error messages look like they have to do with npm's log or something. In any case, I'm not sure so I left them in.
Thanks for looking into this issue, I love etherpad :smile: !

**Comment by Gared** [comment]
Please try this (removes dependencies and installs them again):
```
rm -Rf src/node_modules
bin/run.sh
```

**Comment by monokles** [comment]
It doesn't occur anymore, that fixed it!
However while setting mysql's global wait_timeout to very low values I noticed that no keep-alives are sent to the database while etherpad is waiting for me to fill in my PEM password, as it crashed if it took me longer than wait_timeout amount of seconds. Personally I don't really consider this an issue at all anymore though,  as the default wait_timeout is 8 hours.

**Comment by Gared** [comment]
You can file a bug report on the ueberDB repo:
https://github.com/Pita/ueberDB
Please close this issue if there is only the ueberDB problem left.
