### ISSUE TITLE
convert.js "Cannot read property 'subDomain' of undefined"

### ISSUE THREAD

**Issue by colttt** [ether/etherpad-lite#2758]
Hello,

will migrate from etherpad to etherpad-lite, i will also use all the old data and use the etherpad-lite convert script, as described here: https://github.com/ether/etherpad-lite/wiki/How-to-migrate-the-database-from-Etherpad-to-Etherpad-Lite

but i get the following error:
```
node convert.js convertSettings.json etherpad-lite.sql 
0.092   read settings file...
0.093   done
0.093   open output file...
0.096   done
0.097   get all padIds out of the database...
0.112   done

/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'subDomain' of undefined
    at Query._callback (/opt/etherpad/etherpad-lite/bin/convert.js:291:37)
    at Query.Sequence.end (/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
```

**Comment by Gared** [comment]
Is the table "pro_domains" present in your database?
Do you use the same login data for the script as for the etherpad service? If not, maybe you have a problem with your permissions.

**Comment by Gared** [comment]
@colttt Any update on this?

**Comment by derunterstrich** [comment]
hi i have the same problem. 
the table pro_domains exist and the user is root (dev-system)


/root/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'subDomain' of undefined
    at Query._callback (/root/etherpad-lite/bin/convert.js:292:37)
    at Query.Sequence.end (/root/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/root/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/root/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/root/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/root/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/root/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
