### ISSUE TITLE
ODF Export not working

### ISSUE THREAD

**Issue by bjonnh** [ether/etherpad-lite#2782]
I am able to export with DOC, PDF, Etherpad but not with ODF.

2015-09-15 23:39:20.828] [ERROR] console - Abiword File failed to convert [Error: Abiword died with exit code null]
Error: Abiword died with exit code null
    at module.exports (/opt/etherpad-lite/src/node_modules/async-stacktrace/ERR.js:46:13)
    at /opt/etherpad-lite/src/node/handler/ExportHandler.js:224:36
    at /opt/etherpad-lite/src/node_modules/async/lib/async.js:254:17
    at /opt/etherpad-lite/src/node_modules/async/lib/async.js:151:21
    at /opt/etherpad-lite/src/node_modules/async/lib/async.js:251:21
    at Object.callback (/opt/etherpad-lite/src/node_modules/async/lib/async.js:615:34)
    at stdoutCallback (/opt/etherpad-lite/src/node/utils/Abiword.js:135:14)
    at ChildProcess.<anonymous> (/opt/etherpad-lite/src/node/utils/Abiword.js:94:7)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:809:12)

**Comment by bjonnh** [comment]
tried with Version number: 1.5.7
with and without plugins

**Comment by bjonnh** [comment]
AbiWord:> convert /tmp/etherpad_export_976394458.html /tmp/test.odt odt
Aborted (core dumped)

Likely to be related to my AbiWord install…

**Comment by quydang** [comment]
Hi @bjonnh,
I have same issue with you. Have you find the solution to fix it?
I see a ticket relative: https://github.com/AbiWord/abiword/commit/ed9856d44bdf4ee1885b571d3464e49e888f1b91. 
But I installed abiword from packet (abiword 3.0.0). So I still not fix it.

**Comment by bjonnh** [comment]
My solution has been to make a patch allowing the use of pandoc instead of abiword. But I had to move to another project at work and couldn't allow more time on it. It was not working perfectly but it did the job. The last changes in the master branch broke the compatibility with it, so it is still stuck there…
