### ISSUE TITLE
TypeError: Failed to decode param '%b1%b4%b1%c3%b4_%b1%c3%b4%c3%b1%b4'

### ISSUE THREAD

**Issue by ratmole** [ether/etherpad-lite#2793]
there is a problem when pad name contains greek letters
if the pad name is "τεστ" it works ok
if the pad name contains a space char : "τεστ τεστ" then it crashes with:

TypeError: Failed to decode param '%c4%b5%c3%c4_%c4%b5%c3%c4'
   at decode_param (/srv/etherpad-lite/src/node_modules/express/lib/router/layer.js:162:15)
   at Layer.match (/srv/etherpad-lite/src/node_modules/express/lib/router/layer.js:136:11)
   at matchLayer (/srv/etherpad-lite/src/node_modules/express/lib/router/index.js:545:18)
   at next (/srv/etherpad-lite/src/node_modules/express/lib/router/index.js:206:15)
   at Layer.handle [as handle_request] (/srv/etherpad-lite/src/node_modules/express/lib/router/layer.js:78:12)
   at trim_prefix (/srv/etherpad-lite/src/node_modules/express/lib/router/index.js:302:13)
   at /srv/etherpad-lite/src/node_modules/express/lib/router/index.js:270:7
   at Function.proto.process_params (/srv/etherpad-lite/src/node_modules/express/lib/router/index.js:321:12)
   at next (/srv/etherpad-lite/src/node_modules/express/lib/router/index.js:261:10)
   at /srv/etherpad-lite/src/node/hooks/express/webaccess.js:82:20 

etherpad lite version is the master from git.

**Comment by Gared** [comment]
It looks like this is an issue with the HTTP header "Location". If the pad name contains a white space or a colon the user will be redirected to a url with an underscore instead. Is any "special character" in this parameter you get this error message.
I don't really know why, but when I call encodeURIComponent before sending the new pad name to the client this fixes this issue.

**Comment by Gared** [comment]
@ratmole Please test my pull request

**Comment by ratmole** [comment]
just tested and seems to work.
thank you Gared.
