### ISSUE TITLE
Running etherpad-lite on nodejs 4.2.0 doesn't connect to Mysql

### ISSUE THREAD

**Issue by MorrisJobke** [ether/etherpad-lite#2803]
```
$ sudo -u etherpad /usr/share/webapps/etherpad-lite/bin/run.sh -s /etc/webapps/etherpad-lite/settings.json
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.

> ws@0.5.0 install /usr/share/webapps/etherpad-lite/src/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Verzeichnis „/usr/share/webapps/etherpad-lite/src/node_modules/ws/build“ wird betreten
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:92: die Regel für Ziel „Release/obj.target/bufferutil/src/bufferutil.o“ scheiterte
make: Verzeichnis „/usr/share/webapps/etherpad-lite/src/node_modules/ws/build“ wird verlassen
npm WARN EPACKAGEJSON ep_etherpad-lite@1.5.7 No license field.
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-10-13 09:21:50.895] [ERROR] console - ERROR: Problem while initalizing the database
[2015-10-13 09:21:50.898] [ERROR] console - Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:154:17)
    at emitNone (events.js:67:13)
    at Handshake.emit (events.js:166:7)
    at Handshake._onTimeout (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:116:8)
    at Timer.listOnTimeout (timers.js:92:15)
    --------------------
    at Protocol._enqueue (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/Connection.js:109:18)
    at Connection._implyConnect (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/Connection.js:387:10)
    at Connection.query (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/Connection.js:174:8)
    at exports.database.init (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/mysql_db.js:74:6)
    at exports.database.init (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/CacheAndBufferLayer.js:110:18)
    at exports.database.init (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/CloneAndAtomicLayer.js:48:11)
    at Object.exports.init (/usr/share/webapps/etherpad-lite/src/node/db/DB.js:41:6)
    at /usr/share/webapps/etherpad-lite/src/node/server.js:62:8
```

I then downgraded to nodejs 0.12.7 and etherpad just starts fine.

cc @Gared 

This could also be very likely a nodejs problem, but I'm unsure where and how to report this.

@gared I add you, because you added the switch: https://github.com/Gared/etherpad-lite/commit/bf7930fccb37ac6d2b40115ff41c2c0b70fb1061 - I also admit that I used a 1.5.7 and only applied your patch. Maybe this couldn't work, but on ther other side I also couldn't find big changes between 1.5.7 and the current HEAD: https://github.com/ether/etherpad-lite/compare/83597562c1dd8f9d284cc68a8a94b63cdac039a1...develop#diff-5d2aa4336c4964b828a123e20e09b73c

Feel free to simply close this, if I just did it the wrong way.

**Comment by dvzrv** [comment]
You have this problem because of a configuration problem. Add
    "socketPath": "/var/run/mysqld/mysqld.sock"
to your "dbSettings" and all should be fine.

This needs to be added to the default configuration file shipped with etherpad-lite!

**Comment by MorrisJobke** [comment]
I just tested it. Doesn't work either.

https://github.com/Pita/ueberDB/wiki/MySQL-Sockets

I also couldn't find socketPath in the code: 
https://github.com/Pita/ueberDB/search?utf8=%E2%9C%93&q=socketPath
https://github.com/ether/etherpad-lite/search?utf8=%E2%9C%93&q=socketPath

I used "port" to specify the socket, as it is written in the documentation. Or is the documentation out of date? :see_no_evil:

**Comment by dvzrv** [comment]
@MorrisJobke can you post your current output of etherpad-lite, when running with the above mentioned settings?

Just asking, because I suspect something else here, as we seem to be running the same software, but for me it's working!

**Comment by MorrisJobke** [comment]
This is the output for nodejs 0.12.x:

```
$ sudo -u etherpad /usr/share/webapps/etherpad-lite/bin/run.sh -s /etc/webapps/etherpad-lite/settings.json
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.

> ws@0.5.0 install /usr/share/webapps/etherpad-lite/src/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Verzeichnis „/usr/share/webapps/etherpad-lite/src/node_modules/ws/build“ wird betreten
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Verzeichnis „/usr/share/webapps/etherpad-lite/src/node_modules/ws/build“ wird verlassen
npm WARN EPACKAGEJSON ep_etherpad-lite@1.5.7 No license field.
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-10-13 13:18:49.275] [WARN] pluginfw - /usr/share/webapps/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/has-cors requires global@'https://github.com/component/global/archive/v2.0.1.tar.gz' but will load
/usr/share/webapps/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/global,
which is version 2.0.1 unmet dependency
[2015-10-13 13:18:49.281] [WARN] pluginfw - /usr/share/webapps/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/engine.io-client requires xmlhttprequest@'https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz' but will load
/usr/share/webapps/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/xmlhttprequest,
which is version 1.5.0 unmet dependency
[2015-10-13 13:18:49.926] [INFO] console - Installed plugins: ep_tasklist@0.0.11, ep_adminpads@0.0.9
[2015-10-13 13:18:49.949] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2015-10-13 13:18:49.949] [WARN] console - Can't get git version for server header
ENOENT, no such file or directory '/usr/share/webapps/etherpad-lite/.git/HEAD'
[2015-10-13 13:18:49.951] [WARN] console - Can't get git version for server header
ENOENT, no such file or directory '/usr/share/webapps/etherpad-lite/.git/HEAD'
[2015-10-13 13:18:49.951] [INFO] console - Your Etherpad version is 1.5.7 ()
[2015-10-13 13:18:50.076] [INFO] console - You can access your Etherpad instance at http://127.0.0.1:9001/
[2015-10-13 13:18:50.076] [INFO] console - The plugin admin page is at http://127.0.0.1:9001/admin/plugins
```

And this is the output for nodejs 4.2.0

```
$ sudo -u etherpad /usr/share/webapps/etherpad-lite/bin/run.sh -s /etc/webapps/etherpad-lite/settings.json
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.

> ws@0.5.0 install /usr/share/webapps/etherpad-lite/src/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Verzeichnis „/usr/share/webapps/etherpad-lite/src/node_modules/ws/build“ wird betreten
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:92: die Regel für Ziel „Release/obj.target/bufferutil/src/bufferutil.o“ scheiterte
make: Verzeichnis „/usr/share/webapps/etherpad-lite/src/node_modules/ws/build“ wird verlassen
npm WARN EPACKAGEJSON ep_etherpad-lite@1.5.7 No license field.
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-10-13 13:19:46.772] [ERROR] console - ERROR: Problem while initalizing the database
[2015-10-13 13:19:46.775] [ERROR] console - Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:154:17)
    at emitNone (events.js:67:13)
    at Handshake.emit (events.js:166:7)
    at Handshake._onTimeout (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:116:8)
    at Timer.listOnTimeout (timers.js:92:15)
    --------------------
    at Protocol._enqueue (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/Connection.js:109:18)
    at Connection._implyConnect (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/Connection.js:387:10)
    at Connection.query (/usr/share/webapps/etherpad-lite/src/node_modules/mysql/lib/Connection.js:174:8)
    at exports.database.init (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/mysql_db.js:74:6)
    at exports.database.init (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/CacheAndBufferLayer.js:110:18)
    at exports.database.init (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/CloneAndAtomicLayer.js:48:11)
    at Object.exports.init (/usr/share/webapps/etherpad-lite/src/node/db/DB.js:41:6)
    at /usr/share/webapps/etherpad-lite/src/node/server.js:62:8
```

Also connecting to the socket works:

```
$ mysql -u etherpad -p etherpad-lite -S /var/run/mysqld/mysqld.sock
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 6878
Server version: 10.0.21-MariaDB-log MariaDB Server

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [etherpad-lite]>
```

I just noticed following line during the startup:

```
bufferutil.target.mk:92: die Regel für Ziel „Release/obj.target/bufferutil/src/bufferutil.o“ scheiterte
```

This means something like "the rule for targe 'Release/obj.target/bufferutil/src/bufferutil.o' failed". I think that this is the problem.

**Comment by dvzrv** [comment]
Ha! still on nodejs 4.1.2 here!
Maybe it's a nodejs > 4.2 issue then.

**Comment by MorrisJobke** [comment]
> Ha! still on nodejs 4.1.2 here!
> Maybe it's a nodejs > 4.2 issue then.

Let me check that.

**Comment by MorrisJobke** [comment]
Yes. Works just fine with 4.1.2. I used a version from the Arch Rollback Machine: http://seblu.net/a/arm/packages/n/nodejs/

\o/

**Comment by webzwo0i** [comment]
thanks for testing!
bisect reveals https://github.com/nodejs/node/pull/3143

**Comment by webzwo0i** [comment]
v4.2.1 is out and should fix this. please reopen the issue if the bug remains/reoccurs.

**Comment by webzwo0i** [comment]
upstream fix https://github.com/nodejs/node/commit/c245a199a7

**Comment by MorrisJobke** [comment]
Just upgraded to 4.2.1 and it works :+1: Thanks :)

**Comment by Gared** [comment]
@webzwo0i Thanks for the good work!
