### ISSUE TITLE
Cannot find module 'ueberDB' error running bin/run.sh 

### ISSUE THREAD

**Issue by mnolae** [ether/etherpad-lite#2869]
Hi!

Working with:
* Debian 8
* nodejs v5.3.0
* npm 3.3.12

Following the installation steps, when i try to run *bin/run.sh* get this error:
```
module.js:328
    throw err;
    ^

Error: Cannot find module 'ueberDB'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/html/etherpad/src/node/db/DB.js:22:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

No problem if i change [this line](https://github.com/ether/etherpad-lite/blob/develop/src/node/db/DB.js#L22) to this one:
```
var ueberDB = require("ueberdb2");
```
It's a good change?

**Comment by JohnMcLear** [comment]
Fixed, sorry I didn't see your PR!

**Comment by mnolae** [comment]
Thanks to both!
