### ISSUE TITLE
not starting on windows 10

### ISSUE THREAD

**Issue by scienceapps** [ether/etherpad-lite#2880]
Hello, 

Etherpad doesn't start on windows 10 
```
[2016-01-11 09:38:56.664] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2016-01-11 09:39:00.102] [INFO] console - Installed plugins: ep_adminpads, ep_etherpad-lite
[2016-01-11 09:39:00.196] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2016-01-11 09:39:00.211] [INFO] console - Your Etherpad version is 1.5.6 (e509824)
[2016-01-11 09:39:00.461] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2016-01-11 09:39:00.476] [INFO] console - The plugin admin page is at http://0.0.0.0:9001/admin/plugins
[2016-01-11 09:39:00.476] [ERROR] console - Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1146:14)
    at listen (net.js:1172:10)
    at net.js:1270:9
    at dns.js:85:18
    at process._tickDomainCallback (node.js:381:11)
[2016-01-11 09:39:00.492] [INFO] console - graceful shutdown...
[2016-01-11 09:39:00.492] [INFO] console - db sucessfully closed.
```

**Comment by JohnMcLear** [comment]
Read the error output please before posting issues :)
