### ISSUE TITLE
Systemd service won't start

### ISSUE THREAD

**Issue by flyingrub** [ether/etherpad-lite#2902]
```
[Unit]
Description=etherpad-lite (real-time collaborative document editing)
After=syslog.target network.target

[Service]
Type=simple
User=web
Group=web
WorkingDirectory=/var/www/ether.pulsr.xyz
ExecStart=/var/www/ether.pulsr.xyz/bin/run.sh
#Restart=always

[Install]
WantedBy=multi-user.target
```
```
root@pulsr:~# systemctl status ether.service -l
● ether.service - etherpad-lite (real-time collaborative document editing)
   Loaded: loaded (/etc/systemd/system/ether.service; enabled)
   Active: failed (Result: exit-code) since Wed 2016-02-03 20:01:20 CET; 10s ago
  Process: 1310 ExecStart=/var/www/ether.pulsr.xyz/bin/run.sh (code=exited, status=1/FAILURE)
 Main PID: 1310 (code=exited, status=1/FAILURE)

Feb 03 20:01:20 pulsr.xyz run.sh[1310]: at Module.require (module.js:354:17)
Feb 03 20:01:20 pulsr.xyz run.sh[1310]: at require (internal/module.js:12:17)
Feb 03 20:01:20 pulsr.xyz run.sh[1310]: at Object.<anonymous> (/var/www/ether.pulsr.xyz/src/node/server.js:39:11)
Feb 03 20:01:20 pulsr.xyz run.sh[1310]: at Module._compile (module.js:410:26)
Feb 03 20:01:20 pulsr.xyz run.sh[1310]: at Object.Module._extensions..js (module.js:417:10)
Feb 03 20:01:20 pulsr.xyz run.sh[1310]: at Module.load (module.js:344:32)
Feb 03 20:01:20 pulsr.xyz run.sh[1310]: at Function.Module._load (module.js:301:12)
Feb 03 20:01:20 pulsr.xyz run.sh[1310]: at Function.Module.runMain (module.js:442:10)
Feb 03 20:01:20 pulsr.xyz systemd[1]: ether.service: main process exited, code=exited, status=1/FAILURE
Feb 03 20:01:20 pulsr.xyz systemd[1]: Unit ether.service entered failed state.
```

I have no problem runnning it from command line but it won't launch from service.

**Comment by flyingrub** [comment]
i greped run.sh and saw that npm was missing from the module. I installed it by hand and it works now. :)
