### ISSUE TITLE
EP 1.5.7 Abiword 2.9.2 export odt & pdf error

### ISSUE THREAD

**Issue by Cyrille37** [ether/etherpad-lite#2915]
Hi,

With EP 1.5.7 and Abiword 2.9.2 I could not export to ODT and PDF.
For PDF the log say:
```
[2016-02-21 22:17:45.675] [ERROR] console - Abiword File failed to convert [Error: convert /tmp/etherpad_export_1889797278.h<rpad_export_1889797278.html /tmp/etherpad_export_1889797278.pdf pdf         
AbiWord: could not open the file [/tmp/etherpad_export_1889797278.html]
error -1 
AbiWord:> ]
<rpad_export_1889797278.html /tmp/etherpad_export_1889797278.pdf pdf         
AbiWord: could not open the file [/tmp/etherpad_export_1889797278.html]
error -1 
AbiWord:> 
    at module.exports (/home/etherpad-lite/etherpad-lite/src/node_modules/async-stacktrace/ERR.js:46:13)
    at /home/etherpad-lite/etherpad-lite/src/node/handler/ExportHandler.js:224:36
    at /home/etherpad-lite/etherpad-lite/src/node_modules/async/lib/async.js:254:17
    at /home/etherpad-lite/etherpad-lite/src/node_modules/async/lib/async.js:151:21
    at /home/etherpad-lite/etherpad-lite/src/node_modules/async/lib/async.js:251:21
    at Object.callback (/home/etherpad-lite/etherpad-lite/src/node_modules/async/lib/async.js:615:34)
    at stdoutCallback (/home/etherpad-lite/etherpad-lite/src/node/utils/Abiword.js:135:14)
    at Socket.<anonymous> (/home/etherpad-lite/etherpad-lite/src/node/utils/Abiword.js:116:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
```

And the html file exists and readable:
```
-rw-r--r-- 1 etherpad-lite etherpad-lite 60998 Feb 21 22:17 /tmp/etherpad_export_1889797278.html
```

It's not the same error as #2301 (Abiword 3)

**Comment by Cyrille37** [comment]
Ok, I removed the plugin [font_size](https://npmjs.org/package/ep_font_size) and can now export as PDF (ODT continue to failed but on client side while opening with Libre Office...).
