### ISSUE TITLE
characters crash

### ISSUE THREAD

**Issue by xjtluapp** [ether/etherpad-lite#2927]
The developers and participants:

The Etherpad server it now looks like there’s another issue: if anyone suffers from the simliar problem, can someone share the experienc how to resolve the problem?

```
[2016-03-15 15:51:17.574] [INFO] access - [ENTER] Pad "g.iSgksK1v9WA9pe4O$ice201516": Client KHxQGPWlZmgGqqduAAH4 with IP "10.8.17.75" entered the pad
[2016-03-15 15:51:17.595] [ERROR] console - Error: Lone surrogate U+D83D is not a scalar value
    at Error (<anonymous>)
    at checkScalarValue (/home/etherpad/etherpad-ite/src/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/node_modules/utf8/utf8.js:69:10)
    at encodeCodePoint (/home/etherpad/etherpad- lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/node_modules/utf8/utf8.js:90:4)
    at Object.utf8encode [as encode] (/home/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/node_modules/utf8/utf8.js:111:18)
    at Object.exports.encodePacket (/home/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:74:34)
    at encodeOne (/home/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:387:13)
    at eachWithIndex (/home/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:256:5)
    at map (/home/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:263:5)
    at Object.exports.encodePayloadAsBinary (/home/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:411:3)
    at Object.exports.encodePayload (/home/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:225:20)
[2016-03-15 15:51:17.596] [INFO] console - graceful shutdown...
[2016-03-15 15:51:17.660] [INFO] ueberDB - Flushed 1 values
[2016-03-15 15:51:17.773] [INFO] ueberDB - Flushed 4 values
[2016-03-15 15:51:17.880] [INFO] ueberDB - Flushed 7 values
[2016-03-15 15:51:17.988] [INFO] ueberDB - Flushed 4 values
[2016-03-15 15:51:18.094] [INFO] console - db sucessfully closed.



```

**Comment by JohnMcLear** [comment]
Please check your database encoding is correct.

**Comment by lpagliari** [comment]
@xjtluapp this might help you: https://github.com/ether/etherpad-lite/issues/2107#issuecomment-185241914

**Comment by JohnMcLear** [comment]
Closed as due to admin error
