### ISSUE TITLE
Crash after starting the service : TypeError: Cannot set property 'timestamp' of null

### ISSUE THREAD

**Issue by auchalet** [ether/etherpad-lite#2946]
Hello !

Since 2 days we have some crashes with Etherpad.
We migrated etherpad from another server since 1 week.

Server : 
- OS : Debian 8 Jessie
- npm : 3.8.3
- node : 5.10.1

Etherpad - Develop Branch
Plugins : 
- ep_pad-lister
- ep_admin_pads

Etherpad is on MySQL. The settings.json file for DB connection is ok.

The bug is coming when I want to start the service.

It seems pretty similar to #2669 

Logfile :

```
[2016-04-12 11:53:24.854] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2016-04-12 11:53:24.855] [INFO] console - Your Etherpad version is 1.5.7 (6e78895)
[2016-04-12 11:53:25.022] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2016-04-12 11:53:25.022] [INFO] console - The plugin admin page is at http://0.0.0.0:9001/admin/plugins
[2016-04-12 11:53:27.532] [DEBUG] SessionStore - GET bFWjeSDPPy9cwhw82Qjf6nLQaid8bJ9A
[2016-04-12 11:53:27.549] [DEBUG] ueberDB - GET    - sessionstorage:bFWjeSDPPy9cwhw82Qjf6nLQaid8bJ9A - {"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true}} - from database 
[2016-04-12 11:53:27.601] [DEBUG] ueberDB - GET    - token2author:t.A3QspfWL03Ooe974HbR6 - "a.ItEsB2hUqDftkXQH" - from database 
[2016-04-12 11:53:27.602] [DEBUG] ueberDB - SETSUB - globalAuthor:a.ItEsB2hUqDftkXQH["timestamp"] - 1460454807602
[2016-04-12 11:53:27.604] [DEBUG] message - from ysBStvWYt4ukDU58AAAA: {"component":"pad","type":"CLIENT_READY","padId":"nuit-debout","sessionID":"null","password":null,"token":"t.A3QspfWL03Ooe974HbR6","protocolVersion":2,"client_rev":1,"reconnect":true}

[2016-04-12 11:53:27.605] [DEBUG] ueberDB - GET    - token2author:t.A3QspfWL03Ooe974HbR6 - "a.ItEsB2hUqDftkXQH" - from cache
[2016-04-12 11:53:27.627] [DEBUG] ueberDB - GET    - globalAuthor:a.ItEsB2hUqDftkXQH - null - from database
[2016-04-12 11:53:27.633] [ERROR] console - TypeError: Cannot set property 'timestamp' of null
    at /home/etherpad/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:317:41
    at fn (/home/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:525:34)
    at /home/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:449:34
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
[2016-04-12 11:53:27.633] [INFO] console - graceful shutdown...
[2016-04-12 11:53:27.640] [INFO] console - db sucessfully closed.

```

Do you need more informations ? 

Thanks for your help.

**Comment by JohnMcLear** [comment]
Can you provide more information such as frequency and if the error is the same each time?  This looks like an upstream bug but we need to be sure..

Can you provide steps to replicate?

**Comment by akosiaris** [comment]
We have the exact same problem right now.  Frequency is 4 secs apart, most of which is etherpad-lite dying and systemd is restarting it and then we are in a loop. I am trying to figure out if it is pad specific but I have no culrpits yet.

Steps to replicate ? I have none unfortunately.

**Comment by akosiaris** [comment]
So various things we tried:

* Restrict access  to one client (namely me) - via firewalling and visiting various pads as collected from the logs during the previous crashes. No crashes.
* Trying with a new clean DB. No crashes.
* Restoring the database to a day old snapshot. No crashes.

The above meant to us our DB was corrupted somehow. Unfortunately there was no way to figure out what exactly has happened since we can't really reproduce it and logs even at DEBUG level were not useful.

Since we wanted to restore access to the service, we 've stayed with the 1 day old database. That means some people may have lost some data and our `old` and `new` databases are diverging, making reconcilliation impossible. We are working on providing users with a way to access PADs from the  corrupted database so they can selectively restore stuff. 

FWIW, we are now at a stable state and trying to figure out what happened.

**Comment by JohnMcLear** [comment]
What database table encoding were you using on the old database?

**Comment by akosiaris** [comment]
utf8mb4. old/new database is the exact same thing btw, it's just old is a snapshot of new

Arbitrarily:

old == the database we 've restored from the backups. 1,5 day old backups that is
new == the one that crashed and was allegedly corrupted. We still have it around, but no instance of etherpad is running using it.
