### ISSUE TITLE
Restart loop when mysql server is stopped manually

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#2966]
I use mysql and execute Etherpad [as a service](https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service#ubuntu-1004-debian-6-sysvinit) and when I manually stop the mysql service, etherpad-lite crashes and tries to restart every time:

```
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2016-05-06 xx:yy] [ERROR] console - ERROR: Problem while initalizing the database
[2016-05-06 xx:yy] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:893:11)
    at exports._exceptionWithHostPort (util.js:916:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
    --------------------
    at Protocol._enqueue (/home/etherpad/src/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/home/etherpad/src/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/home/etherpad/src/node_modules/mysql/lib/Connection.js:109:18)
    at Connection._implyConnect (/home/etherpad/src/node_modules/mysql/lib/Connection.js:387:10)
    at Connection.query (/home/etherpad/src/node_modules/mysql/lib/Connection.js:174:8)
    at exports.database.init (/home/etherpad/src/node_modules/ueberdb2/mysql_db.js:74:6)
    at exports.database.init (/home/etherpad/src/node_modules/ueberdb2/CacheAndBufferLayer.js:110:18)
    at exports.database.init (/home/etherpad/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:48:11)
    at Object.exports.init (/home/etherpad/src/node/db/DB.js:41:6)
    at /home/etherpad/src/node/server.js:62:8
RESTART!
[2016-05-06 xx:yy] [ERROR] console - ERROR: Problem while initalizing the database
[2016-05-06 xx:yy] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:893:11)
    at exports._exceptionWithHostPort (util.js:916:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
    --------------------
    at Protocol._enqueue (/home/etherpad/src/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/home/etherpad/src/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/home/etherpad/src/node_modules/mysql/lib/Connection.js:109:18)
    at Connection._implyConnect (/home/etherpad/src/node_modules/mysql/lib/Connection.js:387:10)
    at Connection.query (/home/etherpad/src/node_modules/mysql/lib/Connection.js:174:8)
    at exports.database.init (/home/etherpad/src/node_modules/ueberdb2/mysql_db.js:74:6)
    at exports.database.init (/home/etherpad/src/node_modules/ueberdb2/CacheAndBufferLayer.js:110:18)
    at exports.database.init (/home/etherpad/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:48:11)
    at Object.exports.init (/home/etherpad/src/node/db/DB.js:41:6)
    at /home/etherpad/src/node/server.js:62:8
RESTART!
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
```

**Comment by Cyrille37** [comment]
And what's happen after mysql start ? Is EP could connect and works fine again ?

**Comment by rugk** [comment]
Yes, but I still don't like this endless restart loop. Probably a maximum of - say - 10 restarts would be good.

**Comment by JohnMcLear** [comment]
This is a duplicate of another issue, please find it and close this.

**Comment by rugk** [comment]
Well... no. It is basically what is done by the `runSafe.sh` script. To fix this this script would have to handle mysql errors differently or something like that, which is not a good idea.
Therefore I'm closing this issue.
