### ISSUE TITLE
Error in migrateDirtyDBtoRealDB: "Cannot find module 'dirty'"

### ISSUE THREAD

**Issue by cdparra** [ether/etherpad-lite#2989]
I am trying to run the script to migrate my old dirty db to the new production MYSQL db, but I keep getting this error

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'dirty'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at EventEmitter.<anonymous> (/home/etherpad/etherpad-lite/bin/migrateDirtyDBtoRealDB.js:10:15)
    at process._tickCallback (node.js:355:11)
```

I am using version 1.6.0 of Etherpad on Ubuntu 14

**Comment by cdparra** [comment]
Solved. For some reason, my first running of npm install dirty didn't work but after it did.
