### ISSUE TITLE
 Error in migrateDirtyDBtoRealDB: "Cannot find module '../src/node_modules/ueberDB'"

### ISSUE THREAD

**Issue by Rudloff** [ether/etherpad-lite#2996]
Hello,

I am using etherpad-lite 1.6.0 with node 0.10.4.

I get this error when I run migrateDirtyDBtoRealDB.js:
```
Error: Cannot find module '../src/node_modules/ueberDB'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at EventEmitter.<anonymous> (/home/etherpad/etherpad-lite/bin/migrateDirtyDBtoRealDB.js:11:17)
    at process._tickCallback (node.js:415:13)
```

The correct path seems to be ```../src/node_modules/ueberdb2/```.

**Comment by Gared** [comment]
You're right. We forgot to change this
