### ISSUE TITLE
can not get plugin list in page of   http://localhost:9001/admin/plugins

### ISSUE THREAD

**Issue by kwang1971** [ether/etherpad-lite#3062]
Try to get the available plugins list , but get the error log as following 
[2016-09-30 08:25:47.392] [ERROR] console - error parsing plugins.json: [SyntaxError: Unexpected token <]
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (E:\etherpad16\node_modules\ep_etherpad-lite\static\js\pluginfw\installer.js:70:22)
    at Request.self.callback (E:\etherpad16\node_modules\ep_etherpad-lite\node_modules\request\request.js:368:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (E:\etherpad16\node_modules\ep_etherpad-lite\node_modules\request\request.js:1219:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (E:\etherpad16\node_modules\ep_etherpad-lite\node_modules\request\request.js:1167:12)
    at emitNone (events.js:72:20)

**Comment by Gared** [comment]
Fixed it. Plesse try it again

**Comment by kwang1971** [comment]
It works now , thanks.
