### ISSUE TITLE
Unable to access etherpad

### ISSUE THREAD

**Issue by EPEffects** [ether/etherpad-lite#3069]
I tried out running etherpad on Debian 8, Ubuntu 14.04, Ubuntu 16.04 and CentOS07. 

I can't run it on Debian 8 and if i run it on Ubuntu 14.04, Ubuntu 16.04 and CentOS07, i get following error:

```
[2016-11-01 13:04:00.789] [ERROR] console - (node:14477) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

[2016-11-01 13:04:01.240] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.

[2016-11-01 13:04:03.067] [INFO] console - Installed plugins:

[2016-11-01 13:04:03.073] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues

[2016-11-01 13:04:03.074] [INFO] console - Your Etherpad version is 1.6.0 (223127b)

[2016-11-01 13:04:03.303] [INFO] console - You can access your Etherpad instance at http://[hidden ip]:9001/

[2016-11-01 13:04:03.303] [INFO] console - The plugin admin page is at http://[hidden ip]:9001/admin/plugins
```

I used Google and tried to solve it:
```
[etherpad@root596541 etherpad-lite]$ npm info graceful-fs -v
3.10.3
[etherpad@root596541 etherpad-lite]$ npm update -g npm
```
But after that, npm stopped working:

```
[root@root596541 ~]#  npm info graceful-fs -v
module.js:457
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

I hope, someone can help me!

Thank you :)

**Comment by lpagliari** [comment]
Some other users reported the same error, does the steps mentioned [on this issue](https://github.com/ether/etherpad-lite/issues/2956) solve your problem?

**Comment by EPEffects** [comment]
I tried this out on Debian, but it didn't work... I noticed some problems with nodejs on Debian in an older project of mine... I'm reinstalling my server right now and ill try the same steps on ubuntu 14.04

**Comment by EPEffects** [comment]
Well, i tried all steps on the issue, but at least the error has changed ^^

```
etherpad@root596541:~/etherpad-lite/bin$ ./run.sh
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/home/etherpad/etherpadlite/src/node_modules/npm/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

I tried to install graceful-fs, but it's still the same error:
```
etherpad@root596541:~/etherpad-lite/bin$ npm install graceful-fs
/home/etherpad/etherpad-lite
└── graceful-fs@4.1.9

npm WARN enoent ENOENT: no such file or directory, open '/home/etherpad/etherpad-lite/package.json'
npm WARN etherpad-lite No description
npm WARN etherpad-lite No repository field.
npm WARN etherpad-lite No README data
npm WARN etherpad-lite No license field.

```

**Comment by lpagliari** [comment]
@EPEffects I've notices you're running the bash script from inside of `bin/`. The script should be run from the `etherpad-lite/` folder, so maybe that's what causing the error. Can you try running `~/etherpad-lite$ ./bin/run.sh`, please? Thanks!

**Comment by EPEffects** [comment]
Still getting the same error...

**Comment by EPEffects** [comment]
After 2 hours, I was able to fix this error... I don't know how, though ^^
