### ISSUE TITLE
While I run ./run.sh I meet the problem(release1.6). 

### ISSUE THREAD

**Issue by DannieFly** [ether/etherpad-lite#3082]
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2016-11-18 01:33:29.286] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
/var/www/html/CTFPad/etherpad-lite/src/node_modules/underscore/underscore.js:40
    if (obj instanceof _) return obj;
            ^

RangeError: Maximum call stack size exceeded
    at new _ (/var/www/html/CTFPad/etherpad-lite/src/node_modules/underscore/underscore.js:40:13)
    at _ (/var/www/html/CTFPad/etherpad-lite/src/node_modules/underscore/underscore.js:41:38)
    at Function._.chain (/var/www/html/CTFPad/etherpad-lite/src/node_modules/underscore/underscore.js:1473:20)
    at _.(anonymous function) [as chain] (/var/www/html/CTFPad/etherpad-lite/src/node_modules/underscore/underscore.js:1496:34)
    at result (/var/www/html/CTFPad/etherpad-lite/src/node_modules/underscore/underscore.js:1486:37)
    at _.(anonymous function) [as keys] (/var/www/html/CTFPad/etherpad-lite/src/node_modules/underscore/underscore.js:1496:16)
    at flatten (/var/www/html/CTFPad/etherpad-lite/src/static/js/pluginfw/plugins.js:111:21)
    at /var/www/html/CTFPad/etherpad-lite/src/static/js/pluginfw/plugins.js:120:52
    at Function._.each._.forEach (/var/www/html/CTFPad/etherpad-lite/src/node_modules/underscore/underscore.js:153:9)
    at _.(anonymous function) [as each] (/var/www/html/CTFPad/etherpad-lite/src/node_modules/underscore/underscore.js:1496:34)
    at flatten (/var/www/html/CTFPad/etherpad-lite/src/static/js/pluginfw/plugins.js:111:28)

**Comment by joassouza** [comment]
What version of node are you running?

**Comment by DannieFly** [comment]
npm version 3.10.9 
node version 7.0.0

**Comment by joassouza** [comment]
I guess you're having the same error reported in #3074 .
Can you downgrade the node version and try again?

**Comment by DannieFly** [comment]
Thanks ,but i solve the problem by npm install xxx@xxx. Then problem raises where i run the xx.js.

**Comment by DannieFly** [comment]
So i think it's not about dependencies.

**Comment by lpagliari** [comment]
@DannieFly as @joassouza mentioned, you're having the same error we're having when trying to update the dependencies to work with node v. 7 (see [here](https://github.com/ether/etherpad-lite/issues/3074#issuecomment-261005995)). Using node 6.9 would probably work for you, but if you must use v. 7, then you'll have to wait for #3074 to be fixed.

**Comment by DannieFly** [comment]
Thanks
