### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by DocMAX** [ether/etherpad-lite#3091]
```
Dez 03 12:02:20 server run.sh[22775]: Started Etherpad...
Dez 03 12:02:22 server run.sh[22775]: [2016-12-03 12:02:22.481] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
Dez 03 12:02:24 server run.sh[22775]: /usr/share/webapps/etherpad-lite/src/static/js/pluginfw/plugins.js:50
Dez 03 12:02:24 server run.sh[22775]:       res.push("<dt>" + hook.hook_name + "</dt><dd>" + hook.hook_fn_name + " from " + hook.part.full_name + "</dd>");
Dez 03 12:02:24 server run.sh[22775]:                                           ^
Dez 03 12:02:24 server run.sh[22775]: RangeError: Maximum call stack size exceeded
Dez 03 12:02:24 server run.sh[22775]:     at _ (/usr/share/webapps/etherpad-lite/src/node_modules/underscore/underscore.js:40:13)
Dez 03 12:02:24 server run.sh[22775]:     at Function._.chain (/usr/share/webapps/etherpad-lite/src/node_modules/underscore/underscore.js:1473:20)
Dez 03 12:02:24 server run.sh[22775]:     at flatten (/usr/share/webapps/etherpad-lite/src/static/js/pluginfw/plugins.js:111:9)
Dez 03 12:02:24 server run.sh[22775]:     at /usr/share/webapps/etherpad-lite/src/static/js/pluginfw/plugins.js:120:52
Dez 03 12:02:24 server run.sh[22775]:     at Function._.each._.forEach (/usr/share/webapps/etherpad-lite/src/node_modules/underscore/underscore.js:153:9)
Dez 03 12:02:24 server run.sh[22775]:     at _.(anonymous function) [as each] (/usr/share/webapps/etherpad-lite/src/node_modules/underscore/underscore.js:1496:34)
Dez 03 12:02:24 server run.sh[22775]:     at flatten (/usr/share/webapps/etherpad-lite/src/static/js/pluginfw/plugins.js:111:28)
Dez 03 12:02:24 server run.sh[22775]:     at /usr/share/webapps/etherpad-lite/src/static/js/pluginfw/plugins.js:120:52
Dez 03 12:02:24 server run.sh[22775]:     at Function._.each._.forEach (/usr/share/webapps/etherpad-lite/src/node_modules/underscore/underscore.js:153:9)
Dez 03 12:02:24 server run.sh[22775]:     at _.(anonymous function) [as each] (/usr/share/webapps/etherpad-lite/src/node_modules/underscore/underscore.js:1496:34)
Dez 03 12:02:24 server run.sh[22775]:     at flatten (/usr/share/webapps/etherpad-lite/src/static/js/pluginfw/plugins.js:111:28)

```

**Comment by lpagliari** [comment]
@DocMAX there's another issue related to this error message: https://github.com/ether/etherpad-lite/issues/3074#issuecomment-261005995. You can use Node 6.9 to work around this error message, or wait until the PR is merged and available on `develop` branch.
