### ISSUE TITLE
Etherpad /admin/plugins page lower section "Available plugins" hangs with "Fetching..."

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#3095]
I don't know what happened. My Etherpad worked for a long time, now I wanted to update to the new version of the `ep_small_list` plugin which had a small bug see https://github.com/spruce/ep_small_list/issues/4#event-889306252 . So I deinstalled the older version of that plugin.

Before and after deinstallation of that plugin I noticed, that the lower section of my 

#### /admin/plugins page shows "Fetching..."

and the fetching of available plugins apparently failed.

The subdirectory and all files for my etherpad-lite belong to the `etherpad` user (to be sure, I issued a `$ sudo -R chown etherpad:etherpad /etherpad-lite`). I also read older closed issues relating to admin panel problems, but could not find anything which helped to fix the issue.

Please can you help me, perhaps it is a new and different problem.

```
$ systemctl status -l etherpad-lite
Started Etherpad...
run.sh[447]: [2016-12-10 16:29:09.540] [WARN] pluginfw - /etherpad-lite/node_modules/ep_etherpad-lite/node_modules/ueberdb2/node_modules/pg requires semver@'^4.1.0' but will load
run.sh[447]: /etherpad-lite/node_modules/ep_etherpad-lite/node_modules/semver,
run.sh[447]: which is version 5.1.0 unmet dependency
run.sh[447]: [2016-12-10 16:29:09.557] [WARN] pluginfw - /etherpad-lite/node_modules/ep_etherpad-lite/node_modules/wd/node_modules/archiver/node_modules/glob requires graceful-fs@'^3.0.2' but will load
run.sh[447]: /etherpad-lite/node_modules/ep_etherpad-lite/node_modules/graceful-fs,
run.sh[447]: which is version 4.1.3 unmet dependency
run.sh[447]: [2016-12-10 16:29:10.276] [INFO] console - Installed plugins: ep_adminpads@0.0.11, ep_align@0.0.23, ep_author_hover@0.0.9, ep_authornames@0.1.3, ep_autocomp@0.0.2, ep_email_notifications@0.1.4, ep_font_color@0.0.11, ep_font_family@0.2.6, ep_font_size@0.1.11, ep_hash_auth@2.0.3, ep_headings@0.1.6, ep_horizontal_line@0.0.4, ep_infopanel@0.1.2, ep_linebreak@0.0.4, ep_mediawiki@0.0.7, ep_printer@0.0.2, ep_signature@0.0.5, ep_timesliderdiff@0.0.5, ep_wrap@0.0.4
```

**Comment by Dhwty** [comment]
Pretty sure this is related to #3090. I'm also having this problem.

**Comment by Wikinaut** [comment]
My log file now shows:

```
[2016-12-10 17:01:46.332] [ERROR] console - { [Error: connect ETIMEDOUT 104.130.77.39:443]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.130.77.39',
  port: 443 }
Error: connect ETIMEDOUT 104.130.77.39:443
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1078:14)
[2016-12-10 17:01:46.458] [WARN] console - { [Error: connect ETIMEDOUT 104.130.77.39:443]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.130.77.39',
  port: 443 }
Error: connect ETIMEDOUT 104.130.77.39:443
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1078:14)
```

**Comment by Wikinaut** [comment]
@Dhwty yes, seems so.

**Comment by Wikinaut** [comment]
duplicate pf #3090
