### ISSUE TITLE
Question: How to solve connect timeout？

### ISSUE THREAD

**Issue by yileye** [ether/etherpad-lite#3102]
if my database is mysql ？ Emergency situation？ Please help me！！Thanks！

**Comment by lpagliari** [comment]
Can you provide more details, please?

**Comment by yileye** [comment]
ok, my server is Centos 6.4  and Mysql version is 5.1.
When I input command './run.sh --root', etherpad is running,but after a period of time in the past, the etherpad service is stoped
# vim  /var/log/etherpad-lite.log
[2016-12-23 23:34:10.231] [ERROR] console - Error: Connection lost: The server closed the connection.
    at Protocol.end (/data/tools/etherpad/etherpad-lite/node_modules/mysql/lib/protocol/Protocol.js:73:13)
    at Socket.onend (_stream_readable.js:498:10)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
[2016-12-23 23:34:10.275] [INFO] console - db sucessfully closed.
[root@bogon ~]# vim  /var/log/etherpad-lite.log 
[root@bogon ~]# vim  /var/log/etherpad-lite.log 

    at Socket.onend (_stream_readable.js:498:10)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
^[[32m[2016-12-23 23:34:10.227] [INFO] console - ^[[39mgraceful shutdown...
^[[31m[2016-12-23 23:34:10.231] [ERROR] console - ^[[39mError: Connection lost: The server closed the connection.
    at Protocol.end (/data/tools/etherpad/etherpad-lite/node_modules/mysql/lib/protocol/Protocol.js:73:13)
    at Socket.onend (_stream_readable.js:498:10)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
^[[32m[2016-12-23 23:34:10.275] [INFO] console - ^[[39mdb sucessfully closed.

I must to restart the service again and again to keep the etherpad worked, in this case, I do my best,but the result is bad

**Comment by lpagliari** [comment]
Can you try the suggestions posted [here](https://github.com/ether/etherpad-lite/issues/2747#issuecomment-135983809), please?

```
rm -Rf src/node_modules
bin/run.sh --root
```

**Comment by yileye** [comment]
ok.I will try. Thank you for you help.
