### ISSUE TITLE
ER_TRUNCATED_WRONG_VALUE_FOR_FIELD crash on 𝕬 and 🔗

### ISSUE THREAD

**Issue by dereckson** [ether/etherpad-lite#3105]
At 01d23b1f6a24, when the character 𝕬 has been added to a pad, the following crash occurred:

```
[2016-12-26 14:25:36.244] [ERROR] console - Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9D\x95\xAC\n...' for column 'value' at row 1
    at Query.Sequence._packetToError (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    --------------------
    at Protocol._enqueue (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Connection.query (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/Connection.js:185:25)
    at /opt/etherpad-lite/src/node_modules/ueberdb2/mysql_db.js:214:18
    at /opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:462:21
    at /opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:194:13
    at /opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:97:13
    at Array.forEach (native)
    at _forEach (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:26:24)
    at async.forEach (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:96:9)
    at _asyncMap (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:193:9)
[2016-12-26 14:25:36.245] [INFO] console - graceful shutdown...
```

**Comment by dereckson** [comment]
Can repro on 🔗: \xF0\x9F\x94\x97\n...

**Comment by lpagliari** [comment]
Please take a look on #2651 for instructions on how to fix your issue.
