### ISSUE TITLE
Changing port to connect to mysql don't work!

### ISSUE THREAD

**Issue by flotho** [ether/etherpad-lite#3107]
Hi,

I'm working on the latest fresh install of etherpad on a server and a second server with mySQL 5.5.52 on centos6.6.
The mysql server is listening on a specific port and I would like to be able to specify it in the json. I tried many things like :
```
   "dbType" : "mysql",
   "dbSettings" : {
                    "user"    : "etherpad",
                    "host"    : "database",
                    "password": "etherpad",
                    "database": "etherpad",
                    "port": 5133
                  },
```
But when running ./run.sh I have the following message :
```
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'etherpad'@'10.0.130.109' (using password: YES)
    at Handshake.Sequence._packetToError (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Handshake.ErrorPacket (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/sequences/Handshake.js:101:18)
    at Protocol._parsePacket (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/Connection.js:82:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/Connection.js:109:18)
    at Connection._implyConnect (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/Connection.js:387:10)
    at Connection.query (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/Connection.js:174:8)
    at exports.database.init (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/mysql_db.js:74:6)
    at exports.database.init (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:110:18)
    at exports.database.init (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:48:11)
    at Object.exports.init (/opt/etherpad/etherpad-lite/src/node/db/DB.js:41:6)
    at /opt/etherpad/etherpad-lite/src/node/server.js:62:8

```
Yet when I'm trying to connect from the etherpad server to the mysql using the mysq command it succeed :
```
[etherpad@gestion etherpad-lite]$ mysql -P 5133 -h database -u etherpad -D etherpad
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 30
Server version: 5.5.52 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [etherpad]> 

```

any help/advice would be appreciated,

regards

**Comment by flotho** [comment]
Hi,

I made additionnal debugging and see that the file /opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/node_modules/mysql/lib/Connection.js correctly used the port set up in the settings file.
So what could be wrong

**Comment by lpagliari** [comment]
@flotho this seems to be an issue with `ueberdb` lib. Can you try to run [this example](https://github.com/Pita/ueberDB#example) with your credentials to check if you're able to connect to your database?

**Comment by flotho** [comment]
Well actually, it's definitevly a mysql server part because it looks like the server prevent the access.
I'll let you know.
Thanks for the fast support

**Comment by flotho** [comment]
The answer was on the server part :
* skip-name-resolve in the my.cnf help a bit
* the user conf was not correctly set in mysql.

Now it works almost like a charm....
