### ISSUE TITLE
 Error | ep_frontend_community | etherpad

### ISSUE THREAD

**Issue by pajaro23** [ether/etherpad-lite#3144]
Hello, I'm setting up a plugin for etherpad but I get the following error, but I have not had success to solve it.

console - TypeError: Cannot read property '0' of null
at /var/www/site/softw/etherpad-lite-1.6.1/node_modules/ep_frontend_community/hooks.js:1819:58
at Query._callback (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/ep_frontend_community/hooks.js:203:13)
at Query.Sequence.end (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:75:24)
at Query._handleFinalResultPacket (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
at Query.EofPacket (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
at Protocol._parsePacket (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/mysql/lib/protocol/Protocol.js:172:24)
at Parser.write (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/mysql/lib/protocol/Parser.js:62:12)
at Protocol.write (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/mysql/lib/protocol/Protocol.js:37:16)
at Socket.ondata (_stream_readable.js:542:20)

**Comment by lpagliari** [comment]
This seems an issue on the plugin code, so I've added some comments on [the issue you've opened on its repository](https://github.com/reality/ep_frontend_community/issues/17).
