### ISSUE TITLE
Error in etherpad with mysql

### ISSUE THREAD

**Issue by pajaro23** [ether/etherpad-lite#3151]
Currently this error is causing me many problems with my etherpad but I still have not had success to solve it ...

 [ERROR] console - Error: Connection lost: The server closed the connection.
    at Protocol.end (/root/etherpad-lite/node_modules/mysql/lib/protocol/Protocol.js:73:13)
    at Socket.onend (_stream_readable.js:498:10)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)

**Comment by lpagliari** [comment]
You didn't provide a lot of information about your issue, but looking on other similar issues here at Etherpad repo I found [this one](https://github.com/ether/etherpad-lite/issues/3102). Can you try what was suggested there are see if it works?

**Comment by pajaro23** [comment]
ok.I will try. Thank you for you help.
