### ISSUE TITLE
Failed to run etherpad-lite after create package.json

### ISSUE THREAD

**Issue by EricTiger1986** [ether/etherpad-lite#3155]
I want to install plugins automatically, so I create package.json. Then I could use command 'npm install' to install my plugins.

I find after I create the package.json and run bin/run.sh. An error occurs:

path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at loadPlugin (/home/etherpad/etherpad-lite/src/static/js/pluginfw/plugins.js:133:26)
    at /home/etherpad/etherpad-lite/src/static/js/pluginfw/plugins.js:90:9
    at /home/etherpad/etherpad-lite/src/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/home/etherpad/etherpad-lite/src/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/home/etherpad/etherpad-lite/src/node_modules/async/lib/async.js:124:9)
    at /home/etherpad/etherpad-lite/src/static/js/pluginfw/plugins.js:87:11
    at /home/etherpad/etherpad-lite/src/static/js/pluginfw/plugins.js:128:5
    at /home/etherpad/etherpad-lite/src/static/js/pluginfw/read-installed.js:128:5

If I remove package.json, it works well.

Who could help me? Thank you in advance.

**Comment by farizluqman** [comment]
up
