### ISSUE TITLE
Error After submit form

### ISSUE THREAD

**Issue by M-Husein** [ether/etherpad-lite#3168]
I have error when I submit start form in my browser localhost:9001

This is error in my browser after I submit form 

TypeError: Cannot read property 'language' of undefined
   at D:\NodeJS\ether-etherpad-lite\node_modules\ep_etherpad-lite\node\hooks\express\specialpages.js:46:20
   at Layer.handle [as handle_request] (D:\NodeJS\ether-etherpad-lite\node_modules\express\lib\router\layer.js:95:5)
   at next (D:\NodeJS\ether-etherpad-lite\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (D:\NodeJS\ether-etherpad-lite\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (D:\NodeJS\ether-etherpad-lite\node_modules\express\lib\router\layer.js:95:5)
   at D:\NodeJS\ether-etherpad-lite\node_modules\express\lib\router\index.js:277:22
   at param (D:\NodeJS\ether-etherpad-lite\node_modules\express\lib\router\index.js:349:14)
   at paramCallback (D:\NodeJS\ether-etherpad-lite\node_modules\express\lib\router\index.js:401:21)
   at D:\NodeJS\ether-etherpad-lite\node_modules\ep_etherpad-lite\node\hooks\express\padurlsanitize.js:28:11
   at Object.exports.sanitizePadId (D:\NodeJS\ether-etherpad-lite\node_modules\ep_etherpad-lite\node\db\PadManager.js:208:5)

Please Help. Thanks

**Comment by lpagliari** [comment]
There's [another issue](https://github.com/ether/etherpad-lite/issues/3139#issuecomment-291069776) with the same error message. Does the suggestion there help you to solve yours?
