### ISSUE TITLE
tidyhtml/libreoffice crash

### ISSUE THREAD

**Issue by skupfer** [ether/etherpad-lite#3209]
Crash on PDF export (probably word and others, too)
Path used: "/usr/bin/tidy" and "/usr/bin/libreoffice"

```
[2017-06-29 18:11:30.305] [ERROR] TidyHtml - Failed to tidy /tmp/etherpad_export_1358957654.html
line 179 column 96 - Error: <fontmonospace> is not recognized!
line 179 column 96 - Warning: discarding unexpected <fontmonospace>
line 179 column 132 - Warning: discarding unexpected </fontmonospace>
line 179 column 205 - Error: <fontmonospace> is not recognized!
line 179 column 205 - Warning: discarding unexpected <fontmonospace>
line 179 column 256 - Warning: discarding unexpected </fontmonospace>
line 179 column 286 - Warning: replacing invalid character code 156
line 179 column 300 - Error: <fontmonospace> is not recognized!
line 179 column 300 - Warning: discarding unexpected <fontmonospace>
line 179 column 384 - Warning: discarding unexpected </fontmonospace>
line 179 column 427 - Error: <fontmonospace> is not recognized!
line 179 column 427 - Warning: discarding unexpected <fontmonospace>
line 179 column 451 - Warning: discarding unexpected </fontmonospace>
line 179 column 472 - Warning: missing <li>
line 179 column 476 - Warning: missing <li>
line 179 column 499 - Error: <fontmonospace> is not recognized!
line 179 column 499 - Warning: discarding unexpected <fontmonospace>
line 179 column 585 - Warning: discarding unexpected </fontmonospace>
line 179 column 610 - Error: <fontmonospace> is not recognized!
221 warnings, 51 errors were found! Not all warnings/errors were shown.

This document has errors that must be fixed before
using HTML Tidy to generate a tidied up version.

Character codes 128 to 159 (U+0080 to U+009F) are not allowed in HTML;
even if they were, they would likely be unprintable control characters.
Tidy assumed you wanted to refer to a character with the same byte value in the
specified encoding and replaced that reference with the Unicode equivalent.

The table summary attribute should be used to describe
the table structure. It is very helpful for people using
non-visual browsers. The scope and headers attributes for
table cells are useful for specifying which headers apply
to each table cell, enabling non-visual browsers to provide
a meaningful context for each cell.

For further advice on how to make your pages accessible
see http://www.w3.org/WAI/GL.
. You may also want to try
"http://www.cast.org/bobby/" which is a free Web-based
service for checking URLs for accessibility.

To learn more about HTML Tidy see http://tidy.sourceforge.net
Please fill bug reports and queries using the "tracker" on the Tidy web site.
Additionally, questions can be sent to html-tidy@w3.org
HTML and CSS specifications are available from http://www.w3.org/
Lobby your company to join W3C, see http://www.w3.org/Consortium

[2017-06-29 18:11:30.308] [ERROR] console - Error: Tidy died with exit code 2
    at module.exports (/usr/share/nginx/www/etherpad-lite/src/node_modules/async-stacktrace/ERR.js:46:13)
    at /usr/share/nginx/www/etherpad-lite/src/node/handler/ExportHandler.js:182:36
    at /usr/share/nginx/www/etherpad-lite/src/node_modules/async/lib/async.js:254:17
    at /usr/share/nginx/www/etherpad-lite/src/node_modules/async/lib/async.js:151:21
    at /usr/share/nginx/www/etherpad-lite/src/node_modules/async/lib/async.js:251:21
    at /usr/share/nginx/www/etherpad-lite/src/node_modules/async/lib/async.js:615:34
    at ChildProcess.<anonymous> (/usr/share/nginx/www/etherpad-lite/src/node/utils/TidyHtml.js:38:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
[2017-06-29 18:11:30.309] [INFO] console - graceful shutdown...
[2017-06-29 18:11:30.332] [INFO] console - db sucessfully closed.
```

EDIT: does anyone know non outdated projects but like etherpad with non outdated plugins (if used)? Very sad to see that most of the plugins became useless or not working properly

**Comment by JohnMcLear** [comment]
Looks like plugin bug, not Etherpad.

**Comment by JohnMcLear** [comment]
PS Re request to see plugins that are bug free.  I'm spending 3 hours today just triaging bugs.  Anyone could do this, literally anyone, if you contributed just a little bit of your time to the project I can spend my time fixing bugs in the code and not triaging bugs to remove the cruft so please contribute if you can!

**Comment by skupfer** [comment]
Tried this with no plugins installed if I remember correctly. If I encounter such an error (in this case crashing etherpad) I always try a clean setup in a virtual machine or new docker instance. Unfortunately I have no interest in ep anymore because we needed things working properly and changed to another project. I wish you all the best for the future and thanks for your support!
