### ISSUE TITLE
PDF generation with AbiWord crashes Etherpad-Lite when page contains UTF-32 Char

### ISSUE THREAD

**Issue by ghost** [ether/etherpad-lite#3240]
etherpad crashes when the pad contains UTF-32 Characters like '🍆' and '😂'.

I'm using abiword (3.0.2-2) and Etherpad 12cb8e0d.

#189

**Comment by JohnMcLear** [comment]
Confirmed.  This is a serious bug.

**Comment by JohnMcLear** [comment]
I found a more severe bug.

If you create a pad with name 😂 and remove all contents then paste 😂 it causes EP to crash

```
[2018-04-04 11:53:02.331] [ERROR] console - Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x98\x82":...' for column 'value' at row 
1
    at Query.Sequence._packetToError (/home/etherpad-lite/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/home/etherpad-lite/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
```

**Comment by JohnMcLear** [comment]
Okay here is an update..  

If your charset is properly set in settings.json your Etherpad instance wont crash.  

Follow this guide: https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL

Either way Etherpad is not properly exporting UTF32 chars irrespective of Abiword the HTML is garbage too!

**Comment by JohnMcLear** [comment]
Etherpad HTML is exporting
```
<body>
&#55357;&#56834;test<br>
<div style="display:none"><a href="/javascript" data-jslicense="1">JavaScript license information</a></div>
```
Note to self, notice that weird license thing we have had complaints about!

**Comment by JohnMcLear** [comment]
This is fixed btw :)
