### ISSUE TITLE
Error after restart (even on fresh DB): TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by SvenAbels** [ether/etherpad-lite#3243]
We are running Etherpad within Docker via 3 steps:

1. Downloading https://github.com/ether/etherpad-lite/archive/1.6.1.zip
2. executing bin/installDeps.sh
3. doing an npm install --production sqlite3

This has never changed. However, since this morning we get the following error - even when starting with a fresh sq-lite DB file:

```
[2017-08-09 08:52:36.834] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2017-08-09 08:52:36.834] [INFO] console - The plugin admin page is at http://0.0.0.0:9001/admin/plugins
[2017-08-09 08:52:39.792] [ERROR] console - TypeError: Cannot read property 'prototype' of undefined
    at Server.onWebSocket (/opt/etherpad-lite/src/node_modules/engine.io/lib/server.js:358:40)
    at /opt/etherpad-lite/src/node_modules/engine.io/lib/server.js:343:12
    at completeHybiUpgrade2 (/opt/etherpad-lite/src/node_modules/ws/lib/WebSocketServer.js:284:5)
    at completeHybiUpgrade1 (/opt/etherpad-lite/src/node_modules/ws/lib/WebSocketServer.js:309:13)
    at WebSocketServer.handleHybiUpgrade (/opt/etherpad-lite/src/node_modules/ws/lib/WebSocketServer.js:337:3)
    at WebSocketServer.handleUpgrade (/opt/etherpad-lite/src/node_modules/ws/lib/WebSocketServer.js:173:26)
    at /opt/etherpad-lite/src/node_modules/engine.io/lib/server.js:342:13
    at Server.verify (/opt/etherpad-lite/src/node_modules/engine.io/lib/server.js:142:12)
    at Server.handleUpgrade (/opt/etherpad-lite/src/node_modules/engine.io/lib/server.js:331:8)
    at Server.<anonymous> (/opt/etherpad-lite/src/node_modules/engine.io/lib/server.js:451:14)
[2017-08-09 08:52:39.792] [INFO] console - graceful shutdown...

```
The error appears as soon as we access the first PAD page.

Does anyone have an idea why this comes or how we can fix this?

**Comment by SvenAbels** [comment]
I assume that this would be fixable by https://github.com/ether/etherpad-lite/pull/3241
