### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by klausweiss** [ether/etherpad-lite#3256]
I've just cloned the repository, run the etherpad with `./bin/run.sh` and put it behind reverse proxy to get:
```
[2017-09-18 00:52:00.161] [ERROR] console - TypeError: Cannot read property 'prototype' of undefined
    at Server.onWebSocket (/srv/etherpad/etherpad-lite/src/node_modules/engine.io/lib/server.js:358:40)
    at /srv/etherpad/etherpad-lite/src/node_modules/engine.io/lib/server.js:343:12
    at completeHybiUpgrade2 (/srv/etherpad/etherpad-lite/src/node_modules/ws/lib/WebSocketServer.js:284:5)
    at completeHybiUpgrade1 (/srv/etherpad/etherpad-lite/src/node_modules/ws/lib/WebSocketServer.js:309:13)
    at WebSocketServer.handleHybiUpgrade (/srv/etherpad/etherpad-lite/src/node_modules/ws/lib/WebSocketServer.js:337:3)
    at WebSocketServer.handleUpgrade (/srv/etherpad/etherpad-lite/src/node_modules/ws/lib/WebSocketServer.js:173:26)
    at /srv/etherpad/etherpad-lite/src/node_modules/engine.io/lib/server.js:342:13
    at Server.verify (/srv/etherpad/etherpad-lite/src/node_modules/engine.io/lib/server.js:142:12)
    at Server.handleUpgrade (/srv/etherpad/etherpad-lite/src/node_modules/engine.io/lib/server.js:331:8)
    at Server.<anonymous> (/srv/etherpad/etherpad-lite/src/node_modules/engine.io/lib/server.js:451:14)
```
after opening first pad. It's clean install - all that I've done was 
```bash
git clone https://github.com/ether/etherpad-lite.git
cd etherpad-lite/
./bin/run.sh 
```

After the error server goes down. I cannot access any pad.

**Server OS**: Ubuntu 16.04
**Client OS**: Ubuntu 16.04
**Client browser**: Opera 46.0.2597.39

**Comment by lpagliari** [comment]
Does this help? https://github.com/ether/etherpad-lite/issues/3243#issuecomment-321266273

**Comment by klausweiss** [comment]
Yes, updating `socket.io` to `1.7.3` helped. Thanks!
