### ISSUE TITLE
Plugin Manager Errors Behind Proxy

### ISSUE THREAD

**Issue by Annihil8ted** [ether/etherpad-lite#3344]
I currently have etherpad installed behind a proxy and am getting this as an error. 
[2018-03-13 14:30:10.790] [ERROR] console - { Error: tunneling socket could not be established, cause=write EPROTO 139880163968896:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

    at ClientRequest.onError (/root/etherpad-lite-develop/src/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at onwriteError (_stream_writable.js:418:12)
    at onwrite (_stream_writable.js:440:5)
    at _destroy (internal/streams/destroy.js:39:7) code: 'ECONNRESET' }
Error: tunneling socket could not be established, cause=write EPROTO 139880163968896:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

    at ClientRequest.onError (/root/etherpad-lite-develop/src/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at onwriteError (_stream_writable.js:418:12)
    at onwrite (_stream_writable.js:440:5)
    at _destroy (internal/streams/destroy.js:39:7)

I can't see to find anything that will turn off SSL verification.

**Comment by JohnMcLear** [comment]
Proxy configuration issue.  Not Etherpad issue.
