### ISSUE TITLE
Error using password protected redis as database

### ISSUE THREAD

**Issue by moretocome** [ether/etherpad-lite#3349]
I have successfully used redis as database for my etherpad-lite installation, but after adding `requirepass` to `redis.conf`, I can't get etherpad-lite to run.

I have this in `settings.conf`, which should be the right syntax according to [redis_db.js](https://github.com/Pita/ueberDB/blob/master/redis_db.js#L26):
```
   "dbType" : "redis",
   "dbSettings" : {
                    "host"        : "localhost",
                    "port"        : 6379, // Adjust port if you have multiple instances of redis.
                    "database"    : 1, // You should choose a database id that is not already used. If you run redis only for etherpad you can leave this as 0.
                    "password"    : "MyPasswordHere"
                  },
```
When I issue `systemctl restart etherpad-lite`, I get the following errors in syslog:
```
Mar 23 14:06:28 hostname systemd[1]: Started Etherpad-lite, the collaborative editor..
Mar 23 14:06:30 hostname nodejs[6778]: /srv/etherpad-lite/src/node_modules/redis/lib/utils.js:89
Mar 23 14:06:30 hostname nodejs[6778]:         callback(err, res);
Mar 23 14:06:30 hostname nodejs[6778]:         ^
Mar 23 14:06:30 hostname nodejs[6778]: TypeError: callback is not a function
Mar 23 14:06:30 hostname nodejs[6778]:     at Object.callbackOrEmit [as callback_or_emit] (/srv/etherpad-lite/src/node_modules/redis/lib/utils.js:89:9)
Mar 23 14:06:30 hostname nodejs[6778]:     at Command.callback (/srv/etherpad-lite/src/node_modules/redis/lib/individualCommands.js:41:15)
Mar 23 14:06:30 hostname nodejs[6778]:     at normal_reply (/srv/etherpad-lite/src/node_modules/redis/index.js:726:21)
Mar 23 14:06:30 hostname nodejs[6778]:     at RedisClient.return_reply (/srv/etherpad-lite/src/node_modules/redis/index.js:824:9)
Mar 23 14:06:30 hostname nodejs[6778]:     at JavascriptRedisParser.returnReply (/srv/etherpad-lite/src/node_modules/redis/index.js:192:18)
Mar 23 14:06:30 hostname nodejs[6778]:     at JavascriptRedisParser.execute (/srv/etherpad-lite/src/node_modules/redis-parser/lib/parser.js:574:12)
Mar 23 14:06:30 hostname nodejs[6778]:     at Socket.<anonymous> (/srv/etherpad-lite/src/node_modules/redis/index.js:274:27)
Mar 23 14:06:30 hostname nodejs[6778]:     at Socket.emit (events.js:180:13)
Mar 23 14:06:30 hostname nodejs[6778]:     at Socket.emit (domain.js:421:20)
Mar 23 14:06:30 hostname nodejs[6778]:     at addChunk (_stream_readable.js:269:12)
Mar 23 14:06:30 hostname systemd[1]: etherpad-lite.service: Main process exited, code=exited, status=1/FAILURE
Mar 23 14:06:30 hostname systemd[1]: etherpad-lite.service: Unit entered failed state.
Mar 23 14:06:30 hostname systemd[1]: etherpad-lite.service: Failed with result 'exit-code'.
Mar 23 14:06:30 hostname systemd[1]: etherpad-lite.service: Service hold-off time over, scheduling restart.
Mar 23 14:06:30 hostname systemd[1]: Stopped Etherpad-lite, the collaborative editor..
```
Those errors are repeated until I stop the etherpad-lite service.

I have other services running, that does connect to redis with the password, and if I change the password in `settings.conf`, I get `#033[39mReplyError: ERR invalid password`, so I am pretty sure the errors are not caused by wrong syntax or a wrong password.

Has anyone successfully configured etherpad-lite to connect to redis with a password? Or can anyone spot from the logs what goes wrong?

Thanks in advance!

**Comment by JohnMcLear** [comment]
Here would be the right place for this bug by the sounds of things: https://github.com/Pita/ueberDB/issues

Try to replicate directly with ueberDB and if you can you know the problem is w/ ueber not Etherpad
