### ISSUE TITLE
Can't use mongodb ?

### ISSUE THREAD

**Issue by ljoets** [ether/etherpad-lite#3353]
Hello,
I can't make a working install of etherpad-lite with mongodb in place of dirtydb on a Debian Jessie nor a Debian Stretch server.
My etherpad-lite installation is working fine with dirtydb.
I installed mongodb and mongodb npm module, but when runing etherpad-lite, I have an error:
```
root@Etherpad:/home/etherpad/etherpad-lite# su -c 'sh /home/etherpad/etherpad-lite/bin/run.sh' etherpad
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json async-stacktrace@0.0.2 No repository field.
npm WARN package.json channels@0.0.4 No repository field.
npm WARN package.json tinycon@0.0.1 No repository field.
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[..................] \ : verb node symlink /usr/bin/node
/home/etherpad/etherpad-lite/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:72
const MongoParseError = function(message) {
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/etherpad/etherpad-lite/node_modules/mongodb/node_modules/mongodb-core/index.js:17:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```
I saw that settings.json nor settings.json.template are mentioning mongodb as examples. Is it always possible to use it ?

Thanks,

**Comment by JohnMcLear** [comment]
MongoDB is supported by Ueber so should work.

Take a look at https://github.com/Pita/ueberDB
