### ISSUE TITLE
Pad fails to load when containing ????????

### ISSUE THREAD

**Issue by rasos** [ether/etherpad-lite#3358]
We run a public etherpad instance for various NGOs since 2010, continuously updated, now on 1.6.3. It has quite huge traffic, the DB has 5GB but it is still performing and runs stable.

We observed that pads containing a series of question marks fail to load and can not be deleted.  Luckily we  could access it with adding /timeslider . Attached is an export of the affected pad.

[25thFreedomCoopAssembly.etherpad.zip](https://github.com/ether/etherpad-lite/files/1873024/25thFreedomCoopAssembly.etherpad.zip)

When trying to import, it throws:
```
[2018-04-03 20:47:58.322] [INFO] ueberDB - Flushed 1 values
[2018-04-03 20:48:04.101] [WARN] console - Error: Can't apply USER_CHANGES Z:sg>1*6*7*4*5+1$* with oldLen 1024 to document of length 1032
    at /opt/etherpad-lite/src/node/handler/PadMessageHandler.js:770:25
    at /opt/etherpad-lite/src/node_modules/async/lib/async.js:610:21
    at /opt/etherpad-lite/src/node_modules/async/lib/async.js:249:17
    at iterate (/opt/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
    at /opt/etherpad-lite/src/node_modules/async/lib/async.js:160:25
    at /opt/etherpad-lite/src/node_modules/async/lib/async.js:251:21
    at /opt/etherpad-lite/src/node_modules/async/lib/async.js:615:34
    at Object.async.whilst (/opt/etherpad-lite/src/node_modules/async/lib/async.js:686:13)
    at /opt/etherpad-lite/src/node_modules/async/lib/async.js:682:23
    at Object.callback (/opt/etherpad-lite/src/node/handler/PadMessageHandler.js:753:15)
[2018-04-03 20:48:04.153] [INFO] access - [LEAVE] Pad "25thFreedomCoopAssembly2": Author "a.GrhpdaAI0GW5EUsl" on client KUGeQYmEGxzcPaSZAAB9 with IP "127.0.0.1" left the pad
```

**Comment by JohnMcLear** [comment]
1. Please provide steps to replicate IE create new EP instance, type in ??????????, try export/import bla blah..
2. What is your database/database encoding?
