### ISSUE TITLE
ODT export throws an error, ODT import treats the file as plaintext

### ISSUE THREAD

**Issue by kuba-orlik** [ether/etherpad-lite#3361]
I have abiword 3.0.2 installed. When I try to export to ODT, the following error is being thrown on the server: 

```
<rpad_export_529129786.html /tmp/etherpad_export_529129786.odt odt            to convert Error: convert /tmp/etherpad_export_529129786.html /tmp/etherpad_export_52
etherpad_1  | error -1 
etherpad_1  | AbiWord:> 
etherpad_1  |     at module.exports (/opt/etherpad-lite/src/node_modules/async-stacktrace/ERR.js:46:13)
etherpad_1  |     at /opt/etherpad-lite/src/node/handler/ExportHandler.js:182:36
etherpad_1  |     at /opt/etherpad-lite/src/node_modules/async/lib/async.js:254:17
etherpad_1  |     at /opt/etherpad-lite/src/node_modules/async/lib/async.js:151:21
etherpad_1  |     at /opt/etherpad-lite/src/node_modules/async/lib/async.js:251:21
etherpad_1  |     at Object.callback (/opt/etherpad-lite/src/node_modules/async/lib/async.js:615:34)
etherpad_1  |     at stdoutCallback (/opt/etherpad-lite/src/node/utils/Abiword.js:135:14)
etherpad_1  |     at Socket.<anonymous> (/opt/etherpad-lite/src/node/utils/Abiword.js:116:11)
etherpad_1  |     at emitOne (events.js:116:13)
etherpad_1  |     at Socket.emit (events.js:211:7)
<rpad_export_529129786.html /tmp/etherpad_export_529129786.odt odt           d_export_52
etherpad_1  | error -1 
etherpad_1  | AbiWord:> 
etherpad_1  |     at module.exports (/opt/etherpad-lite/src/node_modules/async-stacktrace/ERR.js:46:13)
etherpad_1  |     at /opt/etherpad-lite/src/node/handler/ExportHandler.js:182:36
etherpad_1  |     at /opt/etherpad-lite/src/node_modules/async/lib/async.js:254:17
etherpad_1  |     at /opt/etherpad-lite/src/node_modules/async/lib/async.js:151:21
etherpad_1  |     at /opt/etherpad-lite/src/node_modules/async/lib/async.js:251:21
etherpad_1  |     at Object.callback (/opt/etherpad-lite/src/node_modules/async/lib/async.js:615:34)
etherpad_1  |     at stdoutCallback (/opt/etherpad-lite/src/node/utils/Abiword.js:135:14)
etherpad_1  |     at Socket.<anonymous> (/opt/etherpad-lite/src/node/utils/Abiword.js:116:11)
etherpad_1  |     at emitOne (events.js:116:13)
etherpad_1  |     at Socket.emit (events.js:211:7)
```

When trying to import the file, it's treated as a plaintext file and shows all the "insides" of odt...

**Comment by JohnMcLear** [comment]
What is your Etherpad version?

**Comment by kuba-orlik** [comment]
We're on `1.6.3`

**Comment by fcecagno** [comment]
I see the same error here while exporting to ODT:

```
[2019-01-22 15:44:11.239] [INFO] console - req.params.pad 8ec713e1_1
[2019-01-22 15:44:11.250] [INFO] ueberDB - Flushed 1 values
[2019-01-22 15:44:11.252] [ERROR] console - Not a PDF
[2019-01-22 15:44:11.400] [INFO] console - queue continue
[2019-01-22 15:44:11.401] [ERROR] console - Abiword File failed to convert Error: Abiword died with exit code null
    at module.exports (/app/src/node_modules/async-stacktrace/ERR.js:46:13)
    at /app/src/node/handler/ExportHandler.js:182:36
    at /app/src/node_modules/async/lib/async.js:254:17
    at /app/src/node_modules/async/lib/async.js:151:21
    at /app/src/node_modules/async/lib/async.js:251:21
    at Object.callback (/app/src/node_modules/async/lib/async.js:615:34)
    at stdoutCallback (/app/src/node/utils/Abiword.js:135:14)
    at ChildProcess.<anonymous> (/app/src/node/utils/Abiword.js:94:7)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:422:20)
Error: Abiword died with exit code null
    at module.exports (/app/src/node_modules/async-stacktrace/ERR.js:46:13)
    at /app/src/node/handler/ExportHandler.js:182:36
    at /app/src/node_modules/async/lib/async.js:254:17
    at /app/src/node_modules/async/lib/async.js:151:21
    at /app/src/node_modules/async/lib/async.js:251:21
    at Object.callback (/app/src/node_modules/async/lib/async.js:615:34)
    at stdoutCallback (/app/src/node/utils/Abiword.js:135:14)
    at ChildProcess.<anonymous> (/app/src/node/utils/Abiword.js:94:7)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:422:20)
```

I'm using `1.7.0`.

**Comment by fcecagno** [comment]
Never mind - I was using Etherpad inside Docker based on Node 9, then I changed to Node 8 and it worked well, so I believe it was something in my Docker image.

**Comment by muxator** [comment]
I'll close this, but I suspect there may be some minor stability check we could do anyway.
Thanks.
