### ISSUE TITLE
Current Master crashed

### ISSUE THREAD

**Issue by noppelmax** [ether/etherpad-lite#3394]
`
[2018-05-16 01:31:52.880] [ERROR] console - RangeError: Maximum call stack size exceeded
    at exports.database.get (/home/etherpad/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:1:1)

    at exports.channels.doOperation [as operatorFunction] (/home/etherpad/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:94:18)

    at exports.channels.emit (/home/etherpad/etherpad-lite/src/node_modules/channels/channels.js:49:11)

    at exports.database.get (/home/etherpad/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:62:17)

    at /home/etherpad/etherpad-lite/src/node/utils/ExportEtherpad.js:42:10

    at iterate (/home/etherpad/etherpad-lite/src/node_modules/async/lib/async.js:149:13)

    at /home/etherpad/etherpad-lite/src/node_modules/async/lib/async.js:160:25

    at Object.callback (/home/etherpad/etherpad-lite/src/node/utils/ExportEtherpad.js:63:9)

    at /home/etherpad/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:100:17

    at /home/etherpad/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:185:7
`

on Linux xxx.yyy 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1 (2018-04-28) x86_64 GNU/Linux
Last Commit (Master Branch): 6dd172d6b76cb219f0aa095ea09e43ef7f259d3d

Best Regards,
Max

**Comment by noppelmax** [comment]
About 600 points of history, yes.

**Comment by JohnMcLear** [comment]
Etherpad shouldn't struggle to export anything up to ~3.5Gb file .etherpad files.  Afaik I tested up to about 2Gb.

It's possible this machine didn't have sufficient memory available for Etherpad so it crashed.  If this problem persists please comment here and I will re-open.
