### ISSUE TITLE
Error: listen EADDRNOTAVAIL 54.169.248.101:9001

### ISSUE THREAD

**Issue by RAZA-ABBBASI** [ether/etherpad-lite#3406]
I am working on linux server, an amazon aws instance. 
My server ip address is 54.169.248.101 and i have node installed. i have cloneed etherpad-lite repo.
Now when i run command bin/run.sh , it first starts etherpad and then due to following error 

[2018-05-31 10:18:23.997] [ERROR] console - Error: listen EADDRNOTAVAIL 54.169.248.101:9001
    at Server.setupListenHandle [as _listen2] (net.js:1329:19)
    at listenInCluster (net.js:1387:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1502:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:72:10)

it shutdown the etherpad. Please help, i will be really thankful

**Comment by nashe** [comment]
It is likely that something is already attached to this port. Can you please run `lsof -i :9001`, kill the process it gives you and then try starting etherpad again?

**Comment by RAZA-ABBBASI** [comment]
@nashe you were right, that port was blocked. I fixed it by unblocking that port. Thanks
