### ISSUE TITLE
Failed installation on Debian 8.8

### ISSUE THREAD

**Issue by RonaldEcke** [ether/etherpad-lite#3438]
Hey github,

i am really struggling with the installation of Etherpad-lite. First it says my NPM version is too old and then i tried to update it but it didnt work. Im very new du Debian and Linux in general but i cant find solutions online because i actually dont know what the problem is. When i run etherpad via bin/run.sh - like they tell on their website -  i get this error:

Please type 'Etherpad rocks my socks' or supply the '--root' argument if you still want to start it as root
Etherpad rocks my socks
bin/run.sh: 24: [: Etherpad rocks my socks: unexpected operator

/usr/local/lib/node_modules/npm/bin/npm-cli.js:82
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
Cannot extract npm major version from version string ""

so it tried to reinstall npm new but i cant make it work.
Im glad for any help!

Best Regards
Ronald

**Comment by ukcb** [comment]
https://deb.nodesource.com has a package nodejs version 10.8 including npm for Debian 8 aka jessie.

**Comment by muxator** [comment]
I guess this can be closed?
