### ISSUE TITLE
DEP0079: Custom inspection function on Objects via .inspect()

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3457]
- Start Etherpad with `abiword` enabled in `settings.json`
- Etherpad's node process will spawn abiword
- Take note of abiword PID
- `kill <PID>`
- a stack trace is printed (that's normal), along with a deprecation warning (that's our target):
   ```
   [2018-08-12 22:37:35.050] [ERROR] console - Abiword File failed to convert Error: Abiword died with exit code null
       at module.exports (.../src/node_modules/async-stacktrace/ERR.js:46:13)
       at .../src/node/handler/ExportHandler.js:182:36
       at .../src/node_modules/async/lib/async.js:254:17
       at .../src/node_modules/async/lib/async.js:151:21
       at .../src/node_modules/async/lib/async.js:251:21
       at Object.callback (.../src/node_modules/async/lib/async.js:615:34)
       at stdoutCallback (.../src/node/utils/Abiword.js:135:14)
       at ChildProcess.<anonymous> (.../src/node/utils/Abiword.js:94:7)
       at ChildProcess.emit (events.js:182:13)
       at ChildProcess.EventEmitter.emit (domain.js:442:20)
   Error: Abiword died with exit code null
       at module.exports (.../src/node_modules/async-stacktrace/ERR.js:46:13)
       at .../src/node/handler/ExportHandler.js:182:36
       at .../src/node_modules/async/lib/async.js:254:17
       at .../src/node_modules/async/lib/async.js:151:21
       at .../src/node_modules/async/lib/async.js:251:21
       at Object.callback (.../src/node_modules/async/lib/async.js:615:34)
       at stdoutCallback (.../src/node/utils/Abiword.js:135:14)
       at ChildProcess.<anonymous> (.../src/node/utils/Abiword.js:94:7)
       at ChildProcess.emit (events.js:182:13)
       at ChildProcess.EventEmitter.emit (domain.js:442:20)
   [2018-08-12 22:37:35.053] [ERROR] console - (node:2945) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
   ```

**Comment by muxator** [comment]
This is really needed [only on Node < 6.4.0](https://nodejs.org/api/all.html#deprecations_dep0079_custom_inspection_function_on_objects_via_inspect
):

>Using a property named inspect on an object to specify a custom inspection function for util.inspect() is deprecated. Use util.inspect.custom instead. For backward compatibility with Node.js prior to version 6.4.0, both may be specified.

Given that Etherpad **1.7** requires node >= 6.9.0, getting rid of this should be risk-free.

**Comment by JohnMcLear** [comment]
```
jose@server:~/johnmcether/src/node$ grep -rni inspect .
jose@server:~/johnmcether/src/node$
```
:?

**Comment by JohnMcLear** [comment]
When I kill the pid I get

```
[2020-03-31 12:35:04.101] [ERROR] console - TypeError: stdoutCallback is not a function
    at ChildProcess.<anonymous> (/home/jose/johnmcether/src/node/utils/Abiword.js:94:7)
    at ChildProcess.emit (events.js:316:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[2020-03-31 12:35:04.102] [INFO] console - graceful shutdown...
[2020-03-31 12:35:04.103] [INFO] console - db sucessfully closed.
```

I'm gonna close this because I don't think it's still relevant.
