### ISSUE TITLE
Unable to install etherpad-lite (Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-87-generic x86_64))

### ISSUE THREAD

**Issue by your1p** [ether/etherpad-lite#3461]
I use Ubuntu instance created from Vagrant, and following the instructions of installing Etherpad, after executing the `bin/run.sh`, it will fail :
I used Etherpad 1.6.6 since 2 mouth and it already works. I don't understand why it fail now. 

```
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
ep_etherpad-lite@1.6.6 /home/etherpad/src
├── ansi-regex@2.1.1 
├── cacache@11.1.0 
├── cli-table3@0.5.0 
├── figgy-pudding@3.2.0 
├── hosted-git-info@2.7.1 
├── iferr@1.0.2 
├── is-cidr@2.0.6 
├── is-fullwidth-code-point@1.0.0 
├── JSONStream@1.3.3 
├── libcipm@2.0.1 
├── node-gyp@3.8.0 
├─┬ npm@6.4.0
│ └── request@2.87.0 
├── npm-audit-report@1.3.1 
├── npm-profile@3.0.2 
├── stringify-package@1.0.0 
├── strip-ansi@3.0.1 
├── tar@4.4.6 
├── uuid@3.3.2 
├── validate-npm-package-license@3.0.4 
└── which@1.3.1 

Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
/home/etherpad/src/node_modules/npm/lib/config/defaults.js:392
    nic => interfaces[nic].map(({address}) => address)
                                ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/etherpad/src/node_modules/npm/lib/config/core.js:3:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by muxator** [comment]
@your1p, do you have more details about your environment (os, node & npm version, output of `git log -1` and `git status`)?

**Comment by your1p** [comment]
Yes, of course. 

`git log -1` : 
```
commit 275f1b1fef88333b0d8a0bcc1f36fe28f244add9
Merge: e4a8581 7e69a82
Author: muxator <a.mux@inwind.it>
Date:   Fri May 4 23:47:44 2018 +0200

    Merge new release into master branch
```

`git status` : 
```
HEAD detached at 1.6.6
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.npm/

nothing added to commit but untracked files present (use "git add" to track)
```
I use npm 3.8.6 anf nodejs 5.12.0 on a Ubuntu 16.04.03 LTS full stock on vagrant.

**Comment by muxator** [comment]
@Your1p, could you do a short debrief on this?

Version 1.7 was the first that started explicitly checking the nodejs version, requiring at least 6.9.0, and deprecating anything < 8.9.0, [plan](https://github.com/ether/etherpad-lite/issues/3424), [PR](https://github.com/ether/etherpad-lite/pull/3432)).
Starting from Etherpad 1.8, thus, node 8.9 will be the minimum supported version.

I ask this because I would have expected that the documentation and the startup messages should have been clear enough, but probably they weren't.

What could have you spared you this time? Did the startup error not fire? Is the requirement in the documentation clear enough?

Thanks for your help
