### ISSUE TITLE
Pad stuck loading after crash when viewing

### ISSUE THREAD

**Issue by adamprocter** [ether/etherpad-lite#3501]
When connected to a Pad etherpad crashed (I think too many users editing at once (18)) But when i restart service the pad gets stuck, it appears to load as per terminal data but just loads like this

<img width="1200" alt="screenshot 2018-10-19 18 03 50" src="https://user-images.githubusercontent.com/123951/47233107-936bc180-d3c9-11e8-8b85-65056c8d9c63.png">

**Comment by muxator** [comment]
Hi @adamprocter, could you please try to find a way to reproduce this?

Without more information it's hard to figure out what's happening.
Thanks

**Comment by adamprocter** [comment]
The crash was related to 'max_allowed_packet' bytes - so I have increased this to 128M and turned production on.. cant seem to crash now and even if I close the service while pad is open the broken loading doesnt happen...

not sure if the broken loading thing could be fixable if someone hits the bytes crash.... will see how It goes over the next few days

**Comment by adamprocter** [comment]
[2018-11-01 11:31:45.208] [ERROR] console - Error: ER_NET_PACKET_TOO_LARGE: Got a packet bigger than 'max_allowed_packet' bytes
    at Query.Sequence._packetToError (/root/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/root/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/root/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/root/etherpad-lite/src/node_modules/mysql/lib/protocol/Parser.js:76:12)  
    at Protocol.write (/root/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/etherpad-lite/src/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:127:13)
    at Socket.emit (domain.js:421:20)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    --------------------
    at Protocol._enqueue (/root/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/root/etherpad-lite/src/node_modules/mysql/lib/Connection.js:208:25)  
    at /root/etherpad-lite/src/node_modules/ueberdb2/mysql_db.js:214:18
    at /root/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:462:21
    at /root/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:194:13
    at /root/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:97:13
    at Array.forEach (<anonymous>)
    at _forEach (/root/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:26:24)
    at async.forEach (/root/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:96:9)
    at _asyncMap (/root/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:193:9)
[2018-11-01 11:31:45.208] [INFO] console - graceful shutdown...
[2018-11-01 11:31:45.213] [ERROR] console - Error: Connection lost: The server closed the connection.
    at Protocol.end (/root/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:113:13)
    at Socket.<anonymous> (/root/etherpad-lite/src/node_modules/mysql/lib/Connection.js:109:28)
    at Socket.emit (events.js:132:15)
    at Socket.emit (domain.js:421:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
[2018-11-01 11:31:47.617] [INFO] access - [LEAVE] Pad "Testing123": Author "a.5HA7VHQC7GgRuPv8" on client ymshg78FhMr7vquAAAAE with IP "XXX.XX.XX.XXX" left the pad

**Comment by muxator** [comment]
A brief follow-up on this: 

A reference to the `ER_NET_PACKET_TOO_LARGE` can be found [here](https://dev.mysql.com/doc/refman/5.5/en/packet-too-large.html#packet-too-large):

> A communication packet is a single SQL statement sent to the MySQL server, a single row that is sent to the client, or a binary log event sent from a master replication server to a slave. 

I am just wandering now: if the error happens when inserting data, maybe a wise driver should be able to split the offending statements in two parts. If the problems happens when reading, instead, some more radical design work might be required, in which the DB interaction itself is aware of the size of the exchanged objects and mitigates it somehow.

The practical approach of just increasing `max_allowed_packet` is probably the right one for Etherpad, which - for now - does not have a big development force behind it.

**Comment by JohnMcLear** [comment]
Waiting on method to replicate to triage.

**Comment by flotho** [comment]
tested successfully
