### ISSUE TITLE
Stuck on Loading -  undefined is not an object 

### ISSUE THREAD

**Issue by adamprocter** [ether/etherpad-lite#3515]
I have a few pads that have got stuck on loading after the server crashed while they where open
Is there anyway to retrieve / fix them ?

Left Pad open and eventual hit this error (though takes a long time ?)

TypeError: undefined is not an object (evaluating 'r.dropdowns.length') in http://etherpad.myserver.com:9001/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 18'

**Comment by muxator** [comment]
Hi, @adamprocter.

If you want a quick way of retrieving your pads, I suggest to export them.

As for the error you are indicating, Etherpad does not have a good infrastructure for reporting client side errors, and I suspect that there will be no direct way of debugging it "remotely".

Given the origin of your error (a crash that resulted - probably - in a corruption), it will be interesting to revise the persistency guarantees of our data layer.

Even if it will not lead to solving your problem, would you mind sharing details on your installation (Etherpad version, what DB are you using & its version, your browser, and such)?

**Comment by muxator** [comment]
Hi @adamprocter, sorry for the late response.

You can have a look at https://github.com/ether/etherpad-lite/wiki/Backing-up-and-Restoring-Etherpad-Lite-Pads

**Comment by adamprocter** [comment]
thanks will do, noted another type of crash this week, which did the same to the pad.
# etherpad version 
 1.7.0 (20be994)

# DB
mysql

# plug ins
adminpads | 0.0.12 
headings | 0.1.6

# browser
everytime crash has occured we have had a mix of firefox / chrome on mac and pc

**Comment by adamprocter** [comment]
```
[2018-12-04 22:49:14.037] [INFO] console - req.params.pad daytwo
[2018-12-04 22:49:14.066] [ERROR] console - Error: Failed assertion: newlineEnd <= 0 in splitAttributionLines
    at Object.error (/root/etherpad-lite/src/static/js/Changeset.js:39:11)
    at Object.assert (/root/etherpad-lite/src/static/js/Changeset.js:53:13)
    at Object.exports.splitAttributionLines (/root/etherpad-lite/src/static/js/Changeset.js:1285:15)
    at getTXTFromAtext (/root/etherpad-lite/src/node/utils/ExportTxt.js:80:31)
    at /root/etherpad-lite/src/node/utils/ExportTxt.js:58:12
    at fn (/root/etherpad-lite/src/node_modules/async/lib/async.js:641:34)
    at Immediate.<anonymous> (/root/etherpad-lite/src/node_modules/async/lib/async.js:557:34)
    at runCallback (timers.js:757:18)
    at tryOnImmediate (timers.js:718:5)
    at processImmediate [as _immediateCallback] (timers.js:698:5)
[2018-12-04 22:49:14.066] [INFO] console - graceful shutdown...
[2018-12-04 22:49:14.067] [INFO] ueberDB - Flushed 1 values
[2018-12-04 22:49:14.069] [INFO] access - [LEAVE] Pad "daytwo": Author "a.EDFxja7Y1wnPdqOJ" on client QeWgNIJUQSAdaf6FAAAD with IP "109.148.17.163" left the pad
[2018-12-04 22:49:14.169] [INFO] console - db sucessfully closed.
```

**Comment by adamprocter** [comment]
another recent crash when trying to back up a pad using /export/txt

**Comment by JohnMcLear** [comment]
Is this still an issue?  If so we can reopen.

**Comment by JocelynDelalande** [comment]
I encountered this same issue those days, on 4 different pads of an instance.

Etherpad-lite 1.7.5

The faulty pad was unreachable, and also triggers a full crash (full etherpad auto-restart) of the server on some uses of that pad, like trying to `/export/html`it.
