### ISSUE TITLE
Can't install any plugin : "Argument #5: Expected object but got string"

### ISSUE THREAD

**Issue by Leuchtmarker** [ether/etherpad-lite#3522]
I'm trying to install `ep_markdownify` and I got this error message:

An error occurred while installing ep_markdownify 
Argument #5: Expected object but got string

This is my console log:
[2018-12-02 00:38:50.730] [WARN] console - { Error: Argument #5: Expected object but got string
    at inflatableChild (/var/www/html/etherpad-lite/src/node_modules/npm/lib/install/inflate-shrinkwrap.js:93:3)
    at BB.each (/var/www/html/etherpad-lite/src/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
    at tryCatcher (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5) code: 'EINVALIDTYPE' }
Error: Argument #5: Expected object but got string
    at inflatableChild (/var/www/html/etherpad-lite/src/node_modules/npm/lib/install/inflate-shrinkwrap.js:93:3)
    at BB.each (/var/www/html/etherpad-lite/src/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
    at tryCatcher (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/html/etherpad-lite/src/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

this happen with every other plugin.
I'm using `node v8.14.0` and the newest etherpad version

**Comment by muxator** [comment]
@Leuchtmarker, I tried replicating your bug with various node & npm combinations without success.

**Comment by JohnMcLear** [comment]
Closing due to no input
