### ISSUE TITLE
Cant install any plugins, different issue

### ISSUE THREAD

**Issue by lerugray** [ether/etherpad-lite#3531]
Can't install any of the plugins, manually or otherwise, I keep getting this version issue which makes little sense to me, thanks

```
{ ep_etherpad-lite: No valid versions available for ep_etherpad-lite
    at pickManifest (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\npm-pick-manifest\index.js:20:11)
    at fetchPackument.then.packument (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:39:14)
    at tryCatcher (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
  cause:
   { ep_etherpad-lite: No valid versions available for ep_etherpad-lite
    at pickManifest (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\npm-pick-manifest\index.js:20:11)
    at fetchPackument.then.packument (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:39:14)
    at tryCatcher (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
     code: 'ENOVERSIONS',
     name: 'ep_etherpad-lite',
     type: 'version',
     wanted: '1.7.0' },
  isOperational: true,
  code: 'ENOVERSIONS',
  type: 'version',
  wanted: '1.7.0' }
ep_etherpad-lite: No valid versions available for ep_etherpad-lite
    at pickManifest (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\npm-pick-manifest\index.js:20:11)
    at fetchPackument.then.packument (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:39:14)
    at tryCatcher (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb\node_modules\ep_etherpad-lite\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by lerugray** [comment]
Just another note, I've tried the solutions mentioned here and elsewhere for similar issues but none of them have worked. I have a feeling it is maybe a permissions issue but I have no idea how to check, not a developer myself. thanks

**Comment by lerugray** [comment]
more errors

```
C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb>npm i ep_spellcheck
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! enoent request to https://registry.npmjs.org/ep_spellcheck failed, reason: connect ENOENT /]localhost.org
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lerug\AppData\Roaming\npm-cache\_logs\2018-12-30T17_58_49_862Z-debug.log

C:\Users\lerug\Downloads\etherpad-lite-win-1.7.0-96ac381afb>
```

**Comment by JohnMcLear** [comment]
Clear your npm cache I think that will fix it.  Come back if it's still an issue <3
