### ISSUE TITLE
Don't get etherpad-lite to work. #Cpanel, Node.js 10.15.0, Application Mode Developement, log4js.replaceConsole not a function

### ISSUE THREAD

**Issue by Dubidubiduu** [ether/etherpad-lite#3569]
Hello everyone,

I try to get etherpad-lite to work. After npm install log4js and npm install measured-core I get the following errormessage when starting ./bin.run.sh

```
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN etherpad5@1.0.0 No description
npm WARN etherpad5@1.0.0 No repository field.

audited 21 packages in 0.62s
found 0 vulnerabilities

Clearing minified cache...
Started Etherpad...
/home/xxx/etherpad5/etherpad-lite/src/node/server.js:30
log4js.replaceConsole();
       ^

TypeError: log4js.replaceConsole is not a function
    at Object.<anonymous> (/home/xxx/etherpad5/etherpad-lite/src/node/server.js:30:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

My Node.js Version is in the title. Anyone has an idea what to do?

**Comment by lpagliari** [comment]
@Dubidubiduu I'm not sure if we still have issues with node versions, but could you try with node `8.9.0`, please? We've had this type of error message you've mentioned, and changing the node version stopped the error from happening.
