### ISSUE TITLE
Timeline error: atext is null or Error: Not a exports: null

### ISSUE THREAD

**Issue by Hiswe** [ether/etherpad-lite#3574]
Hi,

first thanks for maintaining Etherpad! 

I have 2 problems:

1. **atext is null** print an error but doesn't throw
2. **Error: Not a exports: null** crash etherpad

I don't know how it comes, but my DB seems to miss some data…

For Etherpad I have the version:

- 1.7.5
- DB: mySql

For the plugins I have:

- [ep_auth_session](https://www.npmjs.com/package/ep_auth_session)
- [ep_image_upload](https://github.com/citizenos/ep_image_upload)
- [ep_headings2](https://github.com/ether/ep_headings2) manually installed because the update hasn't been published on NPM yet

## atext is null

- doesn't crash etherpad
- Timeline doesn't work

If I check in DB, it doesn't have any `pad:actus:revs:xx` with any atext.
And I didn't found a way to reset a pad's revisions to be on tracks.
I need to copy/paste the Pad content on a new pad.

```
Error while handling a changeset request for actus { Async Stacktrace:
    at /Users/user-name/Sites/etherpad/src/node/handler/PadMessageHandler.js:1655:8
    at /Users/user-name/Sites/etherpad/src/node/handler/PadMessageHandler.js:1603:16
    at /Users/user-name/Sites/etherpad/src/node/handler/PadMessageHandler.js:1714:8
    at /Users/user-name/Sites/etherpad/src/node/handler/PadMessageHandler.js:1695:14
    at /Users/user-name/Sites/etherpad/src/node/db/Pad.js:238:8

Error: atext is null
    at Object.error (/Users/user-name/Sites/etherpad/src/static/js/Changeset.js:39:11)
    at Object.exports.cloneAText (/Users/user-name/Sites/etherpad/src/static/js/Changeset.js:1636:18)
    at Object.callback (/Users/user-name/Sites/etherpad/src/node/db/Pad.js:194:33)
    at /Users/user-name/Sites/etherpad/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:149:17
    at /Users/user-name/Sites/etherpad/src/node_modules/ueberdb2/CacheAndBufferLayer.js:378:7
    at exports.database.get (/Users/user-name/Sites/etherpad/src/node_modules/ueberdb2/CacheAndBufferLayer.js:144:5)
    at exports.database.getSub (/Users/user-name/Sites/etherpad/src/node_modules/ueberdb2/CacheAndBufferLayer.js:350:8)
    at exports.channels.doOperation [as operatorFunction] (/Users/user-name/Sites/etherpad/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:143:18)
    at exports.channels.emit (/Users/user-name/Sites/etherpad/src/node_modules/channels/channels.js:49:11)
    at exports.database.getSub (/Users/user-name/Sites/etherpad/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:82:17)
    at /Users/user-name/Sites/etherpad/src/node/db/Pad.js:189:14
    at /Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:570:21
    at /Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:249:17
    at /Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:125:13
    at Array.forEach (<anonymous>)
    at _each (/Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:46:24) easysync: true }
Async Stacktrace:
    at /Users/user-name/Sites/etherpad/src/node/handler/PadMessageHandler.js:1655:8
    at /Users/user-name/Sites/etherpad/src/node/handler/PadMessageHandler.js:1603:16
    at /Users/user-name/Sites/etherpad/src/node/handler/PadMessageHandler.js:1714:8
    at /Users/user-name/Sites/etherpad/src/node/handler/PadMessageHandler.js:1695:14
    at /Users/user-name/Sites/etherpad/src/node/db/Pad.js:238:8
```

## Error: Not a exports: null

- crash Etherpad

For this one I have no ideas…
Seems also to have no revisions with `atext`

```
Error: Not a exports: null
    at Object.error (/Users/user-name/Sites/etherpad/src/static/js/Changeset.js:39:11)
    at Object.exports.unpack (/Users/user-name/Sites/etherpad/src/static/js/Changeset.js:874:13)
    at Object.exports.inverse (/Users/user-name/Sites/etherpad/src/static/js/Changeset.js:1882:26)
    at /Users/user-name/Sites/etherpad/src/node/handler/PadMessageHandler.js:1624:35
    at /Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:610:21
    at /Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:249:17
    at iterate (/Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:149:13)
    at /Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:160:25
    at /Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:251:21
    at /Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:615:34
    at /Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:254:17
    at done (/Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:135:19)
    at /Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:32:16
    at /Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:251:21
    at /Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:575:34
    at done (/Users/user-name/Sites/etherpad/src/node_modules/async/lib/async.js:135:19)    
```

**Comment by muxator** [comment]
Hi @hiswe, I do not have a solution for you right now, but your problem makes me think once again about the opportunity to use transactions in the DB layer where applicable.

**Comment by Hiswe** [comment]
Hi @muxator Thanks for your answer.

I'm not too much in DB things so I can't provide any insight on this…
But what could help is for now is:

- not crashing the application when `Error: Not a exports: null` happen
- having an API endpoint to reset the history of a Pad

For now to do the latter I can only think of:

- create a temporary pad (`B`)
- copy the “buggy timelined” pad (`A`)  content to `B` (with [getText](https://etherpad.org/doc/v1.7.5/#index_gettext_padid_rev)/[setText](https://etherpad.org/doc/v1.7.5/#index_settext_padid_text))

This will ensure us that we don't have an history ([copyPad](https://etherpad.org/doc/v1.7.5/#index_copypad_sourceid_destinationid_force_false) doesn't provide a way to omit the history)

- remove the pad `A`
- create a pad `A bis` with the same ID as `A`
- copy the pad `B`  content to `A bis`
- remove the pad `B`

Maybe you have a better solution?

**Comment by JohnMcLear** [comment]
Hey guys, I'm gonna close this because we haven't had additional reports of a similar issue.  If it's still an issue I'd love to take a look and solve it!  Thanks
