### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colorId' of null

### ISSUE THREAD

**Issue by ddeenniiss** [ether/etherpad-lite#3612]
We have a lot of error like this. 

[2019-05-31 14:51:16.994] [ERROR] console - (node:10107) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colorId' of null
    at p.then.authorInfo (/home/etherpad/public/etherpad/src/node/handler/PadMessageHandler.js:1199:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-31 14:51:16.995] [ERROR] console - (node:10107) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[2019-05-31 14:51:16.996] [ERROR] console - (node:10107) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mixotroph** [comment]
[2019-07-11 20:40:05.168] [ERROR] console - (node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)

**Comment by muxator** [comment]
Not working on it right now, but confirmed.

**Comment by xshadow** [comment]
I can confirm this is still a bug in 1.8.0

**Comment by muxator** [comment]
Fixed via a workaround in #3719.

The underlying bug still remains, but instead of a unhandled promise rejection, we'll get clear warning messages and a fallback to predefined values.
