### ISSUE TITLE
beta.etherpad.org is down 502 Bad Gateway

### ISSUE THREAD

**Issue by horner** [ether/etherpad-lite#3637]
Getting 502 Bad Gateway

![image](https://user-images.githubusercontent.com/6094599/63656756-71b83500-c766-11e9-9aea-2ffcc81bdf24.png)

**Comment by muxator** [comment]
Thanks for the info @horner.

Micro post mortem: the DB went down:

```
Jul 26 06:43:51 beta node[26869]: [2019-07-26 06:43:51.134] [ERROR] console - Error: Connection lost: The server closed the connection.
Jul 26 06:43:51 beta node[26869]:     at Protocol.end (<base>/src/node_modules/ueberdb2/node_modules/mysql/lib/protocol/Protocol.js:113:13)
Jul 26 06:43:51 beta node[26869]:     at Socket.<anonymous> (<base>/src/node_modules/ueberdb2/node_modules/mysql/lib/Connection.js:109:28)
Jul 26 06:43:51 beta node[26869]:     at Socket.emit (events.js:194:15)
Jul 26 06:43:51 beta node[26869]:     at Socket.EventEmitter.emit (domain.js:441:20)
Jul 26 06:43:51 beta node[26869]:     at endReadableNT (_stream_readable.js:1125:12)
Jul 26 06:43:51 beta node[26869]:     at process._tickCallback (internal/process/next_tick.js:63:19)

Jul 26 06:43:51 beta node[26869]: [2019-07-26 06:43:51.136] [INFO] console - graceful shutdown...
Jul 26 06:43:51 beta node[26869]: [2019-07-26 06:43:51.158] [INFO] console - db sucessfully closed.
Jul 26 06:43:51 beta systemd[1]: etherpad-lite.service: Service hold-off time over, scheduling restart.
Jul 26 06:43:51 beta systemd[1]: etherpad-lite.service: Scheduled restart job, restart counter is at 1.
Jul 26 06:43:51 beta systemd[1]: Stopped Etherpad-lite, the collaborative editor..
Jul 26 06:43:51 beta systemd[1]: Started Etherpad-lite, the collaborative editor..
Jul 26 06:43:51 beta node[7524]: [2019-07-26 06:43:51.743] [DEBUG] console - Running on Node v10.15.3 (minimum required Node version: 8.9.0)
Jul 26 06:43:52 beta node[7524]: [2019-07-26 06:43:52.190] [INFO] console - All relative paths will be interpreted relative to the identified Etherpad base dir: /home/etherpad-lite/etherpad
Jul 26 06:43:52 beta node[7524]: [2019-07-26 06:43:52.191] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "<base>/settings.json"
Jul 26 06:43:52 beta node[7524]: [2019-07-26 06:43:52.191] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "<base>/credentials.json"
Jul 26 06:43:52 beta node[7524]: [2019-07-26 06:43:52.201] [INFO] console - settings loaded from: <base>/settings.json
Jul 26 06:43:52 beta node[7524]: [2019-07-26 06:43:52.201] [INFO] console - No credentials file found in <base>/credentials.json. Ignoring.
Jul 26 06:43:52 beta node[7524]: [2019-07-26 06:43:52.235] [INFO] console - Using skin "colibris" in dir: <base>/src/static/skins/colibris
Jul 26 06:43:52 beta node[7524]: [2019-07-26 06:43:52.236] [DEBUG] AbsolutePaths - Relative path "./SESSIONKEY.txt" can be rewritten to "<base>/SESSIONKEY.txt"
Jul 26 06:43:52 beta node[7524]: [2019-07-26 06:43:52.237] [INFO] console - Session key loaded from: <base>/SESSIONKEY.txt
Jul 26 06:43:52 beta node[7524]: [2019-07-26 06:43:52.434] [ERROR] console - ERROR: Problem while initalizing the database
Jul 26 06:43:52 beta node[7524]: [2019-07-26 06:43:52.434] [ERROR] console - Error: connect ECONNREFUSED 127.0.0.1:3306
```
