### ISSUE TITLE
Etherpad keeps on loading

### ISSUE THREAD

**Issue by musanii** [ether/etherpad-lite#3642]
i keep on getting this erorr when i run etherpad. and my  pad application is on  the load mode . somebody help 
[2019-09-26 12:30:30.278] [ERROR] console - (node:32759) UnhandledPromiseRejectionWarning: apierror: sessionID does not exist
    at Object.exports.getSessionInfo (/home/etherpad/etherpad-lite/src/node/db/SessionManager.js:129:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
[2019-09-26 12:30:30.278] [ERROR] console - (node:32759) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[2019-09-26 12:30:30.278] [ERROR] console - (node:32759) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ukcb** [comment]
I have a similar problem. I use etherpad-lite 1.8.0 with plugin ep_delete_after_delay@0.0.8, pads are not loaded.


> [2019-12-08 09:55:23.234] [ERROR] console - (node:2907) UnhandledPromiseRejectionWarning: apierror: text is not a string
>     at Object.exports.getPad (/home/etherpad/apps/etherpad-lite/src/node/db/PadManager.js:126:13)
>     at /home/etherpad/apps/etherpad-lite/node_modules/ep_delete_after_delay/delete.js:213:20
>     at Layer.handle [as handle_request] (/home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
>     at next (/home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/route.js:137:13)
>     at Route.dispatch (/home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/route.js:112:3)
>     at Layer.handle [as handle_request] (/home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
>     at /home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/index.js:281:22
>     at param (/home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/index.js:354:14)
>     at paramCallback (/home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/index.js:401:21)
> [2019-12-08 09:55:23.235] [ERROR] console - (node:2907) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

**Comment by JohnMcLear** [comment]
Confirmed error in plugin.  Please open issue on plugin repo.

```
[2020-03-14 20:02:57.548] [ERROR] console - (node:1879) UnhandledPromiseRejectionWarning: apierror: text is not a string
    at Object.exports.getPad (/home/jose/etherpad-lite/src/node/db/PadManager.js:126:13)
    at /home/jose/etherpad-lite/node_modules/ep_delete_after_delay/delete.js:213:20
    at Layer.handle [as handle_request] (/home/jose/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jose/etherpad-lite/src/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/jose/etherpad-lite/src/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/jose/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
    at /home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:281:22
    at param (/home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:354:14)
    at paramCallback (/home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:401:21)
[2020-03-14 20:02:57.552] [ERROR] console - (node:1879) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[2020-03-14 20:02:57.552] [ERROR] console - (node:1879) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-03-14 20:02:57.773] [ERROR] console - (node:1879) UnhandledPromiseRejectionWarning: apierror: text is not a string
    at Object.exports.getPad (/home/jose/etherpad-lite/src/node/db/PadManager.js:126:13)
    at Object.exports.handleMessage [as hook_fn] (/home/jose/etherpad-lite/node_modules/ep_delete_after_delay/delete.js:136:20)
    at normalizedhook (/home/jose/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
    at hookCallWrapper (/home/jose/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
    at /home/jose/etherpad-lite/src/static/js/pluginfw/hooks.js:88:7
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:249:17
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:125:13
    at Array.forEach (<anonymous>)
    at _each (/home/jose/etherpad-lite/src/node_modules/async/lib/async.js:46:24)
[2020-03-14 20:02:57.777] [ERROR] console - (node:1879) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2020-03-14 20:02:58.720] [ERROR] console - (node:1879) UnhandledPromiseRejectionWarning: apierror: text is not a string
    at Object.exports.getPad (/home/jose/etherpad-lite/src/node/db/PadManager.js:126:13)
    at /home/jose/etherpad-lite/node_modules/ep_delete_after_delay/delete.js:213:20
    at Layer.handle [as handle_request] (/home/jose/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jose/etherpad-lite/src/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/jose/etherpad-lite/src/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/jose/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
    at /home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:281:22
    at param (/home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:354:14)
    at paramCallback (/home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:401:21)
[2020-03-14 20:02:58.726] [ERROR] console - (node:1879) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[2020-03-14 20:03:03.538] [ERROR] console - (node:1879) UnhandledPromiseRejectionWarning: apierror: text is not a string
    at Object.exports.getPad (/home/jose/etherpad-lite/src/node/db/PadManager.js:126:13)
    at Object.exports.handleMessage [as hook_fn] (/home/jose/etherpad-lite/node_modules/ep_delete_after_delay/delete.js:136:20)
    at normalizedhook (/home/jose/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
    at hookCallWrapper (/home/jose/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
    at /home/jose/etherpad-lite/src/static/js/pluginfw/hooks.js:88:7
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:249:17
    at /home/jose/etherpad-lite/src/node_modules/async/lib/async.js:125:13
    at Array.forEach (<anonymous>)
    at _each (/home/jose/etherpad-lite/src/node_modules/async/lib/async.js:46:24)
[2020-03-14 20:03:03.540] [ERROR] console - (node:1879) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```
