### ISSUE TITLE
UnhandledPromiseRejectionWarning when using Etherpad remotely

### ISSUE THREAD

**Issue by Duddy67** [ether/etherpad-lite#3645]
I installed Node.js on my server to run Etherpad Lite in order to use it remotely.
Etherpad Lite is called through its API from another website. 
But when the website tries to load a pad previously created I get these errors:
```
[2019-10-01 06:29:49.378] [INFO] API - REQUEST, v1.2.11:listSessionsOfGroup, {"groupID":"g.tmG0M1C0NlWZmIda","apikey":"c3bbaabe1dcdf87c88bcaf744069e8c7e5270b7b331d484faa2debd957701064"}
[2019-10-01 06:29:49.379] [INFO] API - RESPONSE, listSessionsOfGroup, {"code":0,"message":"ok","data":{"s.352dc0a46382ab16c030d93c31e5a33d":{"groupID":"g.tmG0M1C0NlWZmIda","authorID":"a.NQUUTpWqPVV2LezT","validUntil":1569911468}}}
[2019-10-01 06:29:49.391] [INFO] API - REQUEST, v1.2.11:listSessionsOfGroup, {"groupID":"g.tmG0M1C0NlWZmIda","apikey":"c3bbaabe1dcdf87c88bcaf744069e8c7e5270b7b331d484faa2debd957701064"}
[2019-10-01 06:29:49.392] [INFO] API - RESPONSE, listSessionsOfGroup, {"code":0,"message":"ok","data":{"s.352dc0a46382ab16c030d93c31e5a33d":{"groupID":"g.tmG0M1C0NlWZmIda","authorID":"a.NQUUTpWqPVV2LezT","validUntil":1569911468}}}
[2019-10-01 06:29:49.406] [INFO] ueberDB - Flushed 2 values
[2019-10-01 06:29:49.706] [INFO] ueberDB - Flushed 1 values
[2019-10-01 06:29:49.906] [INFO] ueberDB - Flushed 1 values
[2019-10-01 06:29:50.007] [INFO] ueberDB - Flushed 1 values
[2019-10-01 06:29:50.039] [ERROR] console - (node:2498) UnhandledPromiseRejectionWarning: apierror: sessionID does not exist
    at Object.exports.getSessionInfo (/home/etherpad/etherpad-lite/src/node/db/SessionManager.js:128:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-10-01 06:29:50.044] [ERROR] console - (node:2498) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[2019-10-01 06:29:50.108] [INFO] ueberDB - Flushed 1 values
```
I checked in the MySQL Etherpad store table but the session does exist. 
So I have no idea where those errors come from.
Can someone help me.

Ubuntu 18.04
Node.js v10.16.3
Etherpad 1.7.5
MySQL 5.7

**Comment by muxator** [comment]
That kind of error on `src/node/db/SessionManager.js:128` seems to be more compatible with a version _after_ 1.7.5 (specifically, after  #3540 was merged).

Etherpad **1.8.0-beta.1** code:
https://github.com/ether/etherpad-lite/blob/ba38ed3bbae20bd195bd7fef983ab0ff5e387395/src/node/db/SessionManager.js#L121-L133

At the same location, Etherpad **1.7.5** has an empty line :)
https://github.com/ether/etherpad-lite/blob/6a3e4c69b8e83ff98c468529bc6a0ba1698a7526/src/node/db/SessionManager.js#L127-L130

**Comment by muxator** [comment]
@Duddy67, did you happen to step on this error again? Do you remember which Etherpad version you were using?

**Comment by JohnMcLear** [comment]
Closing due to staleness.
