### ISSUE TITLE
new install crashes

### ISSUE THREAD

**Issue by mouseb** [ether/etherpad-lite#3658]
hi etherland,

im trying to install e-lite on a debian buster box. nodejs -v = 12.13.0, npm -v = 6.12.0.
installed following this:https://github.com/nodejs/help/wiki/Installation, but substituing 12.13.0 for VERSION.

i git clone the master branch as per general etherpad instructions, and when it tries to start up it does this:
[2019-10-31 15:26:52.110] [ERROR] console - exception thrown: Maximum call stack size exceeded
[2019-10-31 15:26:52.111] [INFO] console - RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at ReadStream (/opt/etherpad/etherpad-lite/src/node_modules/graceful-fs/graceful-fs.js:194:14)
    at ReadStream (/opt/etherpad/etherpad-lite/src/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/opt/etherpad/etherpad-lite/src/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/opt/etherpad/etherpad-lite/src/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/opt/etherpad/etherpad-lite/src/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/opt/etherpad/etherpad-lite/src/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/opt/etherpad/etherpad-lite/src/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/opt/etherpad/etherpad-lite/src/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/opt/etherpad/etherpad-lite/src/node_modules/graceful-fs/graceful-fs.js:195:28)

i tried resolving the 25 listed vulnerabilities, ie cd /src, create lockfile, run npm audit fix. and it seems to work, but once i run ether again with bin/run.sh it seems to bring them all back while checking for dependencies. and perhaps thats not the issue?

i also tried npm update graceful-fs. as per https://github.com/ether/etherpad-lite/issues/3654. the command worked, but didn't help.

i installed node and etherpad as a normal user.

im not a programmer so its not necessary a tech thing screwing me up. any pointers appreciated tho. or also, is no one else having this issue on installing?

thanks

**Comment by muxator** [comment]
Hi, the problem on graceful-fs is solved in the develop branch. By the way this is the reason for which I blocked releasing 1.8. I'll release a hotfix asap, as a Halloween present :)

**Comment by muxator** [comment]
Hi @mouseb, version 1.8.0-beta.1 is released.

You may switch to the master branch, if you like.
If so, could you please confirm that everything is still working, and close this issue?

**Comment by muxator** [comment]
I think we can safely close this.
