### ISSUE TITLE
Installation issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by dcr18** [ether/etherpad-lite#3671]
I have installation issue on Ubuntu 18.04, Apache.

Please find attached log.

[2019-11-25T09_28_30_506Z-debug.log](https://github.com/ether/etherpad-lite/files/3891368/2019-11-25T09_28_30_506Z-debug.log)
[Uploading 2019-11-25T09_32_52_461Z-debug.log…]()

**Comment by dcr18** [comment]
I am getting this error while running the bash script


Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.

> wd@1.11.4 install /home/etherpad/etherpad-lite/src/node_modules/wd
> node scripts/build-browser-scripts

/home/etherpad/etherpad-lite/src/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/home/etherpad/etherpad-lite/src/node_modules/wd/build'
    at Object.mkdirSync (fs.js:757:3)
    at sync (/home/etherpad/etherpad-lite/src/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/home/etherpad/etherpad-lite/src/node_modules/wd/scripts/build-browser-scripts.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd@1.11.4 install: `node scripts/build-browser-scripts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wd@1.11.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-30T07_20_34_709Z-debug.log

**Comment by dcr18** [comment]
You shouldn't start Etherpad as root!
Please type 'Etherpad rocks my socks' or supply the '--root' argument if you still want to start it as root
Etherpad rocks my socks
bin/run.sh: 24: [: Etherpad rocks my socks: unexpected operator
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.

> wd@1.11.4 install /home/etherpad/etherpad-lite/src/node_modules/wd
> node scripts/build-browser-scripts

/home/etherpad/etherpad-lite/src/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/home/etherpad/etherpad-lite/src/node_modules/wd/build'
    at Object.mkdirSync (fs.js:757:3)
    at sync (/home/etherpad/etherpad-lite/src/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/home/etherpad/etherpad-lite/src/node_modules/wd/scripts/build-browser-scripts.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd@1.11.4 install: `node scripts/build-browser-scripts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wd@1.11.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-30T08_50_14_437Z-debug.log

**Comment by dcr18** [comment]
PFA
[ether3.txt](https://github.com/ether/etherpad-lite/files/3906930/ether3.txt)
[ether2.txt](https://github.com/ether/etherpad-lite/files/3906931/ether2.txt)

**Comment by muxator** [comment]
@dcr18, what user were you impersonating while executing `bin/installDeps.sh`?

For executing an mkdir inside `/home/etherpad/etherpad-lite/src/node_modules/wd/build` you should be user `etherpad-lite`.

Please do not run as root: it rarely solves your problem (not in this case for sure), and often makes it worse.

Anyway, thanks for the report, because this log line:

```
bin/run.sh: 24: [: Etherpad rocks my socks: unexpected operator
```

generated while running as root (do not do this, again), probably uncovered an unrelated bug in the startup script.

**Comment by dcr18** [comment]
@muxator  i am running it as root.

do i have to create a seperate user  etherpad-lite and add it to sudo group?

**Comment by muxator** [comment]
Do not run as root. Something is going bad either in permissions or system setup if you are resorting to running as root.

Closing this.
