### ISSUE TITLE
mongodb fails

### ISSUE THREAD

**Issue by buttle** [ether/etherpad-lite#3672]
Hi,

I've been running ethepad-lite for ages now and I'm trying to move it to a new server.
I have problems when running bin/run.sh
```

[2019-11-27 08:41:49.667] [ERROR] console - (node:7175) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
/opt/etherpad/node_modules/mongodb/lib/topologies/server.js:301
          throw err;
          ^

TypeError: this.db.collection is not a function
    at exports.database._onMongoConnect (/opt/etherpad/src/node_modules/ueberdb2/mongodb_db.js:130:29)
    at result (/opt/etherpad/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at executeCallback (/opt/etherpad/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at err (/opt/etherpad/node_modules/mongodb/lib/operations/connect.js:195:7)
    at connectCallback (/opt/etherpad/node_modules/mongodb/lib/operations/connect.js:345:5)
    at server.connect (/opt/etherpad/node_modules/mongodb/lib/operations/connect.js:438:5)
    at Server.connectHandler (/opt/etherpad/node_modules/mongodb/lib/topologies/server.js:298:9)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)
    at Server.EventEmitter.emit (domain.js:448:20)

```

I've tried installing an older mongodb client and an older etherpad-lite release, but no joy.

Where should I start looking?

Thanks! :)

**Comment by muxator** [comment]
I guess https://github.com/pita/ueberDB MongoDB code needs to be updated to keep up with new mongodb client driver.

I do not maintain that package, maybe try to open a issue there?

**Comment by buttle** [comment]
Thanks,
The solution is commented there.
https://github.com/Pita/ueberDB/issues/109#issuecomment-444496273

**Comment by muxator** [comment]
Closing, thanks
