### ISSUE TITLE
vendorize ueberDB2

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3675]
Etherpad storage abstraction layer is implemented in an external module, [ueberDB](https://github.com/Pita/ueberDB).

The module is not part of Etherpad, and it cannot be updated easily. For example, there is no direct way of publishing a new version on npm.

Looking at [ueberDB's depentents page on npm](https://www.npmjs.com/package/ueberdb2?activeTab=dependents) it is clear that, exluding an Etherpad plugin by Framasoft, no project whatsoever use ueberDB2: its only user is Etherpad.

**Forking/vendorizing ueberDB2** would remove an administrative bound without impacting on anything.

**Example 1**: in #3674 a user had to manually install the **sqlite3** driver (thankfully uncovering an unrelated issue in the process). That is surprising, since it would be normal to expect that a generic storage layer supports such a widespread (and well regarded) db library.

**Example 2**: another user had a problem with mongodb support (#3672), opened an issue here, and had to find the solution he needed inside the ueberDB's [issue tracker](https://github.com/Pita/ueberDB/issues/109#issuecomment-444496273). 

The work on this theme will start after **1.8.0** is released.

**Comment by pedrobmarin** [comment]
Hello. Just to endorse this up. We had a similar issue using ueberDB with redis. https://github.com/Pita/ueberDB/issues/110

**Comment by JohnMcLear** [comment]
Afaik I'm the maintainer and if @muxator wants 100% control he has it, just needs to let me know :)  <3

**Comment by JohnMcLear** [comment]
Pretty sure this can be closed now as I can give @muxator access.  If w ewant ueberdb2 moving to /ether that can be arranged too.

**Comment by muxator** [comment]
I still think that having to publish a new package on npm && pull it on etherpad && upgrading dependencies & lockfile there is just **too much work** for a package no one else is using.

Low priority now that we own ueberdb, but reopening.

**Comment by JohnMcLear** [comment]
etherdraw uses it afaik?



-----Original message-----

**Comment by JohnMcLear** [comment]
I don't think this is causing any issues tbh.  I'm +1 leaving things as they are.

**Comment by muxator** [comment]
Low priority, let's keep dragging it to the next release (**1.8.4**) :smile:

**Comment by brunob** [comment]
FTR, etherpad 1.8.5 on debian stretch with mongodb 3.2.11 cf 

```
apt policy mongodb
mongodb:
  Installé : 1:3.2.11-2+deb9u2
  Candidat : 1:3.2.11-2+deb9u2
 Table de version :
 *** 1:3.2.11-2+deb9u2 990
        990 http://security.debian.org stretch/updates/main amd64 Packages
```

...is  still getting the error pointed in https://github.com/ether/ueberDB/issues/109 and it can be fixed by `npm install mongodb@2.2.28`.

Maybe this one should be reopened ?

**Comment by JohnMcLear** [comment]
Didn't we drop mongo support?

**Comment by brunob** [comment]
Can't find any word about this drop in the repo, but "recent" mentions about mongo here https://github.com/ether/etherpad-lite/issues/3672#issuecomment-559952316 & https://github.com/ether/etherpad-lite/issues/3353#issuecomment-378238058

**Comment by brunob** [comment]
Hi again, since version 1.8.8 of etherpad we can't use mongodb. First i got an error pointing that : 

```[2021-03-03 20:17:57.345] [ERROR] server - Error: You must specify a mongodb database
    at new exports.Database (/opt/etherpad/master/src/node_modules/ueberdb2/databases/mongodb_db.js:22:36)
    at exports.Database.init (/opt/etherpad/master/src/node_modules/ueberdb2/index.js:66:14)
    at Promise (/opt/etherpad/master/src/node/db/DB.js:43:6)
    at new Promise (<anonymous>)
    at Object.exports.init (/opt/etherpad/master/src/node/db/DB.js:42:34)
    at Object.exports.start (/opt/etherpad/master/src/node/server.js:139:14)
    at Object.<anonymous> (/opt/etherpad/master/src/node/server.js:266:38)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
[2021-03-03 20:17:57.345] [INFO] server - Exiting...
```

So i've updated our settings.json to add `"url": "mongodb://localhost:27017",` in `dbSettings` field, and now i get :

```
[2021-03-03 20:20:58.641] [INFO] console - Your Etherpad version is 1.8.11 (ad84c8a)
[2021-03-03 20:21:00.018] [ERROR] server - MongoError: $not cannot have a regex
    at Connection.<anonymous> (/opt/etherpad/master/src/node_modules/mongodb/lib/core/connection/pool.js:451:61)
    at Connection.emit (events.js:198:13)
    at Connection.EventEmitter.emit (domain.js:448:20)
    at processMessage (/opt/etherpad/master/src/node_modules/mongodb/lib/core/connection/connection.js:451:10)
    at Socket.<anonymous> (/opt/etherpad/master/src/node_modules/mongodb/lib/core/connection/connection.js:620:15)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
[2021-03-03 20:21:00.021] [INFO] server - Exiting...
```
Mongo version is : 

```
apt policy mongodb
mongodb:
  Installé : 1:3.2.11-2+deb9u2
  Candidat : 1:3.2.11-2+deb9u2
 Table de version :
 *** 1:3.2.11-2+deb9u2 990
        990 http://security.debian.org stretch/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1:3.2.11-2+deb9u1 990
        990 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
```

And i've tested with npm package mongodb on v2.2.28 and @latest which is mongodb@3.6.4.

Should we forget to use mongodb with etherpad or are we missing something ?

**Comment by JohnMcLear** [comment]
If you have a problem with mongodb please see the ueberdb repo GitHub issues.  Afaik we have ci for mongo so it should work fine.

Please see ueberdb repository.

**Comment by brunob** [comment]
thx @JohnMcLear i'll post on ueberdb repo, for sure i've already searched in the issues of this repo ;)
