### ISSUE TITLE
Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by rasos** [ether/etherpad-lite#3687]
Running etherpad for ages, tried an update from 1.6.3 to 1.8 master, upgraded node from v6.17.1 to v12.14.0 LTS, updated dependencies with `bin/run.sh` - getting the same error - even after a fresh install (with existing DB):

```
TypeError: ejs:67
    65|             <ul class="menu_left" role="toolbar">
    66|                 <% e.begin_block("editbarMenuLeft"); %>
 >> 67|                 <%- toolbar.menu(settings.toolbar.left, isReadOnly) %>
    68|                 <% e.end_block(); %>
    69|             </ul>
    70|             <ul class="menu_right" role="toolbar">

Cannot read property 'constructor' of undefined
    at Function.Button.load (/opt/etherpad-lite/src/node/utils/toolbar.js:93:14)
    at /opt/etherpad-lite/src/node/utils/toolbar.js:60:31
    at Function._.each._.forEach (/opt/etherpad-lite/src/node_modules/underscore/underscore.js:153:9)
    at Function.ButtonsGroup.fromArray (/opt/etherpad-lite/src/node/utils/toolbar.js:59:5)
    at /opt/etherpad-lite/src/node/utils/toolbar.js:261:27
    at Function._.map._.collect (/opt/etherpad-lite/src/node_modules/underscore/underscore.js:172:24)
    at Object.menu (/opt/etherpad-lite/src/node/utils/toolbar.js:260:20)
    at eval (eval at compile (/opt/etherpad-lite/src/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:55:25)
    at returnedFn (/opt/etherpad-lite/src/node_modules/ejs/lib/ejs.js:653:17)
    at Object.exports.render (/opt/etherpad-lite/src/node_modules/ejs/lib/ejs.js:416:37)
```

Reverted back to EP 1.6.3, keeping node v12.14.0, works fine.

**Comment by muxator** [comment]
Hi @rasos, is the `toolbar` section of settings.json customized (i.e., uncommented)?

**Comment by rasos** [comment]
Hi @muxator, yes, we have a customized toolbar section with `["addImage"]` added (for the `ep_images_upload` plugin): 

```
  "toolbar": {
    "left": [
      ["bold", "italic", "underline", "strikethrough"],
      ["orderedlist", "unorderedlist", "indent", "outdent"],
      ["undo", "redo"],
      ["clearauthorship"], 
      ["addImage"]
    ],
    "right": [
      ["importexport", "timeslider", "savedrevision"],
      ["settings", "embed"],
      ["showusers"]
    ],
    "timeslider": [
      ["timeslider_export", "timeslider_returnToPad"]
    ]
  },
```

**Comment by rasos** [comment]
Moving `addImage` to another, existing field fixed it:

```
  "toolbar": {
    "left": [
      ["bold", "italic", "underline", "strikethrough"],
      ["orderedlist", "unorderedlist", "indent", "outdent"],
      ["undo", "redo"],
      ["clearauthorship", "addImage"]
    ],
    "right": [
      ["importexport", "timeslider", "savedrevision"],
      ["settings", "embed"],
      ["showusers"]
    ],
    "timeslider": [
      ["timeslider_export", "timeslider_returnToPad"]
    ]
  },
```
