### ISSUE TITLE
Importing a file can crash the instance

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3705]
https://github.com/ether/etherpad-lite/blob/bb868beb9cf636180f31227c823eb261108ca23e/src/node/handler/ImportHandler.js#L86

If import fails ( I can't replicate ) it can crash the instance.  I have had 5 cases of this happening today after nothing for a long time.  It's in latest but not previous versions.

It's caused by the conversion to async.

```
[2020-03-09 17:11:18.136] [WARN] console - Uploading Error: Error: Request aborted
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: at IncomingMessage.<anonymous> (/home/etherpad-lite/src/node_modules/formidable/lib/incoming
_form.js:122:19)
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: at IncomingMessage.emit (events.js:305:20)
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: at IncomingMessage.EventEmitter.emit (domain.js:483:12)
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: at abortIncoming (_http_server.js:526:9)
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: at socketOnClose (_http_server.js:519:3)
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: at TLSSocket.emit (events.js:317:22)
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: at TLSSocket.EventEmitter.emit (domain.js:483:12)
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: at net.js:667:12
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: at Socket.done (_tls_wrap.js:491:7)
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: at Object.onceWrapper (events.js:412:26)
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: [2020-03-09 17:11:18.139] [ERROR] console - TypeError: Cannot read property 'path' of undefi
ned
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: at /home/etherpad-lite/src/node/handler/ImportHandler.js:86:26
Mar 09 17:11:18 etherpad.coronaresponse.who.int run.sh[41760]: at IncomingForm.<anonymous> (/home/etherpad-lite/src/node_modules/formidable/lib/incoming_fo
rm.js:104:9)
```

For now I monkey patched with an ``if`` statement but I don't think that's good enough.

**Comment by muxator** [comment]
https://github.com/ether/etherpad-lite/blob/bb868beb9cf636180f31227c823eb261108ca23e/src/node/handler/ImportHandler.js#L79-L86

Sadly in js there is no null coalescing operator that I know ([there is in typescript](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining)).

We may have to add another if.

**Comment by JohnMcLear** [comment]
Closing this as I haven't been able to replicate
