### ISSUE TITLE
Abiword can still crash Etherpad

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3727]
```
Mar 13 15:13:11 EtherpadL systemd[1]: Stopping Run Etherpad-lite, the collaborative editor....
Mar 13 15:13:11 EtherpadL run.sh[7622]: [2020-03-13 20:13:11.896] [ERROR] console - SIGTERM
Mar 13 15:13:11 EtherpadL run.sh[7622]: [2020-03-13 20:13:11.903] [ERROR] console - TypeError: stdoutCallback is not a function
Mar 13 15:13:11 EtherpadL run.sh[7622]: at ChildProcess.<anonymous> (/home/etherpad-lite/src/node/utils/Abiword.js:97:7)
Mar 13 15:13:11 EtherpadL run.sh[7622]: at ChildProcess.emit (events.js:315:20)
Mar 13 15:13:11 EtherpadL run.sh[7622]: at ChildProcess.EventEmitter.emit (domain.js:485:12)
Mar 13 15:13:11 EtherpadL run.sh[7622]: at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
Mar 13 15:13:11 EtherpadL systemd[1]: Stopped Run Etherpad-lite, the collaborative editor..
Mar 13 15:13:11 EtherpadL systemd[1]: Started Run Etherpad-lite, the collaborative editor..
```

In this instance I was able to see that Abiword was not " properly" installed by running

```
abiword --to=html test.pdf
```

The HTML created had a load of garbage in.  Runnin the same command on a "good" server produced clean HTML.

This is an abiword issue but documenting here.  We should not allow any third party application to ever kill the Etherpad instance.

OS: CentOS 7.
Abiword: 3.0.2

**Comment by JohnMcLear** [comment]
Actually I think someone stopped Etherpad here..  Ignore thi sissue.
