### ISSUE TITLE
postgresql connection issues

### ISSUE THREAD

**Issue by jmaupetit** [ether/etherpad-lite#3751]
:wave: there!

I have troubles in connecting `etherpad` with postgresql using the official docker container. Here is a simple docker-compose file that you can use to reproduce the issue:

```yaml
# docker-compose.yml
version: "3.4"

services:

  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_DB: etherpad
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: pass

  etherpad:
    image: etherpad/etherpad:1.8.0
    ports:
      - "9001:9001"
    environment:
      DB_TYPE: postgres
      DB_NAME: etherpad
      DB_USER: foo
      DB_PASSWORD: pass
      DB_HOST: postgresql
      DB_PORT: 5432
    depends_on:
      - postgresql
```

Running the postgresql and then the etherpad service:

```
$ docker-compose up etherpad
```

Leads to the following stack trace:

```Attaching to etherpad_etherpad_1
etherpad_1    | [36m[2020-03-23 23:00:18.937] [DEBUG] console - [39mRunning on Node v10.17.0 (minimum required Node version: 8.9.0)
etherpad_1    | [32m[2020-03-23 23:00:19.086] [INFO] console - [39mAll relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad-lite
etherpad_1    | [36m[2020-03-23 23:00:19.087] [DEBUG] AbsolutePaths - [39mRelative path "settings.json" can be rewritten to "/opt/etherpad-lite/settings.json"
etherpad_1    | [36m[2020-03-23 23:00:19.087] [DEBUG] AbsolutePaths - [39mRelative path "credentials.json" can be rewritten to "/opt/etherpad-lite/credentials.json"
etherpad_1    | [32m[2020-03-23 23:00:19.094] [INFO] console - [39msettings loaded from: /opt/etherpad-lite/settings.json
etherpad_1    | [36m[2020-03-23 23:00:19.095] [DEBUG] console - [39mEnvironment variable "TITLE" not found for configuration key "title". Falling back to default value.
etherpad_1    | [36m[2020-03-23 23:00:19.095] [DEBUG] console - [39mEnvironment variable "FAVICON" not found for configuration key "favicon". Falling back to default value.
etherpad_1    | [36m[2020-03-23 23:00:19.095] [DEBUG] console - [39mEnvironment variable "SKIN_NAME" not found for configuration key "skinName". Falling back to default value.
etherpad_1    | [36m[2020-03-23 23:00:19.095] [DEBUG] console - [39mEnvironment variable "IP" not found for configuration key "ip". Falling back to default value.
etherpad_1    | [36m[2020-03-23 23:00:19.095] [DEBUG] console - [39mEnvironment variable "PORT" not found for configuration key "port". Falling back to default value.
etherpad_1    | [36m[2020-03-23 23:00:19.095] [DEBUG] console - [39mEnvironment variable "SHOW_SETTINGS_IN_ADMIN_PAGE" not found for configuration key "showSettingsInAdminPage". Falling back to default value.
etherpad_1    | [36m[2020-03-23 23:00:19.095] [DEBUG] console - [39mConfiguration key "dbType" will be read from environment variable "DB_TYPE"
etherpad_1    | [36m[2020-03-23 23:00:19.095] [DEBUG] console - [39mConfiguration key "host" will be read from environment variable "DB_HOST"
etherpad_1    | [36m[2020-03-23 23:00:19.095] [DEBUG] console - [39mConfiguration key "port" will be read from environment variable "DB_PORT"
etherpad_1    | [36m[2020-03-23 23:00:19.095] [DEBUG] console - [39mConfiguration key "database" will be read from environment variable "DB_NAME"
etherpad_1    | [36m[2020-03-23 23:00:19.095] [DEBUG] console - [39mConfiguration key "user" will be read from environment variable "DB_USER"
etherpad_1    | [33m[2020-03-23 23:00:19.096] [WARN] console - [39mEnvironment variable "DB_PASS" does not contain any value for configuration key "password", and no default was given. Returning null. Please check your configuration and environment settings.
etherpad_1    | [33m[2020-03-23 23:00:19.096] [WARN] console - [39mEnvironment variable "DB_CHARSET" does not contain any value for configuration key "charset", and no default was given. Returning null. Please check your configuration and environment settings.
etherpad_1    | [36m[2020-03-23 23:00:19.096] [DEBUG] console - [39mEnvironment variable "DB_FILENAME" not found for configuration key "filename". Falling back to default value.
etherpad_1    | [36m[2020-03-23 23:00:19.096] [DEBUG] console - [39mEnvironment variable "TRUST_PROXY" not found for configuration key "trustProxy". Falling back to default value.
etherpad_1    | [33m[2020-03-23 23:00:19.096] [WARN] console - [39mEnvironment variable "ADMIN_PASSWORD" does not contain any value for configuration key "password", and no default was given. Returning null. Please check your configuration and environment settings.
etherpad_1    | [33m[2020-03-23 23:00:19.096] [WARN] console - [39mEnvironment variable "USER_PASSWORD" does not contain any value for configuration key "password", and no default was given. Returning null. Please check your configuration and environment settings.
etherpad_1    | [36m[2020-03-23 23:00:19.096] [DEBUG] console - [39mEnvironment variable "LOGLEVEL" not found for configuration key "loglevel". Falling back to default value.
etherpad_1    | [32m[2020-03-23 23:00:19.096] [INFO] console - [39mNo credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
etherpad_1    | [32m[2020-03-23 23:00:19.097] [INFO] console - [39mUsing skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
etherpad_1    | [33m[2020-03-23 23:00:19.097] [WARN] console - [39mRemoving user "admin", because its password is null.
etherpad_1    | [33m[2020-03-23 23:00:19.097] [WARN] console - [39mRemoving user "user", because its password is null.
etherpad_1    | [32m[2020-03-23 23:00:19.098] [INFO] console - [39mSession key loaded from: /opt/etherpad-lite/SESSIONKEY.txt
etherpad_1    | events.js:174
etherpad_1    |       throw er; // Unhandled 'error' event
etherpad_1    |       ^
etherpad_1    | 
etherpad_1    | error: password authentication failed for user "foo"
etherpad_1    |     at Connection.parseE (/opt/etherpad-lite/src/node_modules/pg/lib/connection.js:569:11)
etherpad_1    |     at Connection.parseMessage (/opt/etherpad-lite/src/node_modules/pg/lib/connection.js:396:17)
etherpad_1    |     at Socket.<anonymous> (/opt/etherpad-lite/src/node_modules/pg/lib/connection.js:132:22)
etherpad_1    |     at Socket.emit (events.js:198:13)
etherpad_1    |     at Socket.EventEmitter.emit (domain.js:448:20)
etherpad_1    |     at addChunk (_stream_readable.js:287:12)
etherpad_1    |     at readableAddChunk (_stream_readable.js:268:11)
etherpad_1    |     at Socket.Readable.push (_stream_readable.js:223:10)
etherpad_1    |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
etherpad_1    | Emitted 'error' event at:
etherpad_1    |     at Connection.<anonymous> (/opt/etherpad-lite/src/node_modules/pg/lib/client.js:183:19)
etherpad_1    |     at Connection.emit (events.js:198:13)
etherpad_1    |     at Connection.EventEmitter.emit (domain.js:448:20)
etherpad_1    |     at Socket.<anonymous> (/opt/etherpad-lite/src/node_modules/pg/lib/connection.js:136:12)
etherpad_1    |     at Socket.emit (events.js:198:13)
etherpad_1    |     [... lines matching original stack trace ...]
etherpad_1    |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
etherpad_etherpad_1 exited with code 1
```

Any idea why? Is ueberDB broken in some way? Which type of database would you recommend?

Thank you for your amazing work on this project :muscle: :pray: :heart:

**Comment by muxator** [comment]
Hi,

I do not have time right now to execute your whole setup, but this log line strikes me:

```
[...] [WARN] console - Environment variable "DB_PASS" does not contain any value for configuration key "password", and no default was given. Returning null. Please check your configuration and environment settings.
```


Is it possible that for some reason the `$DB_PASS` environment variable is not being passed at startup to the Docker container?

On the other side, from this log we know that you are successfully managing to pass a username via `$DB_USER`:

```
etherpad_1    | error: password authentication failed for user "foo"
```

**Comment by jmaupetit** [comment]
Good catch! I've used `DB_PASSWORD` environment variable instead of `DB_PASS` :sweat_smile: 

Thank you for your help and sorry for the noise...
