### ISSUE TITLE
aborted uploads crash instance?

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3825]
```
 13:06:36  [2020-04-02 13:06:36.044] [WARN] console - Uploading Error: Error: Request aborted
 13:06:36  at IncomingMessage.<anonymous> (/home/etherpad-lite/src/node_modules/formidable/lib/incoming_form.js:122:19)
 13:06:36  at IncomingMessage.emit (events.js:315:20)
 13:06:36  at IncomingMessage.EventEmitter.emit (domain.js:485:12)
 13:06:36  at abortIncoming (_http_server.js:536:9)
 13:06:36  at socketOnClose (_http_server.js:529:3)
 13:06:36  at TLSSocket.emit (events.js:327:22)
 13:06:36  at TLSSocket.EventEmitter.emit (domain.js:485:12)
 13:06:36  at net.js:674:12
 13:06:36  at Socket.done (_tls_wrap.js:563:7)
 13:06:36  at Object.onceWrapper (events.js:422:26)
 13:06:36  at Socket.emit (events.js:315:20)
 13:06:36  at Socket.EventEmitter.emit (domain.js:485:12)
 13:06:36  at TCP.<anonymous> (net.js:674:12)
 13:06:36  [2020-04-02 13:06:36.044] [ERROR] console - TypeError: Cannot read property 'path' of undefined
 13:06:36  at /home/etherpad-lite/src/node/handler/ImportHandler.js:86:26 <-- 
 13:06:36  at IncomingForm.<anonymous> (/home/etherpad-lite/src/node_modules/formidable/lib/incoming_form.js:104:9)
 13:06:36  at IncomingForm.emit (events.js:315:20)
 13:06:36  at IncomingForm.EventEmitter.emit (domain.js:485:12)
 13:06:36  at IncomingForm._error (/home/etherpad-lite/src/node_modules/formidable/lib/incoming_form.js:298:8)
 13:06:36  at IncomingMessage.<anonymous> (/home/etherpad-lite/src/node_modules/formidable/lib/incoming_form.js:122:12)
 13:06:36  at IncomingMessage.emit (events.js:315:20)
 13:06:36  at IncomingMessage.EventEmitter.emit (domain.js:485:12)
 13:06:36  at abortIncoming (_http_server.js:536:9)
 13:06:36  at socketOnClose (_http_server.js:529:3)
 13:06:36  at TLSSocket.emit (events.js:327:22)
 13:06:36  at TLSSocket.EventEmitter.emit (domain.js:485:12)
 13:06:36  at net.js:674:12
 13:06:36  at Socket.done (_tls_wrap.js:563:7)
 13:06:36  at Object.onceWrapper (events.js:422:26)
 13:06:36  at Socket.emit (events.js:315:20)
 13:06:39 systemd[1]: etherpad.service: main process exited, code=exited, status=1/FAILURE
```
Develop branch 03 04 2020
CentOS 7?
Using ``soffice``

**Comment by JohnMcLear** [comment]
I can simluate this crash with this command 

```
curl -X POST --data-binary @/usr/bin/aria_chk http://192.168.1.51:9001/p/MTCmR87COvkFbRsKjYdG/import
```

**Comment by JohnMcLear** [comment]
Fixed with https://github.com/ether/etherpad-lite/pull/3828
