### ISSUE TITLE
Error: listen EACCES: permission denied 5.5.5.5:443

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3856]
Hello everyone. I managed to configure https for the etherpad - for this it was necessary to register the necessary parameter in the settings.json and specify the working keys of the certificate. The server worked as it should.

The problem arose when I wanted to get rid of port 9001 by setting port 443 for https in the settings.json. But here I got a mistake.

```
...
Started Etherpad...
[2020-04-12 18:56:21.765] [DEBUG] console - Running on Node v12.16.2 (minimum required Node version: 10.13.0)
[2020-04-12 18:56:21.945] [INFO] console - All relative paths will be interpreted relative to the identified Etherpad base dir: /home/spexfy/public_html
[2020-04-12 18:56:21.946] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/home/spexfy/public_html/settings.json"
[2020-04-12 18:56:21.946] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/home/spexfy/public_html/credentials.json"
[2020-04-12 18:56:21.955] [INFO] console - settings loaded from: /home/spexfy/public_html/settings.json
[2020-04-12 18:56:21.957] [INFO] console - credentials loaded from: /home/spexfy/public_html/credentials.json
[2020-04-12 18:56:21.958] [INFO] console - Using skin "colibris" in dir: /home/spexfy/public_html/src/static/skins/colibris
[2020-04-12 18:56:21.959] [INFO] console - Session key loaded from: /home/spexfy/public_html/SESSIONKEY.txt
[2020-04-12 18:56:21.959] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production. File location: /home/spexfy/public_html/var/dirty.db
[2020-04-12 18:56:23.032] [INFO] APIHandler - Api key file read from: "/home/spexfy/public_html/APIKEY.txt"
[2020-04-12 18:56:23.370] [INFO] console - Installed plugins: 
[2020-04-12 18:56:23.371] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2020-04-12 18:56:23.372] [INFO] console - Your Etherpad version is 1.8.0 (83d72d2)
[2020-04-12 18:56:23.374] [INFO] console - SSL -- enabled
[2020-04-12 18:56:23.374] [INFO] console - SSL -- server key file: /home/spexfy/ssl.key
[2020-04-12 18:56:23.374] [INFO] console - SSL -- Certificate Authority's certificate file: /home/spexfy/ssl.cert
[2020-04-12 18:56:23.472] [INFO] console - You can access your Etherpad instance at http://5.5.5.5:443/
[2020-04-12 18:56:23.472] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
[2020-04-12 18:56:23.472] [WARN] console - Etherpad is running in Development mode.  This mode is slower for users and less secure than production mode.  You should set the NODE_ENV environment variable to production by using: export NODE_ENV=production
[2020-04-12 18:56:25.009] [ERROR] console - Error: listen EACCES: permission denied 5.5.5.5:443
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at doListen (net.js:1500:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[2020-04-12 18:56:25.010] [INFO] console - graceful shutdown...
[2020-04-12 18:56:25.011] [INFO] console - db sucessfully closed.
```

My credentials.json
```
{
  "ip": "5.5.5.5",
  "port": 443,
  "ssl": {
    "key": "/home/spexfy/ssl.key",
    "cert": "/home/spexfy/ssl.cert",
    "ca": ["/home/spexfy/ssl.ca"]
  }
}
```

My nginx.conf
```
server {
	server_name spexfy.xx www.spexfy.xx;
    
	listen 5.5.5.5;
    
	root /home/spexfy/public_html;
    
	index index.html index.php;
    
	access_log /var/log/virtualmin/spexfy.xx_access_log;
	error_log /var/log/virtualmin/spexfy.xx_error_log;
    
	fastcgi_param GATEWAY_INTERFACE CGI/1.1;
	fastcgi_param SERVER_SOFTWARE nginx;
	fastcgi_param QUERY_STRING $query_string;
	fastcgi_param REQUEST_METHOD $request_method;
	fastcgi_param CONTENT_TYPE $content_type;
	fastcgi_param CONTENT_LENGTH $content_length;
	fastcgi_param SCRIPT_FILENAME /home/spexfy/public_html$fastcgi_script_name;
	fastcgi_param SCRIPT_NAME $fastcgi_script_name;
	fastcgi_param REQUEST_URI $request_uri;
	fastcgi_param DOCUMENT_URI $document_uri;
	fastcgi_param DOCUMENT_ROOT /home/spexfy/public_html;
	fastcgi_param SERVER_PROTOCOL $server_protocol;
	fastcgi_param REMOTE_ADDR $remote_addr;
	fastcgi_param REMOTE_PORT $remote_port;
	fastcgi_param SERVER_ADDR $server_addr;
	fastcgi_param SERVER_PORT $server_port;
	fastcgi_param SERVER_NAME $server_name;
	fastcgi_param HTTPS $https;
    
	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_pass unix:/var/php-nginx/15863561136474.sock/socket;
	}
    
    # 301 redirect (http -> https)
    if ($server_port = 80) {
    	rewrite ^/(.*) https://$server_name/$1 permanent;
    }
    
    # 301 redirect (www -> non-www)
    if ($http_host ~* "^www\.(.+)$") {
    	rewrite ^/(.*) https://$server_name/$1 permanent;
    }
    
	listen 5.5.5.5:443 default ssl;
    
	ssl_certificate /home/spexfy/ssl.combined;
	ssl_certificate_key /home/spexfy/ssl.key;
}
```

Server Ubuntu 18.04.4 LTS

Please help solve 2 questions (The wiki article did not help me):
- How to get rid of the port at the end of the domain? https://domain.com:9001/ -> https://domain.com/
- How to remove the parameter "/p/" in URL when viewing a pad? https://domain.com:9001/p/newpad -> https://domain.com:9001/newpad

Thanks!

**Comment by JohnMcLear** [comment]
Unless I'm misunderstanding..  

You would leave Etherpad on 9001 and only expose it to the local IP address (127.0.0.1)

And you would only allow 443 (maybe 80 redirect to 443) in nginx.

You wouldn't have SSL certs in both nginx and etherpad, I don't think?????   Maybe SSL pinning?  I don't usually do that anyway...

**Comment by alekso87** [comment]
> Unless I'm misunderstanding..
> 
> You would leave Etherpad on 9001 and only expose it to the local IP address (127.0.0.1)
> 
> And you would only allow 443 (maybe 80 redirect to 443) in nginx.
> 
> You wouldn't have SSL certs in both nginx and etherpad, I don't think????? Maybe SSL pinning? I don't usually do that anyway...

I understood you. Thanks!

**Comment by Plaintive12** [comment]
> > Unless I'm misunderstanding..
> > You would leave Etherpad on 9001 and only expose it to the local IP address (127.0.0.1)
> > And you would only allow 443 (maybe 80 redirect to 443) in nginx.
> > You wouldn't have SSL certs in both nginx and etherpad, I don't think????? Maybe SSL pinning? I don't usually do that anyway...
> 
> I understood you. Thanks!





https://defaultdict-faisal.github.io/dwgpa6TJJDMPjYVvEqhOZ0YF7at/
