### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by aboettger-tuhh** [ether/etherpad-lite#3916]
Version 1.8.0

```
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d | [2020-04-21 13:02:47.813] [ERROR] console - Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x90\xB1\xE2\x80...' for column `foobar`.`store`.`value` at row 1
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at Query.Sequence._packetToError (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at Query.ErrorPacket (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at Protocol._parsePacket (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:279:23)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at Parser.write (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/Parser.js:76:12)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at Protocol.write (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:39:16)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at Socket.<anonymous> (/opt/etherpad-lite/src/node_modules/mysql/lib/Connection.js:103:28)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at Socket.emit (events.js:198:13)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at Socket.EventEmitter.emit (domain.js:448:20)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at addChunk (_stream_readable.js:288:12)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at readableAddChunk (_stream_readable.js:269:11)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     --------------------
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at Protocol._enqueue (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:145:48)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at Connection.query (/opt/etherpad-lite/src/node_modules/mysql/lib/Connection.js:208:25)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at /opt/etherpad-lite/src/node_modules/ueberdb2/mysql_db.js:214:18
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at /opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:462:21
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at /opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:194:13
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at /opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:97:13
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at Array.forEach (<anonymous>)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at _forEach (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:26:24)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at async.forEach (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:96:9)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d |     at _asyncMap (/opt/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:193:9)
Apr 21 15:02:47 laurana docker-compose[19539]: app_1_291a1583a34d | [2020-04-21 13:02:47.813] [INFO] console - graceful shutdown...
```

**Comment by muxator** [comment]
This specific error seems very low level, almost at the level of the mysql driver.

I'd definitely suggest to either upgrade to the current development branch, or wait a few days and update to **1.8.3**. There will be a lot of improvements, especially regarding mysql.

**Comment by JohnMcLear** [comment]
@aboettger-tuhh I'm gonna close this as it's not an Etherpad issue or so it seems but please if it persists or we can help further please do comment and we will be happy to help you out!
