### ISSUE TITLE
Possibility of a new formidable crash

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4009]
Not sure on steps to replicate.
```
[WARN] console - Uploading Error: Error: Request aborted
run.sh[43238]: at IncomingMessage.<anonymous> (/home/etherpad-lite/src/node_modules/formidable/lib/incoming_form.js:122:19)
run.sh[43238]: at IncomingMessage.emit (events.js:315:20)
run.sh[43238]: at IncomingMessage.EventEmitter.emit (domain.js:485:12)
...
run.sh[43238]: [2020-05-14 17:45:18.692] [ERROR] console - Error **[ERR_STREAM_DESTROYED]**: Cannot call write after a stream was destroyed
May 14 17:45:18 EtherpadL run.sh[43238]: at WriteStream._write (internal/fs/streams.js:417:33)
May 14 17:45:18 EtherpadL run.sh[43238]: at WriteStream.<anonymous> (internal/fs/streams.js:413:12)
```

**Comment by JohnMcLear** [comment]
Proposed fix here: https://github.com/node-formidable/formidable/issues/469

**Comment by JohnMcLear** [comment]
Okay so it looks like it "could" be a thing, to test..  Start uploading a large file (I have 600mb internet here so it has to be fucking huge).  After 500ms, abort it, in theory this error should throw..  

~Tomorrow I will write some test coverage/scripts then apply some patches to fix.

**Comment by JohnMcLear** [comment]
```
curl -vs -F'thefile=@test.txt' -H'Content-Length: 300' -m 2 http://httpbin.org/anything
```
Props to @tomnomnom https://twitter.com/TomNomNom/status/1261441448387411968

Will try this 2mrw and see if I can get it to fail

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/pull/4018 ready for test/merge
