### ISSUE TITLE
Redis TLS support

### ISSUE THREAD

**Issue by Bengrunt** [ether/etherpad-lite#4044]
Hello there,

Is redis connection over TLS supported ?

Seems like redis node library used in ueberDB should support `rediss://` URLs but I don't know how I can set it up in the etherpad configuration. Is it with the `client_options` parameter?

It seems like it cannot be set natively with the official docker image anyway, that's in the image settings.json file:
```
  "dbType": "${DB_TYPE:dirty}",
  "dbSettings": {
    "host":     "${DB_HOST}",
    "port":     "${DB_PORT}",
    "database": "${DB_NAME}",
    "user":     "${DB_USER}",
    "password": "${DB_PASS}",
    "charset":  "${DB_CHARSET}",
    "filename": "${DB_FILENAME:var/dirty.db}"
  },
```

Thanks for the help.

**Comment by JohnMcLear** [comment]
No idea about docker but it should be in hostname value no?

**Comment by JohnMcLear** [comment]
Ah wait no it's the URL value.  Lemme see if we poss that through ueberdb

**Comment by JohnMcLear** [comment]
Yeh we do just set the URL value.

**Comment by Bengrunt** [comment]
> 
> 
> No idea about docker but it should be in hostname value no?

If I set the `rediss://` prefix in the `host` field of db_settings I get a DNS lookup error, which makes sense.

>
>
> Yeh we do just set the url value.

That's what I thought but it's not exposed as an environment variable in the official docker image. I guess it should work as is on a classic installation?

**Comment by JohnMcLear** [comment]
Try it on classic and see :)

**Comment by BaptisteLotigier** [comment]
I was able to run etherpad and redis with TLS activated on the redis database.
I looked on how the node package for redis handle a TLS connection [here](https://github.com/NodeRedis/node-redis/blob/master/lib/createClient.js) and it seems that we can pass the url in the port argument.

So I put `rediss://redis-url:6379` in the DB_PORT environment variable and was able to properly connect to the database.

Also, if you set the value of both DB_PORT and DB_HOST when you try to use a TLS connection, etherpad will throw an exception saying : 
```
[2020-05-28 13:10:33.188] [ERROR] console - exception thrown: Cannot create property 'tls' on string 'redis-etherpad'
[2020-05-28 13:10:33.188] [INFO] console - TypeError: Cannot create property 'tls' on string 'redis-etherpad'
    at createClient (/opt/etherpad-lite/src/node_modules/redis/lib/createClient.js:36:33)
    at Object.exports.createClient (/opt/etherpad-lite/src/node_modules/redis/index.js:1022:41)
    at exports.database.init (/opt/etherpad-lite/src/node_modules/ueberdb2/redis_db.js:54:25)
    at exports.database.init (/opt/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:115:18)
    at exports.database.init (/opt/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:47:11)
    at Promise (/opt/etherpad-lite/src/node/db/DB.js:42:8)
    at new Promise (<anonymous>)
    at Object.exports.init (/opt/etherpad-lite/src/node/db/DB.js:41:10)
    at EventEmitter.<anonymous> (/opt/etherpad-lite/src/node/server.js:62:6)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
So be sure to not set DB_HOST if you plan to use a TLS connection.

**Comment by JohnMcLear** [comment]
Awesome tnx for documenting here.  Can you also please document this at https://github.com/ether/ueberDB/blob/dirtyref/README.md

We're hoping  to move over to that branch soon and I want it to be up to date w/ all the quirks :)

**Comment by MatheoAtche** [comment]
I worked with @BaptisteLotigier on this issue and opened a PR [here](https://github.com/ether/ueberDB/pull/132) to document it. Hoping it is clear enough.

**Comment by JohnMcLear** [comment]
Waiting on @muxator for how to merge dirtyref branch into ueberdb.  It's a big job for him to review so will give him some time :)

**Comment by JohnMcLear** [comment]
Landed.
