### ISSUE TITLE
Can't apply USER_CHANGES, because Trying to submit changes as another author in changeset 

### ISSUE THREAD

**Issue by jinbullsushil** [ether/etherpad-lite#4104]
I am trying to open the project then got the error message and pad disconnected.
Error: Can't apply USER_CHANGES, because Trying to submit changes as another author in changeset Z:2sk>0|f=2r8*0*1=b|1=1*0*2=b|1=1*0*1=b|1=1*0=b$
    at \node_modules\ep_etherpad-lite\node\handler\PadMessageHandler.js:708:25
    at \node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:610:21
    at \node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:249:17
    at iterate (\node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:149:13)
    at \node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:160:25
    at \node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:251:21
    at \node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:615:34
    at \node_modules\ep_etherpad-lite\node\handler\PadMessageHandler.js:658:9
    at Object.exports.getPad (\node_modules\ep_etherpad-lite\node\db\PadManager.js:161:5)
    at \node_modules\ep_etherpad-lite\node\handler\PadMessageHandler.js:654:18

**Comment by JohnMcLear** [comment]
https://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/

Any details would be useful.  URL.  Etherpad version etc.

**Comment by webzwo0i** [comment]
reopening this. I'm seeing this not very often, but it happens.
On one pad the first author copied a lot of text with formatting and lists and had no more activity. Then, after 1000+ revisions another author copied something into one of those lists (the line text was empty and it was a bullet list). The changeset was logged as coming from the first (inactive) author.

Looking at the changeset (multiple ops with new lines) I think we are in a list, too. Interesting is also that no character is added, so probably only attributes are changing.

I believe I've already seen a issue with this, so maybe it's already fixed in recent releases. I just don't want to forget about it

**Comment by rhansen** [comment]
This reminded me of this: https://github.com/ether/etherpad-lite/commit/462530eafb6116b490177ff3b7f6a7f2ce7cbe74
Maybe it's related?

**Comment by webzwo0i** [comment]
Possible yeah, good hint. Still can't replicate with a version before those commits. I have some of those errors in my log, dating back years ago. Let's see if new errors happen with the recent patches.

All of the errors contain `*0` (attribute 0, normally the first author) and nearly all of them (not all, though) happened in a short period after updating to 1.8.4 (we skipped a lot of versions, I think the update was 1.6.6 with some custom patches -> 1.8.4).

Maybe it helps if we at least log the navigator/browser in case of those errors (and the revision the CS wants to apply to - as this speeds up debugging a little bit). Will try to better understand the patches, if they can lead to introduce a false author/0 or that the old author is left in a line. However, due to all of the changesets having author 0, I think it's unlikely that the bug is "the old author of a line is not replaced by the new author", because odds are high that the old author is not always 0)
