### ISSUE TITLE
API method padUsers on fresh restart causes error

### ISSUE THREAD

**Issue by mir123** [ether/etherpad-lite#4120]
Calling the API method padUsers for an open pad right after restart (pad is open upon restart) causes a server error. Closing or reloading the pad fixes the problem. Same method on other pads and other methods on the same pad (padUsersCount, getReadOnlyID) run ok.

**Etherpad version:**
1.8.4

**Request URL:**
`https://mysite.today:9001/api/1.2.13/padUsers?apikey=<APIKEY>&padID=g.RAdNdf7vAEJjpCbX%2415-06-2020`

**Response:**
`{"code":2,"message":"createHTTPError.InternalError is not a constructor","data":null}`

**Log:**
```
Jun 16 18:59:37 mysite node[20892]: #033[36m[2020-06-16 18:59:37.399] [DEBUG] SessionStore - #033[39mGET eoedM83lnE1qqgvqqAZZPneapvCW4Kx5d
Jun 16 18:59:37 mysite node[20892]: #033[36m[2020-06-16 18:59:37.400] [DEBUG] ueberDB - #033[39mGET    - sessionstorage:eoedM83lnE1qqgvqqAZZPneapvCW4Kx5d - {"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true,"secure":true}} - from cache
Jun 16 18:59:37 mysite node[20892]: #033[32m[2020-06-16 18:59:37.403] [INFO] API - #033[39mREQUEST, v1.2.13:padUsers, {"apikey":"<APIKEY>","padID":"g.RAdNdf7vAEJjpCbX$15-06-2020"}
Jun 16 18:59:37 mysite node[20892]: #033[36m[2020-06-16 18:59:37.404] [DEBUG] ueberDB - #033[39mGET    - pad:g.RAdNdf7vAEJjpCbX$15-06-2020 - {"atext":{"text":"Monday\n","attribs":"*0+6|1+1"},"pool":{"numToAttrib":{"0":["author","a.beJhEFzqw6zhEVKQ"]},"nextNum":1},"head":6,"chatHead":-1,"publicStatus":false,"passwordHash":null,"savedRevisions":[]} - from cache
Jun 16 18:59:37 mysite node[20892]: #033[36m[2020-06-16 18:59:37.404] [DEBUG] ueberDB - #033[39mGET    - globalAuthor:undefined - null - from cache
Jun 16 18:59:37 mysite node[20892]: #033[36m[2020-06-16 18:59:37.405] [DEBUG] ueberDB - #033[39mGET    - globalAuthor:undefined - null - from cache
Jun 16 18:59:37 mysite node[20892]: #033[31m[2020-06-16 18:59:37.405] [ERROR] API - #033[39mTypeError: Cannot set property 'id' of null
Jun 16 18:59:37 mysite node[20892]:     at authorManager.getAuthor.then.author (/home/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.js:1498:19)
Jun 16 18:59:37 mysite node[20892]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Jun 16 18:59:37 mysite node[20892]: TypeError: Cannot set property 'id' of null
Jun 16 18:59:37 mysite node[20892]:     at authorManager.getAuthor.then.author (/home/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.js:1498:19)
Jun 16 18:59:37 mysite node[20892]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Jun 16 18:59:37 mysite node[20892]: #033[36m[2020-06-16 18:59:37.406] [DEBUG] http - #033[39m500, GET /api/1.2.13/padUsers?apikey=<APIKEY>&padID=g.RAdNdf7vAEJjpCbX%2415-06-2020
```

**Comment by JohnMcLear** [comment]
Steps to replicate is ideal btw.  I will do it but making assumptions I',m doing it right.

1. Visit http://etherpad/p/foo
2. Type in "hello world"
3. Restart Etherpad server
4. Do ``curl http://etherpad/api/1.2.13/padUsers?apikey=<APIKEY>&padID=foo``

- [ ] I noticed that omitting padID doesn't error which it should

I can confirm the bug:

```
[2020-06-16 21:10:20.877] [INFO] API - REQUEST, v1.2.13:padUsers, {"apikey":"7c6","padID":"moon"}
[2020-06-16 21:10:20.880] [ERROR] API - TypeError: Cannot set property 'id' of null
    at authorManager.getAuthor.then.author (/home/jose/develop/src/node/handler/                                                                             PadMessageHandler.js:1499:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot set property 'id' of null
    at authorManager.getAuthor.then.author (/home/jose/develop/src/node/handler/                                                                             PadMessageHandler.js:1499:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```
