### ISSUE TITLE
etherpad crashes hard after upgrade: TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by devkral** [ether/etherpad-lite#4300]
After an upgrade to 1.8.5 etherpad fails often hard (without recovering) with an db error. I don't know exactly how to reproduce this error but I think having an editing user without name is enough.
I suspect one of these commits:
6c2a361935fdf3bfa6107781913881ba030f688f
2bf076043f6c4d49fdc18f4e3163390aacb8d314
or the upgrade of ueberdb2 to be the problem.

Affected Version: 1.8.5
Not affected: 1.8.4

Stacktrace
[ERROR] console - TypeError: Cannot read property 'name' of null
    at Client._handleParseComplete (/opt/etherpad-lite/src/node_modules/pg/lib/client.js:358:26)
    at Connection.emit (events.js:198:13)
    at Connection.EventEmitter.emit (domain.js:448:20)
    at parse (/opt/etherpad-lite/src/node_modules/pg/lib/connection.js:109:12)
    at Parser.parse (/opt/etherpad-lite/src/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.stream.on (/opt/etherpad-lite/src/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)

**Comment by devkral** [comment]
Maybe a check if .user is available would be enough. Does ueberdb2 understand ?.

**Comment by JohnMcLear** [comment]
Please use develop branch.  We are aware of this issue and it's been patched.  We need to release 1.8.6 which will include the fix.
