### ISSUE TITLE
Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

### ISSUE THREAD

**Issue by UnixFriend** [ether/etherpad-lite#4334]
Hello, I got this error when I'm trying to access etherpad at port 9001 via the browser. It exits immediatley.  Am I missing something?

Full log:
>Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
> wd@1.12.1 install /home/pi/etherpad-lite/src/node_modules/wd
> node scripts/build-browser-scripts
added 1127 packages in 41.911s
Clearing minified cache...
Starting Etherpad...
All relative paths will be interpreted relative to the identified Etherpad base dir: /home/pi/etherpad-lite
Random string used for versioning assets: 650daa0b
[2020-09-22 18:08:58.773] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/home/pi/etherpad-lite/settings.json"
[2020-09-22 18:08:58.777] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/home/pi/etherpad-lite/credentials.json"
settings loaded from: /home/pi/etherpad-lite/settings.json
No credentials file found in /home/pi/etherpad-lite/credentials.json. Ignoring.
[2020-09-22 18:08:58.856] [INFO] console - Using skin "colibris" in dir: /home/pi/etherpad-lite/src/static/skins/colibris
[2020-09-22 18:08:58.857] [INFO] console - Session key file "/home/pi/etherpad-lite/SESSIONKEY.txt" not found. Creating with random contents.
[2020-09-22 18:08:58.860] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production. File location: /home/pi/etherpad-lite/var/dirty.db
[2020-09-22 18:09:04.523] [INFO] APIHandler - Api key file "/home/pi/etherpad-lite/APIKEY.txt" not found. Creating with random contents.
[2020-09-22 18:09:05.183] [INFO] console - Installed plugins: 
[2020-09-22 18:09:05.195] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2020-09-22 18:09:05.197] [INFO] console - Your Etherpad version is 1.8.6 (299bd96)
[2020-09-22 18:09:06.047] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2020-09-22 18:09:06.048] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
[2020-09-22 18:09:06.049] [WARN] console - Etherpad is running in Development mode.  This mode is slower for users and less secure than production mode.  You should set the NODE_ENV environment variable to production by using: export NODE_ENV=production
Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
[2020-09-22 18:13:21.760] [ERROR] console - Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout.setTimeout [as _onTimeout] (/home/pi/etherpad-lite/src/node_modules/threads/dist/master/spawn.js:34:53)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2020-09-22 18:13:21.761] [INFO] console - graceful shutdown...
[2020-09-22 18:13:21.764] [INFO] console - db sucessfully closed.

**Comment by JohnMcLear** [comment]
What version of node?

**Comment by UnixFriend** [comment]
Version v10.22.1

**Comment by JohnMcLear** [comment]
I swear I saw a similar bug report recently.  I suggested to update Node and heard nothing back.  Please try update node and let me know.

**Comment by UnixFriend** [comment]
apt says it is the newest version. Should I update it manually?

**Comment by JohnMcLear** [comment]
yes

**Comment by UnixFriend** [comment]
Ok I updated node to version 12. Works now

**Comment by webzwo0i** [comment]
@UnixFriend Is this on ARM?

**Comment by woeterman94** [comment]
Got the same issue when trying to run etherpad in docker.

**Comment by webzwo0i** [comment]
Please paste your Dockerfile

**Comment by woeterman94** [comment]
I'm using the one in the master branch.

I changed `FROM node:10-buster-slim` to `FROM node:12-buster-slim`

**Comment by webzwo0i** [comment]
Weird. Cannot reproduce. Are you running on special hardware like Raspberry PI?

**Comment by woeterman94** [comment]
An Azure App Service with the docker image.

**Comment by jeanfabrice** [comment]
I can confirm that vanilla etherpad docker image 1.8.6 and 1.8.5 recently built are broken.
Base image has not changed since 1.8.0 (node:10-buster-slim) so unless it is rebuild on dockerhub, etherpad image 1.8.4 should still work. 

Seems related to #4335

**Comment by rhansen** [comment]
@jeanfabrice: Can you reproduce the problem with the current develop branch? Please report success/failure on bug #4335.

**Comment by rhansen** [comment]
Duplicate of #4335

**Comment by woeterman94** [comment]
> Weird. Cannot reproduce. Are you running on special hardware like Raspberry PI?

What hardware are you testing on?
