### ISSUE TITLE
Node 10 is broken

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4335]
Updating fixes..  I'm wondering if they hot patched an old release and now we're seeing issues with it...

**Comment by JohnMcLear** [comment]
```
Ensure that all dependencies are up to date... If this is the first time you have run Etherpad please be patient.
wd@1.12.1 install /home/pi/etherpad-lite/src/node_modules/wd
node scripts/build-browser-scripts
added 1127 packages in 41.911s
Clearing minified cache...
Starting Etherpad...
All relative paths will be interpreted relative to the identified Etherpad base dir: /home/pi/etherpad-lite
Random string used for versioning assets: 650daa0b
[2020-09-22 18:08:58.773] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/home/pi/etherpad-lite/settings.json"
[2020-09-22 18:08:58.777] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/home/pi/etherpad-lite/credentials.json"
settings loaded from: /home/pi/etherpad-lite/settings.json
No credentials file found in /home/pi/etherpad-lite/credentials.json. Ignoring.
[2020-09-22 18:08:58.856] [INFO] console - Using skin "colibris" in dir: /home/pi/etherpad-lite/src/static/skins/colibris
[2020-09-22 18:08:58.857] [INFO] console - Session key file "/home/pi/etherpad-lite/SESSIONKEY.txt" not found. Creating with random contents.
[2020-09-22 18:08:58.860] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production. File location: /home/pi/etherpad-lite/var/dirty.db
[2020-09-22 18:09:04.523] [INFO] APIHandler - Api key file "/home/pi/etherpad-lite/APIKEY.txt" not found. Creating with random contents.
[2020-09-22 18:09:05.183] [INFO] console - Installed plugins:
[2020-09-22 18:09:05.195] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2020-09-22 18:09:05.197] [INFO] console - Your Etherpad version is 1.8.6 (299bd96)
[2020-09-22 18:09:06.047] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2020-09-22 18:09:06.048] [WARN] console - Admin username and password not set in settings.json. To access admin please uncomment and edit 'users' in settings.json
[2020-09-22 18:09:06.049] [WARN] console - Etherpad is running in Development mode. This mode is slower for users and less secure than production mode. You should set the NODE_ENV environment variable to production by using: export NODE_ENV=production
Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
[2020-09-22 18:13:21.760] [ERROR] console - Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
at Timeout.setTimeout [as _onTimeout] (/home/pi/etherpad-lite/src/node_modules/threads/dist/master/spawn.js:34:53)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)
[2020-09-22 18:13:21.761] [INFO] console - graceful shutdown...
[2020-09-22 18:13:21.764] [INFO] console - db sucessfully closed.
```

We support node 10 afaik...

**Comment by JohnMcLear** [comment]
Steps to replicate that I haven't yet done...

- [ ]  Install 10.22.1
- [ ]  Setup MVP environment
- [ ]  Test.

If bug is found report at https://github.com/avoidwork/tiny-worker/issues

**Comment by webzwo0i** [comment]
https://travis-ci.org/github/ether/etherpad-lite/builds/729439713
seems to work fine on x86 with all v10 versions that have been released. I asked in https://github.com/ether/etherpad-lite/issues/4334 if the issue could be related to ARM.

**Comment by woeterman94** [comment]
What version should I try for the docker image?

**Comment by jeanfabrice** [comment]
Well, I'm a bit puzzled.

Ran a few tests without being able to reproduce this issue as often as I would:
- local NodeJS 10.22.1 + etherpad 1.8.6 + DirtyDB : works
- local Docker image etherpad/etherpad:1.8.6 + DirtyDB : works
- Docker image etherpad/etherpad:1.8.6 + few plugins + MySQL 8 : works
- Kubernetes deployment using Docker image etherpad/etherpad:1.8.6 + few plugins + MySQL 8 : don't works

```
[2020-10-01 20:29:50.772] [WARN] console - No "skinName" parameter found. Please check out settings.json.template and update your settings.json. Falling back to the default "colibris".
[2020-10-01 20:29:50.773] [INFO] console - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
[2020-10-01 20:29:50.773] [INFO] console - Session key file "/opt/etherpad-lite/SESSIONKEY.txt" not found. Creating with random contents.
[2020-10-01 20:29:59.123] [INFO] APIHandler - Api key file read from: "/opt/etherpad-lite/APIKEY.txt"
[2020-10-01 20:30:04.149] [INFO] console - Installed plugins: ep_adminpads2@2.1.3, ep_font_color@0.0.15, ep_author_hover@0.3.1, ep_list_pads@0.1.5, ep_markdown@0.1.7, ep_mammoth@0.1.5, ep_prompt_for_name@1.0.4, ep_comments_page@0.1.6
[2020-10-01 20:30:04.245] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2020-10-01 20:30:04.253] [INFO] console - Your Etherpad version is 1.8.6 (299bd96)
[2020-10-01 20:30:06.947] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2020-10-01 20:30:06.947] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
[2020-10-01 20:30:26.650] [ERROR] console - Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout.setTimeout [as _onTimeout] (/opt/etherpad-lite/src/node_modules/threads/dist/master/spawn.js:34:53)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2020-10-01 20:30:26.650] [INFO] console - graceful shutdown...
[2020-10-01 20:30:26.669] [INFO] console - db sucessfully closed.
```

what about @JohnMcLear own's setup ?

**Comment by JohnMcLear** [comment]
I am too oldschool to use any containers.  Sorry!

**Comment by jeanfabrice** [comment]
@JohnMcLear np, but what was your setup when you ran into this error? NodeJS version? arch?

**Comment by JohnMcLear** [comment]
Oh my log is from another issue...  I should have linked it.

**Comment by jeanfabrice** [comment]
Well, original issue mentioned by @JohnMcLear was #4334. Environment may be ARM (?), solved upgrading to Node 12

@woeterman94 seems to encounter the issue as well, running Docker 1.8.6 image on Azure. Again, solved changing the Dockerfile base image to node:12. @woeterman94: were you ran some tests locally?

And now, me, encountering the issue running Docker images on on-premise Kubernetes platform while running images locally seems ok.

**Comment by jeanfabrice** [comment]
Also : 
- Kubernetes deployment using Docker image etherpad/etherpad:1.8.4 + MySQL 8 : works
- Kubernetes deployment using Docker image etherpad/etherpad:1.8.5 + MySQL 8 : doesn't work

**Comment by JohnMcLear** [comment]
Switching to terser broke something with containers.  1.8.5 kn and node 12 okay?

**Comment by jeanfabrice** [comment]
@JohnMcLear I did not test Node12 on containers but @woeterman94 did. And success. 

I will bisect around terser’s commit and will post result

**Comment by MikkCZ** [comment]
I hit the same issue today on fresh installation of Debian 9. After first boot, I upgraded all packaged and the followed installation steps as in Etherpad README file. A workaround for me was to update the `bin/run.sh` file and adding `--experimental-worker` flag right after `exec node`. on the very last line.

**Comment by jeanfabrice** [comment]
> Switching to terser broke something with containers. 1.8.5 kn and node 12 okay?

This is a nice catch!
Docker image jeanfabrice/etherpad:f1e3aff7 (based on f1e3aff7, terser's commit) : doesn't work
Docker image jeanfabrice/etherpad:166e1371 (based on 166e1371 previous commit) : works

**Comment by JohnMcLear** [comment]
Good catch re experimental workers..

**Comment by jeanfabrice** [comment]
So etherpad >= 1.8.5 + node 10 requires `--experimental-worker` flags to work properly

What are your plans ? Add `--experimental-worker` to the node 10 based docker image ? or switch to node 12 ?

**Comment by JohnMcLear** [comment]
Adding ``--experimental-worker`` doesn't fix things for users of debian using node out of the box.  That's a problem.

Add ``--experimental-worker `` doesn't hurt though, would you like to put forward a PR with that included please?

**Comment by jeanfabrice** [comment]
> Adding `--experimental-worker` doesn't fix things for users of debian using node out of the box. That's a problem.
If this is the way you want to go (i.e keep node10 as a valid interpreter), some magic in `bin/run.sh` (and others bootstrap shells) should test the node version and add `--experimental-worker` accordingly, no?
> 
> Add `--experimental-worker ` doesn't hurt though, would you like to put forward a PR with that included please?
Sure

**Comment by JohnMcLear** [comment]
> If this is the way you want to go (i.e keep node10 as a valid interpreter), some magic in `bin/run.sh` (and others bootstrap shells) should test the node version and add `--experimental-worker` accordingly, no?

Good idea, but what about node 10 on Windows?  Same issue or fine?

**Comment by MikkCZ** [comment]
@JohnMcLear might be worth adding the switch to wiki as well. One example is [this page](https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service), but there might be more.

**Comment by JohnMcLear** [comment]
@MikkCZ Go for it!  Happy for you to make the required changes if you are comfortable to do so :+1:

**Comment by MikkCZ** [comment]
Done, I think. I found and updated three pages that contained string `server.js`:
- https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service
- https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-as-a-service
- https://github.com/ether/etherpad-lite/wiki/Running-Etherpad-on-Phusion-Passenger

**Comment by JohnMcLear** [comment]
Awesome tnx
