### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: self signed certificate in certificate chain in 1.8.5 and 1.8.6

### ISSUE THREAD

**Issue by ber8749** [ether/etherpad-lite#4376]
**Describe the bug**
When spinning up etherpad 1.8.5 or 1.8.6 in ubuntu 16.04, the following error is encountered:
```
[2020-09-29 19:17:21.103] [WARN] console - No "skinName" parameter found. Please check out settings.json.template and update your settings.json. Falling back to the default "colibris".
[2020-09-29 19:17:21.104] [INFO] console - Using skin "colibris" in dir: /opt/etherpad/src/static/skins/colibris
[2020-09-29 19:17:21.105] [WARN] console - Declaring the sessionKey in the settings.json is deprecated. This value is auto-generated now. Please remove the setting from the file. -- If you are seeing this error after restarting using the Admin User Interface then you can ignore this message.
[2020-09-29 19:17:21.260] [DEBUG] console - Running on Node v10.13.0 (minimum required Node version: 10.13.0)
[2020-09-29 19:17:21.404] [ERROR] console - (node:2899) UnhandledPromiseRejectionWarning: Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
```
We have previously run etherpad versions 1.6.1 through 1.8.4 without issue.

**To Reproduce**
N / A

**Expected behavior**
Server to start.

**Screenshots**
N / A

**Desktop (please complete the following information):**
N / A

**Smartphone (please complete the following information):**
N / A

**Additional context**
We understand that this bug report is somewhat light on details, but we hope that someone might have an idea why we're encountering this issue in the latest version(s) of etherpad.

**Comment by rhansen** [comment]
Did you upgrade node.js and/or your SSL library? That might explain why it's not working for you now.

See https://stackoverflow.com/q/45088006 for workarounds, but I highly recommend using a real certificate. You can get them for free with https://letsencrypt.org/.

**Comment by JohnMcLear** [comment]
closing as inactive.

**Comment by sylvinus** [comment]
Got the same error on heroku while using https://github.com/citizenos/etherpad-lite-heroku

**Comment by rhansen** [comment]
> Got the same error on heroku while using https://github.com/citizenos/etherpad-lite-heroku

See https://github.com/ether/etherpad-lite/issues/4376#issuecomment-701106347.
