### ISSUE TITLE
Can't install my plugin: No valid version available

### ISSUE THREAD

**Issue by woeterman94** [ether/etherpad-lite#4388]
I've developed a plugin for etherpad. But when I try to install it I get : "Can't install my plugin: No valid version available".
Happens when using `npm install` or the web interface

![image](https://user-images.githubusercontent.com/5755057/95063895-3de86680-06ff-11eb-81bf-d6dd643240fd.png)

My package.json looks like this
```
{
  "name": "ep_auth_session_samesite_none",
  "version": "3.0.0",
  "description": "Using samesite none. Provides a route that authenticates the user with the provided sessionID parameter and redirects to the given padName",
  "main": "index.js",
  "dependencies": {},
  "engines": {
    "node": ">= 0.6.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/woeterman94/ep_auth_session.git"
  },
  "author": "woeterman94",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/woeterman94/ep_auth_session/issues"
  },
  "homepage": "https://github.com/woeterman94/ep_auth_session",
  "keywords": [
    "etherpad",
    "authentication",
    "session"
  ]
}
```

**Comment by JohnMcLear** [comment]
Obvious question...  Do you get this issue with other plugins?

**Comment by woeterman94** [comment]
Didn't try it before. But yes.

**Comment by JohnMcLear** [comment]
Does your ``node_modules/`` folder have anything other than ``ep_etherpad-lite`` inside?

**Comment by woeterman94** [comment]
no, just that folder

**Comment by JohnMcLear** [comment]
try using the npm command.

``npm install your_plugin_name``.

I have a feeling it's a bug in the plugin web based installation logic...

**Comment by woeterman94** [comment]
Tried that as well, no luck
![image](https://user-images.githubusercontent.com/5755057/95080588-99731e00-0718-11eb-844c-300991a99df8.png)

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ep_auth_session_samesite_none'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose npm-session ce0cc9287d681c0d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/ep_auth_session_samesite_none 954ms (from cache)
8 silly pacote tag manifest for ep_auth_session_samesite_none@latest fetched in 966ms
9 timing stage:loadCurrentTree Completed in 2504ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 12ms
13 silly install loadShrinkwrap
14 http fetch GET 304 https://registry.npmjs.org/ep_etherpad-lite 68ms (from cache)
15 silly fetchPackageMetaData error for ep_etherpad-lite@1.8.6 No valid versions available for ep_etherpad-lite
16 timing stage:rollbackFailedOptional Completed in 0ms
17 timing stage:runTopLevelLifecycles Completed in 2600ms
18 silly saveTree etherpad
19 verbose type version
20 verbose stack ep_etherpad-lite: No valid versions available for ep_etherpad-lite
20 verbose stack     at pickManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-pick-manifest\index.js:39:11)
20 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:24:14
20 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
20 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
20 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
20 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
20 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:699:18)
20 verbose stack     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
20 verbose stack     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
20 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
20 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
20 verbose stack     at processImmediate (internal/timers.js:456:21)
21 verbose cwd C:\Users\wovd\Documents\Code\Etherpad\etherpad
22 verbose Windows_NT 10.0.18363
23 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ep_auth_session_samesite_none"
24 verbose node v12.18.3
25 verbose npm  v6.14.6
26 error code ENOVERSIONS
27 error No valid versions available for ep_etherpad-lite
28 verbose exit [ 1, true ]
```

**Comment by JohnMcLear** [comment]
what if you do

``npm install ep_headings2`` ????

**Comment by woeterman94** [comment]
same error:  `No valid versions available for ep_etherpad-lite`

**Comment by JohnMcLear** [comment]
@woeterman94 Try a clean install of Etherpad, it looks like you borked something...

**Comment by JohnMcLear** [comment]
@woeterman94 I assume this is resolved now?

**Comment by JohnMcLear** [comment]
@woeterman94 it's good manners to update issues when requested :+1:

**Comment by woeterman94** [comment]
Retried with clean install and still not working.

**Comment by woeterman94** [comment]
It works when I delete package-lock.json

**Comment by JohnMcLear** [comment]
``src/package-lock.json`` or ``package-lock.json``?

It looks like someone/some plugin tried to do ``npm install ep_etherpad-lite`` or something weird which added that to ``package-lock``..  

A clean install would have fixed this.

**Comment by woeterman94** [comment]
![image](https://user-images.githubusercontent.com/5755057/96722195-659d2700-13ad-11eb-86f5-38d8e1b6efc9.png)
just package-lock (not the one in the src folder)

**Comment by woeterman94** [comment]
Not ideal, but for now it's workable. Thanks for your help and time.
