### ISSUE TITLE
own project

### ISSUE THREAD

**Issue by asharuDheen-code** [ether/etherpad-lite#4476]
Error: secret option required for sessions
    at session (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express-session\index.js:200:12)
    at Layer.handle [as handle_request] (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\index.js:275:10)
    at expressInit (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\index.js:275:10)
    at query (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\ashar\OneDrive\Desktop\My Projrcts\realtime-pizza-app-node-express-mongo\node_modules\express\lib\router\index.js:284:7

**Comment by JohnMcLear** [comment]
Please read issue guidelines before posting issues.

**Comment by asharuDheen-code** [comment]
> Please read issue guidelines before posting issues.



> Please read issue guidelines before posting issues.

am a fresher i didn't get it can you help me

**Comment by JohnMcLear** [comment]
You did get it you are just too lazy to read it.  

Click new issue and read the guidelines.

Fresher or long time contributor, no one cares in the real world.

**Comment by asharuDheen-code** [comment]
> You did get it you are just too lazy to read it.
> 
> Click new issue and read the guidelines.
> 
> Fresher or long time contributor, no one cares in the real world.

ok
