### ISSUE TITLE
Loadtest bug with not huge load for long time.

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4478]
**Describe the bug**
```
etherpad-loadtest -a 10 -l 15
```
After 78 minutes errors with
```
Load Test Metrics -- Target Pad http://192.168.1.33:9001/p/8FcrttOaqB

Local Clients Connected: 33
Authors Connected: 11
Lurkers Connected: 22
Sent Append messages: 58996
Commits accepted by server: 58009
Commits sent from Server to Client: 1390741
Current rate per second of Commits sent from Server to Client: 0
Mean(per second) of # of Commits sent from Server to Client: 298
Max(per second) of # of Messages (SocketIO has cap of 10k): 1985
Number of commits not yet replied as ACCEPT_COMMIT from server 987
Seconds test has been running for: **4665**
/home/pi/etherpad-load-test/node_modules/etherpad-cli-client/lib/Changeset.js:41
  throw e;
  ^

Error: Failed assertion: mismatched follow - cannot transform cs1 on top of cs2
    at Object.error (/home/pi/etherpad-load-test/node_modules/etherpad-cli-client/lib/Changeset.js:39:11)
    at Object.assert (/home/pi/etherpad-load-test/node_modules/etherpad-cli-client/lib/Changeset.js:53:13)
    at Object.exports.follow (/home/pi/etherpad-load-test/node_modules/etherpad-cli-client/lib/Changeset.js:2022:11)
    at transformX (/home/pi/etherpad-load-test/node_modules/etherpad-cli-client/lib/index.js:167:24)
    at Socket.<anonymous> (/home/pi/etherpad-load-test/node_modules/etherpad-cli-client/lib/index.js:83:9)
    at Socket.Emitter.emit (/home/pi/etherpad-load-test/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/home/pi/etherpad-load-test/node_modules/socket.io-client/lib/socket.js:278:10)
    at Socket.onpacket (/home/pi/etherpad-load-test/node_modules/socket.io-client/lib/socket.js:236:12)
    at Manager.<anonymous> (/home/pi/etherpad-load-test/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/pi/etherpad-load-test/node_modules/component-emitter/index.js:133:20) {
  easysync: true
}
```

**To Reproduce**
Bring up Etherpad instance with loadTest set to true
Generate load as per above command.

**Expected behavior**
Doesn't crash

Raspberry Pi 3b over network

I will run the test again, I'm dumping here to see if it's reproducable.

**Comment by JohnMcLear** [comment]
Load Test Metrics -- Target Pad http://192.168.1.33:9001/p/Z6tUnn5Jn2

Local Clients Connected: 25
Authors Connected: 10
Lurkers Connected: 15
Sent Append messages: 86329
Commits accepted by server: 84504
Commits sent from Server to Client: 2028065
Current rate per second of Commits sent from Server to Client: 0
Mean(per second) of # of Commits sent from Server to Client: 222
Max(per second) of # of Messages (SocketIO has cap of 10k): 1792
Number of commits not yet replied as ACCEPT_COMMIT from server 1825
Seconds test has been running for: 9118

unable to replicate, I wonder if it was a network drop or so.
