### ISSUE TITLE
no RESPONSE from createSession, authorID is returning null, I want an etherpad that becomes readonly after x mintes

### ISSUE THREAD

**Issue by bharath-naik** [ether/etherpad-lite#4484]
**Describe the bug**

**Desktop:**
 - OS: Ubuntu [linux] version 20.04
 - Browser firefox
 - Version 82.0 (64-bit)

Hi, I am All New, I am creating an etherpad with the following rules only with the API like only admin can create the epl, it will be available for editing upto x minutes after x minutes it should become read-only mode and members can see their own etherpads finally. this is my achievement.
MY INSTANCE with settings.json
```
"editOnly" : "${EDITONLY : true}",
```
so while creating new etherpads from the following docs link [https://etherpad.org/doc/v1.7.5/#index_createsession_groupid_authorid_validuntil](url) i have used api as follows:
```
etherpad.createGroup(function(error, data) {
  if(error) 
  	console.error(error.message)
  else
  	console.log(data)
```
logs response is
```
[2020-11-10 09:45:58.278] [INFO] API - RESPONSE, createGroup, {"code":0,"message":"ok","data":{"groupID":"g.zn9i8KNnCWbjTiZE"}}
```
passing the groupID as parameter to create session
```
var sesArg ={
 groupID: data.groupID,
 validUntil :46060,
}
 authorsID = etherpad.createAuthor(['epluser'])
etherpad.createSession(sesArg, authorsID)  
```
i get no RESPONSE, see the logs below
logs
```
 REQUEST, v1.2.12:createSession, {"apikey":"api secret key","groupID":"g.zn9i8KNnCWbjTiZE","validUntil":"46060"}
```
The authorID is returning null 
```
authorID = etherpad.createAuthor(['epluser'])
console.log(authorID)
```
logs the console as ``` null``` but from in the server logs i can see the authorID, full server logs is specified below

PS: After getting the response like ```session id : s.16SESSCHARACTERS```, how should i need to enter url like 16 characters in https://pad.tld/p/16SESSCHARACTERS or how should i proceed with it.

**Additional context**
All pads should be created by admin only.
full logs
```
[2020-11-10 12:10:31.608] [INFO] API - REQUEST, v1.2.12:createGroup, {"apikey":"api-secret-key"}
[2020-11-10 12:10:31.610] [INFO] API - RESPONSE, createGroup, {"code":0,"message":"ok","data":{"groupID":"g.3jaWPzKZbOEOYF0Q"}}
[2020-11-10 12:10:31.637] [INFO] API - REQUEST, v1.2.12:createAuthor, {"0":"epluser","apikey":"api-secret-key"}
[2020-11-10 12:10:31.638] [INFO] API - RESPONSE, createAuthor, {"code":0,"message":"ok","data":{"authorID":"a.k8qSGQLejeJTrRqp"}}
[2020-11-10 12:10:31.646] [INFO] API - REQUEST, v1.2.12:createSession, {"apikey":"api-secret-key","groupID":"g.3jaWPzKZbOEOYF0Q","validUntil":"46060"}

```

**Comment by JohnMcLear** [comment]
Peep the logic in https://github.com/ether/etherpad-lite/blob/develop/tests/backend/specs/api/sessionsAndGroups.js

It shows the steps you will need to take.

**Comment by bharath-naik** [comment]
Thanks, it helped.
i have used docker and run the tests with the following url [http://localhost:9001/tests/frontend/index.html](url), it passed all tests, 
i have my server logs as follows but 

```
[2020-11-11 10:35:44.983] [INFO] API - REQUEST, v1.2.12:createAuthorIfNotExistsFor, {"apikey":"secretkey","name":"epluser","authorMapper":"15132"}
[2020-11-11 10:35:44.985] [INFO] API - RESPONSE, createAuthorIfNotExistsFor, {"code":0,"message":"ok","data":{"authorID":"a.lrxdPvDvnrjRMWcF"}}
[2020-11-11 10:35:45.006] [INFO] API - REQUEST, v1.2.12:createGroupIfNotExistsFor, {"apikey":"secretkey","groupMapper":"110"}
[2020-11-11 10:35:45.007] [INFO] API - RESPONSE, createGroupIfNotExistsFor, {"code":0,"message":"ok","data":{"groupID":"g.C0oy7eZmAOHo9pfr"}}
[2020-11-11 10:35:45.016] [INFO] API - REQUEST, v1.2.12:createGroupPad, {"apikey":"secretkey","groupID":"g.C0oy7eZmAOHo9pfr","padName":"t5p1ldtq1a2qbt5fase42","text":"prova"}
[2020-11-11 10:35:45.018] [INFO] API - RESPONSE, createGroupPad, {"code":0,"message":"ok","data":{"padID":"g.C0oy7eZmAOHo9pfr$t5p1ldtq1a2qbt5fase42"}}
[2020-11-11 10:35:45.023] [INFO] API - REQUEST, v1.2.12:createSession, {"apikey":"secretkey","groupID":"g.C0oy7eZmAOHo9pfr","authorID":"a.lrxdPvDvnrjRMWcF","validUntil":"1702999999"}
[2020-11-11 10:35:45.025] [INFO] API - RESPONSE, createSession, {"code":0,"message":"ok","data":{"sessionID":"s.02f45f41e18b4bc23441bbe28a0b8b9d"}}

```

1. what will be my next move, how should i proceed from here, like i want to open the etherpad as soon as i call the API. no docs explains it clear as far i have searched.

2. How to use ```document.cookie=sessionID.s.xxxxxx``` from the API, as it throws this kind of error like
```
document.cookie = 'sessionID =' + data.sessionID;
^									
ReferenceError: document is not defined
    at /home/dhachi/etherpad/actionapi.js:67:12
    at IncomingMessage.<anonymous> (/home/dhachi/etherpad/node_modules/etherpad-lite-client/main.js:61:22)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
3. **You do not have permission to access this pad**
why this appears, i know edit only in settings.json is set to ```true```, but using API only it should create so that anyone cannot create new etherpad as they wish

**Comment by JohnMcLear** [comment]
The test I linked to is a backend test.  Not frontend.

**Comment by bharath-naik** [comment]
what do i do with the test, can you please give me more information, as i am just a kick starter. please  check above comment what i want to acheive

**Comment by JohnMcLear** [comment]
Afaik its in the wiki under running backend tests.  Take a look at the docs.  If you can't find it ask on discord Chan for help

**Comment by bharath-naik** [comment]
```
args ={"groupID": groupID, "authorID": authorID, "validUntil": 1312201246}
createSession(args) ```
this is still accessible after the validity of time, it should expire after valid time right!

**Comment by bharath-naik** [comment]
@JohnMcLear .. iam sorry to say, if docs got me clear, i wouldn't have reached here, Do you have exactly any idea on how etherpad can only created by JavaScript API.

**Comment by JohnMcLear** [comment]
Yea, see the test coverage for examples.  I didn't link you already?  I'm not doing your work for you...

**Comment by bharath-naik** [comment]
yep @John .. you are right ! Pleased, but how this test coverage example will help, i am completely stuck and unable to find any new way.

**Comment by rhansen** [comment]
If you want a pad to automatically become read-only after a period of time, your best bet is to create a plugin that uses the [`authorize` hook](https://github.com/ether/etherpad-lite/blob/develop/doc/api/hooks_server-side.md#authorize). Your function would look up the pad's creation time (or last edit time or whatever) and return either `'create'` or `'readOnly'` depending on how much time had elapsed.
