### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4495]
Introduced/first appeared in ed5a635f4c113ba7a535b51b30245adc5cfb6cf0

Replicated by wget http://localhost:9001/javascript which results in an 500 and the stack trace below. /javascript is not very important, but the stack traced looked important, so I did the bisect... :)

@rhansen Do you have an idea what's causing this?
```
[2020-11-18 20:48:16.829] [ERROR] console - TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/home/etherpad/eplite-bisect-circular-dep/src/node_modules/express/lib/response.js:1123:12)
    at ServerResponse.json (/home/etherpad/eplite-bisect-circular-dep/src/node_modules/express/lib/response.js:260:14)
    at ServerResponse.send (/home/etherpad/eplite-bisect-circular-dep/src/node_modules/express/lib/response.js:158:21)
    at ServerResponse.res.send (/home/etherpad/eplite-bisect-circular-dep/src/node/hooks/express.js:124:48)
    at /home/etherpad/eplite-bisect-circular-dep/src/node/hooks/express/specialpages.js:23:9
    at Layer.handle [as handle_request] (/home/etherpad/eplite-bisect-circular-dep/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/etherpad/eplite-bisect-circular-dep/src/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/etherpad/eplite-bisect-circular-dep/src/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/etherpad/eplite-bisect-circular-dep/src/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by webzwo0i** [comment]
Regression test can be cherry-picked from https://github.com/ether/etherpad-lite/commit/4645660509117f1acf344542ec289f1d26999704
