### ISSUE TITLE
``express deprecated res.send(status, body):``

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4498]
Weird bug I haven't seen before..  

```
Nov 19 23:14:03 etherpad run.sh[47742]: Fri, 20 Nov 2020 04:14:03 GMT express deprecated res.send(status, body): Use res.status(status).send(body) instead at src/node/hooks/express.js:124:48
Nov 19 23:14:03 etherpad run.sh[47742]: [2020-11-19 23:14:03.081] [ERROR] console - TypeError: Converting circular structure to JSON
Nov 19 23:14:03 etherpad run.sh[47742]: --> starting at object with constructor 'TLSSocket'
Nov 19 23:14:03 etherpad run.sh[47742]: |     property 'parser' -> object with constructor 'HTTPParser'
Nov 19 23:14:03 etherpad run.sh[47742]: --- property 'socket' closes the circle
Nov 19 23:14:03 etherpad run.sh[47742]: at JSON.stringify (<anonymous>)
Nov 19 23:14:03 etherpad run.sh[47742]: at stringify (/home/etherpad-lite/src/node_modules/express/lib/response.js:1123:12)
Nov 19 23:14:03 etherpad run.sh[47742]: at ServerResponse.json (/home/etherpad-lite/src/node_modules/express/lib/response.js:260:14)
Nov 19 23:14:03 etherpad run.sh[47742]: at ServerResponse.send (/home/etherpad-lite/src/node_modules/express/lib/response.js:158:21)
Nov 19 23:14:03 etherpad run.sh[47742]: at ServerResponse.res.send (/home/etherpad-lite/src/node/hooks/express.js:124:48)
Nov 19 23:14:03 etherpad run.sh[47742]: at /home/etherpad-lite/src/node/hooks/express/specialpages.js:23:9
Nov 19 23:14:03 etherpad run.sh[47742]: at Layer.handle [as handle_request] (/home/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
Nov 19 23:14:03 etherpad run.sh[47742]: at next (/home/etherpad-lite/src/node_modules/express/lib/router/route.js:137:13)
Nov 19 23:14:03 etherpad run.sh[47742]: at Route.dispatch (/home/etherpad-lite/src/node_modules/express/lib/router/route.js:112:3)
Nov 19 23:14:03 etherpad run.sh[47742]: at Layer.handle [as handle_request] (/home/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
Nov 19 23:14:03 etherpad run.sh[47742]: at /home/etherpad-lite/src/node_modules/express/lib/router/index.js:281:22
Nov 19 23:14:03 etherpad run.sh[47742]: at Function.process_params (/home/etherpad-lite/src/node_modules/express/lib/router/index.js:335:12)
Nov 19 23:14:03 etherpad run.sh[47742]: at next (/home/etherpad-lite/src/node_modules/express/lib/router/index.js:275:10)
Nov 19 23:14:03 etherpad run.sh[47742]: at Layer.handle [as handle_request] (/home/etherpad-lite/src/node_modules/express/lib/router/layer.js:91:12)
Nov 19 23:14:03 etherpad run.sh[47742]: at trim_prefix (/home/etherpad-lite/src/node_modules/express/lib/router/index.js:317:13)
Nov 19 23:14:03 etherpad run.sh[47742]: at /home/etherpad-lite/src/node_modules/express/lib/router/index.js:284:7
```

Could be caused by a plugin, posting here for posterity...

Note that ep_webrtc does

```
./index.js:27: * @param client the client that send this message
./index.js:54:  // Lookup recipient and send message
./index.js:58:      clients[i].json.send(msg);
```

**Comment by webzwo0i** [comment]
That's probably the same as https://github.com/ether/etherpad-lite/issues/4495

(Based on `Nov 19 23:14:03 etherpad run.sh[47742]: at /home/etherpad-lite/src/node/hooks/express/specialpages.js:23:9` which is the for javascript.html)

Only difference is `TLSSocket` vs `HTTPParser`: Do you do TLS with Express? Because in the setup from #4495 TLS is terminated at a proxy in front of Express and that could explain the missing `TLSSocket`.

**Comment by JohnMcLear** [comment]
Afaik on the instance I do SSL pinning so TLS w/ express and nginx.  

Ack re #4495 - will close this.
