### ISSUE TITLE
EXECABORT Transaction discarded because of previous errors

### ISSUE THREAD

**Issue by sachaz** [ether/etherpad-lite#4550]
Since the upgrade on version is 1.8.6

Etherpad is crashing with the following message:

~~~
[2020-12-06 11:12:01.348] [ERROR] console - ReplyError: EXECABORT Transaction discarded because of previous errors.
    at parseError (/srv/etherpad-lite/src/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/srv/etherpad-lite/src/node_modules/redis-parser/lib/parser.js:302:14)
[2020-12-06 11:12:01.349] [INFO] console - Stopping Etherpad...
[2020-12-06 11:12:04.351] [ERROR] console - Error: Timed out waiting for shutdown tasks
    at Timeout.setTimeout [as _onTimeout] (/srv/etherpad-lite/src/node/server.js:110:40)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
~~~
My system is a Debian Buster with Redis.

**Comment by JohnMcLear** [comment]
Please read the contributing guidelines and provide steps to replicate.  Please also test latest develop branch.

**Comment by JohnMcLear** [comment]
*bump for more details please :)

**Comment by JohnMcLear** [comment]
Closing as 30 days no details.
