### ISSUE TITLE
Installation and de-installation of plugins is broken

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4676]
1. Clicking install and uninstall takes minutes, not seconds (it used to take seconds).
STR: try install ep_font_size
2. Clicking Uninstall will make Etherpad unavailable for a duration (in my case 10+ seconds).

I think this is related to the bugfixes by @rhansen but I am yet to confirm, I can go through and bisect if required :)

I'm currently writing test coverage for this functionality (and other parts of admin).

Develop branch, Debian.  minify set to false, maxAge 0.

User experience is also broken on Windows <- I wanated to ensure my node/npm wasn't being weird.  I did notice windows doesn't seem to disconnect tho and instead just fails to uninstall?  This error on windows did stand out

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
[2021-01-23 20:56:10.846] [ERROR] console -
[2021-01-23 20:56:10.853] [INFO] console - added 1358 packages from 1689 contributors and removed 128 packages in 141.123s
[2021-01-23 20:56:11.981] [WARN] console - { inspect: [Function: inspect] }
[2021-01-23 20:56:11.983] [ERROR] console - (node:6456) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.resolve (path.js:139:9)
    at loadPlugin (C:\etherpad-lite-win\src\static\js\pluginfw\plugins.js:114:28)
    at C:\etherpad-lite-win\src\static\js\pluginfw\plugins.js:77:35
    at Array.map (<anonymous>)
    at Object.exports.update (C:\etherpad-lite-win\src\static\js\pluginfw\plugins.js:76:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.uninstall (C:\etherpad-lite-win\src\static\js\pluginfw\installer.js:38:5)
[2021-01-23 20:56:11.984] [ERROR] console - (node:6456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2021-01-23 20:56:11.990] [ERROR] console - (node:6456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Yea windows uninstall is totally broken...  Leaves the server in a broken state

```
Error: C:\etherpad-lite-win\node_modules\ep_etherpad-lite\templates\pad.html:71
    69|           <% e.begin_block("editbarMenuLeft"); %>
    70|           <%- toolbar.menu(settings.toolbar.left, isReadOnly, 'left', 'pad') %>
 >> 71|           <% e.end_block(); %>
    72|       </ul>
    73|       <ul class="menu_right" role="toolbar">
    74|           <% e.begin_block("editbarMenuRight"); %>

Cannot find module 'ep_font_family/templates/editbarButtons.ejs' from 'C:\etherpad-lite-win\node_modules\ep_etherpad-lite\templates'
```

**Comment by JohnMcLear** [comment]
I think this is a lot better now.
