### ISSUE TITLE
PadMessageHandler Crash

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4701]
Latest develop

```
Feb 02 11:04:48 etherpad fastRun.sh[36480]: [2021-02-02 11:04:48.461] [ERROR] console - TypeError: Cannot read property 'id' of undefined
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at /home/etherpad-lite/src/node/handler/PadMessageHandler.js:1127:22
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at Array.map (<anonymous>)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at handleClientReady (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:1125:47)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at runMicrotasks (<anonymous>)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at async Object.exports.handleMessage (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:252:5)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at async Socket.<anonymous> (/home/etherpad-lite/src/node/handler/SocketIORouter.js:76:7)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: [2021-02-02 11:04:48.648] [ERROR] console - TypeError: Cannot read property 'id' of undefined
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at handleClientReady (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:920:39)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at runMicrotasks (<anonymous>)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at runNextTicks (internal/process/task_queues.js:62:5)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at processImmediate (internal/timers.js:429:9)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at process.topLevelDomainCallback (domain.js:137:15)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at async Object.exports.handleMessage (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:252:5)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: at async Socket.<anonymous> (/home/etherpad-lite/src/node/handler/SocketIORouter.js:76:7)
Feb 02 11:04:48 etherpad fastRun.sh[36480]: [2021-02-02 11:04:48.649] [ERROR] console - Error occurred while waiting to exit. Forcing an immediate unclean exit...
Feb 02 11:04:48 etherpad systemd[1]: etherpad.service: main process exited, code=exited, status=1/FAILURE
Feb 02 11:04:48 etherpad systemd[1]: Unit etherpad.service entered failed state.
Feb 02 11:04:48 etherpad systemd[1]: etherpad.service failed.
```

No steps to replicate.

**Comment by JohnMcLear** [comment]
I have monkey patched the production instance with

```
     await Promise.all(_getRoomSockets(pad.id).map(async (roomSocket) => {
       // Jump over, if this session is the connection session
+      if (!roomSocket || !socket) return;
+      if (!roomSocket.id || !socket.id) return;
```

Will wait to see if it is stable w/ that patch.
