### ISSUE TITLE
PadMessageHandler.js:920 Crashes Etherpad

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4708]
Unable to provide STR.

```
Feb 03 14:31:02 etherpad fastRun.sh[21354]: [2021-02-03 14:31:02.709] [ERROR] console - TypeError: Cannot read property 'id' of undefined
Feb 03 14:31:02 etherpad fastRun.sh[21354]: at handleClientReady (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:920:39)
Feb 03 14:31:02 etherpad fastRun.sh[21354]: at async Object.exports.handleMessage (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:252:5)
Feb 03 14:31:02 etherpad fastRun.sh[21354]: at async Socket.<anonymous> (/home/etherpad-lite/src/node/handler/SocketIORouter.js:76:7)
Feb 03 14:31:04 etherpad fastRun.sh[21354]: [2021-02-03 14:31:04.018] [ERROR] console - TypeError: Cannot read property 'id' of undefined
Feb 03 14:31:04 etherpad fastRun.sh[21354]: at handleClientReady (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:920:39)
Feb 03 14:31:04 etherpad fastRun.sh[21354]: at async Object.exports.handleMessage (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:252:5)
Feb 03 14:31:04 etherpad fastRun.sh[21354]: at async Socket.<anonymous> (/home/etherpad-lite/src/node/handler/SocketIORouter.js:76:7)
Feb 03 14:31:04 etherpad fastRun.sh[21354]: [2021-02-03 14:31:04.019] [ERROR] console - Error occurred while waiting to exit. Forcing an immediate unclean exit...
Feb 03 14:31:04 etherpad systemd[1]: etherpad.service: main process exited, code=exited, status=1/FAILURE
Feb 03 14:31:04 etherpad systemd[1]: Unit etherpad.service entered failed state.
Feb 03 14:31:04 etherpad systemd[1]: etherpad.service failed.
Feb 03 14:33:05 etherpad fastRun.sh[21530]: [2021-02-03 14:33:05.031] [ERROR] console - UNSETTLED FUNCTION BUG IN HOOK FUNCTION (plugin: ep_token_auth, function name: /home/etherpad-lite/node_modules/ep_token_auth/index:expressConfigure, hook: expressConfigure): The hook function neither called the callback nor returned a non-undefined value. This is prohibited because it will result in freezes when a future version of Etherpad updates the hook to support asynchronous behavior.
```

monkey patched with

```
  for (const socket of roomSockets) {
    if (!socket.id) return;
    const sinfo = sessioninfos[socket.id];
    if (sinfo && sinfo.author === authorID) {
      // fix user's counter, works on page refresh or if user closes browser window and then rejoins
      sessioninfos[socket.id] = {};
      socket.leave(padIds.padId);
      socket.json.send({disconnect: 'userdup'});
    }
  }
```

related to #4701

**Comment by JohnMcLear** [comment]
```
[2021-02-26 16:12:10.907] [INFO] access - [LEAVE] pad:undefined socket:cuvIgX-a-YKbWVwQAAHn IP:127.0.0.1 authorID:a.3jzpsKk7v8wdEu4c
[2021-02-26 16:12:10.910] [INFO] access - [ENTER] pad:test2 socket:6d1aJ-66vqd1Hq64AAHm IP:127.0.0.1 authorID:a.TvBoXN1RxUJ05rQn
[2021-02-26 16:12:10.928] [ERROR] server - TypeError: Cannot read property 'id' of undefined
    at C:\etherpad-lite\src\node\handler\PadMessageHandler.js:1149:22
    at Array.map (<anonymous>)
    at handleClientReady (C:\etherpad-lite\src\node\handler\PadMessageHandler.js:1147:47)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:434:9)
    at async Object.exports.handleMessage (C:\etherpad-lite\src\node\handler\PadMessageHandler.js:268:5)
    at async Socket.<anonymous> (C:\etherpad-lite\src\node\handler\SocketIORouter.js:77:7)
[2021-02-26 16:12:10.929] [INFO] server - Exiting...
[2021-02-26 16:12:10.930] [INFO] server - Stopping Etherpad...
[2021-02-26 16:12:10.938] [INFO] http - Closing HTTP server...
```

I was able to create this by using the loadTest tool and terminating the testing abruptly.

**Comment by JohnMcLear** [comment]
```
[2021-02-26 16:15:02.193] [WARN] console - TypeError: Cannot read property 'id' of undefined
    at Object.exports.updatePadClients (C:\etherpad-lite\src\node\handler\PadMessageHandler.js:722:24)
    at async handleUserChanges (C:\etherpad-lite\src\node\handler\PadMessageHandler.js:695:5)
[2021-02-26 16:15:02.203] [WARN] console - TypeError: Cannot read property 'id' of undefined
    at Object.exports.updatePadClients (C:\etherpad-lite\src\node\handler\PadMessageHandler.js:722:24)
    at async handleUserChanges (C:\etherpad-lite\src\node\handler\PadMessageHandler.js:695:5)
[2021-02-26 16:15:02.209] [WARN] console - TypeError: Cannot read property 'id' of undefined
    at Object.exports.updatePadClients (C:\etherpad-lite\src\node\handler\PadMessageHandler.js:722:24)
    at async handleUserChanges (C:\etherpad-lite\src\node\handler\PadMessageHandler.js:695:5)
```

**Comment by JohnMcLear** [comment]
It impacts instances even if loadTest is false.

**Comment by JohnMcLear** [comment]
@webzwo0i @rhansen btw this one seems pretty serious, it's hitting a few production boxes now and I'm not seeing a common driving factor..  I am also not able to consistently replicate however loadtesting has raised the error a few times :)

**Comment by webzwo0i** [comment]
ok prio this now

**Comment by JohnMcLear** [comment]
```
[2021-02-26 19:35:13.025] [ERROR] server - TypeError: Cannot read property 'id' of undefined
    at handleClientReady (C:\test2\src\node\handler\PadMessageHandler.js:938:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9)
    at async Object.exports.handleMessage (C:\test2\src\node\handler\PadMessageHandler.js:268:5)
    **at async Socket.<anonymous> (C:\test2\src\node\handler\SocketIORouter.js:77:7)**
```
