### ISSUE TITLE
Plugin installer is hanging again post install

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4763]
https://github.com/ether/etherpad-lite/runs/1887915846?check_suite_focus=true

STR:

1. Go to admin ui
1. Search and select ep_markdown
1. Click install
1. Wait..  Etherpad will not come back up.

In server console

```
[2021-02-12 15:14:06.391] [WARN] console - DirtyDB is used. This is not recommended for production. File location: /home/pi/develop/var/dirty.db
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/develop/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/develop/package.json'
npm WARN ep_markdown@0.1.25 requires a peer of ep_headings2@* but none is installed. You must install peer dependencies yourself.
npm WARN develop No description
npm WARN develop No repository field.
npm WARN develop No README data
npm WARN develop No license field.
[2021-02-12 15:15:52.759] [ERROR] console -
[            ......] | postinstall: sill install printInstalled
```

Plugin will be ``node_modules/`` and in ``/package-lock.json`` you will find 

```
    "ep_markdown": {
      "resolved": "https://registry.npmjs.org/ep_markdown/-/ep_markdown-0.1.25.tgz",
```

This could just be weird that it's behavior to my box only?

I was able to get a decent log output when I tried to install ep_markdown https://github.com/ether/etherpad-lite/runs/1888226516?check_suite_focus=true

**Comment by JohnMcLear** [comment]
```

[2021-02-12 16:00:45.793] [WARN] console - TypeError: Cannot read property 'match' of undefined
    at tarballToVersion (/home/pi/develop/src/node_modules/npm/lib/install/inflate-shrinkwrap.js:95:20)
    at inflatableChild (/home/pi/develop/src/node_modules/npm/lib/install/inflate-shrinkwrap.js:121:22)
    at /home/pi/develop/src/node_modules/npm/lib/install/inflate-shrinkwrap.js:63:12
    at tryCatcher (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
[2021-02-12 16:00:45.853] [ERROR] server - TypeError: Cannot read property 'match' of undefined
    at tarballToVersion (/home/pi/develop/src/node_modules/npm/lib/install/inflate-shrinkwrap.js:95:20)
    at inflatableChild (/home/pi/develop/src/node_modules/npm/lib/install/inflate-shrinkwrap.js:121:22)
    at /home/pi/develop/src/node_modules/npm/lib/install/inflate-shrinkwrap.js:63:12
    at tryCatcher (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/develop/src/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
[2021-02-12 16:01:09.954] [ERROR] server - Error occurred while stopping EtherpaddealTree
[2021-02-12 16:01:09.957] [ERROR] server - Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at Server.close (net.js:1606:12)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:327:22)
    at Server.EventEmitter.emit (domain.js:467:12)
    at emitCloseNT (net.js:1659:8)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
[2021-02-12 16:01:09.959] [ERROR] server - Error occurred while waiting to exit. Forcing an immediate unclean exit...

```

Is an error I was able to get out locally ;/

**Comment by JohnMcLear** [comment]
I'm just gonna assume my local setup is totally b0rked from all the horky borky npm / node setups I have tried over the years..  I think I probably need a fresh image on my deployment device ;\

**Comment by jckoester** [comment]
I'm getting pretty much the same error an a rather fresh setup. I can install one plugin on the second one I will get the same " TypeError: Cannot read property 'match' of undefined" message. A reinstall also didn't help. Any ideas?

**Comment by rhansen** [comment]
> I'm getting pretty much the same error an a rather fresh setup.

* What version of Etherpad? If older than 1.8.9 please try upgrading. If you are using 1.8.9, please try latest `develop` branch.
* What operating system?
* Please paste logs.

**Comment by JohnMcLear** [comment]
I tested this in 1.8.9 and I'm unable to replicate this issue
