### ISSUE TITLE
[ERROR] server - Error: Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by khyoz** [ether/etherpad-lite#4802]
**Describe the bug**
[2021-02-17 08:16:40.956] [INFO] server - Etherpad is running
[2021-02-17 08:16:51.348] [ERROR] server - Error: Connection lost: The server closed the connection.
    at Protocol.end (/opt/etherpad/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/opt/etherpad/etherpad-lite/src/node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (/opt/etherpad/etherpad-lite/src/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:390:22)
    at Socket.EventEmitter.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
[2021-02-17 08:16:51.349] [INFO] server - Stopping Etherpad...
[2021-02-17 08:16:51.350] [INFO] http - Closing HTTP server...
[2021-02-17 08:16:51.352] [INFO] socket.io - Closing socket.io engine...
[2021-02-17 08:16:51.353] [INFO] socket.io - All socket.io clients have disconnected
[2021-02-17 08:16:51.362] [INFO] http - HTTP server closed
[2021-02-17 08:16:51.366] [ERROR] server - Error occurred while stopping Etherpad
[2021-02-17 08:16:51.367] [ERROR] server - Error: Cannot enqueue Quit after fatal error.
    at Protocol._validateEnqueue (/opt/etherpad/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/opt/etherpad/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at Protocol.quit (/opt/etherpad/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:91:23)
    at Connection.end (/opt/etherpad/etherpad-lite/src/node_modules/mysql/lib/Connection.js:239:18)
    at exports.Database.close (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/databases/mysql_db.js:296:11)
    at /opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:195:20
    at exports.Database._callFlushDoneCallbacks (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:383:31)
    at Immediate.<anonymous> (/opt/etherpad/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:397:29)
    at processImmediate (node:internal/timers:463:21)
[2021-02-17 08:16:51.367] [ERROR] server - Error occurred while waiting to exit. Forcing an immediate unclean exit...

**To Reproduce**
run etherpad
 
**Additional context**
centos 7
Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1127.19.1.el7.x86_64

 node -v
v15.8.0

 Report bugs at https://github.com/ether/etherpad-lite/issues
[2021-02-17 08:16:38.208] [INFO] console - Your Etherpad version is 1.8.8 (7dae5e3)

**Comment by JohnMcLear** [comment]
Your database (MySQL) is misconfigured?

**Comment by khyoz** [comment]
I did the same last week to test with nodes 15.6.0, everything was ok
now I can see in settings.json 

"socketIo": {
    /*
     * Maximum permitted client message size (in bytes). All messages from
     * clients that are larger than this will be rejected. Large values make it
     * possible to paste large amounts of text, and plugins may require a larger
     * value to work properly, but increasing the value increases susceptibility
     * to denial of service attacks (malicious clients can exhaust memory).
     */
    "maxHttpBufferSize": 10000
  },

that was not in my previous installation 

and at the end of the file
/* Disable Admin UI tests */
  "enableAdminUITests": false
  

I can see in the previous messages lots of sentences relate to socket...
