### ISSUE TITLE
Spaces in URL = Error

### ISSUE THREAD

**Issue by jannikb16** [ether/etherpad-lite#4883]
When I create a pad with spaces I get the following error in the console: 
`[2021-02-27 23:16:40.534] [ERROR] server - TypeError [ERR_INVALID_URL]: Invalid URL: /p/this%20is%20a%20test                       
    at onParseError (internal/url.js:259:9)
    at new URL (internal/url.js:335:5)
    at /root/etherpad-lite/src/node/hooks/express/padurlsanitize.js:21:60
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-02-27 23:16:40.534] [INFO] server - Exiting...
[2021-02-27 23:16:40.534] [INFO] server - Stopping Etherpad...
[2021-02-27 23:16:40.534] [INFO] http - Closing HTTP server...
[2021-02-27 23:16:40.535] [INFO] socket.io - Closing socket.io engine...
[2021-02-27 23:16:40.536] [INFO] access - [LEAVE] pad:testh socket:FDGBpBpOwJLesqHLAAAB IP:46.114.151.73 authorID:a.ccfacCteR8PZpm0A username:admin
[2021-02-27 23:16:40.536] [INFO] socket.io - All socket.io clients have disconnected
[2021-02-27 23:16:40.538] [INFO] http - Waiting for 2 HTTP clients to disconnect...
[2021-02-27 23:16:40.541] [INFO] console - Database closed
[2021-02-27 23:16:43.538] [ERROR] server - Error occurred while stopping Etherpad
[2021-02-27 23:16:43.538] [ERROR] server - Error: Timed out waiting for shutdown tasks
    at Timeout.<anonymous> (/root/etherpad-lite/src/node/server.js:194:43)
    at Timeout.wrapped [as _onTimeout] (/root/etherpad-lite/src/node_modules/wtfnode/index.js:197:27)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[2021-02-27 23:16:43.538] [ERROR] server - Error occurred while waiting to exit. Forcing an immediate unclean exit...
`

This is a new Installation with v. 1.8.11 and 3 Plugins (headings2, font_color, back_button) 

Link to the error code: https://pastebin.com/0Wp4RLaA

**Comment by webzwo0i** [comment]
Thanks for the report
introduced by 586af5e16e07519affc3570ab45c539da3b5bc32

**Comment by jannikb16** [comment]
Thanks! @webzwo0i

**Comment by jannikb16** [comment]
Thanks! @webzwo0i

**Comment by webzwo0i** [comment]
let's keep this open until the fix in https://github.com/ether/etherpad-lite/pull/4884 is merged.

Would you be so kind and test if it fixes the problem for you?
