### ISSUE TITLE
Lots of erros with ep_comments_page

### ISSUE THREAD

**Issue by meaz** [ether/etherpad-lite#4890]
Hi,

I've just tried the 1.8.11 version. I've got a few errors in Firefox console with ep_comments_page:

```
Failed to load 'ep_comments_page/static/js/index' for 'ep_comments_page/comments_page/client_hooks/postToolbarInit': Error: The module at "ep_etherpad-lite/static/js/browser" does not exist. ace2_common.js:62:948
Failed to load 'ep_comments_page/static/js/index' for 'ep_comments_page/comments_page/client_hooks/postAceInit': Error: The module at "ep_etherpad-lite/static/js/browser" does not exist. ace2_common.js:62:948
Failed to load 'ep_comments_page/static/js/index' for 'ep_comments_page/comments_page/client_hooks/aceAttribsToClasses': Error: The module at "ep_etherpad-lite/static/js/browser" does not exist.
Failed to load 'ep_comments_page/static/js/index' for 'ep_comments_page/comments_page/client_hooks/aceEditorCSS': Error: The module at "ep_etherpad-lite/static/js/browser" does not exist. ace2_common.js:62:948
Failed to load 'ep_comments_page/static/js/index' for 'ep_comments_page/comments_page/client_hooks/aceEditEvent': Error: The module at "ep_etherpad-lite/static/js/browser" does not exist. ace2_common.js:62:948
Failed to load 'ep_comments_page/static/js/index' for 'ep_comments_page/comments_page/client_hooks/aceInitialized': Error: The module at "ep_etherpad-lite/static/js/browser" does not exist. ace2_common.js:62:948
```

**Comment by JohnMcLear** [comment]
Please open issue on plugin repo :)

**Comment by rhansen** [comment]
Actually we need to fix this in Etherpad core by adding a compatibility path like we did with jQuery.

**Comment by JohnMcLear** [comment]
Also job for me, I need to make sure plugins don't use ``vendors`` path else they wont work on old instances
