### ISSUE TITLE
Etherpad 1.8.11 crashes when trying to create a pad with blank in title

### ISSUE THREAD

**Issue by techware01** [ether/etherpad-lite#4915]
**Describe the bug**
Etherpad 1.8.11 can not handle spaces in pad title correctly. When trying to create a pad from the pads landingpage that includes blanks etherpad crashes (e.g. test test). It trys to open /p/test test. So it encodes the blank as a blank (%20).

**To Reproduce**
1. Go to the pads landingpage
2. Type "test test" into the "create/open a Pad with the name:" field 
3. Click
4. See bad gateway error in browser and on the server the error that etherpad crashed

**Expected behavior**
Etherpad should replace the blanks in the pad title with underscores and create a new pad/open an existing pad (if existing) whitout crashing. E.g "test_test"

**Server (please complete the following information):**
 - Etherpad version: 1.8.11
 - OS: Debian GNU/Linux 10 (buster)
 - Node.js version (`node --version`): v12.21.0
 - npm version (`npm --version`): 6.14.8

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 86.0

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11
 - Browser: Vanadium
 - Version: 88

**Additional context**
Error message from etherpad: 
```
[2021-03-03 10:29:06.926] [ERROR] server - TypeError [ERR_INVALID_URL]: Invalid URL: /p/test%20test
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at /opt/etherpad/etherpad-lite/src/node/hooks/express/padurlsanitize.js:21:60
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-03-03 10:29:09.928] [ERROR] server - Error occurred while stopping Etherpad
[2021-03-03 10:29:09.929] [ERROR] server - Error: Timed out waiting for shutdown tasks
    at Timeout.<anonymous> (/opt/etherpad/etherpad-lite/src/node/server.js:194:43)
    at Timeout.wrapped [as _onTimeout] (/opt/etherpad/etherpad-lite/src/node_modules/wtfnode/index.js:197:27)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[2021-03-03 10:29:09.929] [ERROR] server - Error occurred while waiting to exit. Forcing an immediate unclean exit...
```

**Comment by JohnMcLear** [comment]
Can you replicate this on devleop branch?  afaik we patched this and included test coverage for CI.

**Comment by techware01** [comment]
Yeah you are right on develop it's working. Thx. Is their already a next release planned that contains this bug fix?

**Comment by JohnMcLear** [comment]
hopefully tomorrow.

**Comment by JohnMcLear** [comment]
Will be releasing today
