### ISSUE TITLE
etherpad-lite does not start after update

### ISSUE THREAD

**Issue by DC7IA** [ether/etherpad-lite#4926]
**Describe the bug**
Missing dependency:

```
[2021-03-05 09:01:44.433] [ERROR] runCmd|npm - npm ERR! peer dep missing: eslint-plugin-cypress@^2.11.2, required by eslint-config-etherpad@1.0.26
[2021-03-05 09:01:44.473] [ERROR] server - Error occurred while starting Etherpad
[2021-03-05 09:01:44.474] [ERROR] server - Error: Command exited with code 1: npm ls --long --json --depth=0 --no-production
    at exports (/home/user/etherpad-lite/src/node/utils/run_cmd.js:119:25)
    at Object.exports.getPackages (/home/user/etherpad-lite/src/static/js/pluginfw/plugins.js:125:48)
    at Object.exports.update (/home/user/etherpad-lite/src/static/js/pluginfw/plugins.js:99:34)
    at Object.exports.start (/home/user/etherpad-lite/src/node/server.js:140:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-03-05 09:11:15.493] [INFO] server - Exiting...
[2021-03-05 09:11:15.494] [INFO] server - Waiting for Node.js to exit...
[2021-03-05 09:11:20.493] [ERROR] server - Something that should have been cleaned up during the shutdown hook (such as a timer, worker thread, or open connection) is preventing Node.js from exiting
[2021-03-05 09:11:20.494] [INFO] console - [WTF Node?] open handles:
[2021-03-05 09:11:20.495] [INFO] console - - File descriptors: (note: stdio always exists)
[2021-03-05 09:11:20.496] [INFO] console -   - fd 1 (tty) (stdio)
[2021-03-05 09:11:20.496] [INFO] console -   - fd 2 (tty) (stdio)
[2021-03-05 09:11:20.497] [INFO] console - - Sockets:
[2021-03-05 09:11:20.498] [INFO] console -   - 127.0.0.1:58040 -> 127.0.0.1:3306
[2021-03-05 09:11:20.498] [INFO] console -     - Listeners:
[2021-03-05 09:11:20.499] [INFO] console -       - connect: bound  @ /home/user/etherpad-lite/src/node_modules/mysql/lib/Connection.js:98
[2021-03-05 09:11:20.500] [INFO] console - - Intervals:
[2021-03-05 09:11:20.500] [INFO] console -   - (100 ~ 100 ms) (anonymous) @ /home/user/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:180
[2021-03-05 09:11:20.501] [INFO] console -   - (10000 ~ 10 s) (anonymous) @ /home/user/etherpad-lite/src/node_modules/ueberdb2/databases/mysql_db.js:62
[2021-03-05 09:11:20.502] [ERROR] server - Forcing an unclean exit...
```

**To Reproduce**

I used 1.8.8 and then went to 1.8.12 using `git checkout 1.8.12` and then I ran `installDeps.sh`.

I tried `git checkout 1.8.8`, but the error was still there. I had to restore the backup from yesterday, which is on 1.8.8 and I have no idea why that works.

**Expected behavior**

`installDeps.sh` installs the deps and etherpad-lite continues to work, just like 1.8.8.

Tried `npm i eslint-plugin-cypress`, but that did not solve it.

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version: from 1.8.8 to 1.8.12
 - OS: [e.g., Ubuntu 20.04] CentOS
 - Node.js version (`node --version`): v12.19.0
 - npm version (`npm --version`): 6.14.8

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JohnMcLear** [comment]
Do you have a ``package.json`` or ``package-lock.json`` in root?

**Comment by DC7IA** [comment]
Yeah, but I tried just reinstalling etherpad-lite and using my existing config, that solved it.

Whatever it was, not a bug.

**Comment by JohnMcLear** [comment]
Yea, we have CI in for this too as of about an hour ago, so it shouldn't happen moving forward :D

**Comment by robinpaulson** [comment]
I'm getting this error too, having upgraded an hour or so ago to 1.8.12. I'd rather not reinstall ep if possible.

In answer to the question from John, I have a file called package.json and package-lock.json in the root of the installation

**Comment by robinpaulson** [comment]
Also, even after running installDeps.sh, I'm getting errors for 100+ dependencies, mostly those of npm@7.6.1, which I don't entirely understand.

**Comment by JohnMcLear** [comment]
backup package.json and package-lock.json remove them from your root folder and try to run.
