### ISSUE TITLE
CONF: DB configuration "dbSettings" does not support connection string

### ISSUE THREAD

**Issue by tiblu** [ether/etherpad-lite#4985]
**Describe the bug**

In Etherpad 1.8.7 this IS valid DB configuration in `settings.json`:
```
  "dbType": "postgres",
  "dbSettings": "postgres://etherpad:etherpad@localhost:5432/etherpad",
```

In Etherpad 1.8.13 this is NOT valid DB configuration and results in exception:
```
/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/node_modules/ueberdb2/databases/postgres_db.js:24
  this.settings.cache = settings.cache || 1000;
                      ^

TypeError: Cannot create property 'cache' on string 'postgres://etherpad:etherpad@localhost:5432/etherpad'
    at new exports.Database (/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/node_modules/ueberdb2/databases/postgres_db.js:24:23)
    at new exports.Database (/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/node_modules/ueberdb2/index.js:60:14)
    at Object.<anonymous> (/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/node/db/DB.js:32:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**To Reproduce**

Change versions and configuration as described above.

**Expected behavior**

Support `dbSettings` to be a connection string.

**Why and where would you need it to be a connection string?**

* Cloud service platforms like Heroku add the connection string into a single environment variable "DATABASE_URL", when they migrate DB-s, they change the env variable and everything remains working.
* Convenience - most DB providers give you a DB URL and you would just copy-paste into DB configuration instead of splitting it into different properties.

**Comment by webzwo0i** [comment]
bisect seems to indicate 04962bfe39fcf5f95710d42f93054b00cfa64cdc

**Comment by tiblu** [comment]
@webzwo0i I would not consider it a "Minor Bug" as we have a case where patch version update breaks existing deploys.

**Comment by JohnMcLear** [comment]
Just to distill for myself.  The ``dbSettings`` string is important for reasons @tiblu mentions, https://github.com/ether/ueberDB/blob/master/databases/postgres_db.js doesn't have any parsing logic, perhaps before it did?  Either way, OP wants the string method for accessing a postgres database supported by UeberDB, which feels like a fair enough request.

**Comment by JohnMcLear** [comment]
https://github.com/ether/ueberDB/pull/217 -- it's a one liner which is always nice 📦
