### ISSUE TITLE
setup etherpad behind firewall and use http proxy for requests

### ISSUE THREAD

**Issue by adnus** [ether/etherpad-lite#5036]
Hi guys,

this is not a bug report nor a feature request. I didn't find a channel for posting my issue. So don't be angry ;-)

I setup the great etherpad, all is fine and working good.

But I'd like to install a couple of plugins. The problem is, we are behind a firewall and have NO direct access to internet. All what we have is a http and https proxy.

That's works good for base operations like nodejs updates and apt updates. But when I loaded a plugin by command line: npm install ep_<plugin>, after that action the etherpad server crashed:

[2021-05-19 09:24:12.047] [ERROR] server - Error: Command exited with code 1: npm ls --long --json --depth=0 --no-production
May 19 09:24:12 odpad node[619]:     at exports (/opt/etherpad/etherpad-lite/src/node/utils/run_cmd.js:119:25)
May 19 09:24:12 odpad node[619]:     at Object.exports.getPackages (/opt/etherpad/etherpad-lite/src/static/js/pluginfw/plugins.js:125:48)
May 19 09:24:12 odpad node[619]:     at Object.exports.update (/opt/etherpad/etherpad-lite/src/static/js/pluginfw/plugins.js:99:34)
May 19 09:24:12 odpad node[619]:     at Object.exports.start (/opt/etherpad/etherpad-lite/src/node/server.js:143:19)
May 19 09:24:12 odpad node[619]:     at process._tickCallback (internal/process/next_tick.js:68:7)

I guess it has to do with the missing direct internet connection.

Has anyone setup etherpad in such a situation?

I did'nt found any solution in the world wide net.

Thank you very much for your help.
Jens

**Comment by adnus** [comment]
Sorry, found a solution

what I did:

npm install --no-save --legacy-peer-deps
npm install ep_align

then i ran etherpad without systemctl, plugins are available now on the admin webinterface. When I start etherpad by systemctl, plugins dissappear, but i see the installed plugins now.

Sorry
Jens
