### ISSUE TITLE
Connecting to Redis without authentication appears impossible

### ISSUE THREAD

**Issue by JustAnotherArchivist** [ether/etherpad-lite#5048]
**Describe the bug**
It appears to be impossible to connect to a Redis database without authentication. Attempting to do so produces the following error in node-redis:

```
Error: node_redis: The AUTH command contains a invalid argument type.
Only strings, dates and buffers are accepted. Please update your code to use valid argument types.
    at RedisClient.internal_send_command (/opt/etherpad-lite/src/node_modules/redis/index.js:835:39)
    at RedisClient.auth (/opt/etherpad-lite/src/node_modules/redis/lib/individualCommands.js:216:20)
    at RedisClient.create_stream (/opt/etherpad-lite/src/node_modules/redis/index.js:244:14)
    at new RedisClient (/opt/etherpad-lite/src/node_modules/redis/index.js:121:10)
    at Object.exports.createClient (/opt/etherpad-lite/src/node_modules/redis/index.js:1023:12)
    at exports.Database.init (/opt/etherpad-lite/src/node_modules/ueberdb2/databases/redis_db.js:55:23)
    at internal/util.js:308:30
    at new Promise (<anonymous>)
    at Object.bound  [as init] (internal/util.js:307:12)
    at exports.Database.init (/opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:267:24)
```

While I haven't debugged it properly, the background seems to be that node-redis [checks for `auth_pass !== undefined`](https://github.com/NodeRedis/node-redis/blob/4f85030e42da2eed6a178e54994330af5062761e/index.js#L241) to decide whether to send the auth command, but Etherpad passes (via ueberDB) `null`, at least when configured via environment variables (as evidenced by the console warning: `Environment variable "DB_PASS" does not contain any value for configuration key "password", and no default was given. Returning null.`). That then leads to the crash above on the type checking in node-redis's `internal_send_command` function.

**To Reproduce**
1. Build Docker container: `docker build --tag foo/etherpad .`
2. Run Docker with settings to connect to a Redis server that does not require authentication, i.e. with `DB_PASS` unspecified: `docker run -e 'DB_TYPE=redis' -e 'DB_HOST=example.org' foo/etherpad`

In my specific case, I have Redis in another container and exposed via a Docker network, but I don't think that is relevant because the crash happens before it actually attempts to connect to the server anyway.

**Expected behavior**
A connection is established without attempting authentication.

**Server (please complete the following information):**
 - Etherpad version: 3bca8528
 - OS: Debian buster
 - Docker: 18.09.1 (from Debian repos)
 - Node.js version (`node --version`): 14.17.0
 - npm version (`npm --version`): 6.14.13

**Comment by JustAnotherArchivist** [comment]
I can confirm that my interpretation seems to be correct. Overriding the DB password from `null` to `undefined` in `src/node/utils/Settings.js` with the following ugly hack fixes the crash:

```diff
diff --git a/src/node/utils/Settings.js b/src/node/utils/Settings.js
index e5b1636d..bef3c556 100644
--- a/src/node/utils/Settings.js
+++ b/src/node/utils/Settings.js
@@ -805,6 +805,9 @@ exports.reloadSettings = () => {
     exports.dbSettings.filename = absolutePaths.makeAbsolute(exports.dbSettings.filename);
     console.warn(`${dirtyWarning} File location: ${exports.dbSettings.filename}`);
   }
+  if (exports.dbType == 'redis' && exports.dbSettings.password === null) {
+    exports.dbSettings.password = undefined;
+  }
 
   if (exports.ip === '') {
     // using Unix socket for connectivity
```
