### ISSUE TITLE
Error in latest docker image

### ISSUE THREAD

**Issue by designermonkey** [ether/etherpad-lite#5120]
```
etherpad_1       | [2021-07-19 15:40:31.261] [DEBUG] server - unhandled rejection: TypeError: Cannot read property 'sockets' of undefined
etherpad_1       |     at Gauge._readFn (/opt/etherpad-lite/src/node/handler/PadMessageHandler.js:73:54)
etherpad_1       |     at Gauge.toJSON (/opt/etherpad-lite/src/node_modules/measured-core/lib/metrics/Gauge.js:24:17)
etherpad_1       |     at /opt/etherpad-lite/src/node_modules/measured-core/lib/Collection.js:62:46
etherpad_1       |     at Array.forEach (<anonymous>)
etherpad_1       |     at Collection.toJSON (/opt/etherpad-lite/src/node_modules/measured-core/lib/Collection.js:60:32)
etherpad_1       |     at Object.exports.exit (/opt/etherpad-lite/src/node/server.js:221:75)
etherpad_1       |     at process.<anonymous> (/opt/etherpad-lite/src/node/server.js:117:15)
etherpad_1       |     at process.emit (events.js:375:28)
etherpad_1       |     at process.emit (domain.js:470:12)
etherpad_1       |     at process._fatalException (internal/process/execution.js:163:25)
```

**Comment by rhansen** [comment]
Please provide all of the information requested when filing a new bug report.

**Comment by rhansen** [comment]
Also, please try #5121 and see if you get a more useful error message.
