### ISSUE TITLE
404 Error because of missing package-log-only

### ISSUE THREAD

**Issue by lisandi** [ether/etherpad-lite#5188]
**Describe the bug**

**To Reproduce**
1. we install from ithu and run `npm audit fix`
2.
    ```
    npm ERR! code ENOLOCK
    npm ERR! audit This command requires an existing lockfile.
    npm ERR! audit Try creating one first with: npm i --package-lock-only
    npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2021-09-24T09_09_23_460Z-debug.log
    ```
3. So we try to create it
    ```
    root@c3:/opt/etherpad/etherpad-lite# npm i package-log-only
    
    npm WARN old lockfile 
    npm WARN old lockfile The package-lock.json file was created with an old version of npm,
    npm WARN old lockfile so supplemental metadata must be fetched from the registry.
    npm WARN old lockfile 
    npm WARN old lockfile This is a one-time fix-up, please be patient...
    npm WARN old lockfile 
    npm WARN old lockfile src: No matching version found for src@1.8.14.
    npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
    npm WARN old lockfile     at /usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
    npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9)
    npm WARN old lockfile  Could not fetch metadata for src@1.8.14 src: No matching version found for src@1.8.14.
    npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
    npm WARN old lockfile     at /usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
    npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9) {
    npm WARN old lockfile   code: 'ETARGET',
    npm WARN old lockfile   type: 'version',
    npm WARN old lockfile   wanted: '1.8.14',
    npm WARN old lockfile   versions: [ '0.1.0', '1.0.0', '1.1.0', '1.1.1', '1.1.2' ],
    npm WARN old lockfile   distTags: { latest: '1.1.2' },
    npm WARN old lockfile   defaultTag: 'latest'
    npm WARN old lockfile }
    npm ERR! code E404
    npm ERR! 404 Not Found - GET https://registry.npmjs.org/package-log-only - Not found
    npm ERR! 404 
    npm ERR! 404  'package-log-only@*' is not in this registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
    npm ERR! 404 
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2021-09-24T09_09_56_247Z-debug.log
    root@c3:/opt/etherpad/etherpad-lite# 
    ```

**Server (please complete the following information):**
 - Etherpad version: newest from Git today
 - OS: Ubuntu 20.04]
 
 now it is no more starting - we had clicked to install adminpad instead of adminpad2 which we already had installed - we than tried to deinstall it again which diod not work at all - hanging!

**Comment by JohnMcLear** [comment]
"we install from ithu and run npm audit fix" ? 🍡 

What is ithu?

Why aren't you following the install/deployment docs?  Please follow the docs.

**Comment by lisandi** [comment]
"Server (please complete the following information):

Etherpad version: newest from Git today
OS: Ubuntu 20.04]"

GitHub and we installed it like described on Github!

Besides that, you also receive a notice in the shell that the credentials.json file is missing.
I suggest adding simply at least an empty credentials.json file to the package to avoid those messages.

and the package-lock.json file you added has been created with an outdated npm version and that again throws deprecation messages which could simply be avoided by recreating that file with the newest version of npm and adding that to the package.
![Screen Shot 2021-09-25 at 13 58 20](https://user-images.githubusercontent.com/1982011/134765233-690f2d14-58ad-4584-8ef1-f1f861ea680a.png)
The screenshot had been taken after adding that missing credentials.json file manually as an empty valid .json file 

```
/**
 *
 */
{

}
```
as you can see in the screenshot it mentions the 
`npm WARN old lockfile The package-lock.json file was created with an old version of npm` etc.
and several deprecation messages

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated cloudant-follow@0.18.2: This package is no longer maintained.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```
It also shows

`5 vulnerabilities (3 moderate, 2 high)`

when you now try to fix those with any of those:

```
To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force
```
you receive the 
```
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
```

You can create those as suggested which leads to the message already mentioned above.

**Comment by JohnMcLear** [comment]
Closing as we have automated updates of security issues.
