### ISSUE TITLE
log4js start faild

### ISSUE THREAD

**Issue by y377** [ether/etherpad-lite#5468]
**Describe the bug**
Centos7 initializes the newly installed v1 8.7 normal startup, including nodejs V14 19.0 and npm6 14.14； But when I can't start NPM fix and NPM update

**To Reproduce**
```
[root@cd3 bin]# ./run.sh --root
Installing dependencies...
npm WARN prepare removing existing node_modules/ before installation
added 744 packages in 10.946s
Clearing minified cache...
Starting Etherpad...
/root/t/etherpad-lite/src/node/server.js:28
log4js.replaceConsole();
       ^

TypeError: log4js.replaceConsole is not a function
    at Object.<anonymous> (/root/t/etherpad-lite/src/node/server.js:28:8)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/58632405/158021111-932a0ab5-ea88-4904-bcea-cca1ce4b38bc.png)

**Server (please complete the following information):**
 - Etherpad version: `v1.8.17`
 - OS: [`CentOS7x64`]
 - Node.js version (`v14.19.0`):
 - npm version (`6.14.16`):
 - Is the server free of plugins: 

**Additional context**

**Comment by y377** [comment]
## default installed

> [root@cd3 bin]# node -v
v16.14.0
[root@cd3 bin]# npm -v
8.5.4
and
`npm outdated`
```shell
[root@cd3 bin]# npm outdated
Package                      Current   Wanted  Latest  Location                               Depended by
async                          3.2.1    3.2.3   3.2.3  node_modules/async                     src
clean-css                      5.2.1    5.2.4   5.2.4  node_modules/clean-css                 src
cookie-parser                  1.4.5    1.4.5   1.4.6  node_modules/cookie-parser             src
eslint                        7.32.0   7.32.0  8.11.0  node_modules/eslint                    src
eslint-config-etherpad         2.0.0    2.1.0   3.0.7  node_modules/eslint-config-etherpad    src
eslint-plugin-cypress         2.11.3   2.12.1  2.12.1  node_modules/eslint-plugin-cypress     src
eslint-plugin-mocha            9.0.0    9.0.0  10.0.3  node_modules/eslint-plugin-mocha       src
eslint-plugin-promise          5.1.0    5.2.0   6.0.0  node_modules/eslint-plugin-promise     src
express                       4.17.1   4.17.1  4.17.3  node_modules/express                   src
express-rate-limit             5.5.0    5.5.0   6.3.0  node_modules/express-rate-limit        src
formidable                     1.2.2    1.2.2   2.0.1  node_modules/formidable                src
http-errors                    1.8.0    1.8.0   2.0.0  node_modules/http-errors               src
jsdom                         17.0.0   17.0.0  19.0.0  node_modules/jsdom                     src
jsonminify                     0.4.1    0.4.1   0.4.2  node_modules/jsonminify                src
log4js                        0.6.38   0.6.38   6.4.2  node_modules/log4js                    src
mime-types                    2.1.33   2.1.35  2.1.35  node_modules/mime-types                src
mocha                          9.1.1    9.2.2   9.2.2  node_modules/mocha                     src
npm                          6.14.15  6.14.16   8.5.4  node_modules/npm                       src
openapi-backend                4.2.0    4.2.0   5.3.0  node_modules/openapi-backend           src
rate-limiter-flexible          2.3.1    2.3.6   2.3.6  node_modules/rate-limiter-flexible     src
rehype                        11.0.0   11.0.0  12.0.1  node_modules/rehype                    src
rehype-minify-whitespace       4.0.5    4.0.5   5.0.0  node_modules/rehype-minify-whitespace  src
resolve                       1.20.0   1.20.0  1.22.0  node_modules/resolve                   src
selenium-webdriver        4.0.0-rc-1    4.1.1   4.1.1  node_modules/selenium-webdriver        src
sinon                         11.1.2   11.1.2  13.0.1  node_modules/sinon                     src
socket.io                      2.4.1    2.4.1   4.4.1  node_modules/socket.io                 src
superagent                     6.1.0    6.1.0   7.1.1  node_modules/superagent                src
supertest                      6.1.6    6.2.2   6.2.2  node_modules/supertest                 src
terser                         5.9.0   5.12.0  5.12.0  node_modules/terser                    src
ueberdb2                      1.4.18   1.4.19   2.0.3  node_modules/ueberdb2                  src
underscore                    1.13.1   1.13.1  1.13.2  node_modules/underscore                src
```

**Comment by y377** [comment]
![image](https://user-images.githubusercontent.com/58632405/158066630-bb68d242-03be-459b-aec0-8bd832bf4bc3.png)
[clipboard](https://github.com/zenorocha/clipboard.js)

**Comment by DevNathan** [comment]
I have the same issue 

Is a patch coming ? A way to fix the bad behavior ?

**Comment by rhansen** [comment]
log4js > 0.6.38 is not supported, and will not be supported until Etherpad v2.0.0 is released (which is unlikely to happen soon). Any updates will be posted to #1922.
