### ISSUE TITLE
docker version of 1.8.18 is failing, 1.8.17 is working fine

### ISSUE THREAD

**Issue by GuidoDr** [ether/etherpad-lite#5551]
the docker version of 1.8.18 is failing with the below error.
Going back to the docker version of 1.8.17 etherpad is working fine again.

```
etherpad_1    | [2022-06-01 13:29:08.540] [INFO] server - Starting Etherpad...
etherpad_1    | [2022-06-01 13:29:08.698] [ERROR] ueberDB - Database is not configured with charset latin1 -- This may lead to crashes when certain characters are pasted in pads
etherpad_1    | [2022-06-01 13:29:08.698] [ERROR] server - Error occurred while starting Etherpad
etherpad_1    | [2022-06-01 13:29:08.699] [ERROR] server - Metrics at time of fatal error:
etherpad_1    | {
etherpad_1    |   "httpStartTime": 0,
etherpad_1    |   "memoryUsage": 60780544,
etherpad_1    |   "memoryUsageHeap": 11460984
etherpad_1    | }
etherpad_1    | [2022-06-01 13:29:08.699] [ERROR] server - TypeError: Cannot read property 'level' of undefined
etherpad_1    |     at Level.isLessThanOrEqualTo (/opt/etherpad-lite/src/node_modules/log4js/lib/levels.js:37:35)
etherpad_1    |     at Logger.isLevelEnabled (/opt/etherpad-lite/src/node_modules/log4js/lib/logger.js:66:21)
etherpad_1    |     at Logger.log (/opt/etherpad-lite/src/node_modules/log4js/lib/logger.js:54:13)
etherpad_1    |     at exports.Database.init (/opt/etherpad-lite/src/node_modules/ueberdb2/databases/mysql_db.js:78:19)
etherpad_1    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
etherpad_1    |     at async exports.Database.init (/opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:284:5)
etherpad_1    |     at async Object.exports.init (/opt/etherpad-lite/src/node/db/DB.js:41:3)
etherpad_1    |     at async Object.exports.start (/opt/etherpad-lite/src/node/server.js:142:5)
etherpad_1    | [2022-06-01 13:29:08.699] [INFO] server - Exiting...
etherpad_1    | [2022-06-01 13:29:08.699] [INFO] server - Waiting for Node.js to exit...
etherpad_1    | [2022-06-01 13:29:08.921] [DEBUG] runCmd - Command returned successfully: npm --version
etherpad_1    | [2022-06-01 13:29:08.921] [INFO] plugins - npm --version: 6.14.15
etherpad_1    | [2022-06-01 13:29:13.699] [ERROR] server - Something that should have been cleaned up during the shutdown hook (such as a timer, worker thread, or open connection) is preventing Node.js from exiting
etherpad_1    | [2022-06-01 13:29:13.700] [ERROR] server - Enable `dumpOnUncleanExit` setting to get a dump of objects preventing a clean exit
etherpad_1    | [2022-06-01 13:29:13.700] [ERROR] server - Forcing an unclean exit...
```

and here the log of version 1.8.17 which is running fine:
```
etherpad_1    | [2022-06-01 13:38:10.128] [INFO] server - Starting Etherpad...
etherpad_1    | [2022-06-01 13:38:10.812] [ERROR] console - Database is not configured with charset latin1 -- This may lead to crashes when certain characters are pasted in pads
etherpad_1    | [2022-06-01 13:38:10.812] [INFO] console - {
etherpad_1    |   DEFAULT_CHARACTER_SET_NAME: 'utf8mb4',
etherpad_1    |   DEFAULT_COLLATION_NAME: 'utf8mb4_unicode_ci'
etherpad_1    | } latin1
etherpad_1    | [2022-06-01 13:38:10.813] [ERROR] console - Database is not configured with collation name that includes latin1 -- This may lead to crashes when certain characters are pasted in pads
etherpad_1    | [2022-06-01 13:38:10.813] [INFO] console - {
etherpad_1    |   DEFAULT_CHARACTER_SET_NAME: 'utf8mb4',
etherpad_1    |   DEFAULT_COLLATION_NAME: 'utf8mb4_unicode_ci'
etherpad_1    | } latin1 utf8mb4_unicode_ci
etherpad_1    | [2022-06-01 13:38:10.921] [INFO] plugins - Running npm to get a list of installed plugins...
etherpad_1    | [2022-06-01 13:38:10.921] [DEBUG] runCmd - Executing command: npm ls --long --json --depth=0 --no-production
etherpad_1    | [2022-06-01 13:38:10.921] [DEBUG] runCmd - cwd: /opt/etherpad-lite
etherpad_1    | [2022-06-01 13:38:10.921] [DEBUG] runCmd - PATH=/opt/etherpad-lite/src/node_modules/.bin:/opt/etherpad-lite/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
etherpad_1    | [2022-06-01 13:38:11.693] [DEBUG] runCmd - Command returned successfully: npm --version
etherpad_1    | [2022-06-01 13:38:11.693] [INFO] plugins - npm --version: 6.14.15
etherpad_1    | [2022-06-01 13:38:18.922] [DEBUG] runCmd - Command returned successfully: npm ls --long --json --depth=0 --no-production
etherpad_1    | [2022-06-01 13:38:18.925] [INFO] plugins - Loading plugin ep_adminpads2...
etherpad_1    | [2022-06-01 13:38:18.925] [INFO] plugins - Loading plugin ep_author_hover...
etherpad_1    | [2022-06-01 13:38:18.925] [INFO] plugins - Loading plugin ep_disable_error_messages...
etherpad_1    | [2022-06-01 13:38:18.925] [INFO] plugins - Loading plugin ep_etherpad-lite...
etherpad_1    | [2022-06-01 13:38:18.925] [INFO] plugins - Loading plugin ep_font_color...
etherpad_1    | [2022-06-01 13:38:18.926] [INFO] plugins - Loading plugin ep_font_family...
etherpad_1    | [2022-06-01 13:38:18.926] [INFO] plugins - Loading plugin ep_headings2...
etherpad_1    | [2022-06-01 13:38:18.926] [INFO] plugins - Loading plugin ep_padlist2...
etherpad_1    | [2022-06-01 13:38:18.926] [INFO] plugins - Loading plugin ep_set_title_on_pad...
etherpad_1    | [2022-06-01 13:38:18.926] [INFO] plugins - Loading plugin ep_subscript_and_superscript...
etherpad_1    | [2022-06-01 13:38:18.980] [INFO] plugins - Loaded 10 plugins
etherpad_1    | [2022-06-01 13:38:23.071] [DEBUG] AbsolutePaths - Relative path "./APIKEY.txt" can be rewritten to "/opt/etherpad-lite/APIKEY.txt"
etherpad_1    | [2022-06-01 13:38:23.071] [INFO] APIHandler - Api key file "/opt/etherpad-lite/APIKEY.txt" not found.  Creating with random contents.
etherpad_1    | [2022-06-01 13:38:23.620] [DEBUG] server - Removing SIGINT listener because it might interfere with shutdown tasks. Function code:
etherpad_1    | () => terminateWorkersAndMaster()
etherpad_1    | Current stack:
etherpad_1    |     at removeSignalListener (/opt/etherpad-lite/src/node/server.js:81:36)
etherpad_1    |     at process.<anonymous> (/opt/etherpad-lite/src/node/server.js:138:9)
etherpad_1    |     at process.emit (events.js:412:35)
etherpad_1    |     at _addListener (events.js:443:14)
etherpad_1    |     at process.addListener (events.js:497:10)
etherpad_1    |     at initWorkerThreadsWorker (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:138:13)
etherpad_1    |     at selectWorkerImplementation (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:223:16)
etherpad_1    |     at Object.getWorkerImplementation (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:234:26)
etherpad_1    |     at Object.<anonymous> (/opt/etherpad-lite/src/node_modules/threads/dist/master/index.js:13:39)
etherpad_1    |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
etherpad_1    | [2022-06-01 13:38:23.621] [DEBUG] server - Removing SIGTERM listener because it might interfere with shutdown tasks. Function code:
etherpad_1    | () => terminateWorkersAndMaster()
etherpad_1    | Current stack:
etherpad_1    |     at removeSignalListener (/opt/etherpad-lite/src/node/server.js:81:36)
etherpad_1    |     at process.<anonymous> (/opt/etherpad-lite/src/node/server.js:138:9)
etherpad_1    |     at process.emit (events.js:412:35)
etherpad_1    |     at _addListener (events.js:443:14)
etherpad_1    |     at process.addListener (events.js:497:10)
etherpad_1    |     at initWorkerThreadsWorker (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:139:13)
etherpad_1    |     at selectWorkerImplementation (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:223:16)
etherpad_1    |     at Object.getWorkerImplementation (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:234:26)
etherpad_1    |     at Object.<anonymous> (/opt/etherpad-lite/src/node_modules/threads/dist/master/index.js:13:39)
etherpad_1    |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
etherpad_1    | [2022-06-01 13:38:24.874] [INFO] server - Installed plugins: ep_adminpads2@2.1.57, ep_disable_error_messages@0.0.28, ep_author_hover@0.3.37, ep_font_family@0.5.41, ep_font_color@0.0.63, ep_headings2@0.2.44, ep_set_title_on_pad@0.5.33, ep_padlist2@2.1.28, ep_subscript_and_superscript@0.2.47
etherpad_1    | [2022-06-01 13:38:24.874] [DEBUG] server - Installed parts:
etherpad_1    | ep_etherpad-lite/openapi
etherpad_1    | ep_etherpad-lite/adminsettings
etherpad_1    | ep_etherpad-lite/adminplugins
etherpad_1    | ep_etherpad-lite/admin
etherpad_1    | ep_etherpad-lite/tests
etherpad_1    | ep_etherpad-lite/socketio
etherpad_1    | ep_etherpad-lite/errorhandling
etherpad_1    | ep_etherpad-lite/importexport
etherpad_1    | ep_etherpad-lite/apicalls
etherpad_1    | ep_etherpad-lite/webaccess
etherpad_1    | ep_etherpad-lite/padurlsanitize
etherpad_1    | ep_etherpad-lite/specialpages
etherpad_1    | ep_etherpad-lite/i18n
etherpad_1    | ep_etherpad-lite/stats
etherpad_1    | ep_etherpad-lite/static
etherpad_1    | ep_etherpad-lite/express
etherpad_1    | ep_etherpad-lite/Minify
etherpad_1    | ep_etherpad-lite/DB
etherpad_1    | ep_subscript_and_superscript/main
etherpad_1    | ep_padlist2/ep_padlist2
etherpad_1    | ep_set_title_on_pad/set_title_on_pad
etherpad_1    | ep_headings2/main
etherpad_1    | ep_font_color/main
etherpad_1    | ep_font_family/main
etherpad_1    | ep_author_hover/ep_author_hover
etherpad_1    | ep_disable_error_messages/ep_disable_error_messages
etherpad_1    | ep_adminpads2/ep_adminpads2
etherpad_1    | [2022-06-01 13:38:24.889] [DEBUG] server - Installed server-side hooks:
etherpad_1    |   aceAttribClasses:
etherpad_1    |     ep_font_family:
etherpad_1    |       main: ep_font_family/index
etherpad_1    |     ep_subscript_and_superscript:
etherpad_1    |       main: ep_subscript_and_superscript/index
etherpad_1    |   asyncLineHTMLForExport:
etherpad_1    |     ep_subscript_and_superscript:
etherpad_1    |       main: ep_subscript_and_superscript/index
etherpad_1    |   clientVars:
etherpad_1    |     ep_set_title_on_pad:
etherpad_1    |       set_title_on_pad: ep_set_title_on_pad/handleMessage
etherpad_1    |   collectContentPost:
etherpad_1    |     ep_font_color:
etherpad_1    |       main: ep_font_color/static/js/shared
etherpad_1    |     ep_font_family:
etherpad_1    |       main: ep_font_family/static/js/shared
etherpad_1    |     ep_headings2:
etherpad_1    |       main: ep_headings2/static/js/shared
etherpad_1    |     ep_subscript_and_superscript:
etherpad_1    |       main: ep_subscript_and_superscript/static/js/shared
etherpad_1    |   collectContentPre:
etherpad_1    |     ep_font_color:
etherpad_1    |       main: ep_font_color/static/js/shared
etherpad_1    |     ep_font_family:
etherpad_1    |       main: ep_font_family/static/js/shared
etherpad_1    |     ep_headings2:
etherpad_1    |       main: ep_headings2/static/js/shared
etherpad_1    |     ep_subscript_and_superscript:
etherpad_1    |       main: ep_subscript_and_superscript/static/js/shared
etherpad_1    |   createServer:
etherpad_1    |     ep_etherpad-lite:
etherpad_1    |       express: ep_etherpad-lite/node/hooks/express
etherpad_1    |   eejsBlock_adminMenu:
etherpad_1    |     ep_adminpads2:
etherpad_1    |       ep_adminpads2: ep_adminpads2
etherpad_1    |   eejsBlock_body:
etherpad_1    |     ep_set_title_on_pad:
etherpad_1    |       set_title_on_pad: ep_set_title_on_pad/eejs
etherpad_1    |   eejsBlock_dd_format:
etherpad_1    |     ep_font_color:
etherpad_1    |       main: ep_font_color/index
etherpad_1    |     ep_font_family:
etherpad_1    |       main: ep_font_family/index
etherpad_1    |     ep_subscript_and_superscript:
etherpad_1    |       main: ep_subscript_and_superscript/index
etherpad_1    |   eejsBlock_editbarMenuLeft:
etherpad_1    |     ep_font_color:
etherpad_1    |       main: ep_font_color/index
etherpad_1    |     ep_font_family:
etherpad_1    |       main: ep_font_family/index
etherpad_1    |     ep_headings2:
etherpad_1    |       main: ep_headings2/index
etherpad_1    |     ep_subscript_and_superscript:
etherpad_1    |       main: ep_subscript_and_superscript/index
etherpad_1    |   eejsBlock_indexWrapper:
etherpad_1    |     ep_padlist2:
etherpad_1    |       ep_padlist2: ep_padlist2
etherpad_1    |   eejsBlock_mySettings:
etherpad_1    |     ep_author_hover:
etherpad_1    |       ep_author_hover: ep_author_hover/index
etherpad_1    |     ep_set_title_on_pad:
etherpad_1    |       set_title_on_pad: ep_set_title_on_pad/index
etherpad_1    |   exportFileName:
etherpad_1    |     ep_set_title_on_pad:
etherpad_1    |       set_title_on_pad: ep_set_title_on_pad/index
etherpad_1    |   exportHtmlAdditionalTags:
etherpad_1    |     ep_font_family:
etherpad_1    |       main: ep_font_family/index
etherpad_1    |     ep_subscript_and_superscript:
etherpad_1    |       main: ep_subscript_and_superscript/index
etherpad_1    |   exportHtmlAdditionalTagsWithData:
etherpad_1    |     ep_font_color:
etherpad_1    |       main: ep_font_color/exportHTML
etherpad_1    |   expressCloseServer:
etherpad_1    |     ep_etherpad-lite:
etherpad_1    |       socketio: ep_etherpad-lite/node/hooks/express/socketio
etherpad_1    |   expressConfigure:
etherpad_1    |     ep_etherpad-lite:
etherpad_1    |       webaccess: ep_etherpad-lite/node/hooks/express/webaccess
etherpad_1    |   expressCreateServer:
etherpad_1    |     ep_adminpads2:
etherpad_1    |       ep_adminpads2: ep_adminpads2
etherpad_1    |     ep_etherpad-lite:
etherpad_1    |       admin: ep_etherpad-lite/node/hooks/express/admin
etherpad_1    |       adminplugins: ep_etherpad-lite/node/hooks/express/adminplugins
etherpad_1    |       adminsettings: ep_etherpad-lite/node/hooks/express/adminsettings
etherpad_1    |       apicalls: ep_etherpad-lite/node/hooks/express/apicalls
etherpad_1    |       errorhandling: ep_etherpad-lite/node/hooks/express/errorhandling
etherpad_1    |       i18n: ep_etherpad-lite/node/hooks/i18n
etherpad_1    |       importexport: ep_etherpad-lite/node/hooks/express/importexport
etherpad_1    |       openapi: ep_etherpad-lite/node/hooks/express/openapi
etherpad_1    |       padurlsanitize: ep_etherpad-lite/node/hooks/express/padurlsanitize
etherpad_1    |       socketio: ep_etherpad-lite/node/hooks/express/socketio
etherpad_1    |       specialpages: ep_etherpad-lite/node/hooks/express/specialpages
etherpad_1    |       static: ep_etherpad-lite/node/hooks/express/static
etherpad_1    |       tests: ep_etherpad-lite/node/hooks/express/tests
etherpad_1    |     ep_padlist2:
etherpad_1    |       ep_padlist2: ep_padlist2
etherpad_1    |   getLineHTMLForExport:
etherpad_1    |     ep_font_color:
etherpad_1    |       main: ep_font_color/exportHTML
etherpad_1    |     ep_font_family:
etherpad_1    |       main: ep_font_family/index
etherpad_1    |     ep_headings2:
etherpad_1    |       main: ep_headings2/index
etherpad_1    |   handleMessage:
etherpad_1    |     ep_set_title_on_pad:
etherpad_1    |       set_title_on_pad: ep_set_title_on_pad/handleMessage
etherpad_1    |   padCreate:
etherpad_1    |     ep_adminpads2:
etherpad_1    |       ep_adminpads2: ep_adminpads2
etherpad_1    |   padInitToolbar:
etherpad_1    |     ep_font_color:
etherpad_1    |       main: ep_font_color/index
etherpad_1    |     ep_subscript_and_superscript:
etherpad_1    |       main: ep_subscript_and_superscript/index
etherpad_1    |   padRemove:
etherpad_1    |     ep_adminpads2:
etherpad_1    |       ep_adminpads2: ep_adminpads2
etherpad_1    |   restartServer:
etherpad_1    |     ep_etherpad-lite:
etherpad_1    |       express: ep_etherpad-lite/node/hooks/express
etherpad_1    |   shutdown:
etherpad_1    |     ep_etherpad-lite:
etherpad_1    |       DB: ep_etherpad-lite/node/db/DB
etherpad_1    |       express: ep_etherpad-lite/node/hooks/express
etherpad_1    |       Minify: ep_etherpad-lite/node/utils/Minify
etherpad_1    |       stats: ep_etherpad-lite/node/stats
etherpad_1    |   socketio:
etherpad_1    |     ep_adminpads2:
etherpad_1    |       ep_adminpads2: ep_adminpads2
etherpad_1    |     ep_etherpad-lite:
etherpad_1    |       adminplugins: ep_etherpad-lite/node/hooks/express/adminplugins
etherpad_1    |       adminsettings: ep_etherpad-lite/node/hooks/express/adminsettings
etherpad_1    |       socketio: ep_etherpad-lite/node/handler/PadMessageHandler
etherpad_1    |   stylesForExport:
etherpad_1    |     ep_font_color:
etherpad_1    |       main: ep_font_color/exportHTML
etherpad_1    |     ep_headings2:
etherpad_1    |       main: ep_headings2/index
etherpad_1    | [2022-06-01 13:38:24.890] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
etherpad_1    | [2022-06-01 13:38:24.916] [INFO] console - Your Etherpad version is 1.8.17 (c85ab49)
etherpad_1    | [2022-06-01 13:38:27.474] [INFO] http - HTTP server listening for connections
etherpad_1    | [2022-06-01 13:38:27.474] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
etherpad_1    | [2022-06-01 13:38:27.475] [INFO] console - The plugin admin page is at http://0.0.0.0:9001/admin/plugins
etherpad_1    | [2022-06-01 13:38:27.475] [INFO] server - Etherpad is running

```

**Comment by theriverman** [comment]
i'm experiencing exactly the same. rolling back to 1.8.17 makes the problem go away.

last working configuration:
```yaml
services:
  etherpad-db:
    image: mysql:5-debian

  etherpad-service:
    image: etherpad/etherpad:1.8.17
```

**Comment by tim-krieger** [comment]
No issues with etherpad develop (without plugins) and DirtyDB.

**Comment by GuidoDr** [comment]
even without plugins the same error with ueberDB remains.
Looks like the ueberDB changes introduced in 1.8.18 do not work with the mariadb installation (latest mariadb 10.8.3).

**Comment by GoliathLabs** [comment]
I got 1.8.18 working using the second post from https://github.com/ether/etherpad-lite/issues/2516.

I have set `DB_CHARSET` to `utf8mb4`. This may vary for you. After you've `migrated` your DB to the correct charset, 1.8.18 should work fine.

**Comment by GuidoDr** [comment]
after the migration step mentioned above I was also able to install 1.8.18
Only problem was, that most old pad did throw errors when they were tried to be opened.
But since those pad were no longer needed I did just delete them and now 1.8.18 is working fine with new pads.
