### ISSUE TITLE
Etherpad sometimes crashes when installing plugins, installation of a plugin takes 15 minutes

### ISSUE THREAD

**Issue by wsw70** [ether/etherpad-lite#5583]
**Describe the bug**

Using the admin interface to install plugins in a docker context fails (plugins are not installed) and Etherpad finally crashes.

**To Reproduce**

Start etherpad in a docker container
Install a plugin according to https://github.com/ether/etherpad-lite/wiki/Available-Plugins#installing-plugins-with-admin-interface

**Server (please complete the following information):**

- Version number: 1.8.18
- Latest available version: 1.8.17
- Git sha: [4b96ff6](https://github.com/ether/etherpad-lite/commit/4b96ff6)

**Additional context**

I added the full log of a plugin installation session in **LOG 1**.

Initially I thought that the plugins were simply not installed (similar to https://github.com/ether/etherpad-lite/issues/5569). But then, when writing the issue here, I realized that **after 5 minutes** some more logs are appearing.

Please see in **LOG 1** the lines 

```
etherpad-etherpad-1  | [2022-08-16 07:43:11.194] [INFO] plugins - Installing plugin ep_adminpads...
etherpad-etherpad-1  | [2022-08-16 07:48:07.639] [ERROR] runCmd|npm - npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

with the 5 minutes delay.

I then restarted the container and tried to install a recent plugin (`ep_image_upload`). It seems that the installation is extremely slow (despite not having any load and plenty of RAM on the server). The log for this installation is **LOG 2**.
I gave up after 

## LOG 1 - first installation with the crash

```
etherpad-etherpad-1  | [2022-08-16 07:41:13.576] [INFO] plugins - Installing plugin ep_image_upload...
etherpad-etherpad-1  | [2022-08-16 07:41:20.026] [ERROR] runCmd|npm - npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
etherpad-etherpad-1  | [2022-08-16 07:41:20.563] [ERROR] runCmd|npm - npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
etherpad-etherpad-1  | [2022-08-16 07:41:25.046] [INFO] plugins - Installing plugin ep_delete_empty_pads...
etherpad-etherpad-1  | [2022-08-16 07:41:45.718] [INFO] plugins - Installing plugin ep_align...
etherpad-etherpad-1  | [2022-08-16 07:41:54.681] [INFO] plugins - Installing plugin ep_font_color...
etherpad-etherpad-1  | [2022-08-16 07:42:05.875] [INFO] plugins - Installing plugin ep_table_of_contents...
etherpad-etherpad-1  | [2022-08-16 07:42:17.073] [INFO] plugins - Installing plugin ep_font_size...
etherpad-etherpad-1  | [2022-08-16 07:42:23.966] [INFO] plugins - Installing plugin ep_tables5...
etherpad-etherpad-1  | [2022-08-16 07:42:30.607] [INFO] plugins - Installing plugin ep_share_plugin...
etherpad-etherpad-1  | [2022-08-16 07:42:58.561] [INFO] Minify - Compress JS file js/admin/minify.json.js.
etherpad-etherpad-1  | [2022-08-16 07:42:58.562] [INFO] Minify - Compress JS file js/admin/jquery.autosize.js.
etherpad-etherpad-1  | [2022-08-16 07:42:58.600] [INFO] Minify - Compress JS file js/admin/settings.js.
etherpad-etherpad-1  | [2022-08-16 07:43:11.194] [INFO] plugins - Installing plugin ep_adminpads...
etherpad-etherpad-1  | [2022-08-16 07:48:07.639] [ERROR] runCmd|npm - npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
etherpad-etherpad-1  | [2022-08-16 07:48:08.372] [ERROR] runCmd|npm - npm WARN deprecated har-validator@5.1.5: this library is no longer supported
etherpad-etherpad-1  | [2022-08-16 07:48:11.537] [ERROR] runCmd|npm - npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
etherpad-etherpad-1  | [2022-08-16 07:48:11.685] [ERROR] runCmd|npm - npm WARN deprecated har-validator@5.1.5: this library is no longer supported
etherpad-etherpad-1  | [2022-08-16 07:48:11.787] [ERROR] runCmd|npm - npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
etherpad-etherpad-1  | [2022-08-16 07:48:24.815] [ERROR] runCmd|npm - npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
etherpad-etherpad-1  | [2022-08-16 07:48:24.956] [ERROR] runCmd|npm - npm WARN deprecated har-validator@5.1.5: this library is no longer supported
etherpad-etherpad-1  | [2022-08-16 07:48:24.980] [ERROR] runCmd|npm - npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
etherpad-etherpad-1  | [2022-08-16 07:48:29.133] [ERROR] runCmd|npm - npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
etherpad-etherpad-1  | [2022-08-16 07:48:29.561] [ERROR] runCmd|npm - npm WARN deprecated har-validator@5.1.5: this library is no longer supported
etherpad-etherpad-1  | [2022-08-16 07:48:29.582] [ERROR] runCmd|npm - npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
etherpad-etherpad-1  | [2022-08-16 07:48:39.467] [ERROR] runCmd|npm - npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
etherpad-etherpad-1  | [2022-08-16 07:48:39.533] [ERROR] runCmd|npm - npm WARN deprecated har-validator@5.1.5: this library is no longer supported
etherpad-etherpad-1  | [2022-08-16 07:48:39.550] [ERROR] runCmd|npm - npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
etherpad-etherpad-1  | [2022-08-16 07:48:51.626] [ERROR] runCmd|npm - npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
etherpad-etherpad-1  | [2022-08-16 07:48:51.686] [ERROR] runCmd|npm - npm WARN deprecated har-validator@5.1.5: this library is no longer supported
etherpad-etherpad-1  | [2022-08-16 07:48:51.710] [ERROR] runCmd|npm - npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
etherpad-etherpad-1  | [2022-08-16 07:48:58.108] [ERROR] runCmd|npm - npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
etherpad-etherpad-1  | [2022-08-16 07:48:58.168] [ERROR] runCmd|npm - npm WARN deprecated har-validator@5.1.5: this library is no longer supported
etherpad-etherpad-1  | [2022-08-16 07:48:58.188] [ERROR] runCmd|npm - npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
etherpad-etherpad-1  | [2022-08-16 07:49:06.859] [ERROR] runCmd|npm - npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
etherpad-etherpad-1  | [2022-08-16 07:49:06.920] [ERROR] runCmd|npm - npm WARN deprecated har-validator@5.1.5: this library is no longer supported
etherpad-etherpad-1  | [2022-08-16 07:49:06.942] [ERROR] runCmd|npm - npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
etherpad-etherpad-1  | [2022-08-16 07:49:49.051] [ERROR] runCmd|npm - npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
etherpad-etherpad-1  | [2022-08-16 07:49:49.154] [ERROR] runCmd|npm - npm WARN deprecated har-validator@5.1.5: this library is no longer supported
etherpad-etherpad-1  | [2022-08-16 07:49:49.175] [ERROR] runCmd|npm - npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
etherpad-etherpad-1  | [2022-08-16 07:50:03.924] [ERROR] runCmd|npm - npm WARN locking Error: EEXIST: file already exists, open '/home/etherpad/.npm/_locks/staging-6ca38ed3644fb7c1.lock'
etherpad-etherpad-1  | [2022-08-16 07:50:03.924] [ERROR] runCmd|npm - npm WARN locking  /home/etherpad/.npm/_locks/staging-6ca38ed3644fb7c1.lock failed [Error: EEXIST: file already exists, open '/home/etherpad/.npm/_locks/staging-6ca38ed3644fb7c1.lock'] {
etherpad-etherpad-1  | [2022-08-16 07:50:03.924] [ERROR] runCmd|npm - npm WARN locking   errno: -17,
etherpad-etherpad-1  | [2022-08-16 07:50:03.925] [ERROR] runCmd|npm - npm WARN locking   code: 'EEXIST',
etherpad-etherpad-1  | [2022-08-16 07:50:03.925] [ERROR] runCmd|npm - npm WARN locking   syscall: 'open',
etherpad-etherpad-1  | [2022-08-16 07:50:03.925] [ERROR] runCmd|npm - npm WARN locking   path: '/home/etherpad/.npm/_locks/staging-6ca38ed3644fb7c1.lock'
etherpad-etherpad-1  | [2022-08-16 07:50:03.925] [ERROR] runCmd|npm - npm WARN locking }
etherpad-etherpad-1  | [2022-08-16 07:50:04.272] [ERROR] runCmd|npm - npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad-lite/package.json'
etherpad-etherpad-1  | [2022-08-16 07:50:04.283] [ERROR] runCmd|npm - npm WARN etherpad-lite No description
etherpad-etherpad-1  | [2022-08-16 07:50:04.292] [ERROR] runCmd|npm - npm WARN etherpad-lite No repository field.
etherpad-etherpad-1  | [2022-08-16 07:50:04.301] [ERROR] runCmd|npm - npm WARN etherpad-lite No README data
etherpad-etherpad-1  | [2022-08-16 07:50:04.309] [ERROR] runCmd|npm - npm WARN etherpad-lite No license field.
etherpad-etherpad-1  | [2022-08-16 07:50:04.309] [ERROR] runCmd|npm -
etherpad-etherpad-1  | [2022-08-16 07:50:04.329] [ERROR] runCmd|npm - npm ERR! code EEXIST
etherpad-etherpad-1  | [2022-08-16 07:50:04.329] [ERROR] runCmd|npm - npm ERR! syscall open
etherpad-etherpad-1  | [2022-08-16 07:50:04.329] [ERROR] runCmd|npm - npm ERR! path /home/etherpad/.npm/_locks/staging-6ca38ed3644fb7c1.lock
etherpad-etherpad-1  | [2022-08-16 07:50:04.329] [ERROR] runCmd|npm - npm ERR! errno -17
etherpad-etherpad-1  | [2022-08-16 07:50:04.330] [ERROR] runCmd|npm - npm ERR! EEXIST: file already exists, open '/home/etherpad/.npm/_locks/staging-6ca38ed3644fb7c1.lock'
etherpad-etherpad-1  | [2022-08-16 07:50:04.330] [ERROR] runCmd|npm - npm ERR! File exists: /home/etherpad/.npm/_locks/staging-6ca38ed3644fb7c1.lock
etherpad-etherpad-1  | [2022-08-16 07:50:04.330] [ERROR] runCmd|npm - npm ERR! Remove the existing file and try again, or run npm
etherpad-etherpad-1  | [2022-08-16 07:50:04.330] [ERROR] runCmd|npm - npm ERR! with --force to overwrite files recklessly.
etherpad-etherpad-1  | [2022-08-16 07:50:04.338] [ERROR] runCmd|npm -
etherpad-etherpad-1  | [2022-08-16 07:50:04.338] [ERROR] runCmd|npm - npm ERR! A complete log of this run can be found in:
etherpad-etherpad-1  | [2022-08-16 07:50:04.338] [ERROR] runCmd|npm - npm ERR!     /home/etherpad/.npm/_logs/2022-08-16T07_50_04_333Z-debug.log
etherpad-etherpad-1  | [2022-08-16 07:50:04.348] [ERROR] plugins - Failed to install plugin ep_delete_empty_pads
etherpad-etherpad-1  | [2022-08-16 07:50:04.348] [WARN] console - Error: Command exited with code 239: npm install --no-save --legacy-peer-deps ep_delete_empty_pads
etherpad-etherpad-1  |     at exports (/opt/etherpad-lite/src/node/utils/run_cmd.js:119:25)
etherpad-etherpad-1  |     at Object.exports.install (/opt/etherpad-lite/src/static/js/pluginfw/installer.js:56:11)
etherpad-etherpad-1  |     at Socket.<anonymous> (/opt/etherpad-lite/src/node/hooks/express/adminplugins.js:102:17)
etherpad-etherpad-1  |     at Socket.emit (events.js:400:28)
etherpad-etherpad-1  |     at /opt/etherpad-lite/src/node_modules/socket.io/lib/socket.js:528:12
etherpad-etherpad-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11)
etherpad-etherpad-1  | [2022-08-16 07:50:04.350] [ERROR] server - Metrics at time of fatal error:
etherpad-etherpad-1  | {
etherpad-etherpad-1  |   "httpStartTime": 1659974602902,
etherpad-etherpad-1  |   "memoryUsage": 136691712,
etherpad-etherpad-1  |   "memoryUsageHeap": 46576936,
etherpad-etherpad-1  |   "ueberdb_lockAwaits": 49,
etherpad-etherpad-1  |   "ueberdb_lockAcquires": 33556,
etherpad-etherpad-1  |   "ueberdb_lockReleases": 33556,
etherpad-etherpad-1  |   "ueberdb_reads": 477,
etherpad-etherpad-1  |   "ueberdb_readsFailed": 0,
etherpad-etherpad-1  |   "ueberdb_readsFinished": 477,
etherpad-etherpad-1  |   "ueberdb_readsFromCache": 193,
etherpad-etherpad-1  |   "ueberdb_readsFromDb": 284,
etherpad-etherpad-1  |   "ueberdb_readsFromDbFailed": 0,
etherpad-etherpad-1  |   "ueberdb_readsFromDbFinished": 284,
etherpad-etherpad-1  |   "ueberdb_writes": 33133,
etherpad-etherpad-1  |   "ueberdb_writesFailed": 0,
etherpad-etherpad-1  |   "ueberdb_writesFinished": 33133,
etherpad-etherpad-1  |   "ueberdb_writesObsoleted": 0,
etherpad-etherpad-1  |   "ueberdb_writesToDb": 33133,
etherpad-etherpad-1  |   "ueberdb_writesToDbFailed": 0,
etherpad-etherpad-1  |   "ueberdb_writesToDbFinished": 33133,
etherpad-etherpad-1  |   "ueberdb_writesToDbRetried": 0,
etherpad-etherpad-1  |   "totalUsers": 1,
etherpad-etherpad-1  |   "activePads": 1,
etherpad-etherpad-1  |   "httpRequests": {
etherpad-etherpad-1  |     "meter": {
etherpad-etherpad-1  |       "mean": 0.049757498983581304,
etherpad-etherpad-1  |       "count": 32919,
etherpad-etherpad-1  |       "currentRate": 0.049757498981727405,
etherpad-etherpad-1  |       "1MinuteRate": 0.07601229598235151,
etherpad-etherpad-1  |       "5MinuteRate": 0.06302407902314304,
etherpad-etherpad-1  |       "15MinuteRate": 0.05958518111490113
etherpad-etherpad-1  |     },
etherpad-etherpad-1  |     "histogram": {
etherpad-etherpad-1  |       "min": 0.2901099920272827,
etherpad-etherpad-1  |       "max": 1004.9419090747833,
etherpad-etherpad-1  |       "sum": 26973.62440302968,
etherpad-etherpad-1  |       "variance": 32.22300230922897,
etherpad-etherpad-1  |       "mean": 0.8193937969874443,
etherpad-etherpad-1  |       "stddev": 5.676530833989098,
etherpad-etherpad-1  |       "count": 32919,
etherpad-etherpad-1  |       "median": 0.7095760107040405,
etherpad-etherpad-1  |       "p75": 0.7673674821853638,
etherpad-etherpad-1  |       "p95": 1.395012778043747,
etherpad-etherpad-1  |       "p99": 4.441444878578261,
etherpad-etherpad-1  |       "p999": 976.199813673619
etherpad-etherpad-1  |     }
etherpad-etherpad-1  |   },
etherpad-etherpad-1  |   "connects": {
etherpad-etherpad-1  |     "mean": 0.000012092421891192245,
etherpad-etherpad-1  |     "count": 8,
etherpad-etherpad-1  |     "currentRate": 0.000012092421891380184,
etherpad-etherpad-1  |     "1MinuteRate": 0.00003240471899263427,
etherpad-etherpad-1  |     "5MinuteRate": 0.0021905047491773896,
etherpad-etherpad-1  |     "15MinuteRate": 0.0020427656275777938
etherpad-etherpad-1  |   },
etherpad-etherpad-1  |   "pendingEdits": 0,
etherpad-etherpad-1  |   "edits": {
etherpad-etherpad-1  |     "meter": {
etherpad-etherpad-1  |       "mean": 0.00007406673368102619,
etherpad-etherpad-1  |       "count": 49,
etherpad-etherpad-1  |       "currentRate": 0.00007406673368230385,
etherpad-etherpad-1  |       "1MinuteRate": 5.666678584753537e-30,
etherpad-etherpad-1  |       "5MinuteRate": 9.331062917516478e-8,
etherpad-etherpad-1  |       "15MinuteRate": 0.0002051930477504367
etherpad-etherpad-1  |     },
etherpad-etherpad-1  |     "histogram": {
etherpad-etherpad-1  |       "min": 0.6692619323730469,
etherpad-etherpad-1  |       "max": 7.046995043754578,
etherpad-etherpad-1  |       "sum": 116.44380509853363,
etherpad-etherpad-1  |       "variance": 0.9061927572096128,
etherpad-etherpad-1  |       "mean": 2.37640418568436,
etherpad-etherpad-1  |       "stddev": 0.9519415723717568,
etherpad-etherpad-1  |       "count": 49,
etherpad-etherpad-1  |       "median": 2.3876349925994873,
etherpad-etherpad-1  |       "p75": 2.468439504504204,
etherpad-etherpad-1  |       "p95": 3.812286987900734,
etherpad-etherpad-1  |       "p99": 7.046995043754578,
etherpad-etherpad-1  |       "p999": 7.046995043754578
etherpad-etherpad-1  |     }
etherpad-etherpad-1  |   },
etherpad-etherpad-1  |   "lastDisconnect": 1660636204350,
etherpad-etherpad-1  |   "disconnects": {
etherpad-etherpad-1  |     "mean": 0.000010755024986646937,
etherpad-etherpad-1  |     "count": 7,
etherpad-etherpad-1  |     "currentRate": 0.000010755024986669939,
etherpad-etherpad-1  |     "1MinuteRate": 0.016020382419255835,
etherpad-etherpad-1  |     "5MinuteRate": 0.004936304481988291,
etherpad-etherpad-1  |     "15MinuteRate": 0.0025255385195508562
etherpad-etherpad-1  |   }
etherpad-etherpad-1  | }
etherpad-etherpad-1  | [2022-08-16 07:50:04.350] [ERROR] server - Error: Command exited with code 239: npm install --no-save --legacy-peer-deps ep_delete_empty_pads
etherpad-etherpad-1  |     at exports (/opt/etherpad-lite/src/node/utils/run_cmd.js:119:25)
etherpad-etherpad-1  |     at Object.exports.install (/opt/etherpad-lite/src/static/js/pluginfw/installer.js:56:11)
etherpad-etherpad-1  |     at Socket.<anonymous> (/opt/etherpad-lite/src/node/hooks/express/adminplugins.js:102:17)
etherpad-etherpad-1  |     at Socket.emit (events.js:400:28)
etherpad-etherpad-1  |     at /opt/etherpad-lite/src/node_modules/socket.io/lib/socket.js:528:12
etherpad-etherpad-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11)
etherpad-etherpad-1  | [2022-08-16 07:50:04.350] [INFO] server - Exiting...
etherpad-etherpad-1  | [2022-08-16 07:50:04.351] [INFO] server - Stopping Etherpad...
etherpad-etherpad-1  | [2022-08-16 07:50:04.351] [INFO] http - Closing HTTP server...
etherpad-etherpad-1  | [2022-08-16 07:50:04.351] [INFO] socket.io - Closing socket.io engine...
etherpad-etherpad-1  | [2022-08-16 07:50:04.352] [INFO] access - [LEAVE] pad:by3oqnsYAVlk7j0gQ-uY socket:smUuIG4r926wvkOsAAAE IP:172.18.0.5 authorID:a.jo8lyWUZfmJvVPwn
etherpad-etherpad-1  | [2022-08-16 07:50:04.352] [INFO] socket.io - All socket.io clients have disconnected
etherpad-etherpad-1  | [2022-08-16 07:50:04.353] [INFO] ueberDB -
etherpad-etherpad-1  | [2022-08-16 07:50:04.354] [INFO] http - Waiting for 1 HTTP clients to disconnect...
etherpad-etherpad-1  | [2022-08-16 07:50:04.358] [INFO] http - HTTP server closed
etherpad-etherpad-1  | [2022-08-16 07:50:04.359] [INFO] server - Etherpad stopped
etherpad-etherpad-1  | [2022-08-16 07:50:04.359] [INFO] server - Waiting for Node.js to exit...
etherpad-etherpad-1  | [2022-08-16 07:50:09.361] [ERROR] server - Something that should have been cleaned up during the shutdown hook (such as a timer, worker thread, or open connection) is preventing Node.js from exiting
etherpad-etherpad-1  | [2022-08-16 07:50:09.361] [ERROR] server - Enable `dumpOnUncleanExit` setting to get a dump of objects preventing a clean exit
etherpad-etherpad-1  | [2022-08-16 07:50:09.361] [ERROR] server - Forcing an unclean exit...
etherpad-etherpad-1 exited with code 1
```

## LOG 2

```
etherpad-etherpad-1  | [2022-08-16 07:58:24.674] [INFO] plugins - Installing plugin ep_image_upload...
etherpad-etherpad-1  | [2022-08-16 07:58:27.859] [ERROR] runCmd|npm - npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
etherpad-etherpad-1  | [2022-08-16 07:58:28.455] [ERROR] runCmd|npm - npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
etherpad-etherpad-1  | [2022-08-16 08:05:12.429] [ERROR] runCmd|npm - npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
etherpad-etherpad-1  | [2022-08-16 08:05:13.094] [ERROR] runCmd|npm - npm WARN deprecated har-validator@5.1.5: this library is no longer supported
etherpad-etherpad-1  | [2022-08-16 08:11:47.066] [INFO] runCmd|npm -
etherpad-etherpad-1  | [2022-08-16 08:11:47.066] [INFO] runCmd|npm - > sqlite3@5.0.2 install /opt/etherpad-lite/node_modules/sqlite3
etherpad-etherpad-1  | [2022-08-16 08:11:47.066] [INFO] runCmd|npm - > node-pre-gyp install --fallback-to-build
etherpad-etherpad-1  | [2022-08-16 08:11:47.066] [INFO] runCmd|npm -
etherpad-etherpad-1  | [2022-08-16 08:11:48.086] [INFO] runCmd|npm - [sqlite3] Success: "/opt/etherpad-lite/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" is installed via remote
etherpad-etherpad-1  | [2022-08-16 08:11:48.129] [ERROR] runCmd|npm - npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad-lite/package.json'
etherpad-etherpad-1  | [2022-08-16 08:11:48.138] [ERROR] runCmd|npm - npm WARN etherpad-lite No description
etherpad-etherpad-1  | [2022-08-16 08:11:48.148] [ERROR] runCmd|npm - npm WARN etherpad-lite No repository field.
etherpad-etherpad-1  | [2022-08-16 08:11:48.159] [ERROR] runCmd|npm - npm WARN etherpad-lite No README data
etherpad-etherpad-1  | [2022-08-16 08:11:48.166] [ERROR] runCmd|npm - npm WARN etherpad-lite No license field.
etherpad-etherpad-1  | [2022-08-16 08:11:48.167] [ERROR] runCmd|npm -
etherpad-etherpad-1  | [2022-08-16 08:11:48.168] [INFO] runCmd|npm - + ep_image_upload@1.0.87
etherpad-etherpad-1  | [2022-08-16 08:11:48.168] [INFO] runCmd|npm - added 197 packages from 243 contributors and audited 1044 packages in 803.105s
etherpad-etherpad-1  | [2022-08-16 08:11:48.520] [INFO] runCmd|npm -
etherpad-etherpad-1  | [2022-08-16 08:11:48.520] [INFO] runCmd|npm - 89 packages are looking for funding
etherpad-etherpad-1  | [2022-08-16 08:11:48.520] [INFO] runCmd|npm -   run `npm fund` for details
etherpad-etherpad-1  | [2022-08-16 08:11:48.520] [INFO] runCmd|npm -
etherpad-etherpad-1  | [2022-08-16 08:11:48.521] [INFO] runCmd|npm - found 31 vulnerabilities (3 moderate, 12 high, 16 critical)
etherpad-etherpad-1  | [2022-08-16 08:11:48.521] [INFO] runCmd|npm -   run `npm audit fix` to fix them, or `npm audit` for details
etherpad-etherpad-1  | [2022-08-16 08:11:48.561] [INFO] plugins - Successfully installed plugin ep_image_upload
etherpad-etherpad-1  | [2022-08-16 08:11:48.561] [INFO] plugins - Running npm to get a list of installed plugins...
etherpad-etherpad-1  | [2022-08-16 08:11:50.306] [INFO] plugins - Loading plugin ep_etherpad-lite...
etherpad-etherpad-1  | [2022-08-16 08:11:50.306] [INFO] plugins - Loading plugin ep_image_upload...
etherpad-etherpad-1  | [2022-08-16 08:11:50.307] [INFO] plugins - Loaded 2 plugins
etherpad-etherpad-1  | [2022-08-16 08:11:50.509] [INFO] settings - settings loaded from: /opt/etherpad-lite/settings.json
etherpad-etherpad-1  | [2022-08-16 08:11:50.510] [INFO] settings - No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
etherpad-etherpad-1  | [2022-08-16 08:11:50.511] [WARN] settings - The logconfig setting is deprecated.
etherpad-etherpad-1  | [2022-08-16 08:11:50.511] [INFO] settings - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
etherpad-etherpad-1  | [2022-08-16 08:11:50.511] [WARN] settings - Declaring the sessionKey in the settings.json is deprecated. This value is auto-generated now. Please remove the setting from the file. -- If you are seeing this error after restarting using the Admin User Interface then you can ignore this message.
etherpad-etherpad-1  | [2022-08-16 08:11:50.511] [WARN] settings - DirtyDB is used. This is not recommended for production. File location: /opt/etherpad-lite/var/dirty.db
etherpad-etherpad-1  | [2022-08-16 08:11:50.512] [INFO] settings - Random string used for versioning assets: bf377d6b
etherpad-etherpad-1  | [2022-08-16 08:11:50.512] [INFO] http - Closing HTTP server...
etherpad-etherpad-1  | [2022-08-16 08:11:50.512] [INFO] socket.io - Closing socket.io engine...
etherpad-etherpad-1  | [2022-08-16 08:11:50.513] [INFO] socket.io - All socket.io clients have disconnected
etherpad-etherpad-1  | [2022-08-16 08:11:50.513] [INFO] http - Waiting for 1 HTTP clients to disconnect...
etherpad-etherpad-1  | [2022-08-16 08:11:50.516] [INFO] http - HTTP server closed
etherpad-etherpad-1  | [2022-08-16 08:11:51.209] [INFO] http - HTTP server listening for connections
```

**Comment by gu1ll0me** [comment]
Same problem here using the Docker image v1.8.18.

The Docker image v1.8.14 works well, but higher versions takes forever install plugins. I also tested image v1.9.0-develop, same problem.

npm 6.14.15 seems the cause of the problem.

Entering the container with root user and updating npm with `npm install -g npm` solve the long install process.

```
docker exec -it -u root etherpad /bin/bash
npm install -g npm
npm install ep_image_upload
```

**Comment by wsw70** [comment]
> npm 6.14.15 seems the cause of the problem.
> 
> Entering the container with root user and updating npm with `npm install -g npm` solve the long install process.
> 
> ```
> docker exec -it -u root etherpad /bin/bash
> npm install -g npm
> npm install ep_image_upload
> ```

Thank you for the workaround. 
It is a volatile one, though - if the container is updater or recreated for a reason or another the chnages are lost.

**Comment by therysin** [comment]
Same issue on the latest develop version for me. Could be because I'm on arm64 though: https://hub.docker.com/layers/etherpad/etherpad/develop/images/sha256-0a97453df32dde103128bd4b1a541a6e38500f2efe1d7491e272532bbfee4ede?context=explore

**Comment by JohnMcLear** [comment]
See #5643

**Comment by SamTV12345** [comment]
@therysin @wsw70 @fab-kaz could you download plugins without problems with the latest etherpad version?

**Comment by SamTV12345** [comment]
We can finally close this issue. Everything solved in Etherpad 2
