### ISSUE TITLE
MySQL error "Received packet in the wrong sequence" when starting

### ISSUE THREAD

**Issue by rupran** [ether/etherpad-lite#5929]
**Describe the bug**
When starting on the current develop branch (commit 55096db854feddb84647bea6856a075e43ebccdb) with an already existing MySQL database, Etherpad crashes on startup. The tagged version `v1.9.2` works.

**To Reproduce**
1. Check out the repository at commit 55096db854feddb84647bea6856a075e43ebccdb
2. Run `./bin/run.sh`

**Expected behavior**
Etherpad should launch and accept connections

**Server (please complete the following information):**
 - Etherpad version: 55096db854feddb84647bea6856a075e43ebccdb
 - OS: CentOS 7
 - Node.js version (`node --version`): v20.5.1
 - npm version (`npm --version`): 9.8.0
 - Is the server free of plugins: yes

**Additional context**
Stack trace of the error:
```
[2023-09-13 16:34:26.790] [INFO] server - Starting Etherpad...
[2023-09-13 16:34:26.932] [ERROR] ueberDB - Fatal MySQL error: Error: Received packet in the wrong sequence.
    at BPe.c._parsePacket (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:563241)
    at ELe.s._parsePacket (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:412957)
    at ELe.s.write (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:407185)
    at BPe.c.write (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:559709)
    at Socket.<anonymous> (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:569873)
    at Socket.<anonymous> (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:568974)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at BPe.c._enqueue (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:561087)
    at BPe.c.handshake (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:559832)
    at WPe.p.connect (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:570745)
    at a.getConnection (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:577220)
    at a.query (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:579261)
    at /home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:587865
    at new Promise (<anonymous>)
    at cxe._query (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:587777)
    at cxe.init (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:588354)
    at Y.init (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:1:3086)
    at exports.Database.init (/home/user/apps/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:179:1175609)
    at exports.init (/home/user/apps/etherpad-lite/src/node/db/DB.js:41:20)
    at exports.start (/home/user/apps/etherpad-lite/src/node/server.js:142:14)
    at Object.<anonymous> (/home/user/apps/etherpad-lite/src/node/server.js:278:38)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
[2023-09-13 16:34:26.933] [ERROR] server - Error occurred while starting Etherpad
[2023-09-13 16:34:26.935] [ERROR] server - Metrics at time of fatal error:
{
  "httpStartTime": 0,
  "memoryUsage": 110845952,
  "memoryUsageHeap": 34720344
}
```

**Comment by SamTV12345** [comment]
Could you please check again if the error is still happening? It should be fixed by now.

**Comment by rupran** [comment]
Yep, looks good, thanks for the quick fix!

**Comment by SamTV12345** [comment]
I need to thank you for discovering this bug. I normally only test on dirtyDB and this bug wouldn't have been discovered by our test suites.
