### ISSUE TITLE
Etherpad cannot be started: code=exited, status=1/FAILURE

### ISSUE THREAD

**Issue by q2apro** [ether/etherpad-lite#6016]
**Describe the bug**
First installation of Etherpad following [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-the-etherpad-collaborative-web-editor-on-ubuntu-20-04#step-2-creating-a-systemd-service-for-etherpad). After `start etherpad` and then checking by `systemctl status etherpad` the error shows `code=exited, status=1/FAILURE`.

**To Reproduce**
1. Go to tutorial
2. Follow all steps until `sudo systemctl status etherpad`

**Expected behavior**
Etherpad should show "Active: active (running) since ..."

**Server (please complete the following information):**
 - Etherpad version: Latest from https://github.com/ether/etherpad-lite.git
 - OS: Ubuntu 20.04
 - Node.js version: v12.22.9
 - npm version: 8.5.1
 - Is the server free of plugins: yes

**Additional context**
How to fix the error so Etherpad Lite is up and running?

**Comment by q2apro** [comment]
Ah, could it be the NodeJS version?!!

**Comment by q2apro** [comment]
Again, I stopped working. Very strange.

Trying to start etherpad:

![image](https://github.com/ether/etherpad-lite/assets/6764548/4b52ae14-c264-492f-9093-b10cb15366d9)

```
× etherpad.service - Etherpad, a collaborative web editor.
     Loaded: loaded (/etc/systemd/system/etherpad.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-11-01 07:43:35 UTC; 1s ago
    Process: 2135 ExecStart=/usr/bin/node --experimental-worker /opt/etherpad/src/node/server.js (code=exited, status=1/FAILURE)
   Main PID: 2135 (code=exited, status=1/FAILURE)
        CPU: 266ms
```

Is there a mistake in my config file `/etc/systemd/system/etherpad.service`?

```
[Unit]
Description=Etherpad, a collaborative web editor.
After=syslog.target network.target

[Service]
Type=simple
User=etherpad
Group=etherpad
WorkingDirectory=/opt/etherpad
Environment=NODE_ENV=production
ExecStart=/usr/bin/node --experimental-worker /opt/etherpad/node_modules/ep_etherpad-lite/node/server.js
Restart=always

[Install]
WantedBy=multi-user.target
```

When I use `service --status-all` I see `etherpad` is not listed.

**Comment by q2apro** [comment]
When using `sudo systemctl status etherpad` now, I get:

![image](https://github.com/ether/etherpad-lite/assets/6764548/7f46b5a5-bc51-485c-8c3c-fed6e1e65c19)

Looks good.

Nginx is also set up, but I get "502 Bad Gateway" when loading the website.

Server settings are:

```
	server {
		listen       80;
		listen       [::]:80;
		server_name  notes.edumaps.de;

		access_log  /var/log/nginx/etherpad.access.log;
		error_log   /var/log/nginx/etherpad.error.log;

		location / {
			proxy_pass         http://127.0.0.1:9001;
			proxy_buffering    off;
			proxy_set_header   Host $host;
			proxy_pass_header  Server;

			# proxy headers
			proxy_set_header    X-Real-IP $remote_addr;
			proxy_set_header    X-Forwarded-For $remote_addr;
			proxy_set_header    X-Forwarded-Proto $scheme;
			proxy_http_version  1.1;

			# websocket proxying
			proxy_set_header  Upgrade $http_upgrade;
			proxy_set_header  Connection "upgrade";
		}
	}
```

I don't get it. Why is it so difficult (maybe only for me) to set up Etherpad...

**Comment by q2apro** [comment]
I saw `npm --version: 6.14.18` so I upgraded NPM 10.2.2.

Now using `sudo systemctl status etherpad` I get again:

```
 etherpad.service - Etherpad, a collaborative web editor
     Loaded: loaded (/etc/systemd/system/etherpad.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-11-01 09:43:51 UTC; 14s ago
    Process: 1271 ExecStart=/usr/bin/node --experimental-worker /opt/etherpad/node_modules/ep_etherpad-lite/node/server.js (code=exited, status=1/FAILURE)
   Main PID: 1271 (code=exited, status=1/FAILURE)
        CPU: 203ms

Nov 01 09:43:51 edumaps-notes-fsn systemd[1]: etherpad.service: Scheduled restart job, restart counter is at 5.
Nov 01 09:43:51 edumaps-notes-fsn systemd[1]: Stopped Etherpad, a collaborative web editor.
Nov 01 09:43:51 edumaps-notes-fsn systemd[1]: etherpad.service: Start request repeated too quickly.
Nov 01 09:43:51 edumaps-notes-fsn systemd[1]: etherpad.service: Failed with result 'exit-code'.
Nov 01 09:43:51 edumaps-notes-fsn systemd[1]: Failed to start Etherpad, a collaborative web editor.
```

**Comment by SamTV12345** [comment]
Could you show the journalctl output of the unit?

**Comment by SamTV12345** [comment]
Ubuntu somehow still ships these old node versions by default. I use alpine therefore instead.

**Comment by q2apro** [comment]
Terrible, causing so much headache... 

I just installed the latest NPM package because I thought the above shown `npm --version: 6.14.18` is the issue, but no, still the error coming:

```
× etherpad.service - Etherpad, a collaborative web editor
     Loaded: loaded (/etc/systemd/system/etherpad.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-11-01 10:00:56 UTC; 14s ago
    Process: 1160 ExecStart=/usr/bin/node --experimental-worker /opt/etherpad/node_modules/ep_etherpad-lite/node/server.js (code=exited, status=203/EXEC)
   Main PID: 1160 (code=exited, status=203/EXEC)
        CPU: 1ms

Nov 01 10:00:56 edumaps-notes-fsn systemd[1]: etherpad.service: Scheduled restart job, restart counter is at 5.
Nov 01 10:00:56 edumaps-notes-fsn systemd[1]: Stopped Etherpad, a collaborative web editor.
Nov 01 10:00:56 edumaps-notes-fsn systemd[1]: etherpad.service: Start request repeated too quickly.
Nov 01 10:00:56 edumaps-notes-fsn systemd[1]: etherpad.service: Failed with result 'exit-code'.
Nov 01 10:00:56 edumaps-notes-fsn systemd[1]: Failed to start Etherpad, a collaborative web editor.
```

I am no Linux user, how to use `journalctl` so that you can see the necessary data?

**Comment by SamTV12345** [comment]
Yes. That was also the problem I ran into.

**Comment by q2apro** [comment]
Okay, I created a symlink: `ln -s /root/.nvm/versions/node/v21.1.0/bin/node /usr/bin/node`

Then I rebooted the server.

Then I did:

```
sudo systemctl daemon-reload
sudo systemctl enable etherpad
sudo systemctl start etherpad
sudo systemctl status etherpad
```

And again the error:

```
× etherpad.service - Etherpad, a collaborative web editor
     Loaded: loaded (/etc/systemd/system/etherpad.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-11-01 10:12:31 UTC; 1s ago
    Process: 1166 ExecStart=/usr/bin/node --experimental-worker /opt/etherpad/node_modules/ep_etherpad-lite/node/server.js (code=exited, status=203/EXEC)
   Main PID: 1166 (code=exited, status=203/EXEC)
        CPU: 2ms

Nov 01 10:12:31 edumaps-notes-fsn systemd[1]: etherpad.service: Scheduled restart job, restart counter is at 5.
Nov 01 10:12:31 edumaps-notes-fsn systemd[1]: Stopped Etherpad, a collaborative web editor.
Nov 01 10:12:31 edumaps-notes-fsn systemd[1]: etherpad.service: Start request repeated too quickly.
Nov 01 10:12:31 edumaps-notes-fsn systemd[1]: etherpad.service: Failed with result 'exit-code'.
Nov 01 10:12:31 edumaps-notes-fsn systemd[1]: Failed to start Etherpad, a collaborative web editor.
```

Now with `journalctl -f -u etherpad.service` I get:

```
Nov 01 10:12:30 edumaps-notes-fsn systemd[1]: Started Etherpad, a collaborative web editor.
Nov 01 10:12:30 edumaps-notes-fsn systemd[1166]: etherpad.service: Failed to execute /usr/bin/node: Permission denied
Nov 01 10:12:30 edumaps-notes-fsn systemd[1166]: etherpad.service: Failed at step EXEC spawning /usr/bin/node: Permission denied
```

Permission?! ... The owner is user "root" so I need to give it permission to user etherpad I guess.

**Comment by SamTV12345** [comment]
Yes. That is the problem. If you want to start over I just created a step by step guide [here](https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service#debian-12-bookwormubuntu-jammy-systemd). I think this is a bit cleaner and the setup takes at most 5 minutes.

**Comment by q2apro** [comment]
I am trying for 7 hours already.

**Comment by SamTV12345** [comment]
Sure you're welcome. I tested it on two systems. It should work rightaway. It uses the DirtyDB which depending on your use case can be a bit too slow. So if you plan to use that with hundreds of users I can help you with the configuration.

**Comment by q2apro** [comment]
From your tutorial:

> Run `systemctl enable etherpad-lite` to enable the service on boot

I get:

```
Failed to enable unit: Unit file etherpad-lite.service does not exist.
```

With `systemctl enable etherpad` I get:

```
Created symlink /etc/systemd/system/multi-user.target.wants/etherpad.service → /etc/systemd/system/etherpad.service.
```

**Comment by SamTV12345** [comment]
What is /opt/ether? It should be /opt/etherpad.

**Comment by q2apro** [comment]
I think this was cut off... Meanwhile tried the installation of sqlite. I have to do everything again. I report back.

**Comment by SamTV12345** [comment]
Ok. If you follow the old tutorial by DigitalOcean you need to install better-sqlite3 instead of sqlite3.

**Comment by q2apro** [comment]
I have installed the entire server again, did all the necessary steps from your tutorial and the DigitalOcean tutorial.

Now when I run `sudo systemctl status etherpad` I get:

```
● etherpad.service - Etherpad-lite, the collaborative editor.
     Loaded: loaded (/etc/systemd/system/etherpad.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-11-01 13:04:47 UTC; 4s ago
   Main PID: 1920 (node)
      Tasks: 14 (limit: 9237)
     Memory: 109.9M
        CPU: 953ms
     CGroup: /system.slice/etherpad.service
             └─1920 /usr/bin/node --experimental-worker /opt/etherpad/etherpad-lite/var/src/node/server.js

Nov 01 13:04:48 node[1920]:     at Object.<anonymous> (/opt/etherpad/etherpad-lite/var/src/node/server.js:277:38)
Nov 01 13:04:48 node[1920]:     at Module._compile (node:internal/modules/cjs/loader:1241:14)
Nov 01 13:04:48 node[1920]:     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
Nov 01 13:04:48 node[1920]:     at Module.load (node:internal/modules/cjs/loader:1091:32)
Nov 01 13:04:48 node[1920]:     at Module._load (node:internal/modules/cjs/loader:938:12)
Nov 01 13:04:48 node[1920]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
Nov 01 13:04:48 node[1920]:     at node:internal/main/run_main_module:23:47
Nov 01 13:04:48 node[1920]: [2023-11-01T13:04:48.480] [INFO] server - Exiting...
Nov 01 13:04:48 node[1920]: [2023-11-01T13:04:48.480] [INFO] server - Waiting for Node.js to exit...
Nov 01 13:04:48 node[1920]: [2023-11-01T13:04:48.552] [INFO] plugins - npm --version: 6.14.18
```

Running `journalctl -f -u etherpad.service` I see:

```
Nov 01 13:04:54 node[1948]:     at Object.<anonymous> (/opt/etherpad/etherpad-lite/var/src/node/server.js:277:38)
Nov 01 13:04:54 node[1948]:     at Module._compile (node:internal/modules/cjs/loader:1241:14)
Nov 01 13:04:54 node[1948]:     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
Nov 01 13:04:54 node[1948]:     at Module.load (node:internal/modules/cjs/loader:1091:32)
Nov 01 13:04:54 node[1948]:     at Module._load (node:internal/modules/cjs/loader:938:12)
Nov 01 13:04:54 node[1948]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
Nov 01 13:04:54 node[1948]:     at node:internal/main/run_main_module:23:47
Nov 01 13:04:54 node[1948]: [2023-11-01T13:04:54.484] [INFO] server - Exiting...
Nov 01 13:04:54 node[1948]: [2023-11-01T13:04:54.484] [INFO] server - Waiting for Node.js to exit...
Nov 01 13:04:54 node[1948]: [2023-11-01T13:04:54.570] [INFO] plugins - npm --version: 6.14.18
Nov 01 13:04:59 node[1948]: [2023-11-01T13:04:59.484] [ERROR] server - Something that should have been cleaned up during the shutdown hook (such as a timer, worker thread, or open connection) is preventing Node.js from exiting
Nov 01 13:04:59 node[1948]: [2023-11-01T13:04:59.485] [ERROR] server - Enable `dumpOnUncleanExit` setting to get a dump of objects preventing a clean exit
Nov 01 13:04:59 node[1948]: [2023-11-01T13:04:59.485] [ERROR] server - Forcing an unclean exit...
Nov 01 13:04:59 systemd[1]: etherpad.service: Main process exited, code=exited, status=1/FAILURE
Nov 01 13:04:59 systemd[1]: etherpad.service: Failed with result 'exit-code'.
Nov 01 13:04:59 systemd[1]: etherpad.service: Scheduled restart job, restart counter is at 12.
Nov 01 13:04:59 systemd[1]: Stopped Etherpad-lite, the collaborative editor..
Nov 01 13:04:59 systemd[1]: Started Etherpad-lite, the collaborative editor..
Nov 01 13:04:59 node[1973]: [2023-11-01T13:04:59.868] [INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad/etherpad-lite/var
Nov 01 13:04:59 node[1973]: [2023-11-01T13:04:59.881] [INFO] settings - settings loaded from: /opt/etherpad/etherpad-lite/var/settings.json
Nov 01 13:04:59 node[1973]: [2023-11-01T13:04:59.881] [INFO] settings - No credentials file found in /opt/etherpad/etherpad-lite/var/credentials.json. Ignoring.
Nov 01 13:04:59 node[1973]: [2023-11-01T13:04:59.882] [INFO] settings - Using skin "colibris" in dir: /opt/etherpad/etherpad-lite/var/src/static/skins/colibris
Nov 01 13:04:59 node[1973]: [2023-11-01T13:04:59.883] [INFO] settings - Random string used for versioning assets: 2567f3c9
Nov 01 13:05:00 node[1973]: [2023-11-01T13:05:00.428] [INFO] server - Starting Etherpad...
Nov 01 13:05:00 node[1973]: [2023-11-01T13:05:00.480] [ERROR] server - Error occurred while starting Etherpad
Nov 01 13:05:00 node[1973]: [2023-11-01T13:05:00.481] [ERROR] server - Metrics at time of fatal error:
Nov 01 13:05:00 node[1973]: {
Nov 01 13:05:00 node[1973]:   "httpStartTime": 0,
Nov 01 13:05:00 node[1973]:   "memoryUsage": 156368896,
Nov 01 13:05:00 node[1973]:   "memoryUsageHeap": 51921840
Nov 01 13:05:00 node[1973]: }
Nov 01 13:05:00 node[1973]: [2023-11-01T13:05:00.482] [ERROR] server - Error: better-sqlite3 not found. It was removed from ueberdb's dependencies because it requires compilation which fails on several systems. If you still want to use sqlite, run "npm install better-sqlite3" in your etherpad-lite ./src directory.
Nov 01 13:05:00 node[1973]:     at S6e.init (/opt/etherpad/etherpad-lite/var/src/node_modules/ueberdb2/dist/index.js:198:1279013)
Nov 01 13:05:00 node[1973]:     at node:internal/util:442:7
Nov 01 13:05:00 node[1973]:     at new Promise (<anonymous>)
Nov 01 13:05:00 node[1973]:     at bound init [as init] (node:internal/util:428:12)
Nov 01 13:05:00 node[1973]:     at W.init (/opt/etherpad/etherpad-lite/var/src/node_modules/ueberdb2/dist/index.js:1:3143)
Nov 01 13:05:00 node[1973]:     at exports.Database.init (/opt/etherpad/etherpad-lite/var/src/node_modules/ueberdb2/dist/index.js:198:1330468)
Nov 01 13:05:00 node[1973]:     at exports.init (/opt/etherpad/etherpad-lite/var/src/node/db/DB.js:41:20)
Nov 01 13:05:00 node[1973]:     at exports.start (/opt/etherpad/etherpad-lite/var/src/node/server.js:141:14)
```

I do not get it...

**Comment by q2apro** [comment]
I repeated the step of installing better-sql3 again. As the tutorial says:

Change to user etherpad: 
`sudo -u etherpad bash`

Go to src folder:
`cd /opt/etherpad/etherpad-lite/var/src`

Install with:
`npm install better-sqlite3`

I enabled/started etherpad again, but still the same long error message as above.

**Comment by SamTV12345** [comment]
You need to install better sqlite 3 in the src folder. This is where you also find the node folder.

**Comment by SamTV12345** [comment]
I'm unfortunately afk but I'm back at home in around 5 hours.

**Comment by q2apro** [comment]
> You need to install better sqlite 3 in the src folder. This is where you also find the node folder.

Yes, I did.

![image](https://github.com/ether/etherpad-lite/assets/6764548/1900cf89-134b-4bba-b17c-f0ddb75d4f45)

I installed better-sqlite3 inside the src folder.

Or can I have to declare the installation path with this command `npm install better-sqlite3`?

Basically I don't understand that a software in development for 12 years is so difficult to install. I spent the entire day with it and still I have nothing running. Crazy experience.

**Comment by SamTV12345** [comment]
Installing something bare metal is mostly painful. That is why docker and docker compose exist. Anyways I'll check again later on a new vm.

**Comment by q2apro** [comment]
I have a fresh server. I can install whatever is needed.

Where is a tutorial how to install Etherpad with Docker?

**Comment by SamTV12345** [comment]
You install the necessary tools described here: https://docs.docker.com/engine/install/ubuntu/

**Comment by SamTV12345** [comment]
@q2apro I added some more commands to the systemd config. Hopefully this helps you to set it up. Otherwise I could also try to set it up for you if you like to.
