### ISSUE TITLE
Etherpad crashes on startup after updating to latest origin version

### ISSUE THREAD

**Issue by jimj316** [ether/etherpad-lite#6030]
**Describe the bug**
After updating Etherpad to the lastest version (using `git pull origin` ), the software no longer starts. It manages to successfully install dependencies, but fails while starting Etherpad. Please see below for the console output.

**To Reproduce**

1. Run `/bin/run.sh`

**Expected behavior**
The software does not crash.

**Screenshots**
No screenshots available

**Server (please complete the following information):**
 - Etherpad version: lastest as of 2023-11-06
 - OS: Debian GNU/Linux 10 / Linux 4.19.0-23-amd64
 - Node.js version (`node --version`): v14.21.3
 - npm version (`npm --version`): 6.14.18
 - Is the server free of plugins: No, as I don't know how to disable plugins without the web interface. If there is a way, please let me know.

**Additional context**
The console output from run.sh ends with a stack trace; the output is shown below:
```
jimj316@nekobox:/srv/etherpad/etherpad-lite$ sudo -u etherpad ./bin/run.sh --help
Installing dependencies...
Installing dev dependencies
npm WARN prepare removing existing node_modules/ before installation
added 628 packages in 60.009s
Clearing minified cache...
Starting Etherpad...
[2023-11-06T20:56:11.672] [INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /srv/etherpad/etherpad-lite
[2023-11-06T20:56:11.740] [INFO] settings - settings loaded from: /srv/etherpad/etherpad-lite/settings.json
[2023-11-06T20:56:11.743] [INFO] settings - No credentials file found in /srv/etherpad/etherpad-lite/credentials.json. Ignoring.
[2023-11-06T20:56:11.748] [INFO] settings - Using skin "colibris" in dir: /srv/etherpad/etherpad-lite/src/static/skins/colibris
[2023-11-06T20:56:11.750] [INFO] settings - Session key loaded from: /srv/etherpad/etherpad-lite/SESSIONKEY.txt
[2023-11-06T20:56:11.751] [WARN] settings - The sessionKey setting and /srv/etherpad/etherpad-lite/SESSIONKEY.txt file are deprecated; use automatic key rotation instead (see the cookie.keyRotationInterval setting).
[2023-11-06T20:56:11.752] [INFO] settings - Random string used for versioning assets: f809cae4
/srv/etherpad/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:29
    <Very large dump of a JS source file redacted>
    <5 blank lines>
SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/srv/etherpad/etherpad-lite/src/node/db/DB.js:24:17)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)

```

**Comment by Gared** [comment]
You have version 14 of node.js but etherpad needs higher than 16.20.1.
Update to a higher maintained version like node.js 18

**Comment by SamTV12345** [comment]
> You have version 14 of node.js but etherpad needs higher than 16.20.1. Update to a higher maintained version like node.js 18

Exactly. I got a lot of these errors before I migrated all plugin pipelines to Node 20. Current LTS is Node 20 @jimj316 .
