### ISSUE TITLE
Unable to use mysql in fresh Docker image

### ISSUE THREAD

**Issue by TomErnst1972** [ether/etherpad-lite#6080]
Hi guys,

**Describe the bug**
Trying to setup a new docker instance with mysql instead of Dirty.db. Container crashes with:
```[root@pve-xps ~]$ docker logs epad
[2023-12-20T13:31:55.381] [INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad-lite
[2023-12-20T13:31:55.393] [INFO] settings - settings loaded from: /opt/etherpad-lite/settings.json
[2023-12-20T13:31:55.394] [INFO] settings - No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
[2023-12-20T13:31:55.394] [INFO] settings - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
[2023-12-20T13:31:55.395] [INFO] settings - Random string used for versioning assets: 517c9d91
[2023-12-20T13:31:55.735] [INFO] server - Starting Etherpad...
[2023-12-20T13:31:55.784] [ERROR] ueberDB - Fatal MySQL error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (1001)
    at Hash.update (node:internal/crypto/hash:104:11)
    at n (/opt/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:198:521407)
    at e.calculateToken (/opt/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:198:521754)
    at new HandshakeResponse (/opt/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:198:533516)
    at ClientHandshake.sendCredentials (/opt/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:198:548324)
    at ClientHandshake.handshakeInit (/opt/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:198:549950)
    at ClientHandshake.execute (/opt/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:198:543347)
    at t.handlePacket (/opt/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:198:723005)
    at PacketParser.onPacket (/opt/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:198:717628)
    at PacketParser.executeStart (/opt/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:198:511853)
    at Socket.<anonymous> (/opt/etherpad-lite/src/node_modules/ueberdb2/dist/index.js:198:717776)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-12-20T13:31:55.784] [ERROR] server - Error occurred while starting Etherpad
[2023-12-20T13:31:55.784] [ERROR] server - Metrics at time of fatal error:
```

**To Reproduce**
this is my docker run command:
```
docker run -d --restart=always --name epad \
    --health-cmd "wget -q http://localhost:8050/ -O /dev/null" \
    -e PORT=8050 --net=host \
	-e ADMIN_PASSWORD="abc-redacted" \
    -e TRUST_PROXY=true \
    -e TITLE=Notizblock \
    -e PAD_OPTIONS_LANG=de-de \
    -e PAD_OPTIONS_NO_COLORS=true \
    -e PAD_OPTIONS_SHOW_CHAT=false \
    -e DEFAULT_PAD_TEXT="abc-redacted" \
    -e SUPPRESS_ERRORS_IN_PAD_TEXT=true \
    -e DB_TYPE="mysql" \
    -e DB_HOST="192.168.1.246" \
    -e DB_PORT="3306" \
    -e DB_NAME="epad" \
    -e DB_USER="abc-redacted" \
    -e DB_PASS="abc-redacted" \
    -e DB_CHARSET="utf8mb4" \
    etherpad/etherpad
```

These were my steps to create the database:
```
create database epad;
GRANT ALL ON epad.* TO 'abc-recated'@'%';
 show grants for 'abc-redacted'@'%';
>> GRANT ALL PRIVILEGES ON `epad`.* TO `abc-redacted`@`%`
```

**Expected behavior**
running instance with mysql.

**Screenshots**
![image](https://github.com/ether/etherpad-lite/assets/74730314/a932d6f7-7c4f-4cbe-8b59-814df9ce4557)

Any ideas or hints?

**Comment by SamTV12345** [comment]
I'll give that a try and report back later.

**Comment by SamTV12345** [comment]
I tried reproducing the bug unfortunately or fortunately it did work for me.

1.  Set up the docker-compose entry for the database:

```Docker
version: '3'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ueberdb
      MYSQL_PASSWORD: ueberdb
      MYSQL_DATABASE: ueberdb
 ```
 
 2. Add entry to settings.json:
 ```
   "dbType" : "mysql",
  "dbSettings" : {
    "user":     "ueberdb",
    "host":     "localhost",
    "port":     3306,
    "password": "ueberdb",
    "database": "ueberdb",
    "charset":  "utf8mb4"
  },
  ```
  
  3. Start etherpad server.
  
  
  Did you do anything differently?

**Comment by TomErnst1972** [comment]
Well yes, I was able to do it the way you did. 

BUT:  only by "docker -exec -it epad bash"-ing into the container and modifying the settings.json

I'd like to be able to pass these exact same parameters by CLI, when i create the container.
So therefore I ask you (if you have the time) to test like i described initially, by running:

```
docker run -d --restart=always --name epad \
    --health-cmd "wget -q http://localhost:8050/ -O /dev/null" \
    -e PORT=8050 --net=host \
	-e ADMIN_PASSWORD="abc-redacted" \
    -e TRUST_PROXY=true \
    -e TITLE=Notizblock \
    -e PAD_OPTIONS_LANG=de-de \
    -e PAD_OPTIONS_NO_COLORS=true \
    -e PAD_OPTIONS_SHOW_CHAT=false \
    -e DEFAULT_PAD_TEXT="abc-redacted" \
    -e SUPPRESS_ERRORS_IN_PAD_TEXT=true \
    -e DB_TYPE="mysql" \
    -e DB_HOST="192.168.1.246" \
    -e DB_PORT="3306" \
    -e DB_NAME="epad" \
    -e DB_USER="abc-redacted" \
    -e DB_PASS="abc-redacted" \
    -e DB_CHARSET="utf8mb4" \
    etherpad/etherpad
```
thanks for your efforts in advance! :)

**Comment by TomErnst1972** [comment]
I was able to achieve my goal by building my own docker image according to existing documentation. 
e.g.
```
git clone https://github.com/ether/etherpad-lite.git
cd etherpad-lite
nano settings.json.docker
docker build \
 --build-arg ETHERPAD_PLUGINS="ep_adminpads3 ep_author_neat2 ep_embedded_hyperlinks2 ep_headings2 ep_image_upload" \
 --tag abc123xyz/etherpad .
docker run --net=host --name=epad-new abc123xyz/etherpad
```

Don't know if you want to keep the issue open or if we shall close it?

best regards,
Tom

**Comment by SamTV12345** [comment]
Hi Tom,

I've been working on your issue at the same time. I put your docker run command into a docker-compose file and it worked without a problem:

```  
version: '3.7'
services:
  etherpad:
    image: etherpad/etherpad:latest
    ports:
      - "8050:8050"
    environment:
      PORT: 8050
      TRUST_PROXY: true
      TITLE: Notizblock
      PAD_OPTIONS_LANG: de-de
      PAD_OPTIONS_NO_COLORS: true
      PAD_OPTIONS_SHOW_CHAT: false
      DEFAULT_PAD_TEXT: "abc-redacted"
      SUPPRESS_ERRORS_IN_PAD_TEXT: true
      DB_TYPE: "mysql"
      DB_HOST: "mariadb"
      DB_PORT: "3306"
      DB_NAME: "epad"
      DB_USER: "abc-redacted"
      DB_PASS: "abc-redacted"
      DB_CHARSET: "utf8mb4"
    depends_on:
      - mariadb
    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:8050"]
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: epad
      MYSQL_USER: abc-redacted
      MYSQL_PASSWORD: abc-redacted
    volumes:
       - ./mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 10
```
so it could be something with the network configuration but the environment replacement works flawlessly.

**Comment by TomErnst1972** [comment]
Appreciate your efforts! While troubleshooting my initial strategy I already suspected some invisible characters in my text, or missing " or '. But didnt find them...

So anyway, your try with a docker-compose.yml is indeed a solution to the problem, so lets close it than, okay?
all the best
Tom

**Comment by SamTV12345** [comment]
Sure you're more than welcome. It's best to put everything into quotation marks. That way you prevent such issues. Yes let's close this one. 

Best
Sam
