### ISSUE TITLE
Unable to reach static.etherpad.org

### ISSUE THREAD

**Issue by signed-log** [ether/etherpad-lite#6088]
**Describe the bug**

Trying to reach `https://static.etherpad.org/plugins.json` times out, causing `AggregateError`

**To Reproduce**

**Expected behavior**

No warning

**Happening**

<details>

```
[2024-01-02T09:13:11.998] [WARN] settings - AggregateError
    at AxiosError.from (/home/etherpad/etherpad-lite/src/node_modules/axios/dist/node/axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (/home/etherpad/etherpad-lite/src/node_modules/axios/dist/node/axios.cjs:3083:25)
    at RedirectableRequest.emit (node:events:514:28)
    at eventHandlers.<computed> (/home/etherpad/etherpad-lite/src/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2024-01-02T09:13:12.005] [ERROR] settings - AxiosError [AggregateError]
    at AxiosError.from (/home/etherpad/etherpad-lite/src/node_modules/axios/dist/node/axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (/home/etherpad/etherpad-lite/src/node_modules/axios/dist/node/axios.cjs:3083:25)
    at RedirectableRequest.emit (node:events:514:28)
    at eventHandlers.<computed> (/home/etherpad/etherpad-lite/src/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ETIMEDOUT',
  errors: [
    Error: connect ETIMEDOUT 5.75.249.160:443
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '5.75.249.160',
      port: 443
    },
    Error: connect ENETUNREACH 2a01:4f8:c17:ba99::1:443 - Local (:::0)
        at internalConnectMultiple (node:net:1176:40)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2a01:4f8:c17:ba99::1',
      port: 443
    }
  ],
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'Etherpad/1.9.6',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://static.etherpad.org/plugins.json',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/plugins.json',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'static.etherpad.org',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/plugins.json'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /plugins.json HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: Etherpad/1.9.6\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: static.etherpad.org\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/plugins.json',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'static.etherpad.org',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://static.etherpad.org/plugins.json',
    [Symbol(kCapture)]: false
  },
  cause: AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1177:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    [errors]: [ [Error], [Error] ]
  }
}
```

</details>

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version: 1.9.6
 - OS: [e.g., Ubuntu 20.04]: Debian 12
 - Node.js version (`node --version`): v20.5.1
 - npm version (`npm --version`): npm 9.8.0
 - Is the server free of plugins: No, `ep_adminpads2`

**Additional context**

**Comment by SamTV12345** [comment]
It seems to work again. @Gared Do you know what the issue was?

**Comment by signed-log** [comment]
Still encountering the issue @SamTV12345

**Comment by SamTV12345** [comment]
I just entered the address in my browser and I could see the json file. Are you maybe blocked or are you blocking the dns request?

**Comment by signed-log** [comment]
My Windows instance doesn't like that domain for some reason, my machine doesn't pass, got to it through my phone (wanted to see plugin list)

**Comment by yuyongsong** [comment]
how to deal with this problem？

**Comment by yuyongsong** [comment]
how to deal with this problem？

**Comment by SamTV12345** [comment]
> how to deal with this problem？

You can either setup a proxy or lookup the ip address online and edit the host file on your windows/linux machine.

**Comment by yuyongsong** [comment]
> > how to deal with this problem？
> 
> You can either setup a proxy or lookup the ip address online and edit the host file on your windows/linux machine.

thanks

**Comment by yuyongsong** [comment]
> > how to deal with this problem？
> 
> You can either setup a proxy or lookup the ip address online and edit the host file on your windows/linux machine.

i have used proxy and i can Visit the https://static.etherpad.org/plugins.json，but it still does not work

TypeError: t.map is not a function
    at Nh (http://127.0.0.1:9001/admin/assets/index-Cv1HbGYr.js:215:5288)
    at Ic (http://127.0.0.1:9001/admin/assets/index-Cv1HbGYr.js:38:19519)
    at Ru (http://127.0.0.1:9001/admin/assets/index-Cv1HbGYr.js:40:3139)
    at fm (http://127.0.0.1:9001/admin/assets/index-Cv1HbGYr.js:40:44737)
    at lm (http://127.0.0.1:9001/admin/assets/index-Cv1HbGYr.js:40:39727)
    at g1 (http://127.0.0.1:9001/admin/assets/index-Cv1HbGYr.js:40:39655)
    at ua (http://127.0.0.1:9001/admin/assets/index-Cv1HbGYr.js:40:39508)
    at Mu (http://127.0.0.1:9001/admin/assets/index-Cv1HbGYr.js:40:35875)
    at om (http://127.0.0.1:9001/admin/assets/index-Cv1HbGYr.js:40:34826)
    at b (http://127.0.0.1:9001/admin/assets/index-Cv1HbGYr.js:25:1584)
