### ISSUE TITLE
v2.0.0: installing plugins from registry in docker fails

### ISSUE THREAD

**Issue by aine-etke** [ether/etherpad-lite#6234]
**Describe the bug**
Just to be on the same page: the problem is with **plugin installer** (part of etherpad), not plugins.

**To Reproduce**

```bash
# 1. define the list of plugins. The problem happens only when plugins have @xmldom/xmldom dependency, but for the sake of reproducibility the full list of plugins is provided, as the problem happened with that list
export PLUGINS="ep_font_size ep_font_family ep_font_color ep_spellcheck ep_table_of_contents ep_subscript_and_superscript ep_mammoth ep_print ep_comments_page ep_embedded_hyperlinks2 ep_adminpads2 ep_align ep_headings2 ep_cursortrace ep_markdown ep_set_title_on_pad ep_embedmedia ep_themes ep_rewrite_share_paths"

# 2. try to build an image
docker build --build-arg ETHERPAD_PLUGINS="$PLUGINS" --build-arg INSTALL_SOFFICE=true

# 3. observe the error (again, the problem happens with ANY plugin with @xmldom/xmldom dependency, so it looks like the installer is broken):
#23 18.74 [2024-03-17T13:08:31.379] [INFO] settings - Installing plugin from registry: ep_embedded_hyperlinks2
#23 18.74 node:fs:1807
#23 18.74   binding.symlink(
#23 18.74           ^
#23 18.74 
#23 18.74 Error: ENOENT: no such file or directory, symlink '/opt/etherpad-lite/src/plugin_packages/@xmldom/xmldom' -> '/opt/etherpad-lite/src/node_modules/@xmldom/xmldom'
#23 18.74     at symlinkSync (node:fs:1807:11)
#23 18.74     at LinkInstaller.linkDependency (/opt/etherpad-lite/src/static/js/pluginfw/LinkInstaller.ts:2:6716)
#23 18.74     at LinkInstaller.addSubDependency (/opt/etherpad-lite/src/static/js/pluginfw/LinkInstaller.ts:2:5926)
#23 18.74     at /opt/etherpad-lite/src/static/js/pluginfw/LinkInstaller.ts:2:6212
#23 18.74     at Array.forEach (<anonymous>)
#23 18.74     at LinkInstaller.addSubDependency (/opt/etherpad-lite/src/static/js/pluginfw/LinkInstaller.ts:2:6183)
#23 18.74     at LinkInstaller.addSubDependencies (/opt/etherpad-lite/src/static/js/pluginfw/LinkInstaller.ts:2:5741)
#23 18.74     at LinkInstaller.checkLinkedDependencies (/opt/etherpad-lite/src/static/js/pluginfw/LinkInstaller.ts:2:7390)
#23 18.74     at LinkInstaller.installPlugin (/opt/etherpad-lite/src/static/js/pluginfw/LinkInstaller.ts:2:2642)
#23 18.74     at async run (/opt/etherpad-lite/bin/installPlugins.ts:2:1333) {
#23 18.74   errno: -2,
#23 18.74   code: 'ENOENT',
#23 18.74   syscall: 'symlink',
#23 18.74   path: '/opt/etherpad-lite/src/plugin_packages/@xmldom/xmldom',
#23 18.74   dest: '/opt/etherpad-lite/src/node_modules/@xmldom/xmldom'
#23 18.74 }
#23 18.74 
#23 18.74 Node.js v21.7.1
#23 18.75 /opt/etherpad-lite/bin:
#23 18.75  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  bin@2.0.0 install-plugins: `node --import tsx ./installPlugins.ts "ep_font_size" "ep_font_family" "ep_font_color" "ep_spellcheck" "ep_table_of_contents" "ep_subscript_and_superscript" "ep_mammoth" "ep_embedded_hyperlinks2" "ep_adminpads2" "ep_align" "ep_headings2" "ep_cursortrace" "ep_markdown" "ep_set_title_on_pad" "ep_embedmedia" "ep_themes" "ep_rewrite_share_paths"`
#23 18.75 Exit status 1
#23 18.77  ELIFECYCLE  Command failed with exit code 1.
```

**Expected behavior**
Docker image is built successfully, the same as with previous versions, e.g. 1.9.7

**Screenshots**
N/A

**Server (please complete the following information):**
 - Etherpad version: 2.0.0
 - OS: Docker image (official Dockerfile)
 - Node.js version (`node --version`): Docker image (official Dockerfile)
 - npm version (`npm --version`): Docker image (official Dockerfile)
 - Is the server free of plugins: No

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Versions prior 2.0.0 building and working successfully; the automation and history of changes are available in the followin repo: https://gitlab.com/etke.cc/etherpad

**Comment by SamTV12345** [comment]
Thanks for the issue. Yes I discovered the issue. I haven't thought about scoped packages during the implementation. I'll fix it.

**Comment by SamTV12345** [comment]
Could you try again with the latest updates from master?

**Comment by SamTV12345** [comment]
Sure I'll release a patch tag.
