### ISSUE TITLE
Plugins' subdepencies are not being installed

### ISSUE THREAD

**Issue by dhalenok** [ether/etherpad-lite#6239]
When building the docker image via:
```sh
docker build --build-arg ETHERPAD_PLUGINS="ep_openid_connect" --progress=plain --tag etherpad-test .
```

The following error occurs:
```
#23 14.05 [2024-03-18T11:41:53.246] [INFO] settings - Installing plugin from registry: ep_openid_connect
#23 14.05 [2024-03-18T11:41:53.249] [ERROR] settings - (node:73) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
#23 14.05 (Use `node --trace-deprecation ...` to show where the warning was created)
#23 14.29 [2024-03-18T11:41:53.489] [INFO] plugins - pnpm --version: 8.15.5
#23 15.66 [2024-03-18T11:41:54.855] [ERROR] settings - Error reading package.json Error: ENOENT: no such file or directory, open '/opt/etherpad-lite/src/plugin_packages/ajv/package.json' for file:///opt/etherpad-lite/src/plugin_packages/ajv/package.json
#23 15.66 [2024-03-18T11:41:54.856] [ERROR] settings - Error reading package.json Error: ENOENT: no such file or directory, open '/opt/etherpad-lite/src/plugin_packages/lru-cache/package.json' for file:///opt/etherpad-lite/src/plugin_packages/lru-cache/package.json
```

If I start the container, I don't see plugin's server-side hooks being registered in the debug log, and there's errors for every hook:
```
Failed to load hook function "/opt/etherpad-lite/src/plugin_packages/ep_openid_connect:authenticate" for plugin "ep_openid_connect" part "main" hook set "hooks" hook "authenticate": Error: Cannot find module 'ajv/dist/jtd'
Require stack:
- /opt/etherpad-lite/src/plugin_packages/ep_openid_connect/index.js
- /opt/etherpad-lite/src/static/js/pluginfw/shared.js
- /opt/etherpad-lite/src/static/js/pluginfw/plugins.js
- /opt/etherpad-lite/src/static/js/pluginfw/installer.ts
- /opt/etherpad-lite/src/node/server.ts
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at a._resolveFilename (/opt/etherpad-lite/node_modules/.pnpm/tsx@4.7.1/node_modules/tsx/dist/cjs/index.cjs:1:1729)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/opt/etherpad-lite/src/plugin_packages/ep_openid_connect/index.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Object.S (/opt/etherpad-lite/node_modules/.pnpm/tsx@4.7.1/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at loadFn (/opt/etherpad-lite/src/static/js/pluginfw/shared.js:27:12)
    at Object.extractHooks (/opt/etherpad-lite/src/static/js/pluginfw/shared.js:56:18)
    at exports.update (/opt/etherpad-lite/src/static/js/pluginfw/plugins.js:115:28)
    at async exports.start (/opt/etherpad-lite/src/node/server.ts:6:1373
```

I'm using latest commit on develop branch.

**Comment by dhalenok** [comment]
I've tried debugging it a bit, and found that the issue is most likely due to `live-plugin-manager`.
I see that the failing modules are available on host according to debug logs from `live-plugin-manager`:

```
#23 15.63 2024-03-18T14:58:17.146Z live-plugin-manager Installing dependencies of ep_openid_connect: ajv is already available on host
#23 16.00 2024-03-18T14:58:17.517Z live-plugin-manager Installing dependencies of openid-client: lru-cache is already available on host
```

While the other ones, which are installed correctly are in fact downloaded from npm.

I was also able to come up with a possible workaround: 

Setting `hostRequire: undefined` option to [livePluginManager](https://github.com/ether/etherpad-lite/blob/d7869f50140db698186302c774e80fe1ba30097b/src/static/js/pluginfw/LinkInstaller.ts#L20) initialization in [LinkInstaller.ts](https://github.com/ether/etherpad-lite/blob/develop/src/static/js/pluginfw/LinkInstaller.ts) makes the errors go away.
