### ISSUE TITLE
admin webinterface not usable if plugins cannot be fetched

### ISSUE THREAD

**Issue by Vringe** [ether/etherpad-lite#6332]
**Describe the bug**
The admin web interface is completely unusable, if fetching the `plugins.json` file fails:

```
TypeError: t.map is not a function
    at Nh (https://pad.local/admin/assets/index-WmXtrGLT.js:215:5288)
    at Ic (https://pad.local/admin/assets/index-WmXtrGLT.js:38:19519)
    at Ru (https://pad.local/admin/assets/index-WmXtrGLT.js:40:3139)
    at fm (https://pad.local/admin/assets/index-WmXtrGLT.js:40:44737)
    at lm (https://pad.local/admin/assets/index-WmXtrGLT.js:40:39727)
    at g1 (https://pad.local/admin/assets/index-WmXtrGLT.js:40:39655)
    at ua (https://pad.local/admin/assets/index-WmXtrGLT.js:40:39508)
    at Mu (https://pad.local/admin/assets/index-WmXtrGLT.js:40:35875)
    at om (https://pad.local/admin/assets/index-WmXtrGLT.js:40:34826)
    at b (https://pad.local/admin/assets/index-WmXtrGLT.js:25:1584)
```

In my case, I'm using a proxy and it seems like axios does not have a [proper proxy implementation](https://github.com/axios/axios/issues/6320). 

**To Reproduce**
1. Setup proxy by setting `HTTP_PROXY` / `HTTPS_PROXY` env variables
1. Go to the admin webinterface

**Expected behavior**
The admin web interface should display an error instead, that the list of plugins could not be fetched. The rest should still be functional.

It would be even better if you could add an instance of the [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) to axios.

**Server (please complete the following information):**
 - Etherpad version: 2.0.2
 - OS: Alpine (Official Docker Image)
 - Node.js version (`node --version`): v21.7.2
 - npm version (`npm --version`): 10.5.0
 - Is the server free of plugins: ep_font_color and ep_headings2 is used

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 123.0.6312.122

**Comment by SamTV12345** [comment]
Should be fixed and you should be able to control the proxy with http_proxy and https_proxy

**Comment by Vringe** [comment]
Many thanks for the quick fix. Tested with the develop image. Now the page loads 👌🏻 

Still with a "Error retrieving plugins" but that's something axios must fix. I don't install any plugins via the web interface anyway.

**Comment by SamTV12345** [comment]
Yes I agree. You can try the http_proxy/https_proxy option for that :)
