### ISSUE TITLE
Pluggin ep_comments_page issue

### ISSUE THREAD

**Issue by phls** [ether/etherpad-lite#6567]
Hi,

I´m trying to build a custom image to run a docker container, adding some plugins. When I add ep_comments_page, the build fails and I'm getting this:

```
[2024-08-06T18:24:47.696] [INFO] server - Installed plugins: ep_align@0.3.97, ep_font_color@0.0.87, ep_markdown@0.1.78, ep_spellcheck@0.0.60, ep_embedded_hyperlinks2@1.2.4, ep_headings2@0.2.64, ep_author_hover@0.3.55, ep_user_displayname@1.0.7, ep_openid_connect@3.0.7, ep_comments_page@1.0.35
[2024-08-06T18:24:47.700] [INFO] plugin:ep_user_displayname - configured: { changeableDefault: false, changeableByDefault: true }
[2024-08-06T18:24:47.701] [ERROR] settings - (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2024-08-06T18:24:47.735] [INFO] plugin:ep_openid_connect - OpenID Connect Discovery complete.
[2024-08-06T18:24:47.736] [INFO] plugin:ep_openid_connect - Configured.
[2024-08-06T18:24:47.736] [INFO] settings - Report bugs at https://github.com/ether/etherpad-lite/issues
[2024-08-06T18:24:47.737] [INFO] settings - Your Etherpad version is 2.1.1 (1316cc7)
✘ [ERROR] Could not resolve require("./locale/**/*")

    plugin_packages/.versions/ep_comments_page@1.0.35/static/js/moment-with-locales.min.js:1:14102:
      1 │ ...ts)try{a=ea._abbr,require("./locale/"+e),_a(a)}catch(e){}return ...
        ╵                              ~~~~~~~~~~~~~

[2024-08-06T18:24:48.837] [ERROR] server - Error occurred while starting Etherpad
[2024-08-06T18:24:48.837] [ERROR] server - Metrics at time of fatal error:
{
  "httpStartTime": 0,
  "memoryUsage": 343846912,
  "memoryUsageHeap": 166123424,
  "ueberdb_lockAwaits": 0,
  "ueberdb_lockAcquires": 2,
  "ueberdb_lockReleases": 2,
  "ueberdb_reads": 1,
  "ueberdb_readsFailed": 0,
  "ueberdb_readsFinished": 1,
  "ueberdb_readsFromCache": 0,
  "ueberdb_readsFromDb": 1,
  "ueberdb_readsFromDbFailed": 0,
  "ueberdb_readsFromDbFinished": 1,
  "ueberdb_writes": 1,
  "ueberdb_writesFailed": 0,
  "ueberdb_writesFinished": 1,
  "ueberdb_writesObsoleted": 0,
  "ueberdb_writesToDb": 1,
  "ueberdb_writesToDbFailed": 0,
  "ueberdb_writesToDbFinished": 1,
  "ueberdb_writesToDbRetried": 0,
  "totalUsers": 0,
  "activePads": 0
}
[2024-08-06T18:24:48.837] [ERROR] server - Error: Build failed with 1 error:
plugin_packages/.versions/ep_comments_page@1.0.35/static/js/moment-with-locales.min.js:1:14102: ERROR: Could not resolve require("./locale/**/*")
    at failureErrorWithLog (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:1472:15)
    at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:945:25
    at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:897:52
    at buildResponseToResult (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:943:7)
    at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:970:16
    at responseCallbacks.<computed> (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:677:12)
    at Socket.readFromStdout (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:600:7)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
[2024-08-06T18:24:48.838] [INFO] server - Exiting...
[2024-08-06T18:24:48.838] [INFO] server - Waiting for Node.js to exit...
[2024-08-06T18:24:53.838] [ERROR] server - Something that should have been cleaned up during the shutdown hook (such as a timer, worker thread, or open connection) is preventing Node.js from exiting
[2024-08-06T18:24:53.839] [ERROR] server - Enable `dumpOnUncleanExit` setting to get a dump of objects preventing a clean exit
[2024-08-06T18:24:53.839] [ERROR] server - Forcing an unclean exit...
/opt/etherpad-lite/src:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  ep_etherpad-lite@2.1.1 prod: `cross-env NODE_ENV=production node --require tsx/cjs node/server.ts`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by SamTV12345** [comment]
Thanks for the report and confirmed. This is a problem in current develop. If you need to have the plugin try a released version. I'll fix this up.

**Comment by brknkfr** [comment]
Still happening with version 2.2.2

**Comment by SamTV12345** [comment]
Hi try the new updated version. I removed the problematic line in the JavaScript @brknkfr @phls

**Comment by SamTV12345** [comment]
Alright I just pushed another small change. The update should be available soon.

**Comment by phls** [comment]
Hi, when I add the plugin, I'm getting this on the logs

```
[2024-08-19T20:13:46.629] [INFO] settings - Your Etherpad version is 2.2.2 ()
▲ [WARNING] The condition "default" here will never be used as it comes after both "import" and "require" [package.json]

    plugin_packages/.versions/underscore@1.13.7/package.json:42:6:
      42 │       "default": "./underscore-umd.js"
         ╵       ~~~~~~~~~

  The "import" condition comes earlier and will be used for all "import" statements:

    plugin_packages/.versions/underscore@1.13.7/package.json:24:6:
      24 │       "import": {
         ╵       ~~~~~~~~

  The "require" condition comes earlier and will be used for all "require" calls:

    plugin_packages/.versions/underscore@1.13.7/package.json:33:6:
      33 │       "require": {
         ╵       ~~~~~~~~~

[2024-08-19T20:13:47.739] [INFO] http - HTTP server listening for connections
[2024-08-19T20:13:47.740] [INFO] settings - You can access your Etherpad instance at http://0.0.0.0:9001/
[2024-08-19T20:13:47.740] [INFO] settings - The plugin admin page is at http://0.0.0.0:9001/admin/plugins
[2024-08-19T20:13:47.740] [INFO] server - Etherpad is running
```


![Uploading Captura de tela de 2024-08-19 17-28-54.png…]()
