### ISSUE TITLE
 Etherpad update check: AggregateError

### ISSUE THREAD

**Issue by otisrojas** [ether/etherpad-lite#6630]
[2024-09-05T16:58:11.709] [ERROR] settings - Can not perform Etherpad update check: AggregateError
[2024-09-05T16:58:17.026] [ERROR] adminPlugins - Error searching plugins: AggregateError
[2024-09-05T16:58:46.028] [INFO] adminPlugins - Plugin search: 121212'
[2024-09-05T16:58:46.283] [ERROR] adminPlugins - Error searching plugins: AggregateError
[2024-09-05T17:03:17.742] [WARN] settings - AggregateError
    at Function.AxiosError.from (/opt/etherpad-lite/node_modules/.pnpm/axios@1.7.3/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/opt/etherpad-lite/node_modules/.pnpm/axios@1.7.3/node_modules/axios/lib/adapters/http.js:620:25)
    at RedirectableRequest.emit (node:events:520:28)
    at eventHandlers.<computed> (/opt/etherpad-lite/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:520:28)
    at emitErrorEvent (node:_http_client:103:11)
    at TLSSocket.socketErrorListener (node:_http_client:506:5)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/opt/etherpad-lite/node_modules/.pnpm/axios@1.7.3/node_modules/axios/lib/core/Axios.js:45:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async <anonymous> (/opt/etherpad-lite/src/static/js/pluginfw/installer.ts:174:5)

**Comment by SamTV12345** [comment]
> [2024-09-05T16:58:11.709] [ERROR] settings - Can not perform Etherpad update check: AggregateError [2024-09-05T16:58:17.026] [ERROR] adminPlugins - Error searching plugins: AggregateError [2024-09-05T16:58:46.028] [INFO] adminPlugins - Plugin search: 121212' [2024-09-05T16:58:46.283] [ERROR] adminPlugins - Error searching plugins: AggregateError [2024-09-05T17:03:17.742] [WARN] settings - AggregateError at Function.AxiosError.from (/opt/etherpad-lite/node_modules/.pnpm/axios@1.7.3/node_modules/axios/lib/core/AxiosError.js:89:14) at RedirectableRequest.handleRequestError (/opt/etherpad-lite/node_modules/.pnpm/axios@1.7.3/node_modules/axios/lib/adapters/http.js:620:25) at RedirectableRequest.emit (node:events:520:28) at eventHandlers. (/opt/etherpad-lite/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:38:24) at ClientRequest.emit (node:events:520:28) at emitErrorEvent (node:_http_client:103:11) at TLSSocket.socketErrorListener (node:_http_client:506:5) at TLSSocket.emit (node:events:520:28) at emitErrorNT (node:internal/streams/destroy:170:8) at emitErrorCloseNT (node:internal/streams/destroy:129:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) at Axios.request (/opt/etherpad-lite/node_modules/.pnpm/axios@1.7.3/node_modules/axios/lib/core/Axios.js:45:41) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async (/opt/etherpad-lite/src/static/js/pluginfw/installer.ts:174:5)

This is probably because your server can't reach https://static.etherpad.org/plugins.json. Try with curl https://static.etherpad.org/plugins.json in your etherpad instance . If that works it's a bug.

**Comment by 18988628083** [comment]
Indeed can't reach , how to solve the problem

**Comment by brinnjoyce** [comment]
It looks like that page is down, I'm getting a 404 from it.

**Comment by SamTV12345** [comment]
![image](https://github.com/user-attachments/assets/d76e164d-c9ae-43dc-843d-5a098f94ead8) I just visited the page. It works for me.

**Comment by 18988628083** [comment]
server can't reach https://static.etherpad.org/plugins.json., can download down to upload to the server?

**Comment by SamTV12345** [comment]
> server can't reach https://static.etherpad.org/plugins.json., can download down to upload to the server?

Not really currently but you can use a http proxy to access the page.

**Comment by brinnjoyce** [comment]
Looks like the IP for https://static.etherpad.org/plugins.json has ended up on the known malicious IPs list that Unifi uses. Likely applies to other firewalls too.

Sidenote: a proxy doesn't help much with installing plugins with etherpad if it's an internet access issue. 
live-plugin-manager doesn't support using a proxy and it also doesn't respect npm configs for default registry and just defaults to https://registry.npmjs.org/ so you can't point it at a registry mirror either.
