### ISSUE TITLE
having etherpad-lite apache config for port 80 subdir /pad

### ISSUE THREAD

**Issue by narges-lux** [ether/etherpad-lite#6693]
Hi I was using following configuration in my apache for port 443, and everything was working fine, but now I need to have the configuration tuned for port 80, and the one for port 443 does not work.
```
    # Proxy Configuration for /pad
    <Location /pad/>
        RewriteEngine On
        RewriteRule ^/pad/(.*)$ http://localhost:9001/$1 [P,L]
        RewriteRule ^/pad$ /pad/ [R=301,L]
        ProxyPass http://localhost:9001/
        ProxyPassReverse http://localhost:9001/
        ProxyPassReverseCookiePath / /pad/
        ProxyPassReverseCookieDomain localhost localhost
        Header edit Location ^http://localhost:9001/ /pad/
        ProxyPreserveHost On
        SetEnv proxy-sendchunked
    </Location>

    # WebSocket Proxying for /pad
    <Location /pad/socket.io>
        RewriteEngine On
        RewriteRule ^/pad/socket.io/(.*)$ /socket.io/$1 [PT,L]
        ProxyPass http://localhost:9001/socket.io
        ProxyPassReverse http://localhost:9001/socket.io
        ProxyPassReverseCookiePath / /pad/
        ProxyPassReverseCookieDomain localhost localhost
        Header edit Location ^http://localhost:9001/ /pad/
        ProxyPreserveHost On
        ProxyAddHeaders On
        RequestHeader set X-Forwarded-For "%{REMOTE_ADDR}s"
        ProxyPass ws://localhost:9001/socket.io
        ProxyPassReverse ws://localhost:9001/socket.io
    </Location>
```
and I get following error, trying to reach localhost/pad/p/xxxx, although localhost/pad/ is working:

```
padbootstrap-Y1mUw2vMVTM.min.js:56 Uncaught Error: Reconnect timed out
    at Po.<anonymous> (padbootstrap-Y1mUw2vMVTM.min.js:56:85402)
    at at.emit (padbootstrap-Y1mUw2vMVTM.min.js:56:44693)
    at Po.reconnect (padbootstrap-Y1mUw2vMVTM.min.js:56:80858)
    at padbootstrap-Y1mUw2vMVTM.min.js:56:81128
    at Ro.a (padbootstrap-Y1mUw2vMVTM.min.js:56:79125)
    at at.emit (padbootstrap-Y1mUw2vMVTM.min.js:56:44693)
    at Ro._onError (padbootstrap-Y1mUw2vMVTM.min.js:56:61607)
    at at.emit (padbootstrap-Y1mUw2vMVTM.min.js:56:44693)
    at No.onError (padbootstrap-Y1mUw2vMVTM.min.js:56:46485)
    at ws.onerror (padbootstrap-Y1mUw2vMVTM.min.js:56:52796)
```
can you please help me, I do not know why this occurs?

**Comment by SamTV12345** [comment]
Hi sure @narges-lux . What is your current apache config file. Then I could go from there on.

**Comment by narges-lux** [comment]
Hi @SamTV12345 , my issue is solved. Thank you :)

**Comment by nickturrietta** [comment]
Do you recall how you fixed?
