### ISSUE TITLE
TypeError: Cannot read property 'global' of undefined

### ISSUE THREAD

**Issue by jonmz** [ether/etherpad-lite#771]
A current clone of etherpad-lite simply doesn't start.

```
[jonas@lyra ~]$ node -v
v0.6.17

[jonas@lyra ~]$ npm -v
1.1.21

[jonas@lyra ~]$ git clone 'git://github.com/Pita/etherpad-lite.git'
Cloning into etherpad-lite...
remote: Counting objects: 9076, done.
remote: Compressing objects: 100% (2875/2875), done.
remote: Total 9076 (delta 6470), reused 8590 (delta 6051)
Receiving objects: 100% (9076/9076), 2.89 MiB | 678 KiB/s, done.
Resolving deltas: 100% (6470/6470), done.

[jonas@lyra ~]$ cd etherpad-lite

[jonas@lyra etherpad-lite]$ bin/run.sh 
Copy the settings template to settings.json...
`settings.json.template' -> `settings.json'
Ensure that all dependencies are up to date...
[... tons of npm output removed ...]
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
ensure custom css/js files are created...
`src/static/custom/js.template' -> `src/static/custom/index.js'
`src/static/custom/css.template' -> `src/static/custom/index.css'
`src/static/custom/js.template' -> `src/static/custom/pad.js'
`src/static/custom/css.template' -> `src/static/custom/pad.css'
`src/static/custom/js.template' -> `src/static/custom/timeslider.js'
`src/static/custom/css.template' -> `src/static/custom/timeslider.css'
start...

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Cannot read property 'global' of undefined
    at Object.get (/home/jonas/etherpad-lite/src/node_modules/npm/node_modules/proto-list/proto-list.js:42:26)
    at Object.get (/home/jonas/etherpad-lite/src/node_modules/npm/lib/utils/ini.js:316:32)
    at Object.get (/home/jonas/etherpad-lite/src/node_modules/npm/lib/npm.js:384:39)
    at EventEmitter.dir (/home/jonas/etherpad-lite/src/node_modules/npm/lib/npm.js:418:22)
    at Object.<anonymous> (/home/jonas/etherpad-lite/src/node/utils/Settings.js:29:44)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
```

Exactly the same thing happens to etherpad-lite installations that have been perfectly usable before: After a "git pull origin" they simply don't start again with the above error.

"git checkout master~5" brings etherpad-lite back to a working state; "git checkout master~4" breaks it, so it looks like a bug somewhere in 96877bc "Merge branch 'develop'" ... :-/

**Comment by Akhilesh-Kanojia** [comment]
When i am trying to connect my custom api to react its giving below error:

**TypeError: Cannot read property 'global' of undefined**
**and also in console its giving 404 error**

i had tried many solution..but not getting 

Can anyone help me for resolving this issue

Regards
Akhilesh
