### ISSUE TITLE
Etherpad-lite with mysql socket configuration doesn't work

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#974]
I use `--skip-networking` in my rc.mysqld, so mysql does'nt listen on tcp port, only on socket file (/var/run/mysql/mysql.sock).
### with --skip-networking option (socket config)

```
root@davinci:/var/run/mysql# netstat -anop | grep mysql
unix  2      [ ACC ]     STREAM     LISTENING     1227594 8059/mysqld         /var/run/mysql/mysql.sock
```

...error in etherpad:

```
start...
[2012-09-03 17:26:30.102] [ERROR] console - ERROR: Problem while initalizing the database
[2012-09-03 17:26:30.110] [ERROR] console - Error: connect ECONNREFUSED
at errnoException (net.js:642:11)
at Object.afterConnect [as oncomplete] (net.js:633:18)
```

shell mysql works :

```
root@davinci:/var/run/mysql# mysql -u etherpad -h localhost -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.1.56 Source distribution

Copyright (c) 2000, 2010, Oracle and/or its affiliates. All rights reserved.
This software comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to modify and redistribute it under the GPL v2 license

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>

```
### without --skip-networking option

```
root@davinci:/var/run/mysql# netstat -anop | grep mysql
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      8264/mysqld         off (0.00/0/0)
unix  2      [ ACC ]     STREAM     LISTENING     1228673 8264/mysqld         /var/run/mysql/mysql.sock
```

...etherpad-lite works with mysql.
database initialisation works.

_This issue was reported in #etherpad-lite-dev on freenode by mogitux_

**Comment by nesnera** [comment]
Hi guys,
I had the same problem and [suggestion](https://github.com/ether/etherpad-lite/issues/974#issuecomment-9423895) with `"port"    : "/var/run/mysqld/mysqld.sock",` solved it well.
Thank a lot (y)
